package com.example.wms.config;

import java.util.List;

// 权限种子提供器
public final class PermissionSeedProvider {
    private PermissionSeedProvider() {
    }

    public static List<PermissionSeed> permissionSeeds() {
        return List.of(
            new PermissionSeed("warehouse:view", "查看仓库", "查看仓库列表"),
            new PermissionSeed("warehouse:add", "新增仓库", "新增仓库"),
            new PermissionSeed("warehouse:edit", "编辑仓库", "编辑仓库信息"),
            new PermissionSeed("warehouse:delete", "删除仓库", "删除仓库"),

            new PermissionSeed("shelf:view", "查看货架", "查看货架列表"),
            new PermissionSeed("shelf:add", "新增货架", "新增货架"),
            new PermissionSeed("shelf:edit", "编辑货架", "编辑货架信息"),
            new PermissionSeed("shelf:delete", "删除货架", "删除货架"),

            new PermissionSeed("product:view", "查看商品", "查看商品信息"),
            new PermissionSeed("product:add", "新增商品", "新增商品"),
            new PermissionSeed("product:edit", "编辑商品", "编辑商品信息"),
            new PermissionSeed("product:delete", "删除商品", "删除商品"),

            new PermissionSeed("supplier:view", "查看供应商", "查看供应商信息"),
            new PermissionSeed("supplier:add", "新增供应商", "新增供应商"),
            new PermissionSeed("supplier:edit", "编辑供应商", "编辑供应商信息"),
            new PermissionSeed("supplier:delete", "删除供应商", "删除供应商"),

            new PermissionSeed("category:view", "查看分类", "查看分类信息"),
            new PermissionSeed("category:add", "新增分类", "新增分类"),
            new PermissionSeed("category:edit", "编辑分类", "编辑分类信息"),
            new PermissionSeed("category:delete", "删除分类", "删除分类"),

            new PermissionSeed("unit:view", "查看单位", "查看计量单位"),
            new PermissionSeed("unit:add", "新增单位", "新增计量单位"),
            new PermissionSeed("unit:edit", "编辑单位", "编辑计量单位"),
            new PermissionSeed("unit:delete", "删除单位", "删除计量单位"),

            new PermissionSeed("user:view", "查看用户", "查看用户列表"),
            new PermissionSeed("user:add", "新增用户", "新增用户"),
            new PermissionSeed("user:edit", "编辑用户", "编辑用户"),
            new PermissionSeed("user:delete", "删除用户", "删除用户"),

            new PermissionSeed("role:view", "查看角色", "查看角色与权限"),
            new PermissionSeed("role:add", "新增角色", "新增角色"),
            new PermissionSeed("role:edit", "编辑角色", "编辑角色"),
            new PermissionSeed("role:delete", "删除角色", "删除角色"),
            new PermissionSeed("role:assign:view", "查看角色选项", "用户管理角色下拉选项"),
            new PermissionSeed("column:role:manage", "配置角色列权限", "角色列权限配置"),

            new PermissionSeed("audit:view", "查看审计日志", "查看系统审计日志"),
            new PermissionSeed("column:edit", "配置列显示", "租户列显示配置"),
            new PermissionSeed("column:user-management:avatar", "用户管理-头像列", "用户管理头像列显示"),
            new PermissionSeed("column:user-management:username", "用户管理-用户名列", "用户管理用户名列显示"),
            new PermissionSeed("column:user-management:displayName", "用户管理-姓名列", "用户管理姓名列显示"),
            new PermissionSeed("column:user-management:roles", "用户管理-角色列", "用户管理角色列显示"),
            new PermissionSeed("column:user-management:contact", "用户管理-联系方式列", "用户管理联系方式列显示"),
            new PermissionSeed("column:user-management:status", "用户管理-状态列", "用户管理状态列显示"),
            new PermissionSeed("column:user-management:loginTime", "用户管理-登录时间列", "用户管理登录时间列显示"),

            new PermissionSeed("column:role-management:name", "角色管理-名称列", "角色管理名称列显示"),
            new PermissionSeed("column:role-management:code", "角色管理-编码列", "角色管理编码列显示"),
            new PermissionSeed("column:role-management:description", "角色管理-描述列", "角色管理描述列显示"),
            new PermissionSeed("column:role-management:status", "角色管理-状态列", "角色管理状态列显示"),

            new PermissionSeed("column:permission-management:name", "权限管理-名称列", "权限管理名称列显示"),
            new PermissionSeed("column:permission-management:code", "权限管理-编码列", "权限管理编码列显示"),
            new PermissionSeed("column:permission-management:description", "权限管理-描述列", "权限管理描述列显示"),
            new PermissionSeed("column:permission-management:status", "权限管理-状态列", "权限管理状态列显示"),

            new PermissionSeed("column:audit-logs:tenant", "审计日志-租户列", "审计日志租户列显示"),
            new PermissionSeed("column:audit-logs:actor", "审计日志-操作者列", "审计日志操作者列显示"),
            new PermissionSeed("column:audit-logs:action", "审计日志-动作列", "审计日志动作列显示"),
            new PermissionSeed("column:audit-logs:entityType", "审计日志-实体类型列", "审计日志实体类型列显示"),
            new PermissionSeed("column:audit-logs:entityId", "审计日志-实体ID列", "审计日志实体ID列显示"),
            new PermissionSeed("column:audit-logs:detail", "审计日志-详情列", "审计日志详情列显示"),
            new PermissionSeed("column:audit-logs:deleteReason", "审计日志-删除原因列", "审计日志删除原因列显示"),
            new PermissionSeed("column:audit-logs:status", "审计日志-结果列", "审计日志结果列显示"),
            new PermissionSeed("column:audit-logs:requestId", "审计日志-请求ID列", "审计日志请求ID列显示"),
            new PermissionSeed("column:audit-logs:clientIp", "审计日志-客户端IP列", "审计日志客户端IP列显示"),
            new PermissionSeed("column:audit-logs:userAgent", "审计日志-客户端UA列", "审计日志客户端UA列显示"),
            new PermissionSeed("column:audit-logs:method", "审计日志-请求方法列", "审计日志请求方法列显示"),
            new PermissionSeed("column:audit-logs:path", "审计日志-请求路径列", "审计日志请求路径列显示"),
            new PermissionSeed("column:audit-logs:httpStatus", "审计日志-HTTP状态列", "审计日志HTTP状态列显示"),
            new PermissionSeed("column:audit-logs:errorCode", "审计日志-错误码列", "审计日志错误码列显示"),
            new PermissionSeed("column:audit-logs:errorMessage", "审计日志-错误信息列", "审计日志错误信息列显示"),
            new PermissionSeed("column:audit-logs:durationMs", "审计日志-耗时列", "审计日志耗时列显示"),
            new PermissionSeed("column:audit-logs:createdAt", "审计日志-时间列", "审计日志时间列显示"),

            new PermissionSeed("column:system-configs:key", "系统配置-键列", "系统配置键列显示"),
            new PermissionSeed("column:system-configs:value", "系统配置-值列", "系统配置值列显示"),
            new PermissionSeed("column:system-configs:type", "系统配置-类型列", "系统配置类型列显示"),
            new PermissionSeed("column:system-configs:description", "系统配置-描述列", "系统配置描述列显示"),
            new PermissionSeed("column:system-configs:public", "系统配置-公开列", "系统配置公开列显示"),
            new PermissionSeed("column:system-configs:updatedAt", "系统配置-更新时间列", "系统配置更新时间列显示"),

            new PermissionSeed("column:menu-management:title", "菜单管理-标题列", "菜单管理标题列显示"),
            new PermissionSeed("column:menu-management:code", "菜单管理-编码列", "菜单管理编码列显示"),
            new PermissionSeed("column:menu-management:path", "菜单管理-路径列", "菜单管理路径列显示"),
            new PermissionSeed("column:menu-management:permissionCode", "菜单管理-权限列", "菜单管理权限列显示"),
            new PermissionSeed("column:menu-management:sort", "菜单管理-排序列", "菜单管理排序列显示"),
            new PermissionSeed("column:menu-management:status", "菜单管理-状态列", "菜单管理状态列显示"),

            new PermissionSeed("column:tenant-management:code", "租户管理-编码列", "租户管理编码列显示"),
            new PermissionSeed("column:tenant-management:name", "租户管理-名称列", "租户管理名称列显示"),
            new PermissionSeed("column:tenant-management:status", "租户管理-状态列", "租户管理状态列显示"),
            new PermissionSeed("column:tenant-management:createdAt", "租户管理-创建时间列", "租户管理创建时间列显示"),

            new PermissionSeed("column:inbound-management:orderNumber", "入库管理-单号列", "入库管理单号列显示"),
            new PermissionSeed("column:inbound-management:type", "入库管理-类型列", "入库管理类型列显示"),
            new PermissionSeed("column:inbound-management:supplier", "入库管理-供应商列", "入库管理供应商列显示"),
            new PermissionSeed("column:inbound-management:date", "入库管理-日期列", "入库管理日期列显示"),
            new PermissionSeed("column:inbound-management:status", "入库管理-状态列", "入库管理状态列显示"),
            new PermissionSeed("column:inbound-management:product", "入库管理-商品列", "入库管理商品列显示"),
            new PermissionSeed("column:inbound-management:quantity", "入库管理-数量列", "入库管理数量列显示"),
            new PermissionSeed("column:inbound-management:warehouseLabel", "入库管理-仓库列", "入库管理仓库列显示"),
            new PermissionSeed("column:inbound-management:shelfLabel", "入库管理-货架列", "入库管理货架列显示"),
            new PermissionSeed("system-config:view", "查看系统配置", "查看系统配置"),
            new PermissionSeed("system-config:edit", "编辑系统配置", "编辑系统配置"),

            new PermissionSeed("inbound:view", "查看入库单", "查看入库单"),
            new PermissionSeed("inbound:add", "新增入库单", "新增入库单"),
            new PermissionSeed("inbound:edit", "编辑入库单", "编辑入库单"),
            new PermissionSeed("inbound:delete", "删除入库单", "删除入库单"),

            new PermissionSeed("outbound:view", "查看出库单", "查看出库单"),

            // ERP 进销存基础资料
            new PermissionSeed("erp-product:view", "查看商品(ERP)", "查看ERP商品"),
            new PermissionSeed("erp-product:add", "新增商品(ERP)", "新增ERP商品"),
            new PermissionSeed("erp-product:edit", "编辑商品(ERP)", "编辑ERP商品"),
            new PermissionSeed("erp-product:delete", "删除商品(ERP)", "删除ERP商品"),
            new PermissionSeed("erp-product:cost:view", "查看商品成本价(ERP)", "查看ERP商品成本价"),
            new PermissionSeed("erp-product:cost:edit", "编辑商品成本价(ERP)", "编辑ERP商品成本价"),

            new PermissionSeed("erp-customer:view", "查看客户(ERP)", "查看ERP客户"),
            new PermissionSeed("erp-customer:add", "新增客户(ERP)", "新增ERP客户"),
            new PermissionSeed("erp-customer:edit", "编辑客户(ERP)", "编辑ERP客户"),
            new PermissionSeed("erp-customer:delete", "删除客户(ERP)", "删除ERP客户"),

            new PermissionSeed("erp-customer-category:view", "查看客户类别(ERP)", "查看ERP客户类别"),
            new PermissionSeed("erp-customer-category:add", "新增客户类别(ERP)", "新增ERP客户类别"),
            new PermissionSeed("erp-customer-category:edit", "编辑客户类别(ERP)", "编辑ERP客户类别"),
            new PermissionSeed("erp-customer-category:delete", "删除客户类别(ERP)", "删除ERP客户类别"),

            new PermissionSeed("erp-supplier:view", "查看供应商(ERP)", "查看ERP供应商"),
            new PermissionSeed("erp-supplier:add", "新增供应商(ERP)", "新增ERP供应商"),
            new PermissionSeed("erp-supplier:edit", "编辑供应商(ERP)", "编辑ERP供应商"),
            new PermissionSeed("erp-supplier:delete", "删除供应商(ERP)", "删除ERP供应商"),

            new PermissionSeed("erp-warehouse:view", "查看仓库(ERP)", "查看ERP仓库"),
            new PermissionSeed("erp-warehouse:add", "新增仓库(ERP)", "新增ERP仓库"),
            new PermissionSeed("erp-warehouse:edit", "编辑仓库(ERP)", "编辑ERP仓库"),
            new PermissionSeed("erp-warehouse:delete", "删除仓库(ERP)", "删除ERP仓库"),

            new PermissionSeed("erp-location:view", "查看库位(ERP)", "查看ERP库位"),
            new PermissionSeed("erp-location:add", "新增库位(ERP)", "新增ERP库位"),
            new PermissionSeed("erp-location:edit", "编辑库位(ERP)", "编辑ERP库位"),
            new PermissionSeed("erp-location:delete", "删除库位(ERP)", "删除ERP库位"),

            new PermissionSeed("erp-category:view", "查看分类(ERP)", "查看ERP分类"),
            new PermissionSeed("erp-category:add", "新增分类(ERP)", "新增ERP分类"),
            new PermissionSeed("erp-category:edit", "编辑分类(ERP)", "编辑ERP分类"),
            new PermissionSeed("erp-category:delete", "删除分类(ERP)", "删除ERP分类"),

            new PermissionSeed("erp-unit:view", "查看单位(ERP)", "查看ERP单位"),
            new PermissionSeed("erp-unit:add", "新增单位(ERP)", "新增ERP单位"),
            new PermissionSeed("erp-unit:edit", "编辑单位(ERP)", "编辑ERP单位"),
            new PermissionSeed("erp-unit:delete", "删除单位(ERP)", "删除ERP单位"),

            new PermissionSeed("erp-settlement-method:view", "查看结算方式(ERP)", "查看ERP结算方式"),
            new PermissionSeed("erp-settlement-method:add", "新增结算方式(ERP)", "新增ERP结算方式"),
            new PermissionSeed("erp-settlement-method:edit", "编辑结算方式(ERP)", "编辑ERP结算方式"),
            new PermissionSeed("erp-settlement-method:delete", "删除结算方式(ERP)", "删除ERP结算方式"),

            new PermissionSeed("erp-payment-method:view", "查看付款方式(ERP)", "查看ERP付款方式"),
            new PermissionSeed("erp-payment-method:add", "新增付款方式(ERP)", "新增ERP付款方式"),
            new PermissionSeed("erp-payment-method:edit", "编辑付款方式(ERP)", "编辑ERP付款方式"),
            new PermissionSeed("erp-payment-method:delete", "删除付款方式(ERP)", "删除ERP付款方式"),

            new PermissionSeed("erp-delivery-method:view", "查看送货方式(ERP)", "查看ERP送货方式"),
            new PermissionSeed("erp-delivery-method:add", "新增送货方式(ERP)", "新增ERP送货方式"),
            new PermissionSeed("erp-delivery-method:edit", "编辑送货方式(ERP)", "编辑ERP送货方式"),
            new PermissionSeed("erp-delivery-method:delete", "删除送货方式(ERP)", "删除ERP送货方式"),

            new PermissionSeed("erp-vehicle-brand:view", "查看车型品牌(ERP)", "查看ERP车型品牌"),
            new PermissionSeed("erp-vehicle-brand:add", "新增车型品牌(ERP)", "新增ERP车型品牌"),
            new PermissionSeed("erp-vehicle-brand:edit", "编辑车型品牌(ERP)", "编辑ERP车型品牌"),
            new PermissionSeed("erp-vehicle-brand:delete", "删除车型品牌(ERP)", "删除ERP车型品牌"),

            new PermissionSeed("erp-vehicle-series:view", "查看车型车系(ERP)", "查看ERP车型车系"),
            new PermissionSeed("erp-vehicle-series:add", "新增车型车系(ERP)", "新增ERP车型车系"),
            new PermissionSeed("erp-vehicle-series:edit", "编辑车型车系(ERP)", "编辑ERP车型车系"),
            new PermissionSeed("erp-vehicle-series:delete", "删除车型车系(ERP)", "删除ERP车型车系"),

            new PermissionSeed("erp-vehicle-model:view", "查看车型(ERP)", "查看ERP车型"),
            new PermissionSeed("erp-vehicle-model:add", "新增车型(ERP)", "新增ERP车型"),
            new PermissionSeed("erp-vehicle-model:edit", "编辑车型(ERP)", "编辑ERP车型"),
            new PermissionSeed("erp-vehicle-model:delete", "删除车型(ERP)", "删除ERP车型"),

            new PermissionSeed("erp-product-fitment:view", "查看商品适配车型(ERP)", "查看ERP商品适配车型"),
            new PermissionSeed("erp-product-fitment:add", "新增商品适配车型(ERP)", "新增ERP商品适配车型"),
            new PermissionSeed("erp-product-fitment:edit", "编辑商品适配车型(ERP)", "编辑ERP商品适配车型"),
            new PermissionSeed("erp-product-fitment:delete", "删除商品适配车型(ERP)", "删除ERP商品适配车型"),

            // ERP 采购/销售单据
            new PermissionSeed("erp-purchase:view", "查看采购单(ERP)", "查看ERP采购单"),
            new PermissionSeed("erp-purchase:add", "新增采购单(ERP)", "新增ERP采购单"),
            new PermissionSeed("erp-purchase:edit", "编辑采购单(ERP)", "编辑ERP采购单"),
            new PermissionSeed("erp-purchase:cancel", "作废采购单(ERP)", "作废ERP采购单"),
            new PermissionSeed("erp-purchase:approve", "审核采购单(ERP)", "审核ERP采购单"),
            new PermissionSeed("erp-purchase:unapprove", "反审核采购单(ERP)", "反审核ERP采购单"),

            new PermissionSeed("erp-purchase-return:view", "查看采购退货(ERP)", "查看ERP采购退货"),
            new PermissionSeed("erp-purchase-return:add", "新增采购退货(ERP)", "新增ERP采购退货"),
            new PermissionSeed("erp-purchase-return:edit", "编辑采购退货(ERP)", "编辑ERP采购退货"),
            new PermissionSeed("erp-purchase-return:approve", "审核采购退货(ERP)", "审核ERP采购退货"),

            new PermissionSeed("erp-sale:view", "查看销售单(ERP)", "查看ERP销售单"),
            new PermissionSeed("erp-sale:add", "新增销售单(ERP)", "新增ERP销售单"),
            new PermissionSeed("erp-sale:edit", "编辑销售单(ERP)", "编辑ERP销售单"),
            new PermissionSeed("erp-sale:cancel", "作废销售单(ERP)", "作废ERP销售单"),
            new PermissionSeed("erp-sale:approve", "审核销售单(ERP)", "审核ERP销售单"),
            new PermissionSeed("erp-sale:redflush", "红冲销售单(ERP)", "红冲ERP销售单"),

            new PermissionSeed("erp-sale-return:view", "查看销售退货(ERP)", "查看ERP销售退货"),
            new PermissionSeed("erp-sale-return:add", "新增销售退货(ERP)", "新增ERP销售退货"),
            new PermissionSeed("erp-sale-return:edit", "编辑销售退货(ERP)", "编辑ERP销售退货"),
            new PermissionSeed("erp-sale-return:cancel", "作废销售退货(ERP)", "作废ERP销售退货"),
            new PermissionSeed("erp-sale-return:approve", "审核销售退货(ERP)", "审核ERP销售退货"),
            new PermissionSeed("erp-sale-return:redflush", "红冲销售退货(ERP)", "红冲ERP销售退货"),

            // ERP 财务
            new PermissionSeed("erp-ar:view", "查看应收(ERP)", "查看ERP应收"),
            new PermissionSeed("erp-ap:view", "查看应付(ERP)", "查看ERP应付"),
            new PermissionSeed("erp-receipt:view", "查看收款单(ERP)", "查看ERP收款单"),
            new PermissionSeed("erp-receipt:add", "新增收款单(ERP)", "新增ERP收款单"),
            new PermissionSeed("erp-receipt:approve", "审核收款单(ERP)", "审核ERP收款单"),
            new PermissionSeed("erp-receipt:red-flush", "红冲收款单(ERP)", "红冲ERP收款单"),
            new PermissionSeed("erp-payment:view", "查看付款单(ERP)", "查看ERP付款单"),
            new PermissionSeed("erp-finance-summary:view", "查看财务汇总(ERP)", "查看ERP财务汇总"),
            new PermissionSeed("erp-finance-customer-debt:view", "查看客户欠款(ERP)", "查看ERP客户欠款汇总"),
            new PermissionSeed("erp-finance-supplier-debt:view", "查看供应商欠款(ERP)", "查看ERP供应商欠款汇总"),

            // ERP 库存
            new PermissionSeed("erp-stock:view", "查看库存(ERP)", "查看ERP库存"),
            new PermissionSeed("erp-stock-txn:view", "查看库存流水(ERP)", "查看ERP库存流水"),
            new PermissionSeed("erp-stock-count:view", "查看库存调整(ERP)", "查看ERP库存调整"),
            new PermissionSeed("erp-stock-count:add", "新增库存调整(ERP)", "新增ERP库存调整"),
            new PermissionSeed("erp-stock-count:edit", "编辑库存调整(ERP)", "编辑ERP库存调整"),
            new PermissionSeed("erp-stock-count:approve", "审核库存调整(ERP)", "审核ERP库存调整"),
            new PermissionSeed("erp-stock-count:cancel", "作废库存调整(ERP)", "作废ERP库存调整"),
            new PermissionSeed("erp-stock-init:view", "查看初始库存(ERP)", "查看ERP初始库存"),
            new PermissionSeed("erp-stock-init:add", "新增初始库存(ERP)", "新增ERP初始库存"),
            new PermissionSeed("erp-stock-init:edit", "编辑初始库存(ERP)", "编辑ERP初始库存"),
            new PermissionSeed("erp-stock-init:approve", "审核初始库存(ERP)", "审核ERP初始库存"),
            new PermissionSeed("erp-stock-init:redflush", "红冲初始库存(ERP)", "红冲ERP初始库存"),
            new PermissionSeed("erp-stock-init:cancel", "作废初始库存(ERP)", "作废ERP初始库存"),
            new PermissionSeed("erp-stock-warning:view", "查看库存预警(ERP)", "查看ERP库存预警"),
            new PermissionSeed("erp-assembly:view", "查看商品组装(ERP)", "查看ERP商品组装"),
            new PermissionSeed("erp-assembly:add", "新增商品组装(ERP)", "新增ERP商品组装"),
            new PermissionSeed("erp-assembly:edit", "编辑商品组装(ERP)", "编辑ERP商品组装"),
            new PermissionSeed("erp-assembly:approve", "审核商品组装(ERP)", "审核ERP商品组装"),
            new PermissionSeed("erp-assembly:delete", "删除商品组装(ERP)", "删除ERP商品组装"),

            // ERP 列权限
            new PermissionSeed("column:erp-product:code", "ERP商品-编码列", "ERP商品编码列显示"),
            new PermissionSeed("column:erp-product:name", "ERP商品-名称列", "ERP商品名称列显示"),
            new PermissionSeed("column:erp-product:category", "ERP商品-分类列", "ERP商品分类列显示"),
            new PermissionSeed("column:erp-product:unit", "ERP商品-单位列", "ERP商品单位列显示"),
            new PermissionSeed("column:erp-product:defaultWarehouse", "ERP商品-默认仓库列", "ERP商品默认仓库列显示"),
            new PermissionSeed("column:erp-product:defaultLocation", "ERP商品-默认库位列", "ERP商品默认库位列显示"),
            new PermissionSeed("column:erp-product:price", "ERP商品-价格列", "ERP商品价格列显示"),
            new PermissionSeed("column:erp-product:costPrice", "ERP商品-成本价列", "ERP商品成本价列显示"),
            new PermissionSeed("column:erp-product:minStock", "ERP商品-最低库存列", "ERP商品最低库存列显示"),
            new PermissionSeed("column:erp-product:maxStock", "ERP商品-最高库存列", "ERP商品最高库存列显示"),
            new PermissionSeed("column:erp-product:status", "ERP商品-状态列", "ERP商品状态列显示"),

            new PermissionSeed("column:erp-customer:code", "ERP客户-编码列", "ERP客户编码列显示"),
            new PermissionSeed("column:erp-customer:name", "ERP客户-名称列", "ERP客户名称列显示"),
            new PermissionSeed("column:erp-customer:category", "ERP客户-类别列", "ERP客户类别列显示"),
            new PermissionSeed("column:erp-customer:contact", "ERP客户-联系人列", "ERP客户联系人列显示"),
            new PermissionSeed("column:erp-customer:phone", "ERP客户-电话列", "ERP客户电话列显示"),
            new PermissionSeed("column:erp-customer:email", "ERP客户-邮箱列", "ERP客户邮箱列显示"),
            new PermissionSeed("column:erp-customer:status", "ERP客户-状态列", "ERP客户状态列显示"),

            new PermissionSeed("column:erp-customer-category:code", "ERP客户类别-编码列", "ERP客户类别编码列显示"),
            new PermissionSeed("column:erp-customer-category:name", "ERP客户类别-名称列", "ERP客户类别名称列显示"),
            new PermissionSeed("column:erp-customer-category:description", "ERP客户类别-描述列", "ERP客户类别描述列显示"),
            new PermissionSeed("column:erp-customer-category:sort", "ERP客户类别-排序列", "ERP客户类别排序列显示"),
            new PermissionSeed("column:erp-customer-category:default", "ERP客户类别-默认列", "ERP客户类别默认列显示"),
            new PermissionSeed("column:erp-customer-category:status", "ERP客户类别-状态列", "ERP客户类别状态列显示"),

            new PermissionSeed("column:erp-supplier:code", "ERP供应商-编码列", "ERP供应商编码列显示"),
            new PermissionSeed("column:erp-supplier:name", "ERP供应商-名称列", "ERP供应商名称列显示"),
            new PermissionSeed("column:erp-supplier:contact", "ERP供应商-联系人列", "ERP供应商联系人列显示"),
            new PermissionSeed("column:erp-supplier:phone", "ERP供应商-电话列", "ERP供应商电话列显示"),
            new PermissionSeed("column:erp-supplier:mobile", "ERP供应商-手机列", "ERP供应商手机列显示"),
            new PermissionSeed("column:erp-supplier:email", "ERP供应商-邮箱列", "ERP供应商邮箱列显示"),
            new PermissionSeed("column:erp-supplier:status", "ERP供应商-状态列", "ERP供应商状态列显示"),

            new PermissionSeed("column:erp-warehouse:code", "ERP仓库-编码列", "ERP仓库编码列显示"),
            new PermissionSeed("column:erp-warehouse:name", "ERP仓库-名称列", "ERP仓库名称列显示"),
            new PermissionSeed("column:erp-warehouse:address", "ERP仓库-地址列", "ERP仓库地址列显示"),
            new PermissionSeed("column:erp-warehouse:manager", "ERP仓库-负责人列", "ERP仓库负责人列显示"),
            new PermissionSeed("column:erp-warehouse:phone", "ERP仓库-电话列", "ERP仓库电话列显示"),
            new PermissionSeed("column:erp-warehouse:status", "ERP仓库-状态列", "ERP仓库状态列显示"),

            new PermissionSeed("column:erp-location:code", "ERP库位-编码列", "ERP库位编码列显示"),
            new PermissionSeed("column:erp-location:name", "ERP库位-名称列", "ERP库位名称列显示"),
            new PermissionSeed("column:erp-location:warehouse", "ERP库位-仓库列", "ERP库位仓库列显示"),
            new PermissionSeed("column:erp-location:aisle", "ERP库位-巷道列", "ERP库位巷道列显示"),
            new PermissionSeed("column:erp-location:rack", "ERP库位-货架列", "ERP库位货架列显示"),
            new PermissionSeed("column:erp-location:bin", "ERP库位-货位列", "ERP库位货位列显示"),
            new PermissionSeed("column:erp-location:status", "ERP库位-状态列", "ERP库位状态列显示"),

            new PermissionSeed("column:erp-category:code", "ERP分类-编码列", "ERP分类编码列显示"),
            new PermissionSeed("column:erp-category:name", "ERP分类-名称列", "ERP分类名称列显示"),
            new PermissionSeed("column:erp-category:parent", "ERP分类-上级列", "ERP分类上级列显示"),
            new PermissionSeed("column:erp-category:level", "ERP分类-层级列", "ERP分类层级列显示"),
            new PermissionSeed("column:erp-category:sort", "ERP分类-排序列", "ERP分类排序列显示"),
            new PermissionSeed("column:erp-category:status", "ERP分类-状态列", "ERP分类状态列显示"),

            new PermissionSeed("column:erp-unit:code", "ERP单位-编码列", "ERP单位编码列显示"),
            new PermissionSeed("column:erp-unit:name", "ERP单位-名称列", "ERP单位名称列显示"),
            new PermissionSeed("column:erp-unit:symbol", "ERP单位-符号列", "ERP单位符号列显示"),
            new PermissionSeed("column:erp-unit:precision", "ERP单位-精度列", "ERP单位精度列显示"),
            new PermissionSeed("column:erp-unit:status", "ERP单位-状态列", "ERP单位状态列显示"),

            new PermissionSeed("column:erp-settlement-method:code", "ERP结算方式-编码列", "ERP结算方式编码列显示"),
            new PermissionSeed("column:erp-settlement-method:name", "ERP结算方式-名称列", "ERP结算方式名称列显示"),
            new PermissionSeed("column:erp-settlement-method:sort", "ERP结算方式-排序列", "ERP结算方式排序列显示"),
            new PermissionSeed("column:erp-settlement-method:status", "ERP结算方式-状态列", "ERP结算方式状态列显示"),

            new PermissionSeed("column:erp-payment-method:code", "ERP付款方式-编码列", "ERP付款方式编码列显示"),
            new PermissionSeed("column:erp-payment-method:name", "ERP付款方式-名称列", "ERP付款方式名称列显示"),
            new PermissionSeed("column:erp-payment-method:sort", "ERP付款方式-排序列", "ERP付款方式排序列显示"),
            new PermissionSeed("column:erp-payment-method:status", "ERP付款方式-状态列", "ERP付款方式状态列显示"),

            new PermissionSeed("column:erp-delivery-method:code", "ERP送货方式-编码列", "ERP送货方式编码列显示"),
            new PermissionSeed("column:erp-delivery-method:name", "ERP送货方式-名称列", "ERP送货方式名称列显示"),
            new PermissionSeed("column:erp-delivery-method:sort", "ERP送货方式-排序列", "ERP送货方式排序列显示"),
            new PermissionSeed("column:erp-delivery-method:status", "ERP送货方式-状态列", "ERP送货方式状态列显示"),

            new PermissionSeed("column:erp-purchase:orderNo", "ERP采购-单号列", "ERP采购单号列显示"),
            new PermissionSeed("column:erp-purchase:supplier", "ERP采购-供应商列", "ERP采购供应商列显示"),
            new PermissionSeed("column:erp-purchase:status", "ERP采购-状态列", "ERP采购状态列显示"),
            new PermissionSeed("column:erp-purchase:totalAmount", "ERP采购-总金额列", "ERP采购总金额列显示"),
            new PermissionSeed("column:erp-purchase:createdAt", "ERP采购-创建时间列", "ERP采购创建时间列显示"),

            new PermissionSeed("column:erp-sale:orderNo", "ERP销售-单号列", "ERP销售单号列显示"),
            new PermissionSeed("column:erp-sale:customer", "ERP销售-客户列", "ERP销售客户列显示"),
            new PermissionSeed("column:erp-sale:status", "ERP销售-状态列", "ERP销售状态列显示"),
            new PermissionSeed("column:erp-sale:totalAmount", "ERP销售-总金额列", "ERP销售总金额列显示"),
            new PermissionSeed("column:erp-sale:createdAt", "ERP销售-创建时间列", "ERP销售创建时间列显示"),
            new PermissionSeed("column:erp-sale:profit", "ERP销售-利润列", "ERP销售利润列显示"),
            new PermissionSeed("column:erp-sale:discountAllocated", "ERP销售-分摊优惠列", "ERP销售分摊优惠列显示"),

            new PermissionSeed("column:erp-stock:product", "ERP库存-商品列", "ERP库存商品列显示"),
            new PermissionSeed("column:erp-stock:warehouse", "ERP库存-仓库列", "ERP库存仓库列显示"),
            new PermissionSeed("column:erp-stock:location", "ERP库存-库位列", "ERP库存库位列显示"),
            new PermissionSeed("column:erp-stock:qty", "ERP库存-数量列", "ERP库存数量列显示"),
            new PermissionSeed("column:erp-stock:updatedAt", "ERP库存-更新时间列", "ERP库存更新时间列显示"),

            new PermissionSeed("column:erp-stock-txn:txnNo", "ERP流水-流水号列", "ERP流水流水号列显示"),
            new PermissionSeed("column:erp-stock-txn:bizType", "ERP流水-业务类型列", "ERP流水业务类型列显示"),
            new PermissionSeed("column:erp-stock-txn:product", "ERP流水-商品列", "ERP流水商品列显示"),
            new PermissionSeed("column:erp-stock-txn:warehouse", "ERP流水-仓库列", "ERP流水仓库列显示"),
            new PermissionSeed("column:erp-stock-txn:location", "ERP流水-库位列", "ERP流水库位列显示"),
            new PermissionSeed("column:erp-stock-txn:qtyDelta", "ERP流水-变更数量列", "ERP流水变更数量列显示"),
            new PermissionSeed("column:erp-stock-txn:qtyBefore", "ERP流水-变更前列", "ERP流水变更前列显示"),
            new PermissionSeed("column:erp-stock-txn:qtyAfter", "ERP流水-变更后列", "ERP流水变更后列显示"),
            new PermissionSeed("column:erp-stock-txn:unitCost", "ERP流水-单位成本列", "ERP流水单位成本列显示"),
            new PermissionSeed("column:erp-stock-txn:totalCost", "ERP流水-总成本列", "ERP流水总成本列显示"),
            new PermissionSeed("column:erp-stock-txn:createdAt", "ERP流水-时间列", "ERP流水时间列显示"),

            new PermissionSeed("tenant:view", "查看租户", "查看租户列表"),
            new PermissionSeed("tenant:add", "新增租户", "新增租户"),
            new PermissionSeed("tenant:edit", "编辑租户", "编辑租户信息"),
            new PermissionSeed("tenant:delete", "删除租户", "删除租户"),
            new PermissionSeed("tenant:disable", "停用租户", "停用/启用租户"),
            new PermissionSeed("tenant:switch", "切换租户", "切换到指定租户")
        );
    }

    public record PermissionSeed(String code, String name, String description) {
    }
}
