package com.example.wms.config;

import java.util.List;

// 权限种子提供器
public final class PermissionSeedProvider {
    private PermissionSeedProvider() {
    }

    public static List<PermissionSeed> permissionSeeds() {
        return List.of(
            new PermissionSeed("user:view", "查看用户", "查看用户列表"),
            new PermissionSeed("user:add", "新增用户", "新增用户"),
            new PermissionSeed("user:edit", "编辑用户", "编辑用户"),
            new PermissionSeed("user:delete", "删除用户", "删除用户"),

            new PermissionSeed("role:view", "查看角色", "查看角色与权限"),
            new PermissionSeed("role:add", "新增角色", "新增角色"),
            new PermissionSeed("role:edit", "编辑角色", "编辑角色"),
            new PermissionSeed("role:delete", "删除角色", "删除角色"),
            new PermissionSeed("role:assign:view", "查看角色选项", "用户管理角色下拉选项"),
            new PermissionSeed("column:role:manage", "配置角色列权限", "角色列权限配置"),

            new PermissionSeed("permission:view", "查看权限", "查看权限定义列表"),
            new PermissionSeed("permission:add", "新增权限", "新增权限定义"),
            new PermissionSeed("permission:edit", "编辑权限", "编辑权限定义"),
            new PermissionSeed("permission:delete", "删除权限", "删除权限定义"),

            new PermissionSeed("menu:view", "查看菜单", "查看菜单定义列表"),
            new PermissionSeed("menu:add", "新增菜单", "新增菜单定义"),
            new PermissionSeed("menu:edit", "编辑菜单", "编辑菜单定义"),
            new PermissionSeed("menu:delete", "删除菜单", "删除菜单定义"),

            new PermissionSeed("audit:view", "查看审计日志", "查看系统审计日志"),
            new PermissionSeed("column:edit", "配置列显示", "租户列显示配置"),
            new PermissionSeed("column:user-management:avatar", "用户管理-头像列", "用户管理头像列显示"),
            new PermissionSeed("column:user-management:username", "用户管理-用户名列", "用户管理用户名列显示"),
            new PermissionSeed("column:user-management:displayName", "用户管理-姓名列", "用户管理姓名列显示"),
            new PermissionSeed("column:user-management:roles", "用户管理-角色列", "用户管理角色列显示"),
            new PermissionSeed("column:user-management:contact", "用户管理-联系方式列", "用户管理联系方式列显示"),
            new PermissionSeed("column:user-management:status", "用户管理-状态列", "用户管理状态列显示"),
            new PermissionSeed("column:user-management:loginTime", "用户管理-登录时间列", "用户管理登录时间列显示"),

            new PermissionSeed("column:role-management:name", "角色管理-名称列", "角色管理名称列显示"),
            new PermissionSeed("column:role-management:code", "角色管理-编码列", "角色管理编码列显示"),
            new PermissionSeed("column:role-management:description", "角色管理-描述列", "角色管理描述列显示"),
            new PermissionSeed("column:role-management:status", "角色管理-状态列", "角色管理状态列显示"),

            new PermissionSeed("column:permission-management:name", "权限管理-名称列", "权限管理名称列显示"),
            new PermissionSeed("column:permission-management:code", "权限管理-编码列", "权限管理编码列显示"),
            new PermissionSeed("column:permission-management:description", "权限管理-描述列", "权限管理描述列显示"),
            new PermissionSeed("column:permission-management:status", "权限管理-状态列", "权限管理状态列显示"),

            new PermissionSeed("column:audit-logs:tenant", "审计日志-租户列", "审计日志租户列显示"),
            new PermissionSeed("column:audit-logs:actor", "审计日志-操作者列", "审计日志操作者列显示"),
            new PermissionSeed("column:audit-logs:action", "审计日志-动作列", "审计日志动作列显示"),
            new PermissionSeed("column:audit-logs:entityType", "审计日志-实体类型列", "审计日志实体类型列显示"),
            new PermissionSeed("column:audit-logs:entityId", "审计日志-实体ID列", "审计日志实体ID列显示"),
            new PermissionSeed("column:audit-logs:detail", "审计日志-详情列", "审计日志详情列显示"),
            new PermissionSeed("column:audit-logs:deleteReason", "审计日志-删除原因列", "审计日志删除原因列显示"),
            new PermissionSeed("column:audit-logs:status", "审计日志-结果列", "审计日志结果列显示"),
            new PermissionSeed("column:audit-logs:requestId", "审计日志-请求ID列", "审计日志请求ID列显示"),
            new PermissionSeed("column:audit-logs:clientIp", "审计日志-客户端IP列", "审计日志客户端IP列显示"),
            new PermissionSeed("column:audit-logs:userAgent", "审计日志-客户端UA列", "审计日志客户端UA列显示"),
            new PermissionSeed("column:audit-logs:method", "审计日志-请求方法列", "审计日志请求方法列显示"),
            new PermissionSeed("column:audit-logs:path", "审计日志-请求路径列", "审计日志请求路径列显示"),
            new PermissionSeed("column:audit-logs:httpStatus", "审计日志-HTTP状态列", "审计日志HTTP状态列显示"),
            new PermissionSeed("column:audit-logs:errorCode", "审计日志-错误码列", "审计日志错误码列显示"),
            new PermissionSeed("column:audit-logs:errorMessage", "审计日志-错误信息列", "审计日志错误信息列显示"),
            new PermissionSeed("column:audit-logs:durationMs", "审计日志-耗时列", "审计日志耗时列显示"),
            new PermissionSeed("column:audit-logs:createdAt", "审计日志-时间列", "审计日志时间列显示"),

            new PermissionSeed("column:system-configs:key", "系统配置-键列", "系统配置键列显示"),
            new PermissionSeed("column:system-configs:value", "系统配置-值列", "系统配置值列显示"),
            new PermissionSeed("column:system-configs:type", "系统配置-类型列", "系统配置类型列显示"),
            new PermissionSeed("column:system-configs:description", "系统配置-描述列", "系统配置描述列显示"),
            new PermissionSeed("column:system-configs:public", "系统配置-公开列", "系统配置公开列显示"),
            new PermissionSeed("column:system-configs:updatedAt", "系统配置-更新时间列", "系统配置更新时间列显示"),

            new PermissionSeed("column:menu-management:title", "菜单管理-标题列", "菜单管理标题列显示"),
            new PermissionSeed("column:menu-management:code", "菜单管理-编码列", "菜单管理编码列显示"),
            new PermissionSeed("column:menu-management:path", "菜单管理-路径列", "菜单管理路径列显示"),
            new PermissionSeed("column:menu-management:permissionCode", "菜单管理-权限列", "菜单管理权限列显示"),
            new PermissionSeed("column:menu-management:sort", "菜单管理-排序列", "菜单管理排序列显示"),
            new PermissionSeed("column:menu-management:status", "菜单管理-状态列", "菜单管理状态列显示"),

            new PermissionSeed("column:tenant-management:code", "租户管理-编码列", "租户管理编码列显示"),
            new PermissionSeed("column:tenant-management:name", "租户管理-名称列", "租户管理名称列显示"),
            new PermissionSeed("column:tenant-management:status", "租户管理-状态列", "租户管理状态列显示"),
            new PermissionSeed("column:tenant-management:createdAt", "租户管理-创建时间列", "租户管理创建时间列显示"),

            new PermissionSeed("system-config:view", "查看系统配置", "查看系统配置"),
            new PermissionSeed("system-config:edit", "编辑系统配置", "编辑系统配置"),

            // ERP 进销存基础资料
            new PermissionSeed("erp-product:view", "查看商品(ERP)", "查看ERP商品"),
            new PermissionSeed("erp-product:add", "新增商品(ERP)", "新增ERP商品"),
            new PermissionSeed("erp-product:edit", "编辑商品(ERP)", "编辑ERP商品"),
            new PermissionSeed("erp-product:delete", "删除商品(ERP)", "删除ERP商品"),
            new PermissionSeed("erp-product:cost:view", "查看商品成本价(ERP)", "查看ERP商品成本价"),
            new PermissionSeed("erp-product:cost:edit", "编辑商品成本价(ERP)", "编辑ERP商品成本价"),

            new PermissionSeed("erp-customer:view", "查看客户(ERP)", "查看ERP客户"),
            new PermissionSeed("erp-customer:add", "新增客户(ERP)", "新增ERP客户"),
            new PermissionSeed("erp-customer:edit", "编辑客户(ERP)", "编辑ERP客户"),
            new PermissionSeed("erp-customer:delete", "删除客户(ERP)", "删除ERP客户"),

            new PermissionSeed("erp-customer-category:view", "查看客户类别(ERP)", "查看ERP客户类别"),
            new PermissionSeed("erp-customer-category:add", "新增客户类别(ERP)", "新增ERP客户类别"),
            new PermissionSeed("erp-customer-category:edit", "编辑客户类别(ERP)", "编辑ERP客户类别"),
            new PermissionSeed("erp-customer-category:delete", "删除客户类别(ERP)", "删除ERP客户类别"),

            new PermissionSeed("erp-supplier:view", "查看供应商(ERP)", "查看ERP供应商"),
            new PermissionSeed("erp-supplier:add", "新增供应商(ERP)", "新增ERP供应商"),
            new PermissionSeed("erp-supplier:edit", "编辑供应商(ERP)", "编辑ERP供应商"),
            new PermissionSeed("erp-supplier:delete", "删除供应商(ERP)", "删除ERP供应商"),

            new PermissionSeed("erp-warehouse:view", "查看仓库(ERP)", "查看ERP仓库"),
            new PermissionSeed("erp-warehouse:add", "新增仓库(ERP)", "新增ERP仓库"),
            new PermissionSeed("erp-warehouse:edit", "编辑仓库(ERP)", "编辑ERP仓库"),
            new PermissionSeed("erp-warehouse:delete", "删除仓库(ERP)", "删除ERP仓库"),

            new PermissionSeed("erp-location:view", "查看库位(ERP)", "查看ERP库位"),
            new PermissionSeed("erp-location:add", "新增库位(ERP)", "新增ERP库位"),
            new PermissionSeed("erp-location:edit", "编辑库位(ERP)", "编辑ERP库位"),
            new PermissionSeed("erp-location:delete", "删除库位(ERP)", "删除ERP库位"),

            new PermissionSeed("erp-category:view", "查看分类(ERP)", "查看ERP分类"),
            new PermissionSeed("erp-category:add", "新增分类(ERP)", "新增ERP分类"),
            new PermissionSeed("erp-category:edit", "编辑分类(ERP)", "编辑ERP分类"),
            new PermissionSeed("erp-category:delete", "删除分类(ERP)", "删除ERP分类"),

            new PermissionSeed("erp-unit:view", "查看单位(ERP)", "查看ERP单位"),
            new PermissionSeed("erp-unit:add", "新增单位(ERP)", "新增ERP单位"),
            new PermissionSeed("erp-unit:edit", "编辑单位(ERP)", "编辑ERP单位"),
            new PermissionSeed("erp-unit:delete", "删除单位(ERP)", "删除ERP单位"),

            new PermissionSeed("erp-settlement-method:view", "查看结算方式(ERP)", "查看ERP结算方式"),
            new PermissionSeed("erp-settlement-method:add", "新增结算方式(ERP)", "新增ERP结算方式"),
            new PermissionSeed("erp-settlement-method:edit", "编辑结算方式(ERP)", "编辑ERP结算方式"),
            new PermissionSeed("erp-settlement-method:delete", "删除结算方式(ERP)", "删除ERP结算方式"),

            new PermissionSeed("erp-payment-method:view", "查看付款方式(ERP)", "查看ERP付款方式"),
            new PermissionSeed("erp-payment-method:add", "新增付款方式(ERP)", "新增ERP付款方式"),
            new PermissionSeed("erp-payment-method:edit", "编辑付款方式(ERP)", "编辑ERP付款方式"),
            new PermissionSeed("erp-payment-method:delete", "删除付款方式(ERP)", "删除ERP付款方式"),

            new PermissionSeed("erp-receipt-method:view", "查看收款方式(ERP)", "查看ERP收款方式"),
            new PermissionSeed("erp-receipt-method:add", "新增收款方式(ERP)", "新增ERP收款方式"),
            new PermissionSeed("erp-receipt-method:edit", "编辑收款方式(ERP)", "编辑ERP收款方式"),
            new PermissionSeed("erp-receipt-method:delete", "删除收款方式(ERP)", "删除ERP收款方式"),

            new PermissionSeed("erp-delivery-method:view", "查看送货方式(ERP)", "查看ERP送货方式"),
            new PermissionSeed("erp-delivery-method:add", "新增送货方式(ERP)", "新增ERP送货方式"),
            new PermissionSeed("erp-delivery-method:edit", "编辑送货方式(ERP)", "编辑ERP送货方式"),
            new PermissionSeed("erp-delivery-method:delete", "删除送货方式(ERP)", "删除ERP送货方式"),

            new PermissionSeed("erp-vehicle-brand:view", "查看车型品牌(ERP)", "查看ERP车型品牌"),
            new PermissionSeed("erp-vehicle-brand:add", "新增车型品牌(ERP)", "新增ERP车型品牌"),
            new PermissionSeed("erp-vehicle-brand:edit", "编辑车型品牌(ERP)", "编辑ERP车型品牌"),
            new PermissionSeed("erp-vehicle-brand:delete", "删除车型品牌(ERP)", "删除ERP车型品牌"),

            new PermissionSeed("erp-vehicle-series:view", "查看车型车系(ERP)", "查看ERP车型车系"),
            new PermissionSeed("erp-vehicle-series:add", "新增车型车系(ERP)", "新增ERP车型车系"),
            new PermissionSeed("erp-vehicle-series:edit", "编辑车型车系(ERP)", "编辑ERP车型车系"),
            new PermissionSeed("erp-vehicle-series:delete", "删除车型车系(ERP)", "删除ERP车型车系"),

            new PermissionSeed("erp-vehicle-model:view", "查看车型(ERP)", "查看ERP车型"),
            new PermissionSeed("erp-vehicle-model:add", "新增车型(ERP)", "新增ERP车型"),
            new PermissionSeed("erp-vehicle-model:edit", "编辑车型(ERP)", "编辑ERP车型"),
            new PermissionSeed("erp-vehicle-model:delete", "删除车型(ERP)", "删除ERP车型"),

            new PermissionSeed("erp-product-fitment:view", "查看商品适配车型(ERP)", "查看ERP商品适配车型"),
            new PermissionSeed("erp-product-fitment:add", "新增商品适配车型(ERP)", "新增ERP商品适配车型"),
            new PermissionSeed("erp-product-fitment:edit", "编辑商品适配车型(ERP)", "编辑ERP商品适配车型"),
            new PermissionSeed("erp-product-fitment:delete", "删除商品适配车型(ERP)", "删除ERP商品适配车型"),

            // ERP 采购/销售单据
            new PermissionSeed("erp-purchase:view", "查看采购单(ERP)", "查看ERP采购单"),
            new PermissionSeed("erp-purchase:add", "新增采购单(ERP)", "新增ERP采购单"),
            new PermissionSeed("erp-purchase:edit", "编辑采购单(ERP)", "编辑ERP采购单"),
            new PermissionSeed("erp-purchase:cancel", "作废采购单(ERP)", "作废ERP采购单"),
            new PermissionSeed("erp-purchase:approve", "审核采购单(ERP)", "审核ERP采购单"),
            new PermissionSeed("erp-purchase:unapprove", "反审核采购单(ERP)", "反审核ERP采购单"),
            new PermissionSeed("erp-purchase-draft:view", "查看采购单草稿(ERP)", "查看ERP采购单草稿"),
            new PermissionSeed("erp-purchase-draft:add", "新增采购单草稿(ERP)", "新增ERP采购单草稿"),
            new PermissionSeed("erp-purchase-draft:edit", "编辑采购单草稿(ERP)", "编辑ERP采购单草稿"),
            new PermissionSeed("erp-purchase-draft:delete", "删除采购单草稿(ERP)", "删除ERP采购单草稿"),
            new PermissionSeed("erp-purchase-draft:approve", "审核采购单草稿(ERP)", "审核ERP采购单草稿"),
            new PermissionSeed("erp-purchase-draft:print", "打印采购单草稿(ERP)", "打印ERP采购单草稿"),
            new PermissionSeed("erp-purchase-approved:view", "查看已审核采购单(ERP)", "查看ERP已审核采购单"),
            new PermissionSeed("erp-purchase-approved:copy", "复制已审核采购单(ERP)", "复制ERP已审核采购单为草稿"),
            new PermissionSeed("erp-purchase-approved:unapprove", "反审核已审核采购单(ERP)", "反审核ERP已审核采购单"),
            new PermissionSeed("erp-purchase-approved:cancel", "作废已审核采购单(ERP)", "作废ERP已审核采购单"),
            new PermissionSeed("erp-purchase-approved:print", "打印已审核采购单(ERP)", "打印ERP已审核采购单"),

            new PermissionSeed("erp-purchase-return-draft:view", "查看采购退货草稿(ERP)", "查看ERP采购退货草稿"),
            new PermissionSeed("erp-purchase-return-draft:add", "新增采购退货草稿(ERP)", "新增ERP采购退货草稿"),
            new PermissionSeed("erp-purchase-return-draft:edit", "编辑采购退货草稿(ERP)", "编辑ERP采购退货草稿"),
            new PermissionSeed("erp-purchase-return-draft:delete", "删除采购退货草稿(ERP)", "删除ERP采购退货草稿"),
            new PermissionSeed("erp-purchase-return-draft:approve", "审核采购退货草稿(ERP)", "审核ERP采购退货草稿"),
            new PermissionSeed("erp-purchase-return-draft:print", "打印采购退货草稿(ERP)", "打印ERP采购退货草稿"),
            new PermissionSeed("erp-purchase-return-draft:source-view", "查看采购退货来源采购单(ERP)", "查看采购退货可引用的来源采购单"),
            new PermissionSeed("erp-purchase-return-approved:view", "查看已审核采购退货(ERP)", "查看ERP已审核采购退货"),
            new PermissionSeed("erp-purchase-return-approved:copy", "复制已审核采购退货(ERP)", "复制ERP已审核采购退货为草稿"),
            new PermissionSeed("erp-purchase-return-approved:cancel", "作废已审核采购退货(ERP)", "作废ERP已审核采购退货"),
            new PermissionSeed("erp-purchase-return-approved:print", "打印已审核采购退货(ERP)", "打印ERP已审核采购退货"),

            new PermissionSeed("erp-sale:view", "查看销售单(ERP)", "查看ERP销售单"),
            new PermissionSeed("erp-sale:add", "新增销售单(ERP)", "新增ERP销售单"),
            new PermissionSeed("erp-sale:edit", "编辑销售单(ERP)", "编辑ERP销售单"),
            new PermissionSeed("erp-sale:cancel", "作废销售单(ERP)", "作废ERP销售单"),
            new PermissionSeed("erp-sale:approve", "审核销售单(ERP)", "审核ERP销售单"),
            new PermissionSeed("erp-sale:redflush", "红冲销售单(ERP)", "红冲ERP销售单"),
            new PermissionSeed("erp-sale-draft:view", "查看销售单草稿(ERP)", "查看ERP销售单草稿"),
            new PermissionSeed("erp-sale-draft:add", "新增销售单草稿(ERP)", "新增ERP销售单草稿"),
            new PermissionSeed("erp-sale-draft:edit", "编辑销售单草稿(ERP)", "编辑ERP销售单草稿"),
            new PermissionSeed("erp-sale-draft:delete", "删除销售单草稿(ERP)", "删除ERP销售单草稿"),
            new PermissionSeed("erp-sale-draft:approve", "审核销售单草稿(ERP)", "审核ERP销售单草稿"),
            new PermissionSeed("erp-sale-draft:print", "打印销售单草稿(ERP)", "打印ERP销售单草稿"),
            new PermissionSeed("erp-sale-approved:view", "查看已审核销售单(ERP)", "查看ERP已审核销售单"),
            new PermissionSeed("erp-sale-approved:copy", "复制已审核销售单(ERP)", "复制ERP已审核销售单为草稿"),
            new PermissionSeed("erp-sale-approved:cancel", "作废已审核销售单(ERP)", "作废ERP已审核销售单"),
            new PermissionSeed("erp-sale-approved:redflush", "红冲已审核销售单(ERP)", "红冲ERP已审核销售单"),
            new PermissionSeed("erp-sale-approved:print", "打印已审核销售单(ERP)", "打印ERP已审核销售单"),

            new PermissionSeed("erp-sale-return-draft:view", "查看销售退货草稿(ERP)", "查看ERP销售退货草稿"),
            new PermissionSeed("erp-sale-return-draft:add", "新增销售退货草稿(ERP)", "新增ERP销售退货草稿"),
            new PermissionSeed("erp-sale-return-draft:edit", "编辑销售退货草稿(ERP)", "编辑ERP销售退货草稿"),
            new PermissionSeed("erp-sale-return-draft:delete", "删除销售退货草稿(ERP)", "删除ERP销售退货草稿"),
            new PermissionSeed("erp-sale-return-draft:approve", "审核销售退货草稿(ERP)", "审核ERP销售退货草稿"),
            new PermissionSeed("erp-sale-return-draft:print", "打印销售退货草稿(ERP)", "打印ERP销售退货草稿"),
            new PermissionSeed("erp-sale-return-draft:source-view", "查看销售退货来源销售单(ERP)", "查看销售退货可引用的来源销售单"),
            new PermissionSeed("erp-sale-return-approved:view", "查看已审核销售退货(ERP)", "查看ERP已审核销售退货"),
            new PermissionSeed("erp-sale-return-approved:copy", "复制已审核销售退货(ERP)", "复制ERP已审核销售退货为草稿"),
            new PermissionSeed("erp-sale-return-approved:redflush", "红冲已审核销售退货(ERP)", "红冲ERP已审核销售退货"),
            new PermissionSeed("erp-sale-return-approved:print", "打印已审核销售退货(ERP)", "打印ERP已审核销售退货"),

            // ERP 财务
            new PermissionSeed("erp-ar:view", "查看应收(ERP)", "查看ERP应收"),
            new PermissionSeed("erp-ap:view", "查看应付(ERP)", "查看ERP应付"),
            new PermissionSeed("erp-receipt:view", "查看收款单(ERP)", "查看ERP收款单"),
            new PermissionSeed("erp-receipt:add", "新增收款单(ERP)", "新增ERP收款单"),
            new PermissionSeed("erp-receipt:source-view", "查看收款单来源应收单(ERP)", "查看收款单可引用的来源应收单"),
            new PermissionSeed("erp-receipt:approve", "审核收款单(ERP)", "审核ERP收款单"),
            new PermissionSeed("erp-receipt:red-flush", "红冲收款单(ERP)", "红冲ERP收款单"),
            new PermissionSeed("erp-payment:view", "查看付款单(ERP)", "查看ERP付款单"),
            new PermissionSeed("erp-payment:add", "新增付款单(ERP)", "新增ERP付款单"),
            new PermissionSeed("erp-payment:source-view", "查看付款单来源应付单(ERP)", "查看付款单可引用的来源应付单"),
            new PermissionSeed("erp-payment:approve", "审核付款单(ERP)", "审核ERP付款单"),
            new PermissionSeed("erp-payment:red-flush", "红冲付款单(ERP)", "红冲ERP付款单"),
            new PermissionSeed("erp-finance-summary:view", "查看财务汇总(ERP)", "查看ERP财务汇总"),
            new PermissionSeed("erp-finance-customer-debt:view", "查看客户欠款(ERP)", "查看ERP客户欠款汇总"),
            new PermissionSeed("erp-finance-supplier-debt:view", "查看供应商欠款(ERP)", "查看ERP供应商欠款汇总"),

            // ERP 库存
            new PermissionSeed("erp-stock:view", "查看库存(ERP)", "查看ERP库存"),
            new PermissionSeed("erp-stock-txn:view", "查看库存流水(ERP)", "查看ERP库存流水"),
            new PermissionSeed("erp-stock-count:view", "查看库存调整(ERP)", "查看ERP库存调整"),
            new PermissionSeed("erp-stock-count:add", "新增库存调整(ERP)", "新增ERP库存调整"),
            new PermissionSeed("erp-stock-count:edit", "编辑库存调整(ERP)", "编辑ERP库存调整"),
            new PermissionSeed("erp-stock-count:approve", "审核库存调整(ERP)", "审核ERP库存调整"),
            new PermissionSeed("erp-stock-count:cancel", "作废库存调整(ERP)", "作废ERP库存调整"),
            new PermissionSeed("erp-stock-transfer:view", "查看库存移库(ERP)", "查看ERP库存移库"),
            new PermissionSeed("erp-stock-transfer:add", "新增库存移库(ERP)", "新增ERP库存移库"),
            new PermissionSeed("erp-stock-transfer:edit", "编辑库存移库(ERP)", "编辑ERP库存移库"),
            new PermissionSeed("erp-stock-transfer:approve", "审核库存移库(ERP)", "审核ERP库存移库"),
            new PermissionSeed("erp-stock-transfer:cancel", "作废库存移库(ERP)", "作废ERP库存移库"),
            new PermissionSeed("erp-stock-init:view", "查看初始库存(ERP)", "查看ERP初始库存"),
            new PermissionSeed("erp-stock-init:add", "新增初始库存(ERP)", "新增ERP初始库存"),
            new PermissionSeed("erp-stock-init:edit", "编辑初始库存(ERP)", "编辑ERP初始库存"),
            new PermissionSeed("erp-stock-init:approve", "审核初始库存(ERP)", "审核ERP初始库存"),
            new PermissionSeed("erp-stock-init:redflush", "红冲初始库存(ERP)", "红冲ERP初始库存"),
            new PermissionSeed("erp-stock-init:cancel", "作废初始库存(ERP)", "作废ERP初始库存"),
            new PermissionSeed("erp-stock-warning:view", "查看库存预警(ERP)", "查看ERP库存预警"),
            new PermissionSeed("erp-assembly:view", "查看商品组装(ERP)", "查看ERP商品组装"),
            new PermissionSeed("erp-assembly:add", "新增商品组装(ERP)", "新增ERP商品组装"),
            new PermissionSeed("erp-assembly:edit", "编辑商品组装(ERP)", "编辑ERP商品组装"),
            new PermissionSeed("erp-assembly:approve", "审核商品组装(ERP)", "审核ERP商品组装"),
            new PermissionSeed("erp-assembly:delete", "删除商品组装(ERP)", "删除ERP商品组装"),

            // ERP 列权限
            new PermissionSeed("column:erp-product:code", "ERP商品-编码列", "ERP商品编码列显示"),
            new PermissionSeed("column:erp-product:name", "ERP商品-名称列", "ERP商品名称列显示"),
            new PermissionSeed("column:erp-product:category", "ERP商品-分类列", "ERP商品分类列显示"),
            new PermissionSeed("column:erp-product:unit", "ERP商品-单位列", "ERP商品单位列显示"),
            new PermissionSeed("column:erp-product:defaultWarehouse", "ERP商品-默认仓库列", "ERP商品默认仓库列显示"),
            new PermissionSeed("column:erp-product:defaultLocation", "ERP商品-默认库位列", "ERP商品默认库位列显示"),
            new PermissionSeed("column:erp-product:price", "ERP商品-价格列", "ERP商品价格列显示"),
            new PermissionSeed("column:erp-product:costPrice", "ERP商品-成本价列", "ERP商品成本价列显示"),
            new PermissionSeed("column:erp-product:minStock", "ERP商品-最低库存列", "ERP商品最低库存列显示"),
            new PermissionSeed("column:erp-product:maxStock", "ERP商品-最高库存列", "ERP商品最高库存列显示"),
            new PermissionSeed("column:erp-product:status", "ERP商品-状态列", "ERP商品状态列显示"),

            new PermissionSeed("column:erp-customer:code", "ERP客户-编码列", "ERP客户编码列显示"),
            new PermissionSeed("column:erp-customer:name", "ERP客户-名称列", "ERP客户名称列显示"),
            new PermissionSeed("column:erp-customer:category", "ERP客户-类别列", "ERP客户类别列显示"),
            new PermissionSeed("column:erp-customer:contact", "ERP客户-联系人列", "ERP客户联系人列显示"),
            new PermissionSeed("column:erp-customer:phone", "ERP客户-电话列", "ERP客户电话列显示"),
            new PermissionSeed("column:erp-customer:email", "ERP客户-邮箱列", "ERP客户邮箱列显示"),
            new PermissionSeed("column:erp-customer:status", "ERP客户-状态列", "ERP客户状态列显示"),

            new PermissionSeed("column:erp-customer-category:code", "ERP客户类别-编码列", "ERP客户类别编码列显示"),
            new PermissionSeed("column:erp-customer-category:name", "ERP客户类别-名称列", "ERP客户类别名称列显示"),
            new PermissionSeed("column:erp-customer-category:description", "ERP客户类别-描述列", "ERP客户类别描述列显示"),
            new PermissionSeed("column:erp-customer-category:sort", "ERP客户类别-排序列", "ERP客户类别排序列显示"),
            new PermissionSeed("column:erp-customer-category:default", "ERP客户类别-默认列", "ERP客户类别默认列显示"),
            new PermissionSeed("column:erp-customer-category:status", "ERP客户类别-状态列", "ERP客户类别状态列显示"),

            new PermissionSeed("column:erp-vehicle-brand:code", "ERP车型品牌-编码列", "ERP车型品牌编码列显示"),
            new PermissionSeed("column:erp-vehicle-brand:name", "ERP车型品牌-名称列", "ERP车型品牌名称列显示"),
            new PermissionSeed("column:erp-vehicle-brand:enabled", "ERP车型品牌-状态列", "ERP车型品牌状态列显示"),
            new PermissionSeed("column:erp-vehicle-brand:remark", "ERP车型品牌-备注列", "ERP车型品牌备注列显示"),
            new PermissionSeed("column:erp-vehicle-series:code", "ERP车型车系-编码列", "ERP车型车系编码列显示"),
            new PermissionSeed("column:erp-vehicle-series:brand", "ERP车型车系-品牌列", "ERP车型车系品牌列显示"),
            new PermissionSeed("column:erp-vehicle-series:name", "ERP车型车系-名称列", "ERP车型车系名称列显示"),
            new PermissionSeed("column:erp-vehicle-series:enabled", "ERP车型车系-状态列", "ERP车型车系状态列显示"),
            new PermissionSeed("column:erp-vehicle-series:remark", "ERP车型车系-备注列", "ERP车型车系备注列显示"),
            new PermissionSeed("column:erp-vehicle-model:code", "ERP车型-编码列", "ERP车型编码列显示"),
            new PermissionSeed("column:erp-vehicle-model:series", "ERP车型-车系列", "ERP车型车系列显示"),
            new PermissionSeed("column:erp-vehicle-model:name", "ERP车型-名称列", "ERP车型名称列显示"),
            new PermissionSeed("column:erp-vehicle-model:yearFrom", "ERP车型-起始年份列", "ERP车型起始年份列显示"),
            new PermissionSeed("column:erp-vehicle-model:yearTo", "ERP车型-结束年份列", "ERP车型结束年份列显示"),
            new PermissionSeed("column:erp-vehicle-model:displacement", "ERP车型-排量列", "ERP车型排量列显示"),
            new PermissionSeed("column:erp-vehicle-model:engine", "ERP车型-发动机列", "ERP车型发动机列显示"),
            new PermissionSeed("column:erp-vehicle-model:enabled", "ERP车型-状态列", "ERP车型状态列显示"),
            new PermissionSeed("column:erp-vehicle-model:remark", "ERP车型-备注列", "ERP车型备注列显示"),
            new PermissionSeed("column:erp-product-fitment:product", "ERP商品适配车型-商品列", "ERP商品适配车型商品列显示"),
            new PermissionSeed("column:erp-product-fitment:vehicleModel", "ERP商品适配车型-车型列", "ERP商品适配车型车型列显示"),
            new PermissionSeed("column:erp-product-fitment:remark", "ERP商品适配车型-备注列", "ERP商品适配车型备注列显示"),

            new PermissionSeed("column:erp-supplier:code", "ERP供应商-编码列", "ERP供应商编码列显示"),
            new PermissionSeed("column:erp-supplier:name", "ERP供应商-名称列", "ERP供应商名称列显示"),
            new PermissionSeed("column:erp-supplier:contact", "ERP供应商-联系人列", "ERP供应商联系人列显示"),
            new PermissionSeed("column:erp-supplier:phone", "ERP供应商-电话列", "ERP供应商电话列显示"),
            new PermissionSeed("column:erp-supplier:mobile", "ERP供应商-手机列", "ERP供应商手机列显示"),
            new PermissionSeed("column:erp-supplier:email", "ERP供应商-邮箱列", "ERP供应商邮箱列显示"),
            new PermissionSeed("column:erp-supplier:taxNo", "ERP供应商-税号列", "ERP供应商税号列显示"),
            new PermissionSeed("column:erp-supplier:address", "ERP供应商-地址列", "ERP供应商地址列显示"),
            new PermissionSeed("column:erp-supplier:bankAccount", "ERP供应商-银行账号列", "ERP供应商银行账号列显示"),
            new PermissionSeed("column:erp-supplier:status", "ERP供应商-状态列", "ERP供应商状态列显示"),
            new PermissionSeed("column:erp-supplier:recentTransactionAt", "ERP供应商-最近交易时间列", "ERP供应商最近交易时间列显示"),
            new PermissionSeed("column:erp-supplier:createdAt", "ERP供应商-创建时间列", "ERP供应商创建时间列显示"),
            new PermissionSeed("column:erp-supplier:updatedAt", "ERP供应商-更新时间列", "ERP供应商更新时间列显示"),

            new PermissionSeed("column:erp-warehouse:code", "ERP仓库-编码列", "ERP仓库编码列显示"),
            new PermissionSeed("column:erp-warehouse:name", "ERP仓库-名称列", "ERP仓库名称列显示"),
            new PermissionSeed("column:erp-warehouse:address", "ERP仓库-地址列", "ERP仓库地址列显示"),
            new PermissionSeed("column:erp-warehouse:manager", "ERP仓库-负责人列", "ERP仓库负责人列显示"),
            new PermissionSeed("column:erp-warehouse:phone", "ERP仓库-电话列", "ERP仓库电话列显示"),
            new PermissionSeed("column:erp-warehouse:status", "ERP仓库-状态列", "ERP仓库状态列显示"),

            new PermissionSeed("column:erp-location:code", "ERP库位-编码列", "ERP库位编码列显示"),
            new PermissionSeed("column:erp-location:name", "ERP库位-名称列", "ERP库位名称列显示"),
            new PermissionSeed("column:erp-location:warehouse", "ERP库位-仓库列", "ERP库位仓库列显示"),
            new PermissionSeed("column:erp-location:aisle", "ERP库位-巷道列", "ERP库位巷道列显示"),
            new PermissionSeed("column:erp-location:rack", "ERP库位-货架列", "ERP库位货架列显示"),
            new PermissionSeed("column:erp-location:bin", "ERP库位-货位列", "ERP库位货位列显示"),
            new PermissionSeed("column:erp-location:status", "ERP库位-状态列", "ERP库位状态列显示"),

            new PermissionSeed("column:erp-category:code", "ERP分类-编码列", "ERP分类编码列显示"),
            new PermissionSeed("column:erp-category:name", "ERP分类-名称列", "ERP分类名称列显示"),
            new PermissionSeed("column:erp-category:parent", "ERP分类-上级列", "ERP分类上级列显示"),
            new PermissionSeed("column:erp-category:level", "ERP分类-层级列", "ERP分类层级列显示"),
            new PermissionSeed("column:erp-category:sort", "ERP分类-排序列", "ERP分类排序列显示"),
            new PermissionSeed("column:erp-category:status", "ERP分类-状态列", "ERP分类状态列显示"),

            new PermissionSeed("column:erp-unit:code", "ERP单位-编码列", "ERP单位编码列显示"),
            new PermissionSeed("column:erp-unit:name", "ERP单位-名称列", "ERP单位名称列显示"),
            new PermissionSeed("column:erp-unit:symbol", "ERP单位-符号列", "ERP单位符号列显示"),
            new PermissionSeed("column:erp-unit:precision", "ERP单位-精度列", "ERP单位精度列显示"),
            new PermissionSeed("column:erp-unit:status", "ERP单位-状态列", "ERP单位状态列显示"),

            new PermissionSeed("column:erp-settlement-method:code", "ERP结算方式-编码列", "ERP结算方式编码列显示"),
            new PermissionSeed("column:erp-settlement-method:name", "ERP结算方式-名称列", "ERP结算方式名称列显示"),
            new PermissionSeed("column:erp-settlement-method:fundInputMode", "ERP结算方式-即时收付款列", "ERP结算方式即时收付款列显示"),
            new PermissionSeed("column:erp-settlement-method:sort", "ERP结算方式-排序列", "ERP结算方式排序列显示"),
            new PermissionSeed("column:erp-settlement-method:status", "ERP结算方式-状态列", "ERP结算方式状态列显示"),

            new PermissionSeed("column:erp-payment-method:code", "ERP付款方式-编码列", "ERP付款方式编码列显示"),
            new PermissionSeed("column:erp-payment-method:name", "ERP付款方式-名称列", "ERP付款方式名称列显示"),
            new PermissionSeed("column:erp-payment-method:sort", "ERP付款方式-排序列", "ERP付款方式排序列显示"),
            new PermissionSeed("column:erp-payment-method:status", "ERP付款方式-状态列", "ERP付款方式状态列显示"),

            new PermissionSeed("column:erp-receipt-method:code", "ERP收款方式-编码列", "ERP收款方式编码列显示"),
            new PermissionSeed("column:erp-receipt-method:name", "ERP收款方式-名称列", "ERP收款方式名称列显示"),
            new PermissionSeed("column:erp-receipt-method:sort", "ERP收款方式-排序列", "ERP收款方式排序列显示"),
            new PermissionSeed("column:erp-receipt-method:status", "ERP收款方式-状态列", "ERP收款方式状态列显示"),

            new PermissionSeed("column:erp-delivery-method:code", "ERP送货方式-编码列", "ERP送货方式编码列显示"),
            new PermissionSeed("column:erp-delivery-method:name", "ERP送货方式-名称列", "ERP送货方式名称列显示"),
            new PermissionSeed("column:erp-delivery-method:sort", "ERP送货方式-排序列", "ERP送货方式排序列显示"),
            new PermissionSeed("column:erp-delivery-method:status", "ERP送货方式-状态列", "ERP送货方式状态列显示"),

            new PermissionSeed("column:erp-purchase:orderNo", "ERP采购-单号列", "ERP采购单号列显示"),
            new PermissionSeed("column:erp-purchase:supplier", "ERP采购-供应商列", "ERP采购供应商列显示"),
            new PermissionSeed("column:erp-purchase:status", "ERP采购-状态列", "ERP采购状态列显示"),
            new PermissionSeed("column:erp-purchase:totalAmount", "ERP采购-总金额列", "ERP采购总金额列显示"),
            new PermissionSeed("column:erp-purchase:createdAt", "ERP采购-创建时间列", "ERP采购创建时间列显示"),
            new PermissionSeed("column:erp-purchase-draft:orderNo", "ERP采购草稿-单号列", "ERP采购草稿单号列显示"),
            new PermissionSeed("column:erp-purchase-draft:supplier", "ERP采购草稿-供应商列", "ERP采购草稿供应商列显示"),
            new PermissionSeed("column:erp-purchase-draft:status", "ERP采购草稿-状态列", "ERP采购草稿状态列显示"),
            new PermissionSeed("column:erp-purchase-draft:totalAmount", "ERP采购草稿-总金额列", "ERP采购草稿总金额列显示"),
            new PermissionSeed("column:erp-purchase-draft:createdAt", "ERP采购草稿-创建时间列", "ERP采购草稿创建时间列显示"),
            new PermissionSeed("column:erp-purchase-approved:orderNo", "ERP采购已审核-单号列", "ERP采购已审核单号列显示"),
            new PermissionSeed("column:erp-purchase-approved:supplier", "ERP采购已审核-供应商列", "ERP采购已审核供应商列显示"),
            new PermissionSeed("column:erp-purchase-approved:status", "ERP采购已审核-状态列", "ERP采购已审核状态列显示"),
            new PermissionSeed("column:erp-purchase-approved:totalAmount", "ERP采购已审核-总金额列", "ERP采购已审核总金额列显示"),
            new PermissionSeed("column:erp-purchase-approved:createdAt", "ERP采购已审核-创建时间列", "ERP采购已审核创建时间列显示"),
            new PermissionSeed("column:erp-purchase-return:orderNo", "ERP采购退货-单号列", "ERP采购退货单号列显示"),
            new PermissionSeed("column:erp-purchase-return:supplier", "ERP采购退货-供应商列", "ERP采购退货供应商列显示"),
            new PermissionSeed("column:erp-purchase-return:status", "ERP采购退货-状态列", "ERP采购退货状态列显示"),
            new PermissionSeed("column:erp-purchase-return:totalAmount", "ERP采购退货-总金额列", "ERP采购退货总金额列显示"),
            new PermissionSeed("column:erp-purchase-return:createdAt", "ERP采购退货-创建时间列", "ERP采购退货创建时间列显示"),
            new PermissionSeed("column:erp-purchase-return-draft:orderNo", "ERP采购退货草稿-单号列", "ERP采购退货草稿单号列显示"),
            new PermissionSeed("column:erp-purchase-return-draft:supplier", "ERP采购退货草稿-供应商列", "ERP采购退货草稿供应商列显示"),
            new PermissionSeed("column:erp-purchase-return-draft:status", "ERP采购退货草稿-状态列", "ERP采购退货草稿状态列显示"),
            new PermissionSeed("column:erp-purchase-return-draft:totalAmount", "ERP采购退货草稿-总金额列", "ERP采购退货草稿总金额列显示"),
            new PermissionSeed("column:erp-purchase-return-draft:createdAt", "ERP采购退货草稿-创建时间列", "ERP采购退货草稿创建时间列显示"),
            new PermissionSeed("column:erp-purchase-return-approved:orderNo", "ERP采购退货已审核-单号列", "ERP采购退货已审核单号列显示"),
            new PermissionSeed("column:erp-purchase-return-approved:supplier", "ERP采购退货已审核-供应商列", "ERP采购退货已审核供应商列显示"),
            new PermissionSeed("column:erp-purchase-return-approved:status", "ERP采购退货已审核-状态列", "ERP采购退货已审核状态列显示"),
            new PermissionSeed("column:erp-purchase-return-approved:totalAmount", "ERP采购退货已审核-总金额列", "ERP采购退货已审核总金额列显示"),
            new PermissionSeed("column:erp-purchase-return-approved:createdAt", "ERP采购退货已审核-创建时间列", "ERP采购退货已审核创建时间列显示"),

            new PermissionSeed("column:erp-sale:orderNo", "ERP销售-单号列", "ERP销售单号列显示"),
            new PermissionSeed("column:erp-sale:customer", "ERP销售-客户列", "ERP销售客户列显示"),
            new PermissionSeed("column:erp-sale:status", "ERP销售-状态列", "ERP销售状态列显示"),
            new PermissionSeed("column:erp-sale:totalAmount", "ERP销售-总金额列", "ERP销售总金额列显示"),
            new PermissionSeed("column:erp-sale:netSaleAmount", "ERP销售-销售净额列", "ERP销售销售净额列显示"),
            new PermissionSeed("column:erp-sale:netGrossProfit", "ERP销售-毛利列", "ERP销售毛利列显示"),
            new PermissionSeed("column:erp-sale:receivableStatus", "ERP销售-收款状态列", "ERP销售收款状态列显示"),
            new PermissionSeed("column:erp-sale:returnStatus", "ERP销售-退货状态列", "ERP销售退货状态列显示"),
            new PermissionSeed("column:erp-sale:redFlushTrace", "ERP销售-红冲追踪列", "ERP销售红冲追踪列显示"),
            new PermissionSeed("column:erp-sale:createdAt", "ERP销售-创建时间列", "ERP销售创建时间列显示"),
            new PermissionSeed("column:erp-sale:profit", "ERP销售-利润列", "ERP销售利润列显示"),
            new PermissionSeed("column:erp-sale:discountAllocated", "ERP销售-分摊优惠列", "ERP销售分摊优惠列显示"),
            new PermissionSeed("column:erp-sale-draft:orderNo", "ERP销售草稿-单号列", "ERP销售草稿单号列显示"),
            new PermissionSeed("column:erp-sale-draft:customer", "ERP销售草稿-客户列", "ERP销售草稿客户列显示"),
            new PermissionSeed("column:erp-sale-draft:totalAmount", "ERP销售草稿-总金额列", "ERP销售草稿总金额列显示"),
            new PermissionSeed("column:erp-sale-draft:netSaleAmount", "ERP销售草稿-销售净额列", "ERP销售草稿销售净额列显示"),
            new PermissionSeed("column:erp-sale-draft:netGrossProfit", "ERP销售草稿-毛利列", "ERP销售草稿毛利列显示"),
            new PermissionSeed("column:erp-sale-draft:receivableStatus", "ERP销售草稿-收款状态列", "ERP销售草稿收款状态列显示"),
            new PermissionSeed("column:erp-sale-draft:createdAt", "ERP销售草稿-创建时间列", "ERP销售草稿创建时间列显示"),
            new PermissionSeed("column:erp-sale-approved:orderNo", "ERP销售已审核-单号列", "ERP销售已审核单号列显示"),
            new PermissionSeed("column:erp-sale-approved:customer", "ERP销售已审核-客户列", "ERP销售已审核客户列显示"),
            new PermissionSeed("column:erp-sale-approved:status", "ERP销售已审核-状态列", "ERP销售已审核状态列显示"),
            new PermissionSeed("column:erp-sale-approved:totalAmount", "ERP销售已审核-总金额列", "ERP销售已审核总金额列显示"),
            new PermissionSeed("column:erp-sale-approved:netSaleAmount", "ERP销售已审核-销售净额列", "ERP销售已审核销售净额列显示"),
            new PermissionSeed("column:erp-sale-approved:netGrossProfit", "ERP销售已审核-毛利列", "ERP销售已审核毛利列显示"),
            new PermissionSeed("column:erp-sale-approved:receivableStatus", "ERP销售已审核-收款状态列", "ERP销售已审核收款状态列显示"),
            new PermissionSeed("column:erp-sale-approved:returnStatus", "ERP销售已审核-退货状态列", "ERP销售已审核退货状态列显示"),
            new PermissionSeed("column:erp-sale-approved:redFlushTrace", "ERP销售已审核-红冲追踪列", "ERP销售已审核红冲追踪列显示"),
            new PermissionSeed("column:erp-sale-approved:createdAt", "ERP销售已审核-创建时间列", "ERP销售已审核创建时间列显示"),
            new PermissionSeed("column:erp-sale-form:profit", "ERP销售表单-利润列", "ERP销售表单利润列显示"),
            new PermissionSeed("column:erp-sale-form:discountAllocated", "ERP销售表单-分摊优惠列", "ERP销售表单分摊优惠列显示"),
            new PermissionSeed("column:erp-sale-return:orderNo", "ERP销售退货-单号列", "ERP销售退货单号列显示"),
            new PermissionSeed("column:erp-sale-return:customer", "ERP销售退货-客户列", "ERP销售退货客户列显示"),
            new PermissionSeed("column:erp-sale-return:status", "ERP销售退货-状态列", "ERP销售退货状态列显示"),
            new PermissionSeed("column:erp-sale-return:totalAmount", "ERP销售退货-总金额列", "ERP销售退货总金额列显示"),
            new PermissionSeed("column:erp-sale-return:refundStatus", "ERP销售退货-退款状态列", "ERP销售退货退款状态列显示"),
            new PermissionSeed("column:erp-sale-return:createdAt", "ERP销售退货-创建时间列", "ERP销售退货创建时间列显示"),
            new PermissionSeed("column:erp-sale-return-draft:orderNo", "ERP销售退货草稿-单号列", "ERP销售退货草稿单号列显示"),
            new PermissionSeed("column:erp-sale-return-draft:customer", "ERP销售退货草稿-客户列", "ERP销售退货草稿客户列显示"),
            new PermissionSeed("column:erp-sale-return-draft:status", "ERP销售退货草稿-状态列", "ERP销售退货草稿状态列显示"),
            new PermissionSeed("column:erp-sale-return-draft:totalAmount", "ERP销售退货草稿-总金额列", "ERP销售退货草稿总金额列显示"),
            new PermissionSeed("column:erp-sale-return-draft:refundStatus", "ERP销售退货草稿-退款状态列", "ERP销售退货草稿退款状态列显示"),
            new PermissionSeed("column:erp-sale-return-draft:createdAt", "ERP销售退货草稿-创建时间列", "ERP销售退货草稿创建时间列显示"),
            new PermissionSeed("column:erp-sale-return-approved:orderNo", "ERP销售退货已审核-单号列", "ERP销售退货已审核单号列显示"),
            new PermissionSeed("column:erp-sale-return-approved:customer", "ERP销售退货已审核-客户列", "ERP销售退货已审核客户列显示"),
            new PermissionSeed("column:erp-sale-return-approved:status", "ERP销售退货已审核-状态列", "ERP销售退货已审核状态列显示"),
            new PermissionSeed("column:erp-sale-return-approved:totalAmount", "ERP销售退货已审核-总金额列", "ERP销售退货已审核总金额列显示"),
            new PermissionSeed("column:erp-sale-return-approved:refundStatus", "ERP销售退货已审核-退款状态列", "ERP销售退货已审核退款状态列显示"),
            new PermissionSeed("column:erp-sale-return-approved:createdAt", "ERP销售退货已审核-创建时间列", "ERP销售退货已审核创建时间列显示"),
            new PermissionSeed("column:erp-ar:customerName", "ERP应收-客户列", "ERP应收客户列显示"),
            new PermissionSeed("column:erp-ar:orderNo", "ERP应收-订单号列", "ERP应收订单号列显示"),
            new PermissionSeed("column:erp-ar:status", "ERP应收-状态列", "ERP应收状态列显示"),
            new PermissionSeed("column:erp-ar:totalAmount", "ERP应收-总金额列", "ERP应收总金额列显示"),
            new PermissionSeed("column:erp-ar:createdAt", "ERP应收-创建时间列", "ERP应收创建时间列显示"),
            new PermissionSeed("column:erp-ap:supplierName", "ERP应付-供应商列", "ERP应付供应商列显示"),
            new PermissionSeed("column:erp-ap:orderNo", "ERP应付-订单号列", "ERP应付订单号列显示"),
            new PermissionSeed("column:erp-ap:status", "ERP应付-状态列", "ERP应付状态列显示"),
            new PermissionSeed("column:erp-ap:totalAmount", "ERP应付-总金额列", "ERP应付总金额列显示"),
            new PermissionSeed("column:erp-ap:paidAmount", "ERP应付-已付金额列", "ERP应付已付金额列显示"),
            new PermissionSeed("column:erp-ap:discountAmount", "ERP应付-优惠金额列", "ERP应付优惠金额列显示"),
            new PermissionSeed("column:erp-ap:unpaidAmount", "ERP应付-未付金额列", "ERP应付未付金额列显示"),
            new PermissionSeed("column:erp-ap:createdAt", "ERP应付-创建时间列", "ERP应付创建时间列显示"),
            new PermissionSeed("column:erp-receipt:receiptNo", "ERP收款单-单号列", "ERP收款单单号列显示"),
            new PermissionSeed("column:erp-receipt:customerName", "ERP收款单-客户列", "ERP收款单客户列显示"),
            new PermissionSeed("column:erp-receipt:status", "ERP收款单-状态列", "ERP收款单状态列显示"),
            new PermissionSeed("column:erp-receipt:amount", "ERP收款单-金额列", "ERP收款单金额列显示"),
            new PermissionSeed("column:erp-receipt:discountAmount", "ERP收款单-优惠金额列", "ERP收款单优惠金额列显示"),
            new PermissionSeed("column:erp-receipt:createdAt", "ERP收款单-创建时间列", "ERP收款单创建时间列显示"),
            new PermissionSeed("column:erp-payment:paymentNo", "ERP付款单-单号列", "ERP付款单单号列显示"),
            new PermissionSeed("column:erp-payment:supplierName", "ERP付款单-供应商列", "ERP付款单供应商列显示"),
            new PermissionSeed("column:erp-payment:status", "ERP付款单-状态列", "ERP付款单状态列显示"),
            new PermissionSeed("column:erp-payment:amount", "ERP付款单-金额列", "ERP付款单金额列显示"),
            new PermissionSeed("column:erp-payment:discountAmount", "ERP付款单-优惠金额列", "ERP付款单优惠金额列显示"),
            new PermissionSeed("column:erp-payment:createdAt", "ERP付款单-创建时间列", "ERP付款单创建时间列显示"),
            new PermissionSeed("column:erp-finance-customer-debt:customerName", "ERP客户欠款-客户列", "ERP客户欠款客户列显示"),
            new PermissionSeed("column:erp-finance-customer-debt:totalDebt", "ERP客户欠款-欠款总额列", "ERP客户欠款欠款总额列显示"),
            new PermissionSeed("column:erp-finance-supplier-debt:supplierName", "ERP供应商欠款-供应商列", "ERP供应商欠款供应商列显示"),
            new PermissionSeed("column:erp-finance-supplier-debt:totalDebt", "ERP供应商欠款-欠款总额列", "ERP供应商欠款欠款总额列显示"),
            new PermissionSeed("column:erp-print-template:code", "ERP打印模板-编码列", "ERP打印模板编码列显示"),
            new PermissionSeed("column:erp-print-template:name", "ERP打印模板-名称列", "ERP打印模板名称列显示"),
            new PermissionSeed("column:erp-print-template:docType", "ERP打印模板-单据类型列", "ERP打印模板单据类型列显示"),
            new PermissionSeed("column:erp-print-template:sortNo", "ERP打印模板-排序列", "ERP打印模板排序列显示"),
            new PermissionSeed("column:erp-print-template:enabled", "ERP打印模板-状态列", "ERP打印模板状态列显示"),

            new PermissionSeed("column:erp-stock:product", "ERP库存-商品列", "ERP库存商品列显示"),
            new PermissionSeed("column:erp-stock:warehouse", "ERP库存-仓库列", "ERP库存仓库列显示"),
            new PermissionSeed("column:erp-stock:location", "ERP库存-库位列", "ERP库存库位列显示"),
            new PermissionSeed("column:erp-stock:qty", "ERP库存-数量列", "ERP库存数量列显示"),
            new PermissionSeed("column:erp-stock:updatedAt", "ERP库存-更新时间列", "ERP库存更新时间列显示"),
            new PermissionSeed("column:erp-stock-warning:productCode", "ERP库存预警-商品编码列", "ERP库存预警商品编码列显示"),
            new PermissionSeed("column:erp-stock-warning:productName", "ERP库存预警-商品名称列", "ERP库存预警商品名称列显示"),
            new PermissionSeed("column:erp-stock-warning:categoryName", "ERP库存预警-分类列", "ERP库存预警分类列显示"),
            new PermissionSeed("column:erp-stock-warning:unitName", "ERP库存预警-单位列", "ERP库存预警单位列显示"),
            new PermissionSeed("column:erp-stock-warning:totalQty", "ERP库存预警-总库存列", "ERP库存预警总库存列显示"),
            new PermissionSeed("column:erp-stock-warning:minStock", "ERP库存预警-最低库存列", "ERP库存预警最低库存列显示"),
            new PermissionSeed("column:erp-stock-warning:maxStock", "ERP库存预警-最高库存列", "ERP库存预警最高库存列显示"),
            new PermissionSeed("column:erp-stock-warning:status", "ERP库存预警-状态列", "ERP库存预警状态列显示"),
            new PermissionSeed("column:erp-stock-warning:defaultWarehouse", "ERP库存预警-默认仓库列", "ERP库存预警默认仓库列显示"),
            new PermissionSeed("column:erp-stock-warning:defaultLocation", "ERP库存预警-默认库位列", "ERP库存预警默认库位列显示"),
            new PermissionSeed("column:erp-stock-count:countNo", "ERP库存调整-单号列", "ERP库存调整单号列显示"),
            new PermissionSeed("column:erp-stock-count:status", "ERP库存调整-状态列", "ERP库存调整状态列显示"),
            new PermissionSeed("column:erp-stock-count:countAt", "ERP库存调整-盘点时间列", "ERP库存调整盘点时间列显示"),
            new PermissionSeed("column:erp-stock-count:adjustmentReason", "ERP库存调整-调整原因列", "ERP库存调整调整原因列显示"),
            new PermissionSeed("column:erp-stock-count:remark", "ERP库存调整-备注列", "ERP库存调整备注列显示"),
            new PermissionSeed("column:erp-stock-count:createdAt", "ERP库存调整-创建时间列", "ERP库存调整创建时间列显示"),
            new PermissionSeed("column:erp-stock-init:countNo", "ERP初始库存-单号列", "ERP初始库存单号列显示"),
            new PermissionSeed("column:erp-stock-init:status", "ERP初始库存-状态列", "ERP初始库存状态列显示"),
            new PermissionSeed("column:erp-stock-init:countAt", "ERP初始库存-盘点时间列", "ERP初始库存盘点时间列显示"),
            new PermissionSeed("column:erp-stock-init:remark", "ERP初始库存-备注列", "ERP初始库存备注列显示"),
            new PermissionSeed("column:erp-stock-init:createdAt", "ERP初始库存-创建时间列", "ERP初始库存创建时间列显示"),
            new PermissionSeed("column:erp-stock-transfer:transferNo", "ERP库存移库-单号列", "ERP库存移库单号列显示"),
            new PermissionSeed("column:erp-stock-transfer:status", "ERP库存移库-状态列", "ERP库存移库状态列显示"),
            new PermissionSeed("column:erp-stock-transfer:transferAt", "ERP库存移库-移库时间列", "ERP库存移库移库时间列显示"),
            new PermissionSeed("column:erp-stock-transfer:remark", "ERP库存移库-备注列", "ERP库存移库备注列显示"),
            new PermissionSeed("column:erp-stock-transfer:printCount", "ERP库存移库-打印次数列", "ERP库存移库打印次数列显示"),
            new PermissionSeed("column:erp-stock-transfer:lastPrintedAt", "ERP库存移库-最后打印时间列", "ERP库存移库最后打印时间列显示"),

            new PermissionSeed("column:erp-stock-txn:docNo", "ERP流水-单据号列", "ERP流水单据号列显示"),
            new PermissionSeed("column:erp-stock-txn:txnNo", "ERP流水-流水号列", "ERP流水流水号列显示"),
            new PermissionSeed("column:erp-stock-txn:bizType", "ERP流水-业务类型列", "ERP流水业务类型列显示"),
            new PermissionSeed("column:erp-stock-txn:product", "ERP流水-商品列", "ERP流水商品列显示"),
            new PermissionSeed("column:erp-stock-txn:warehouse", "ERP流水-仓库列", "ERP流水仓库列显示"),
            new PermissionSeed("column:erp-stock-txn:location", "ERP流水-库位列", "ERP流水库位列显示"),
            new PermissionSeed("column:erp-stock-txn:adjustmentReason", "ERP流水-调整原因列", "ERP流水调整原因列显示"),
            new PermissionSeed("column:erp-stock-txn:qtyDelta", "ERP流水-变更数量列", "ERP流水变更数量列显示"),
            new PermissionSeed("column:erp-stock-txn:qtyBefore", "ERP流水-变更前列", "ERP流水变更前列显示"),
            new PermissionSeed("column:erp-stock-txn:qtyAfter", "ERP流水-变更后列", "ERP流水变更后列显示"),
            new PermissionSeed("column:erp-stock-txn:unitCost", "ERP流水-单位成本列", "ERP流水单位成本列显示"),
            new PermissionSeed("column:erp-stock-txn:totalCost", "ERP流水-总成本列", "ERP流水总成本列显示"),
            new PermissionSeed("column:erp-stock-txn:operator", "ERP流水-操作人列", "ERP流水操作人列显示"),
            new PermissionSeed("column:erp-stock-txn:remark", "ERP流水-备注列", "ERP流水备注列显示"),
            new PermissionSeed("column:erp-stock-txn:createdAt", "ERP流水-时间列", "ERP流水时间列显示"),

            new PermissionSeed("column:erp-assemble-order:orderNo", "ERP组装单-单号列", "ERP组装单单号列显示"),
            new PermissionSeed("column:erp-assemble-order:orderType", "ERP组装单-类型列", "ERP组装单类型列显示"),
            new PermissionSeed("column:erp-assemble-order:finishedProduct", "ERP组装单-成品列", "ERP组装单成品列显示"),
            new PermissionSeed("column:erp-assemble-order:finishedQty", "ERP组装单-成品数量列", "ERP组装单成品数量列显示"),
            new PermissionSeed("column:erp-assemble-order:totalCost", "ERP组装单-总成本列", "ERP组装单总成本列显示"),
            new PermissionSeed("column:erp-assemble-order:status", "ERP组装单-状态列", "ERP组装单状态列显示"),
            new PermissionSeed("column:erp-assemble-order:orderAt", "ERP组装单-单据时间列", "ERP组装单单据时间列显示"),

            new PermissionSeed("column:erp-disassemble-order:orderNo", "ERP拆卸单-单号列", "ERP拆卸单单号列显示"),
            new PermissionSeed("column:erp-disassemble-order:orderType", "ERP拆卸单-类型列", "ERP拆卸单类型列显示"),
            new PermissionSeed("column:erp-disassemble-order:finishedProduct", "ERP拆卸单-成品列", "ERP拆卸单成品列显示"),
            new PermissionSeed("column:erp-disassemble-order:finishedQty", "ERP拆卸单-成品数量列", "ERP拆卸单成品数量列显示"),
            new PermissionSeed("column:erp-disassemble-order:totalCost", "ERP拆卸单-总成本列", "ERP拆卸单总成本列显示"),
            new PermissionSeed("column:erp-disassemble-order:status", "ERP拆卸单-状态列", "ERP拆卸单状态列显示"),
            new PermissionSeed("column:erp-disassemble-order:orderAt", "ERP拆卸单-单据时间列", "ERP拆卸单单据时间列显示"),

            new PermissionSeed("tenant:view", "查看租户", "查看租户列表"),
            new PermissionSeed("tenant:add", "新增租户", "新增租户"),
            new PermissionSeed("tenant:edit", "编辑租户", "编辑租户信息"),
            new PermissionSeed("tenant:delete", "删除租户", "删除租户"),
            new PermissionSeed("tenant:disable", "停用租户", "停用/启用租户"),
            new PermissionSeed("tenant:switch", "切换租户", "切换到指定租户")
        );
    }

    public record PermissionSeed(String code, String name, String description) {
    }
}
