<template>
  <div class="page-shell">
    <div class="page-header">
      <h2 class="page-title">{{ pageTitle }}</h2>
      <div class="table-toolbar">
        <el-button @click="handleBack">{{ $t('action.back') }}</el-button>
        <el-tag
          v-if="canApprove"
          type="success"
          size="small"
          class="action-tag action-tag--success"
          @click="handleApprove"
        >
          {{ $t('action.approve') }}
        </el-tag>
        <el-button v-if="!isReadOnly" @click="handleSave">{{ $t('action.save') }}</el-button>
        <el-button v-if="!isReadOnly" type="primary" @click="handleSaveAndBack">{{ $t('action.saveAndBack') }}</el-button>
      </div>
    </div>

    <div class="table-card compact-card sale-header-card">
      <div class="table-body sale-header-body">
        <el-form :model="formData" label-position="top" class="sale-form sale-form--compact">
          <div class="form-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.orderNo')">
                <el-input v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.orderTime')">
                <el-date-picker
                  v-model="formData.orderAt"
                  type="datetime"
                  format="YYYY-MM-DD HH:mm:ss"
                  value-format="YYYY-MM-DD HH:mm:ss"
                  class="order-time-picker"
                  style="width: 100%"
                  :clearable="false"
                  :disabled="isReadOnly"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.finishedProduct')" required>
                <FuzzyProductSelect
                  v-model="formData.finishedProductId"
                  :options="productOptions"
                  :placeholder="$t('field.product')"
                  style="width: 100%"
                  :disabled="isReadOnly"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.finishedQty')" required>
                <DecimalInput v-model="formData.finishedQty" :disabled="isReadOnly" />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.warehouse')">
                <el-select v-model="formData.warehouseId" style="width: 100%" :disabled="isReadOnly" @change="formData.locationId = null">
                  <el-option v-for="item in warehouseOptions" :key="item.id" :label="item.name" :value="item.id" />
                </el-select>
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.location')">
                <el-select v-model="formData.locationId" style="width: 100%" :disabled="isReadOnly || !formData.warehouseId">
                  <el-option v-for="item in getLocationOptions(formData.warehouseId || undefined)" :key="item.id" :label="item.name" :value="item.id" />
                </el-select>
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.laborCost')">
                <DecimalInput v-model="formData.laborCost" :disabled="isReadOnly" />
              </el-form-item>
            </div>
          </div>

          <el-form-item :label="$t('field.remark')">
            <el-input v-model="formData.remark" type="textarea" :disabled="isReadOnly" />
          </el-form-item>
        </el-form>
      </div>
    </div>

    <div class="table-card sale-detail-card">
      <div class="table-body sale-detail-body">
        <div class="detail-section">
          <div class="detail-header">
            <h4>{{ $t('field.items') }}</h4>
            <el-button type="primary" plain size="small" @click="addItem" :disabled="isReadOnly">
              + {{ $t('action.addItem') }}
            </el-button>
          </div>
          <div class="detail-table-wrapper">
            <el-table :data="formData.items" style="width: 100%" border stripe :empty-text="$t('table.empty')">
              <el-table-column v-if="canShow('product')" :label="$t('field.product')" min-width="220">
                <template #default="{ row }">
                  <FuzzyProductSelect
                    v-model="row.productId"
                    :options="productOptions"
                    :placeholder="$t('field.product')"
                    style="width: 100%"
                    :disabled="isReadOnly"
                    @change="() => handleProductChange(row)"
                  />
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('warehouse')" :label="$t('field.warehouse')" min-width="160">
                <template #default="{ row }">
                  <el-select v-model="row.warehouseId" filterable style="width: 100%" :disabled="isReadOnly" @change="() => handleWarehouseChange(row)">
                    <el-option v-for="item in warehouseOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('location')" :label="$t('field.location')" min-width="200">
                <template #default="{ row }">
                  <el-select v-model="row.locationId" filterable style="width: 100%" :disabled="isReadOnly || !row.warehouseId">
                    <el-option
                      v-for="item in getStockOptionsForRow(row)"
                      :key="item.locationId ?? item.key"
                      :label="item.searchLabel"
                      :value="item.locationId"
                    >
                      <div class="stock-option">
                        <span class="stock-option__name">{{ item.label }}</span>
                        <span class="stock-option__qty">
                          {{ $t('field.qtyOnHand') }}: {{ item.qtyOnHand }}
                          · {{ $t('field.qtyAvailable') }}: {{ item.qtyAvailable }}
                          · {{ $t('field.qtyLocked') }}: {{ item.qtyLocked }}
                        </span>
                      </div>
                    </el-option>
                  </el-select>
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('qty')" :label="$t('field.quantity')" width="140">
                <template #default="{ row }">
                  <DecimalInput v-model="row.qty" :disabled="isReadOnly" @update:modelValue="() => updateItemAmount(row)" />
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('unitCost')" :label="$t('field.unitCost')" width="140">
                <template #default="{ row }">
                  {{ formatAmount(row.unitCost) }}
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('amount')" :label="$t('field.lineTotal')" width="140">
                <template #default="{ row }">
                  {{ formatAmount(row.amount) }}
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('remark')" :label="$t('field.remark')" min-width="180">
                <template #default="{ row }">
                  <el-input v-model="row.remark" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column v-if="!isReadOnly" label="" width="80" align="center">
                <template #default="{ $index }">
                  <el-button type="danger" circle size="small" @click="removeItem($index)">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                  </el-button>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card compact-card assembly-summary-card">
      <div class="table-body">
        <el-form label-position="top" class="sale-form sale-form--compact">
          <div class="form-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.materialCost')">
                <el-input :model-value="formatAmount(materialCost)" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.laborCost')">
                <el-input :model-value="formatAmount(parsedLaborCost)" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.totalCost')">
                <el-input :model-value="formatAmount(totalCost)" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.unitCost')">
                <el-input :model-value="formatAmount(unitCost)" disabled />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onActivated, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { ElMessageBox } from 'element-plus';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import { useAuthStore } from '@/stores/auth';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import { mergeOptionById } from '@/utils/erpMasterData';

interface OptionItem {
  id: number;
  name: string;
  code?: string;
  costPrice?: number;
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  warehouseId?: number;
}

interface AssemblyItem {
  productId: number | null;
  warehouseId: number | null;
  locationId: number | null;
  qty: string;
  unitCost?: number;
  amount?: number;
  remark?: string;
}

interface StockOption {
  key: string;
  warehouseId: number | null;
  locationId: number | null;
  warehouseName: string;
  locationName: string;
  qtyOnHand: number;
  qtyAvailable: number;
  qtyLocked: number;
  label: string;
  searchLabel: string;
}

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const { notifyError, notifySuccess, notifyWarning } = useApiError();

const productOptions = ref<OptionItem[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const productStockMap = ref<Record<number, StockOption[]>>({});

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  orderType: 'ASSEMBLE',
  finishedProductId: null as number | null,
  finishedQty: '',
  warehouseId: null as number | null,
  locationId: null as number | null,
  laborCost: '',
  remark: '',
  items: [] as AssemblyItem[]
});

const pagePath = ref(route.path);
const lastRouteKey = ref(route.fullPath);
const needsReload = ref(false);

const isEditing = computed(() => Boolean(route.params.id));
const isReadOnly = computed(() => route.query.mode === 'view');

const hasPermission = (code: string) => authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);

const canApprove = computed(() => {
  return !isReadOnly.value && isEditing.value && formData.status === 'DRAFT' && hasPermission('erp-assembly:approve');
});

const canShow = (_key?: string) => true;

const pageTitle = computed(() => (isEditing.value ? t('page.erpAssembleOrderEdit') : t('page.erpAssembleOrderCreate')));

const parsedLaborCost = computed(() => parseDecimal(formData.laborCost));

const materialCost = computed(() => {
  return formData.items.reduce((sum, item) => sum + (Number(item.amount || 0) || 0), 0);
});

const totalCost = computed(() => materialCost.value + parsedLaborCost.value);

const unitCost = computed(() => {
  const finishedQty = parseDecimal(formData.finishedQty);
  if (finishedQty <= 0) return 0;
  return totalCost.value / finishedQty;
});

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const normalizeDateTimeValue = (value: any) => {
  if (!value) return '';
  if (value instanceof Date) {
    return formatDateTime(value);
  }
  const raw = String(value);
  if (!raw) return '';
  if (raw.includes('T')) {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
      return '';
    }
    return formatDateTime(parsed);
  }
  return raw;
};

const formatAmount = (value?: number) => {
  if (value == null || Number.isNaN(value)) return '0';
  return Number(value).toFixed(2);
};

const parseDecimal = (value: string | number) => {
  if (value == null) return 0;
  const normalized = String(value).trim();
  if (!normalized) return 0;
  const parsed = Number(normalized);
  return Number.isNaN(parsed) ? 0 : parsed;
};

const getLocationOptions = (warehouseId?: number | null) => {
  if (!warehouseId) return locationOptions.value;
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const buildStockKey = (warehouseId: number | null | undefined, locationId: number | null | undefined) => {
  const w = warehouseId == null ? 0 : warehouseId;
  const l = locationId == null ? 0 : locationId;
  return `${w}:${l}`;
};

const normalizeStockOption = (option: any): StockOption => {
  const warehouseId = option.warehouseId ?? null;
  const locationId = option.locationId ?? null;
  const warehouseName = option.warehouseName || '-';
  const locationName = option.locationName || t('field.unassignedLocation');
  const qtyOnHand = Number(option.qtyOnHand ?? 0);
  const qtyAvailable = Number(option.qtyAvailable ?? qtyOnHand);
  const qtyLocked = Number(option.qtyLocked ?? 0);
  const baseLabel = `${warehouseName} / ${locationName}`;
  return {
    key: buildStockKey(warehouseId, locationId),
    warehouseId,
    locationId,
    warehouseName,
    locationName,
    qtyOnHand,
    qtyAvailable,
    qtyLocked,
    label: baseLabel,
    searchLabel: `${baseLabel} ${qtyOnHand} ${qtyAvailable} ${qtyLocked}`
  };
};

const fetchStockOptions = async (productId?: number, force = false) => {
  if (!productId) return;
  if (!force && productStockMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/stock/balances/by-product', { params: { productId } });
    const data = res.data.data || [];
    productStockMap.value[productId] = data.map(normalizeStockOption);
  } catch (error) {
    notifyError(error);
  }
};

const buildLocationFallbackOptions = (warehouseId?: number | null): StockOption[] => {
  const locations = warehouseId ? locationOptions.value.filter(item => item.warehouseId === warehouseId) : locationOptions.value;
  return locations.map(location => {
    const warehouse = warehouseOptions.value.find(item => item.id === location.warehouseId);
    const warehouseName = warehouse?.name || '-';
    const baseLabel = `${warehouseName} / ${location.name}`;
    return {
      key: buildStockKey(location.warehouseId ?? null, location.id),
      warehouseId: location.warehouseId ?? null,
      locationId: location.id,
      warehouseName,
      locationName: location.name,
      qtyOnHand: 0,
      qtyAvailable: 0,
      qtyLocked: 0,
      label: baseLabel,
      searchLabel: `${baseLabel} 0 0 0`
    };
  });
};

const getStockOptionsForRow = (row: AssemblyItem) => {
  if (!row.productId) return [];
  const allOptions = productStockMap.value[row.productId] || [];
  const filtered = row.warehouseId ? allOptions.filter(item => item.warehouseId === row.warehouseId) : allOptions;
  const fallback = buildLocationFallbackOptions(row.warehouseId ?? undefined);
  const optionMap = new Map<string, StockOption>();
  fallback.forEach(item => {
    if (item.locationId != null) {
      optionMap.set(String(item.locationId), item);
    }
  });
  filtered.forEach(item => {
    if (item.locationId != null) {
      optionMap.set(String(item.locationId), item);
    }
  });
  return Array.from(optionMap.values());
};

const fetchStockOptionsForItems = async (items: AssemblyItem[]) => {
  const productIds = Array.from(new Set(items.map(item => item.productId).filter(Boolean))) as number[];
  await Promise.all(productIds.map(id => fetchStockOptions(id)));
};

const closePage = () => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path } }));
  }
};

const resetForm = async () => {
  formData.orderNo = '';
  formData.orderAt = formatDateTime(new Date());
  formData.status = '';
  formData.orderType = 'ASSEMBLE';
  formData.finishedProductId = null;
  formData.finishedQty = '';
  formData.warehouseId = null;
  formData.locationId = null;
  formData.laborCost = '';
  formData.remark = '';
  formData.items = [];
  addItem();
  await loadNextOrderNo();
};

const loadNextOrderNo = async () => {
  if (isEditing.value) return;
  try {
    const res: any = await request.get('/erp/assembly-orders/next-order-no', { params: { orderType: formData.orderType } });
    formData.orderNo = res.data?.data || '';
  } catch (error) {
    notifyError(error);
  }
};


const fetchOptions = async () => {
  try {
    const [productsRes, warehousesRes, locationsRes] = await Promise.all([
      request.get('/erp/products'),
      request.get('/erp/warehouses/options'),
      request.get('/erp/locations/options')
    ]);
    productOptions.value = productsRes.data.data || [];
    warehouseOptions.value = warehousesRes.data.data || [];
    locationOptions.value = locationsRes.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const ensureWarehouseOption = async (warehouseId?: number | null) => {
  if (!warehouseId || warehouseOptions.value.some(item => item.id === warehouseId)) return;
  try {
    const res: any = await request.get(`/erp/warehouses/${warehouseId}`);
    const warehouse = res.data.data;
    if (warehouse) {
      warehouseOptions.value = mergeOptionById(warehouseOptions.value, {
        id: warehouse.id,
        name: warehouse.name
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureLocationOption = async (locationId?: number | null) => {
  if (!locationId || locationOptions.value.some(item => item.id === locationId)) return;
  try {
    const res: any = await request.get(`/erp/locations/${locationId}`);
    const location = res.data.data;
    if (location) {
      locationOptions.value = mergeOptionById(locationOptions.value, {
        id: location.id,
        name: location.name,
        warehouseId: location.warehouseId
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const addItem = () => {
  formData.items.push({
    productId: null,
    warehouseId: formData.warehouseId || null,
    locationId: formData.locationId || null,
    qty: '',
    unitCost: 0,
    amount: 0,
    remark: ''
  });
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const handleWarehouseChange = (row: AssemblyItem) => {
  row.locationId = null;
};

const handleProductChange = (row: AssemblyItem) => {
  const product = productOptions.value.find(item => item.id === row.productId);
  if (row.productId) {
    fetchStockOptions(row.productId);
  }
  if (product) {
    if (!row.warehouseId) {
      row.warehouseId = product.defaultWarehouseId || formData.warehouseId || null;
    }
    if (!row.locationId) {
      row.locationId = product.defaultLocationId || formData.locationId || null;
    }
    row.unitCost = Number(product.costPrice || 0);
  }
  updateItemAmount(row);
};

const updateItemAmount = (row: AssemblyItem) => {
  const qty = parseDecimal(row.qty);
  const unitCost = Number(row.unitCost || 0);
  row.amount = Number.isNaN(qty * unitCost) ? 0 : qty * unitCost;
};

const buildPayload = () => {
  const items = formData.items
    .filter(item => item.productId)
    .map(item => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: parseDecimal(item.qty),
      remark: item.remark
    }));

  return {
    orderNo: formData.orderNo || null,
    orderType: formData.orderType,
    orderAt: formData.orderAt || null,
    finishedProductId: formData.finishedProductId,
    finishedQty: parseDecimal(formData.finishedQty),
    warehouseId: formData.warehouseId,
    locationId: formData.locationId,
    laborCost: parseDecimal(formData.laborCost),
    items,
    remark: formData.remark
  };
};

const validateForm = () => {
  if (!formData.finishedProductId) {
    notifyWarning(t('message.required'));
    return false;
  }
  if (parseDecimal(formData.finishedQty) <= 0) {
    notifyWarning(t('message.mustBePositive'));
    return false;
  }
  const hasItems = formData.items.some(item => item.productId);
  if (!hasItems) {
    notifyWarning(t('message.noItems'));
    return false;
  }
  for (const item of formData.items) {
    if (!item.productId) continue;
    if (parseDecimal(item.qty) <= 0) {
      notifyWarning(t('message.mustBePositive'));
      return false;
    }
  }
  return true;
};

const saveData = async (closeOnSuccess = false) => {
  if (!validateForm()) return null;
  const payload = buildPayload();
  try {
    if (isEditing.value) {
      await request.put(`/erp/assembly-orders/${route.params.id}`, payload);
      notifySuccess();
    } else {
      const res: any = await request.post('/erp/assembly-orders', payload);
      if (res.data?.data?.order?.id) {
        const id = res.data.data.order.id;
        await router.replace(`/erp/assemble-orders/${id}/edit`);
      }
      notifySuccess();
    }
    if (closeOnSuccess) {
      closePage();
      await router.push('/erp/assemble-orders');
    }
    return route.params.id || null;
  } catch (error) {
    notifyError(error);
    return null;
  }
};

const handleSave = async () => {
  await saveData();
};

const handleSaveAndBack = async () => {
  await saveData(true);
};

const handleApprove = async () => {
  if (!canApprove.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    await request.post(`/erp/assembly-orders/${route.params.id}/approve`);
    formData.status = 'APPROVED';
    notifySuccess();
    closePage();
    await router.push('/erp/assemble-orders');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleBack = async () => {
  await resetForm();
  closePage();
  await router.push('/erp/assemble-orders');
};

const fetchDetail = async () => {
  try {
    const res: any = await request.get(`/erp/assembly-orders/${route.params.id}`);
    const detail = res.data?.data;
    if (!detail?.order) return;
    const order = detail.order;
    formData.orderNo = order.orderNo || '';
    formData.orderAt = normalizeDateTimeValue(order.orderAt) || formatDateTime(new Date());
    formData.status = order.status || '';
    formData.orderType = order.orderType || 'ASSEMBLE';
    formData.finishedProductId = order.finishedProductId || null;
    formData.finishedQty = String(order.finishedQty ?? '');
    formData.warehouseId = order.warehouseId || null;
    formData.locationId = order.locationId || null;
    await ensureWarehouseOption(formData.warehouseId);
    await ensureLocationOption(formData.locationId);
    formData.laborCost = String(order.laborCost ?? '');
    formData.remark = order.remark || '';
    formData.items = (detail.items || []).map((item: any) => ({
      productId: item.productId || null,
      warehouseId: item.warehouseId || null,
      locationId: item.locationId || null,
      qty: String(item.qty ?? ''),
      unitCost: Number(item.unitCost || 0),
      amount: Number(item.amount || 0),
      remark: item.remark || ''
    }));
    await Promise.all(formData.items.flatMap(item => [
      ensureWarehouseOption(item.warehouseId),
      ensureLocationOption(item.locationId)
    ]));
    await fetchStockOptionsForItems(formData.items);
    if (!formData.items.length) addItem();
  } catch (error) {
    notifyError(error);
  }
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

onMounted(async () => {
  await fetchOptions();
  if (isEditing.value) {
    await fetchDetail();
  } else {
    await resetForm();
  }
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('tags:close', handleTagClosing as EventListener);
  }
});

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('tags:close', handleTagClosing as EventListener);
  }
});

onActivated(async () => {
  const currentKey = route.fullPath;
  if (lastRouteKey.value !== currentKey) {
    lastRouteKey.value = currentKey;
    needsReload.value = true;
  }
  if (!needsReload.value) return;
  needsReload.value = false;
  await fetchOptions();
  if (isEditing.value) {
    await fetchDetail();
  } else {
    await resetForm();
  }
});

</script>

<style scoped>
.page-header + .table-card {
  margin-top: 12px;
}

.table-card + .table-card {
  margin-top: 12px;
}

.table-card .table-body {
  padding: 16px;
}

.form-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.form-group {
  min-width: 220px;
  flex: 1 1 220px;
}

@media (max-width: 1200px) {
  .form-group {
    min-width: 180px;
  }
}

.sale-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 8px;
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 8px;
}

.detail-table-wrapper {
  min-height: 0;
  overflow: auto;
}
</style>
