<template>
  <div class="page-shell page-shell--system sale-page-surface">
    <div class="page-header sale-page-header">
      <div class="sale-title-group">
        <div class="page-title">{{ pageTitle }}</div>
        <div class="sale-breadcrumb">
          <span>{{ $t('page.erpDisassembleOrderManagement') }}</span>
          <span class="sale-breadcrumb__separator">/</span>
          <span>{{ $t('page.erpDisassembleOrder') }}</span>
          <span class="sale-breadcrumb__separator">/</span>
          <span>{{ pageTitle }}</span>
        </div>
      </div>
      <div class="table-actions sale-page-toolbar__actions">
        <el-button class="action-button" @click="handleBack">{{ $t('action.back') }}</el-button>
        <el-tag
          v-if="canApprove"
          type="success"
          size="small"
          class="action-tag action-tag--success"
          @click="handleApprove"
        >
          {{ $t('action.approve') }}
        </el-tag>
        <el-button v-if="!isReadOnly" class="action-button" @click="handleSave">{{ $t('action.save') }}</el-button>
        <el-button v-if="!isReadOnly" type="primary" class="action-button" @click="handleSaveAndBack">{{ $t('action.saveAndBack') }}</el-button>
      </div>
    </div>

    <div class="page-toolbar-card sale-header-card">
      <div class="card-section-header">
        <h4>{{ $t('section.basicInfo') }}</h4>
      </div>
      <div class="sale-header-body">
        <el-form :model="formData" label-position="top" class="sale-form sale-form--compact">
          <div class="form-grid sale-header-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.orderNo')">
                <el-input v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.orderTime')">
                <el-date-picker
                  v-model="formData.orderAt"
                  type="datetime"
                  format="YYYY-MM-DD HH:mm:ss"
                  value-format="YYYY-MM-DD HH:mm:ss"
                  class="order-time-picker"
                  style="width: 100%"
                  :clearable="false"
                  :disabled="isReadOnly"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.finishedProduct')" required>
                <FuzzyProductSelect
                  v-model="formData.finishedProductId"
                  :options="getSelectableProductOptions(formData.finishedProductId)"
                  :placeholder="$t('field.product')"
                  style="width: 100%"
                  :disabled="isReadOnly"
                  @change="handleFinishedProductChange"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.finishedQty')" required>
                <DecimalInput v-model="formData.finishedQty" :disabled="isReadOnly" />
              </el-form-item>
            </div>
            <div class="form-group form-group--wide">
              <el-form-item :label="$t('field.warehouseLocation')">
                <ProductStockSelect
                  v-model="formData.finishedStockKey"
                  :select-style="'width: 100%'"
                  :disabled="isReadOnly"
                  :placeholder="$t('placeholder.selectLocation')"
                  :product-id="formData.finishedProductId"
                  :warehouse-id="formData.warehouseId"
                  :location-id="formData.locationId"
                  :warehouse-options="warehouseOptions"
                  :location-options="locationOptions"
                  @selection-change="handleFinishedStockSelectionChange"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.laborCost')">
                <DecimalInput v-model="formData.laborCost" :disabled="isReadOnly" />
              </el-form-item>
            </div>
          </div>

          <el-form-item :label="$t('field.remark')" class="sale-remark-item">
            <el-input
              v-model="formData.remark"
              type="textarea"
              :disabled="isReadOnly"
              :autosize="{ minRows: 3, maxRows: 4 }"
            />
          </el-form-item>
        </el-form>
      </div>
    </div>

    <div class="table-card sale-detail-card">
      <div class="table-body sale-detail-body">
        <div class="detail-section">
          <div class="card-section-header detail-header">
            <h4>{{ $t('field.items') }}</h4>
            <el-button class="detail-add-item-button" type="primary" plain size="small" @click="addItem" :disabled="isReadOnly">
              + {{ $t('action.addItem') }}
            </el-button>
          </div>
          <div class="detail-table-wrapper">
            <el-table :data="formData.items" style="width: 100%" border stripe :empty-text="$t('table.empty')">
              <el-table-column v-if="canShow('product')" :label="$t('field.product')" min-width="220">
                <template #default="{ row }">
                  <FuzzyProductSelect
                    v-model="row.productId"
                    :options="getSelectableProductOptions(row.productId)"
                    :placeholder="$t('field.product')"
                    style="width: 100%"
                    :disabled="isReadOnly"
                    @change="() => handleProductChange(row)"
                  />
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('warehouseLocation')" :label="$t('field.warehouseLocation')" min-width="240">
                <template #default="{ row }">
                  <ProductStockSelect
                    v-model="row.stockKey"
                    :select-style="'width: 100%'"
                    :disabled="isReadOnly"
                    :placeholder="$t('placeholder.selectLocation')"
                    :product-id="row.productId"
                    :warehouse-id="row.warehouseId"
                    :location-id="row.locationId"
                    :warehouse-options="warehouseOptions"
                    :location-options="locationOptions"
                    @selection-change="(payload) => handleRowStockSelectionChange(row, payload)"
                  />
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('qty')" :label="$t('field.quantity')" width="140">
                <template #default="{ row }">
                  <DecimalInput v-model="row.qty" :disabled="isReadOnly" @update:modelValue="() => updateItemAmount(row)" />
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('unitCost')" :label="$t('field.unitCost')" width="140">
                <template #default="{ row }">
                  {{ formatAmount(row.unitCost) }}
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('amount')" :label="$t('field.lineTotal')" width="140">
                <template #default="{ row }">
                  {{ formatAmount(row.amount) }}
                </template>
              </el-table-column>
              <el-table-column v-if="canShow('remark')" :label="$t('field.remark')" min-width="180">
                <template #default="{ row }">
                  <el-input v-model="row.remark" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column v-if="!isReadOnly" label="" width="80" align="center">
                <template #default="{ $index }">
                  <el-button type="danger" circle size="small" @click="removeItem($index)">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                  </el-button>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card payment-card assembly-summary-card">
      <div class="card-section-header">
        <h4>{{ $t('field.totalCost') }}</h4>
      </div>
      <div class="table-body payment-card-body">
        <el-form label-position="top" class="sale-form sale-form--compact">
          <div class="form-grid payment-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.materialCost')">
                <el-input :model-value="formatAmount(materialCost)" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.laborCost')">
                <el-input :model-value="formatAmount(parsedLaborCost)" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.totalCost')">
                <el-input :model-value="formatAmount(totalCost)" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.unitCost')">
                <el-input :model-value="formatAmount(unitCost)" disabled />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onActivated, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { ElMessageBox } from 'element-plus';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import { useAuthStore } from '@/stores/auth';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import ProductStockSelect from '@/components/ProductStockSelect.vue';
import { mergeOptionById } from '@/utils/erpMasterData';

interface OptionItem {
  id: number;
  name: string;
  code?: string;
  costPrice?: number;
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  warehouseId?: number;
  enabled?: boolean;
}

interface AssemblyItem {
  productId: number | null;
  warehouseId: number | null;
  locationId: number | null;
  stockKey?: string;
  qty: string;
  unitCost?: number;
  amount?: number;
  remark?: string;
}

interface StockOption {
  key: string;
  warehouseId: number | null;
  locationId: number | null;
  warehouseName: string;
  locationName: string;
  qtyOnHand: number;
  qtyAvailable: number;
  qtyLocked: number;
  label: string;
  searchLabel: string;
}

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const { notifyError, notifySuccess, notifyWarning } = useApiError();

const productOptions = ref<OptionItem[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const productStockMap = ref<Record<number, StockOption[]>>({});

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  orderType: 'DISASSEMBLE',
  finishedProductId: null as number | null,
  finishedQty: '',
  finishedStockKey: '',
  warehouseId: null as number | null,
  locationId: null as number | null,
  laborCost: '',
  remark: '',
  items: [] as AssemblyItem[]
});

const pagePath = ref(route.path);
const lastRouteKey = ref(route.fullPath);
const needsReload = ref(false);

const isEditing = computed(() => Boolean(route.params.id));
const isReadOnly = computed(() => route.query.mode === 'view');

const hasPermission = (code: string) => authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);

const canApprove = computed(() => {
  return !isReadOnly.value && isEditing.value && formData.status === 'DRAFT' && hasPermission('erp-assembly:approve');
});

const canShow = (_key?: string) => true;

const pageTitle = computed(() => (isEditing.value ? t('page.erpDisassembleOrderEdit') : t('page.erpDisassembleOrderCreate')));

const parsedLaborCost = computed(() => parseDecimal(formData.laborCost));

const materialCost = computed(() => {
  return formData.items.reduce((sum, item) => sum + (Number(item.amount || 0) || 0), 0);
});

const totalCost = computed(() => materialCost.value + parsedLaborCost.value);

const unitCost = computed(() => {
  const finishedQty = parseDecimal(formData.finishedQty);
  if (finishedQty <= 0) return 0;
  return totalCost.value / finishedQty;
});

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const normalizeDateTimeValue = (value: any) => {
  if (!value) return '';
  if (value instanceof Date) {
    return formatDateTime(value);
  }
  const raw = String(value);
  if (!raw) return '';
  if (raw.includes('T')) {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
      return '';
    }
    return formatDateTime(parsed);
  }
  return raw;
};

const formatAmount = (value?: number) => {
  if (value == null || Number.isNaN(value)) return '0';
  return Number(value).toFixed(2);
};

const parseDecimal = (value: string | number) => {
  if (value == null) return 0;
  const normalized = String(value).trim();
  if (!normalized) return 0;
  const parsed = Number(normalized);
  return Number.isNaN(parsed) ? 0 : parsed;
};

const parseStockKey = (stockKey?: string) => {
  if (!stockKey) return { warehouseId: undefined, locationId: undefined };
  const [warehouseRaw, locationRaw] = stockKey.split(':');
  const warehouseId = Number(warehouseRaw);
  const locationId = Number(locationRaw);
  return {
    warehouseId: Number.isNaN(warehouseId) || warehouseId === 0 ? undefined : warehouseId,
    locationId: Number.isNaN(locationId) || locationId === 0 ? undefined : locationId
  };
};

const getLocationOptions = (warehouseId?: number | null) => {
  if (!warehouseId) return locationOptions.value;
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const buildStockKey = (warehouseId: number | null | undefined, locationId: number | null | undefined) => {
  const w = warehouseId == null ? 0 : warehouseId;
  const l = locationId == null ? 0 : locationId;
  return `${w}:${l}`;
};

const normalizeStockOption = (option: any): StockOption => {
  const warehouseId = option.warehouseId ?? null;
  const locationId = option.locationId ?? null;
  const warehouseName = option.warehouseName || '-';
  const locationName = option.locationName || t('field.unassignedLocation');
  const qtyOnHand = Number(option.qtyOnHand ?? 0);
  const qtyAvailable = Number(option.qtyAvailable ?? qtyOnHand);
  const qtyLocked = Number(option.qtyLocked ?? 0);
  const baseLabel = `${warehouseName} / ${locationName}`;
  return {
    key: buildStockKey(warehouseId, locationId),
    warehouseId,
    locationId,
    warehouseName,
    locationName,
    qtyOnHand,
    qtyAvailable,
    qtyLocked,
    label: baseLabel,
    searchLabel: `${baseLabel} ${qtyOnHand} ${qtyAvailable} ${qtyLocked}`
  };
};

const fetchStockOptions = async (productId?: number, force = false) => {
  if (!productId) return;
  if (!force && productStockMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/stock/balances/by-product', { params: { productId } });
    const data = res.data.data || [];
    productStockMap.value[productId] = data.map(normalizeStockOption);
  } catch (error) {
    notifyError(error);
  }
};

const buildLocationFallbackOptions = (warehouseId?: number | null): StockOption[] => {
  const locations = warehouseId ? locationOptions.value.filter(item => item.warehouseId === warehouseId) : locationOptions.value;
  return locations.map(location => {
    const warehouse = warehouseOptions.value.find(item => item.id === location.warehouseId);
    const warehouseName = warehouse?.name || '-';
    const baseLabel = `${warehouseName} / ${location.name}`;
    return {
      key: buildStockKey(location.warehouseId ?? null, location.id),
      warehouseId: location.warehouseId ?? null,
      locationId: location.id,
      warehouseName,
      locationName: location.name,
      qtyOnHand: 0,
      qtyAvailable: 0,
      qtyLocked: 0,
      label: baseLabel,
      searchLabel: `${baseLabel} 0 0 0`
    };
  });
};

const getStockOptionsForRow = (row: AssemblyItem) => {
  if (!row.productId) return [];
  const options = productStockMap.value[row.productId] || [];
  if (!row.warehouseId && !row.locationId) {
    return options;
  }
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
  if (options.some(item => item.key === key)) {
    return options;
  }
  const fallback = buildFallbackStockOption(row.warehouseId, row.locationId);
  return fallback ? [fallback, ...options] : options;
};

const getFinishedStockOptions = () => {
  if (!formData.finishedProductId) return [];
  const options = productStockMap.value[formData.finishedProductId] || [];
  if (!formData.warehouseId && !formData.locationId) {
    return options;
  }
  const key = buildStockKey(formData.warehouseId ?? null, formData.locationId ?? null);
  if (options.some(item => item.key === key)) {
    return options;
  }
  const fallback = buildFinishedFallbackStockOption();
  return fallback ? [fallback, ...options] : options;
};

const buildFinishedFallbackStockOption = (): StockOption | null => {
  if (!formData.warehouseId && !formData.locationId) return null;
  const warehouse = warehouseOptions.value.find(item => item.id === formData.warehouseId);
  const location = locationOptions.value.find(item => item.id === formData.locationId);
  const warehouseName = warehouse?.name || '-';
  const locationName = location?.name || t('field.unassignedLocation');
  return {
    key: buildStockKey(formData.warehouseId ?? null, formData.locationId ?? null),
    warehouseId: formData.warehouseId ?? null,
    locationId: formData.locationId ?? null,
    warehouseName,
    locationName,
    qtyOnHand: 0,
    qtyAvailable: 0,
    qtyLocked: 0,
    label: `${warehouseName} / ${locationName}`,
    searchLabel: `${warehouseName} / ${locationName} 0 0 0`
  };
};

const buildFallbackStockOption = (warehouseId?: number | null, locationId?: number | null): StockOption | null => {
  if (!warehouseId && !locationId) return null;
  const warehouse = warehouseOptions.value.find(item => item.id === warehouseId);
  const location = locationOptions.value.find(item => item.id === locationId);
  const warehouseName = warehouse?.name || '-';
  const locationName = location?.name || t('field.unassignedLocation');
  return {
    key: buildStockKey(warehouseId ?? null, locationId ?? null),
    warehouseId: warehouseId ?? null,
    locationId: locationId ?? null,
    warehouseName,
    locationName,
    qtyOnHand: 0,
    qtyAvailable: 0,
    qtyLocked: 0,
    label: `${warehouseName} / ${locationName}`,
    searchLabel: `${warehouseName} / ${locationName} 0 0 0`
  };
};

const syncFinishedStockKey = () => {
  if (!formData.finishedProductId) {
    formData.finishedStockKey = '';
    return;
  }
  const options = productStockMap.value[formData.finishedProductId] || [];
  const key = buildStockKey(formData.warehouseId ?? null, formData.locationId ?? null);
  const matched = options.find(item => item.key === key);
  formData.finishedStockKey = matched ? key : (formData.warehouseId || formData.locationId ? key : '');
};

const syncStockKey = (row: AssemblyItem) => {
  if (!row.productId) {
    row.stockKey = '';
    return;
  }
  const options = productStockMap.value[row.productId] || [];
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
  const matched = options.find(item => item.key === key);
  row.stockKey = matched ? key : (row.warehouseId || row.locationId ? key : '');
};

const applyFinishedProductDefaults = (force = true) => {
  if (!formData.finishedProductId) return;
  const product = productOptions.value.find(item => item.id === formData.finishedProductId);
  if (!product) return;
  if (product.defaultWarehouseId && (force || !formData.warehouseId)) {
    formData.warehouseId = product.defaultWarehouseId;
  }
  if (product.defaultLocationId && (force || !formData.locationId)) {
    formData.locationId = product.defaultLocationId;
  }
  if (formData.locationId && formData.warehouseId) {
    const location = locationOptions.value.find(item => item.id === formData.locationId);
    if (location && location.warehouseId && location.warehouseId !== formData.warehouseId) {
      formData.locationId = null;
    }
  }
};

const handleFinishedProductChange = async () => {
  formData.warehouseId = null;
  formData.locationId = null;
  formData.finishedStockKey = '';
  applyFinishedProductDefaults(true);
  syncFinishedStockKey();
};

const handleFinishedStockSelectionChange = (payload: { stockKey: string; warehouseId: number | null; locationId: number | null }) => {
  formData.finishedStockKey = payload.stockKey;
  formData.warehouseId = payload.warehouseId;
  formData.locationId = payload.locationId;
};

const fetchStockOptionsForItems = async (items: AssemblyItem[]) => {
  const productIds = Array.from(new Set(items.map(item => item.productId).filter(Boolean))) as number[];
  await Promise.all(productIds.map(id => fetchStockOptions(id)));
};

const closePage = () => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path } }));
  }
};

const resetForm = async () => {
  formData.orderNo = '';
  formData.orderAt = formatDateTime(new Date());
  formData.status = '';
  formData.orderType = 'DISASSEMBLE';
  formData.finishedProductId = null;
  formData.finishedQty = '';
  formData.finishedStockKey = '';
  formData.warehouseId = null;
  formData.locationId = null;
  formData.laborCost = '';
  formData.remark = '';
  formData.items = [];
  addItem();
  await loadNextOrderNo();
};

const loadNextOrderNo = async () => {
  if (isEditing.value) return;
  try {
    const res: any = await request.get('/erp/assembly-orders/next-order-no', { params: { orderType: formData.orderType } });
    formData.orderNo = res.data?.data || '';
  } catch (error) {
    notifyError(error);
  }
};


const fetchOptions = async () => {
  try {
    const [productsRes, warehousesRes, locationsRes] = await Promise.all([
      request.get('/erp/products/options'),
      request.get('/erp/warehouses/options'),
      request.get('/erp/locations/options')
    ]);
    productOptions.value = productsRes.data.data || [];
    warehouseOptions.value = warehousesRes.data.data || [];
    locationOptions.value = locationsRes.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const ensureProductOption = async (productId?: number | null) => {
  if (!productId || productOptions.value.some(item => item.id === productId)) return;
  try {
    const res: any = await request.get(`/erp/products/${productId}`);
    const product = res.data.data;
    if (product) {
      productOptions.value = mergeOptionById(productOptions.value, {
        id: product.id,
        name: product.name,
        costPrice: product.costPrice,
        defaultWarehouseId: product.defaultWarehouseId,
        defaultLocationId: product.defaultLocationId,
        enabled: product.enabled
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const getSelectableProductOptions = (currentProductId?: number | null) =>
  productOptions.value.filter(item => item.enabled !== false || item.id === currentProductId);

const ensureWarehouseOption = async (warehouseId?: number | null) => {
  if (!warehouseId || warehouseOptions.value.some(item => item.id === warehouseId)) return;
  try {
    const res: any = await request.get(`/erp/warehouses/${warehouseId}`);
    const warehouse = res.data.data;
    if (warehouse) {
      warehouseOptions.value = mergeOptionById(warehouseOptions.value, {
        id: warehouse.id,
        name: warehouse.name
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureLocationOption = async (locationId?: number | null) => {
  if (!locationId || locationOptions.value.some(item => item.id === locationId)) return;
  try {
    const res: any = await request.get(`/erp/locations/${locationId}`);
    const location = res.data.data;
    if (location) {
      locationOptions.value = mergeOptionById(locationOptions.value, {
        id: location.id,
        name: location.name,
        warehouseId: location.warehouseId
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const addItem = () => {
  formData.items.push({
    productId: null,
    warehouseId: formData.warehouseId || null,
    locationId: formData.locationId || null,
    stockKey: '',
    qty: '',
    unitCost: 0,
    amount: 0,
    remark: ''
  });
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const handleProductChange = (row: AssemblyItem) => {
  const product = productOptions.value.find(item => item.id === row.productId);
  if (row.productId) {
    fetchStockOptions(row.productId);
  }
  if (product) {
    if (!row.warehouseId) {
      row.warehouseId = product.defaultWarehouseId || formData.warehouseId || null;
    }
    if (!row.locationId) {
      row.locationId = product.defaultLocationId || formData.locationId || null;
    }
    row.unitCost = Number(product.costPrice || 0);
  }
  syncStockKey(row);
  updateItemAmount(row);
};

const handleRowStockSelectionChange = (row: AssemblyItem, payload: { stockKey: string; warehouseId: number | null; locationId: number | null }) => {
  row.stockKey = payload.stockKey;
  row.warehouseId = payload.warehouseId;
  row.locationId = payload.locationId;
};

const updateItemAmount = (row: AssemblyItem) => {
  const qty = parseDecimal(row.qty);
  const unitCost = Number(row.unitCost || 0);
  row.amount = Number.isNaN(qty * unitCost) ? 0 : qty * unitCost;
};

const buildPayload = () => {
  const items = formData.items
    .filter(item => item.productId)
    .map(item => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: parseDecimal(item.qty),
      remark: item.remark
    }));

  return {
    orderNo: formData.orderNo || null,
    orderType: formData.orderType,
    orderAt: formData.orderAt || null,
    finishedProductId: formData.finishedProductId,
    finishedQty: parseDecimal(formData.finishedQty),
    warehouseId: formData.warehouseId,
    locationId: formData.locationId,
    laborCost: parseDecimal(formData.laborCost),
    items,
    remark: formData.remark
  };
};

const validateForm = () => {
  if (!formData.finishedProductId) {
    notifyWarning(t('message.required'));
    return false;
  }
  if (parseDecimal(formData.finishedQty) <= 0) {
    notifyWarning(t('message.mustBePositive'));
    return false;
  }
  const hasItems = formData.items.some(item => item.productId);
  if (!hasItems) {
    notifyWarning(t('message.noItems'));
    return false;
  }
  for (const item of formData.items) {
    if (!item.productId) continue;
    if (parseDecimal(item.qty) <= 0) {
      notifyWarning(t('message.mustBePositive'));
      return false;
    }
  }
  return true;
};

const saveData = async (closeOnSuccess = false) => {
  if (!validateForm()) return null;
  const payload = buildPayload();
  try {
    if (isEditing.value) {
      await request.put(`/erp/assembly-orders/${route.params.id}`, payload);
      notifySuccess();
    } else {
      const res: any = await request.post('/erp/assembly-orders', payload);
      if (res.data?.data?.order?.id) {
        const id = res.data.data.order.id;
        await router.replace(`/erp/disassemble-orders/${id}/edit`);
      }
      notifySuccess();
    }
    if (closeOnSuccess) {
      closePage();
      await router.push('/erp/disassemble-orders');
    }
    return route.params.id || null;
  } catch (error) {
    notifyError(error);
    return null;
  }
};

const handleSave = async () => {
  await saveData();
};

const handleSaveAndBack = async () => {
  await saveData(true);
};

const handleApprove = async () => {
  if (!canApprove.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    await request.post(`/erp/assembly-orders/${route.params.id}/approve`);
    formData.status = 'APPROVED';
    notifySuccess();
    closePage();
    await router.push('/erp/disassemble-orders');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleBack = async () => {
  await resetForm();
  closePage();
  await router.push('/erp/disassemble-orders');
};

const fetchDetail = async () => {
  try {
    const res: any = await request.get(`/erp/assembly-orders/${route.params.id}`);
    const detail = res.data?.data;
    if (!detail?.order) return;
    const order = detail.order;
    formData.orderNo = order.orderNo || '';
    formData.orderAt = normalizeDateTimeValue(order.orderAt) || formatDateTime(new Date());
    formData.status = order.status || '';
    formData.orderType = order.orderType || 'ASSEMBLE';
    formData.finishedProductId = order.finishedProductId || null;
    await ensureProductOption(formData.finishedProductId);
    formData.finishedQty = String(order.finishedQty ?? '');
    formData.warehouseId = order.warehouseId || null;
    formData.locationId = order.locationId || null;
    await ensureWarehouseOption(formData.warehouseId);
    await ensureLocationOption(formData.locationId);
    formData.laborCost = String(order.laborCost ?? '');
    formData.remark = order.remark || '';
    if (formData.finishedProductId) {
      await fetchStockOptions(formData.finishedProductId);
      syncFinishedStockKey();
    }
    formData.items = (detail.items || []).map((item: any) => ({
      productId: item.productId || null,
      warehouseId: item.warehouseId || null,
      locationId: item.locationId || null,
      stockKey: buildStockKey(item.warehouseId ?? null, item.locationId ?? null),
      qty: String(item.qty ?? ''),
      unitCost: Number(item.unitCost || 0),
      amount: Number(item.amount || 0),
      remark: item.remark || ''
    }));
    await Promise.all(formData.items.flatMap(item => [
      ensureProductOption(item.productId),
      ensureWarehouseOption(item.warehouseId),
      ensureLocationOption(item.locationId)
    ]));
    await fetchStockOptionsForItems(formData.items);
    formData.items.forEach(syncStockKey);
    if (!formData.items.length) addItem();
  } catch (error) {
    notifyError(error);
  }
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

onMounted(async () => {
  await fetchOptions();
  if (isEditing.value) {
    await fetchDetail();
  } else {
    await resetForm();
  }
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('tags:close', handleTagClosing as EventListener);
  }
});

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('tags:close', handleTagClosing as EventListener);
  }
});

onActivated(async () => {
  const currentKey = route.fullPath;
  if (lastRouteKey.value !== currentKey) {
    lastRouteKey.value = currentKey;
    needsReload.value = true;
  }
  if (!needsReload.value) return;
  needsReload.value = false;
  await fetchOptions();
  if (isEditing.value) {
    await fetchDetail();
  } else {
    await resetForm();
  }
});

</script>

<style scoped>
:global(.content-area:has(.sale-page-surface)) {
  background: #f5f7fb;
}

.sale-page-surface {
  --sale-page-bg: #f5f7fb;
  --sale-card-bg: #ffffff;
  --sale-card-border: #e3eaf4;
  --sale-card-shadow: 0 16px 36px rgba(28, 45, 76, 0.08), 0 4px 12px rgba(28, 45, 76, 0.04);
  --sale-card-radius: 12px;
  --sale-text: #17233c;
  --sale-muted: #6d7b91;
  --sale-primary: #1677ff;
  --sale-control-border: #d7e0ec;
  min-height: 100%;
  height: auto;
  padding: 16px 20px;
  box-sizing: border-box;
  background: transparent;
  color: var(--sale-text);
}

.sale-page-surface .page-title {
  color: var(--sale-text);
  font-weight: 800;
  font-size: 24px;
  line-height: 32px;
}

.sale-page-header {
  align-items: center !important;
  margin-bottom: 16px !important;
  gap: 14px;
}

.sale-title-group {
  display: flex;
  align-items: center;
  gap: 18px;
  min-width: 0;
}

.sale-breadcrumb {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  min-width: 0;
  color: #7d889b;
  font-size: 13px;
  font-weight: 500;
  white-space: nowrap;
}

.sale-breadcrumb__separator {
  color: #a8b2c1;
}

.sale-page-toolbar__actions {
  justify-content: flex-end;
  gap: 16px;
}

.action-button {
  min-width: 78px;
  height: 36px;
  border-radius: 8px;
  border-color: #d9e2ef;
  background: #ffffff;
  color: #26344f;
  font-size: 14px;
}

.sale-page-surface .action-button.el-button--primary {
  background: #1677ff;
  border-color: #1677ff;
  color: #ffffff;
  box-shadow: 0 8px 18px rgba(22, 119, 255, 0.18);
}

.sale-page-surface .sale-header-card,
.sale-page-surface .sale-detail-card,
.sale-page-surface .payment-card {
  border: 1px solid var(--sale-card-border);
  border-radius: var(--sale-card-radius);
  background: var(--sale-card-bg);
  box-shadow: var(--sale-card-shadow);
  overflow: visible;
}

.sale-header-card {
  padding: 20px 22px;
}

.sale-page-surface .sale-header-card + .sale-detail-card {
  margin-top: 18px;
}

.sale-detail-card {
  padding: 18px 22px 18px;
}

.payment-card {
  margin-top: 18px;
  padding: 18px 22px 18px;
}

.sale-header-body,
.sale-detail-body,
.payment-card-body {
  padding: 0 !important;
  background: transparent;
  overflow: visible;
}

.card-section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
}

.card-section-header h4 {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  color: var(--sale-text);
  font-size: 15px;
  font-weight: 700;
}

.card-section-header h4::before {
  content: '';
  width: 4px;
  height: 20px;
  border-radius: 999px;
  background: var(--sale-primary);
}

.sale-form :deep(.el-form-item) {
  margin-bottom: 4px;
}

.sale-form--compact :deep(.el-form-item) {
  margin-bottom: 0;
}

.sale-page-surface :deep(.el-form-item__label) {
  color: var(--sale-muted);
  font-weight: 600;
  line-height: 18px;
  padding-bottom: 6px;
}

.form-grid {
  display: grid;
  gap: 16px 32px;
}

.sale-header-grid {
  grid-template-columns: repeat(4, minmax(190px, 1fr));
  gap: 18px 32px;
}

.payment-grid {
  grid-template-columns: minmax(260px, 430px) minmax(220px, 320px) minmax(220px, 320px) minmax(220px, 320px);
  gap: 16px 32px;
}

.form-group {
  min-width: 0;
}

.sale-remark-item {
  width: calc(((100% - 96px) / 4) * 3 + 64px);
  max-width: 100%;
  margin-top: 18px;
}

.sale-page-surface :deep(.el-input__wrapper),
.sale-page-surface :deep(.el-select__wrapper) {
  min-height: 36px;
  border-radius: 6px;
  background: #ffffff;
  box-shadow: 0 0 0 1px var(--sale-control-border) inset;
}

.sale-page-surface :deep(.el-input__wrapper:hover),
.sale-page-surface :deep(.el-select__wrapper:hover) {
  box-shadow: 0 0 0 1px #a9c7f3 inset;
}

.sale-page-surface :deep(.el-input__wrapper.is-focus),
.sale-page-surface :deep(.el-select__wrapper.is-focused) {
  box-shadow: 0 0 0 1px var(--sale-primary) inset, 0 0 0 3px rgba(22, 119, 255, 0.08);
}

.sale-page-surface :deep(.el-input.is-disabled .el-input__wrapper) {
  background: #f7f9fc;
  box-shadow: 0 0 0 1px var(--sale-control-border) inset;
}

.sale-page-surface :deep(.el-input__inner),
.sale-page-surface :deep(.el-select__placeholder),
.sale-page-surface :deep(.el-select__selected-item) {
  font-size: 14px;
}

.sale-page-surface :deep(.el-textarea__inner) {
  border-radius: 6px;
  border: none;
  background: #ffffff;
  box-shadow: 0 0 0 1px var(--sale-control-border) inset;
  padding: 10px 12px;
  font-size: 14px;
  resize: vertical;
}

.sale-page-surface :deep(.el-textarea__inner:focus) {
  box-shadow: 0 0 0 1px var(--sale-primary) inset, 0 0 0 3px rgba(22, 119, 255, 0.08);
}

.sale-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 16px;
}

.detail-header {
  margin-bottom: 0;
}

.detail-add-item-button {
  height: 34px;
  border-radius: 6px;
  border-color: var(--sale-primary);
  background: #ffffff;
  color: var(--sale-primary);
  font-weight: 700;
}

.detail-table-wrapper {
  min-height: 0;
  overflow: auto;
  border: 1px solid #e1e9f4;
  border-radius: 10px;
  background: #fbfdff;
}

.sale-page-surface :deep(.el-table) {
  --el-table-border-color: #e1e9f4;
  --el-table-header-bg-color: #f0f5fc;
  --el-table-row-hover-bg-color: #f7fbff;
  color: var(--sale-text);
}

.sale-page-surface :deep(.el-table th.el-table__cell) {
  background: #f0f5fc;
  color: #344256;
  font-weight: 700;
}

.sale-page-surface :deep(.el-table td.el-table__cell) {
  height: 48px;
  color: #1f2b3d;
}

.sale-page-surface :deep(.el-table .cell) {
  line-height: 1.4;
}

.order-time-picker {
  width: 100%;
}

.order-time-picker :deep(.el-input__wrapper) {
  width: 100%;
  box-sizing: border-box;
}

.action-tag {
  min-height: 32px;
  border-radius: 8px;
  padding: 0 12px;
  font-weight: 600;
  cursor: pointer;
}

@media (max-width: 1280px) {
  .sale-header-grid,
  .payment-grid {
    grid-template-columns: repeat(2, minmax(220px, 1fr));
  }

  .sale-remark-item {
    width: 100%;
  }
}

@media (max-width: 768px) {
  .sale-page-surface {
    padding: 16px;
  }

  .sale-page-header,
  .sale-title-group,
  .sale-page-toolbar__actions {
    align-items: flex-start !important;
    flex-direction: column;
  }

  .sale-page-toolbar__actions {
    width: 100%;
    margin-left: 0;
  }

  .action-button,
  .action-tag {
    width: 100%;
    justify-content: center;
  }

  .sale-breadcrumb {
    flex-wrap: wrap;
    white-space: normal;
  }

  .sale-header-grid,
  .payment-grid {
    grid-template-columns: 1fr;
  }
}
</style>
