<template>
  <div class="page-shell page-shell--system purchase-page-surface">
    <div class="page-header purchase-page-header">
      <div class="purchase-title-group">
        <div class="page-title">{{ pageTitle }}</div>
        <div class="purchase-breadcrumb">
          <span>{{ $t('page.erpPurchaseOrderManagement') }}</span>
          <span class="purchase-breadcrumb__separator">/</span>
          <span>{{ $t('page.erpPurchaseOrder') }}</span>
          <span class="purchase-breadcrumb__separator">/</span>
          <span>{{ pageTitle }}</span>
        </div>
      </div>
      <div class="table-actions purchase-page-toolbar__actions">
        <el-button class="action-button" @click="handleBack">{{ $t('action.back') }}</el-button>
        <el-button
          v-if="shouldShowCopyButton"
          class="action-button action-button--secondary"
          :disabled="isInitializing || !canCopy"
          @click="handleCopy"
        >
          {{ $t('action.copy') }}
        </el-button>
        <el-button
          v-if="canPrint"
          class="action-button action-button--primary"
          type="primary"
          @click="handlePrint"
        >
          {{ $t('action.print') }}
        </el-button>
        <el-button
          v-if="shouldShowRedFlushButton"
          type="danger"
          plain
          class="action-button action-button--danger"
          :disabled="isInitializing || !canRedFlush"
          @click="handleRedFlush"
        >
          {{ $t('action.redFlush') }}
        </el-button>
        <el-button
          v-if="!isReadOnly"
          class="action-button action-button--save"
          :loading="isSaving"
          :disabled="isSaving"
          @click="handleSave"
        >
          {{ $t('action.save') }}
        </el-button>
        <el-button
          v-if="shouldShowApproveButton"
          type="success"
          plain
          class="action-button action-button--success"
          :loading="isSaving"
          :disabled="isSaving || isInitializing || !canApprove"
          @click="handleApprove"
        >
          {{ $t('action.approve') }}
        </el-button>
      </div>
    </div>

    <div class="page-toolbar-card purchase-header-card">
      <div class="card-section-header">
        <h4>{{ $t('section.basicInfo') }}</h4>
      </div>
      <div class="purchase-header-body">
        <el-form :model="formData" label-position="top" class="purchase-form purchase-form--compact">
          <div class="form-grid purchase-header-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.orderNo')">
                <div v-if="isReadOnly" class="readonly-field readonly-field--strong">{{ formData.orderNo || '-' }}</div>
                <el-input v-else v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.orderTime')" required>
                <div v-if="isReadOnly" class="readonly-field">{{ formData.orderAt || '-' }}</div>
                <el-date-picker
                  v-else
                  v-model="formData.orderAt"
                  type="datetime"
                  format="YYYY-MM-DD HH:mm:ss"
                  value-format="YYYY-MM-DD HH:mm:ss"
                  class="order-time-picker"
                  style="width: 100%"
                  :clearable="false"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.supplier')" required>
                <div v-if="isReadOnly" class="readonly-field readonly-field--strong">{{ currentSupplierName }}</div>
                <FuzzyProductSelect
                  v-else
                  v-model="formData.supplierId"
                  :options="supplierOptions"
                  :placeholder="$t('field.supplier')"
                  style="width: 100%"
                  @change="handleSupplierChange"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.createdBy')">
                <div class="readonly-field">{{ formData.createdBy || currentOperatorName }}</div>
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.updatedBy')">
                <div class="readonly-field">{{ formData.updatedBy || formData.createdBy || currentOperatorName }}</div>
              </el-form-item>
            </div>
          </div>

          <el-form-item :label="$t('field.remark')" class="purchase-remark-item">
            <div v-if="isReadOnly" class="readonly-field readonly-field--remark">{{ formData.remark || '-' }}</div>
            <el-input
              v-else
              v-model="formData.remark"
              type="textarea"
              maxlength="200"
              show-word-limit
              :autosize="{ minRows: 3, maxRows: 4 }"
              :placeholder="$t('placeholder.optional')"
            />
          </el-form-item>
          <el-form-item v-if="isReadOnly && formData.status === 'CANCELLED'" :label="$t('field.redFlushReason')">
            <div class="readonly-field readonly-field--danger">{{ extractRedFlushReason(formData.remark) || '-' }}</div>
          </el-form-item>
        </el-form>
      </div>
    </div>

    <div class="table-card purchase-detail-card">
      <div class="table-body purchase-detail-body">
        <div class="detail-section">
          <div class="card-section-header detail-header">
            <h4>{{ $t('section.saleDetailInfo') }}</h4>
            <div v-if="!isReadOnly" class="detail-header-actions">
              <el-button
                class="detail-toolbar-button detail-toolbar-button--primary"
                :icon="Plus"
                @click="addItem"
              >
                {{ $t('action.addItem') }}
              </el-button>
              <el-button
                class="detail-toolbar-button"
                :icon="Delete"
                :disabled="!selectedItems.length"
                @click="removeSelectedItems"
              >
                {{ $t('action.deleteSelected') }}
              </el-button>
            </div>
          </div>
          <div class="detail-table-wrapper">
            <ErpDataTable
              :data="formData.items"
              style="width: 100%"
              border
              @selection-change="handleItemSelectionChange"
              :header-cell-style="{ textAlign: 'center' }"
             table-key="erp-purchase-order-form">
              <ErpDataTableColumn v-if="!isReadOnly" type="selection" width="52" align="center" />
              <ErpDataTableColumn type="index" :label="$t('table.index')" width="72" align="center" />
              <ErpDataTableColumn :label="$t('field.product')" min-width="240" column-key="product">
                <template #header>
                  <span class="required-table-label">{{ $t('field.product') }}</span>
                </template>
                <template #default="{ row, $index }">
                  <div class="product-cell">
                    <span v-if="isReadOnly" class="product-cell__label">{{ resolveProductLabel(row.productId) }}</span>
                    <el-select
                      v-else
                      :ref="(el: any) => setProductSelectRef(el, $index)"
                      :key="formData.supplierId ?? 'no-supplier'"
                      v-model="row.productId"
                      filterable
                      clearable
                      class="product-cell__select"
                      :placeholder="$t('placeholder.selectProduct')"
                      :disabled="!formData.supplierId"
                      @change="handleProductChange(row)"
                    >
                      <el-option
                        v-for="item in getSelectableProductOptions(row.productId)"
                        :key="item.id"
                        :label="item.name"
                        :value="item.id"
                      />
                    </el-select>
                    <el-tag
                      class="history-inline history-tag history-tag--inline"
                      size="small"
                      :type="row.productId ? 'primary' : 'info'"
                      :title="$t('action.detail')"
                      @click.stop="row.productId && openHistoryForRow(row)"
                    >
                      <el-icon class="history-icon"><View /></el-icon>
                    </el-tag>
                  </div>
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.warehouseLocation')" min-width="220" column-key="warehouseLocation">
                <template #header>
                  <span class="required-table-label">{{ $t('field.warehouseLocation') }}</span>
                </template>
                <template #default="{ row }">
                  <span v-if="isReadOnly" class="readonly-cell">
                    {{ resolveWarehouseLabel(row.warehouseId) }} / {{ resolveLocationLabel(row.locationId) }}
                  </span>
                  <ProductStockSelect
                    v-else
                    v-model="row.stockKey"
                    :product-id="row.productId"
                    :warehouse-id="row.warehouseId"
                    :location-id="row.locationId"
                    :allow-manual-location-select="true"
                    :warehouse-options="warehouseOptions"
                    :location-options="locationOptions"
                    :placeholder="$t('placeholder.selectLocation')"
                    @selection-change="(payload) => handleStockSelectionChange(row, payload)"
                  />
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.quantity')" width="140" column-key="quantity">
                <template #header>
                  <span class="required-table-label">{{ $t('field.quantity') }}</span>
                </template>
                <template #default="{ row }">
                  <span v-if="isReadOnly" class="readonly-cell">{{ formatPlainNumber(row.qty) }}</span>
                  <DecimalInput v-else v-model="row.qty" :scale="4" />
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.price')" width="140" column-key="price">
                <template #header>
                  <span class="required-table-label">{{ $t('field.price') }}</span>
                </template>
                <template #default="{ row }">
                  <span v-if="isReadOnly" class="readonly-cell">{{ formatMoney(parseDecimal(row.price, 4) || 0) }}</span>
                  <DecimalInput v-else v-model="row.price" :scale="4" />
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.lineTotal')" width="140" column-key="lineAmount">
                <template #default="{ row }">
                  {{ formatMoney(calcLineAmount(row)) }}
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn v-if="canShowDiscountAllocated" :label="$t('field.discountAllocated')" width="140" column-key="discountAllocated">
                <template #default="{ row }">
                  {{ formatMoney(calcLineDiscount(row)) }}
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.remark')" min-width="180" column-key="remark">
                <template #default="{ row }">
                  <span v-if="isReadOnly" class="readonly-cell">{{ row.remark || '-' }}</span>
                  <el-input v-else v-model="row.remark" :placeholder="$t('field.remark')" />
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn v-if="!isReadOnly" :label="$t('table.actions')" width="88" align="center" fixed="right" column-key="actions">
                <template #default="{ $index }">
                  <el-button class="row-delete-button" link type="danger" @click.stop="removeItem($index)">
                    <el-icon><Delete /></el-icon>
                  </el-button>
                </template>
              </ErpDataTableColumn>
            </ErpDataTable>
          </div>
          <div class="detail-footer">
            <div v-if="!isReadOnly" class="detail-actions">
              <el-button class="detail-add-item-button" type="primary" plain :icon="Plus" @click="addItem">
                {{ $t('action.addItem') }}
              </el-button>
            </div>
            <div class="detail-summary">
              <div class="summary-item">{{ $t('field.productSubtotal') }}: {{ formatMoney(totalAmountBeforeDiscount) }}</div>
              <div class="summary-item">{{ $t('field.discountAmount') }}: {{ formatMoney(getDiscountAmount()) }}</div>
              <div class="summary-item summary-item--total">
                {{ $t('field.totalAmount') }}:
                <strong>¥ {{ formatMoney(totalAmount) }}</strong>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card payment-card">
      <div class="card-section-header">
        <h4>{{ $t('section.saleSettlementInfo') }}</h4>
      </div>
      <div class="table-body payment-card-body">
        <el-form :model="formData" label-position="top" class="purchase-form purchase-form--compact payment-form">
          <div class="payment-grid">
            <div class="form-group form-group--settlement">
              <el-form-item :label="$t('field.settlementMethod')">
                <div v-if="isReadOnly" class="readonly-inline">{{ currentSettlementMethodName }}</div>
                <el-select v-else v-model="formData.settlementMethod" clearable style="width: 100%">
                  <el-option v-for="item in settlementMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
            <div v-if="!isCreditSettlement" class="form-group form-group--settlement">
              <el-form-item :label="$t('field.paymentMethod')">
                <div v-if="isReadOnly" class="readonly-inline">{{ currentPaymentMethodName }}</div>
                <el-select v-else v-model="formData.paymentMethodCode" clearable style="width: 100%">
                  <el-option v-for="item in paymentMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
            <div v-if="!isCreditSettlement" class="form-group form-group--amount">
              <el-form-item :label="$t('field.paidAmount')">
                <div v-if="isReadOnly" class="readonly-inline">{{ formatMoney(parseDecimal(formData.paidAmount, 2) || 0) }}</div>
                <DecimalInput v-else v-model="formData.paidAmount" :scale="2" style="width: 100%" />
              </el-form-item>
            </div>
            <div class="form-group form-group--discount">
              <el-form-item :label="$t('field.discountAmount')">
                <div v-if="isReadOnly" class="readonly-inline">{{ formatMoney(parseDecimal(formData.discountAmount, 2) || 0) }}</div>
                <DecimalInput v-else v-model="formData.discountAmount" :scale="2" style="width: 100%" />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>

    <PrintPreviewDialog
      v-model="printDialogVisible"
      :doc-type="printDocType"
      :doc-id="printDocId"
      :title="$t('page.erpPurchaseOrderPrint')"
    />

    <ProductHistoryDialog
      v-model:visible="historyDialogVisible"
      v-model:active-tab="historyTab"
      :title="$t('action.productHistory')"
      :loading="historyLoading"
      :header-items="purchaseHistoryHeaderItems"
      :tabs="purchaseHistoryTabs"
      :empty-text="$t('table.empty')"
      :keyword-placeholder="$t('placeholder.keyword')"
      :range-separator="$t('separator.to')"
      :start-placeholder="$t('field.startTime')"
      :end-placeholder="$t('field.endTime')"
      @tab-change="handleHistoryTabChange"
      @filter-change="handleHistoryDialogFilterChange"
      @page-change="handleHistoryDialogPageChange"
      @size-change="handleHistoryDialogSizeChange"
    />

    <el-dialog
      v-model="saveSuccessDialogVisible"
      append-to-body
      :title="saveSuccessDialogMode === 'approve' ? $t('message.approveSuccess') : $t('message.saveSuccess')"
      width="440px"
      class="save-success-dialog"
      @closed="handleSaveSuccessDialogClosed"
    >
      <div class="save-success-dialog__content">
        <div class="save-success-dialog__message">
          {{ saveSuccessDialogMode === 'approve' ? $t('message.approveSuccessNextStep') : $t('message.saveSuccessNextStep') }}
        </div>
        <div class="save-success-dialog__order-no">
          {{ t('message.saveSuccessOrderNo', { orderNo: saveSuccessOrderNo || '-' }) }}
        </div>
      </div>
      <template #footer>
        <div class="save-success-dialog__actions">
          <el-button @click="handleContinueCreate">{{ $t('action.continueCreate') }}</el-button>
          <el-button @click="handleStayCurrent">{{ $t('action.stayCurrent') }}</el-button>
          <el-button @click="handleBackToList">{{ $t('action.backToList') }}</el-button>
          <el-button
            v-if="saveSuccessDialogMode === 'approve'"
            type="primary"
            @click="handleSaveSuccessPrint"
          >
            {{ $t('action.print') }}
          </el-button>
          <el-button
            v-else
            type="success"
            plain
            class="dialog-approve-button"
            :disabled="!saveSuccessDocId || isSaving"
            @click="handleApproveFromSaveDialog"
          >
            {{ $t('action.approve') }}
          </el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onActivated, onBeforeUnmount, onDeactivated, onMounted, reactive, ref, watch } from 'vue';
import { Delete, Plus, View } from '@element-plus/icons-vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import { ElMessageBox } from 'element-plus';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import { useValidationMessage } from '@/composables/useValidationMessage';
import { useAuthStore } from '@/stores/auth';
import {
  getCachedCustomerCategories,
  getCachedEnabledPaymentMethods,
  getCachedEnabledSettlementMethods,
  getCachedLocationOptions,
  getCachedProductOptions,
  getCachedSuppliers,
  getCachedWarehouseOptions
} from '@/composables/erpBaseDataCache';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import ProductHistoryDialog from '@/components/ProductHistoryDialog.vue';
import ProductStockSelect from '@/components/ProductStockSelect.vue';
import PrintPreviewDialog from '@/components/PrintPreviewDialog.vue';
import { mergeOptionById } from '@/utils/erpMasterData';

interface OptionItem {
  id: number;
  name: string;
  warehouseId?: number;
  enabled?: boolean;
  defaultSettlementMethodCode?: string;
  defaultPaymentMethodCode?: string;
}

interface ProductOption extends OptionItem {
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  costPrice?: number;
}

interface MethodOption {
  code: string;
  name: string;
  isDefault?: boolean;
  fundInputMode?: 'HIDDEN' | 'OPTIONAL' | 'REQUIRED';
}

interface PurchaseOrderItem {
  id?: number;
  productId?: number;
  warehouseId?: number;
  locationId?: number;
  stockKey?: string;
  qty?: string | number;
  price?: string | number;
  taxRate?: string | number;
  remark?: string;
  sortNo?: number;
}

interface PurchaseRecentItem {
  orderId: number;
  orderNo: string;
  orderAt: string;
  productId: number;
  qty: number;
  price: number;
}

interface PurchaseHistoryItem {
  orderId: number;
  orderNo: string;
  orderAt: string;
  productId: number;
  qty: number;
  price: number;
  priceInclTax: number;
  supplierId: number;
  supplierName: string;
}

interface SaleHistoryItem {
  orderId: number;
  orderNo: string;
  orderAt: string;
  productId: number;
  qty: number;
  price: number;
  priceInclTax: number;
  customerId: number;
  customerName: string;
}

interface PriceHistoryItem {
  customerCategoryName: string;
  salePrice: number;
  updatedAt: string;
}

interface HistoryDialogTabState {
  keyword: string;
  range: string[];
  page: number;
  size: number;
  total: number;
}

const { t } = useI18n();
const router = useRouter();
const route = useRoute();
const { notifyError, notifySuccess, notifyWarning } = useApiError();
const {
  requiredFieldMessage,
  requiredRowFieldMessage,
  positiveRowFieldMessage,
  invalidRowFieldMessage,
} = useValidationMessage();
const authStore = useAuthStore();
const tenantCacheKey = computed(() => authStore.tenantId ?? authStore.tenantCode ?? 'default');

const supplierOptions = ref<OptionItem[]>([]);
const productOptions = ref<ProductOption[]>([]);
const customerCategoryOptions = ref<OptionItem[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const settlementMethodOptions = ref<MethodOption[]>([]);
const paymentMethodOptions = ref<MethodOption[]>([]);
const productRecentPurchaseMap = ref<Record<number, PurchaseRecentItem[]>>({});
const selectedItems = ref<PurchaseOrderItem[]>([]);
const productSelectRefs = ref<any[]>([]);
const isInitializing = ref(true);
const isSaving = ref(false);
const needsReload = ref(false);
const isPageActive = ref(false);
const pagePath = ref(route.path);
const lastRouteKey = ref(route.fullPath);
const detailLoadSeq = ref(0);
const printDialogVisible = ref(false);
const printDocId = ref<number | null>(null);
const pendingPrintDocId = ref<number | null>(null);
const historyDialogVisible = ref(false);
const historyLoading = ref(false);
const historyProduct = ref<ProductOption | null>(null);
const historyTab = ref<'price' | 'purchase' | 'sale-all'>('purchase');
const priceHistoryItems = ref<PriceHistoryItem[]>([]);
const saleHistoryItems = ref<SaleHistoryItem[]>([]);
const purchaseHistoryItems = ref<PurchaseHistoryItem[]>([]);
const saleHistoryKeyword = ref('');
const purchaseHistoryKeyword = ref('');
const saleHistoryRange = ref<string[]>([]);
const purchaseHistoryRange = ref<string[]>([]);
const saleHistoryPage = ref(1);
const saleHistorySize = ref(10);
const saleHistoryTotal = ref(0);
const purchaseHistoryPage = ref(1);
const purchaseHistorySize = ref(10);
const purchaseHistoryTotal = ref(0);
const saveSuccessDialogVisible = ref(false);
const saveSuccessDialogMode = ref<'save' | 'approve'>('save');
const saveSuccessDocId = ref<number | null>(null);
const saveSuccessOrderNo = ref('');
const saveSuccessAction = ref<'stay' | 'continue' | 'list' | 'print' | null>(null);

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  supplierId: null as number | null,
  settlementMethod: '',
  paymentMethodCode: '',
  paidAmount: '',
  discountAmount: '',
  createdBy: '',
  updatedBy: '',
  remark: '',
  items: [] as PurchaseOrderItem[]
});

const isEditing = computed(() => Boolean(route.params.id));
const isApprovedWorkspace = computed(() => route.path.includes('/erp/purchase-orders/approved/'));
const isDraftWorkspace = computed(() => route.path.includes('/erp/purchase-orders/draft/') || !isApprovedWorkspace.value);
const draftBasePath = '/erp/purchase-orders/draft';
const approvedBasePath = '/erp/purchase-orders/approved';
const draftApiBase = '/erp/purchase-orders/draft';
const approvedApiBase = '/erp/purchase-orders/approved';
const detailApiBase = computed(() => isApprovedWorkspace.value ? approvedApiBase : draftApiBase);
const printDocType = computed(() => isApprovedWorkspace.value ? 'PURCHASE_ORDER_APPROVED' : 'PURCHASE_ORDER_DRAFT');
const isReadOnly = computed(() => {
  if (isApprovedWorkspace.value) return true;
  if (route.query.mode === 'view') return true;
  if (!formData.status) return false;
  return formData.status !== 'DRAFT';
});

const pageTitle = computed(() => {
  if (route.query.mode === 'view') return t('page.erpPurchaseOrder');
  return isEditing.value ? t('page.erpPurchaseOrderEdit') : t('page.erpPurchaseOrderCreate');
});

const currentSupplierName = computed(() => supplierOptions.value.find(item => item.id === formData.supplierId)?.name || '-');
const currentSettlementMethodName = computed(() => settlementMethodOptions.value.find(item => item.code === formData.settlementMethod)?.name || '-');
const currentPaymentMethodName = computed(() => paymentMethodOptions.value.find(item => item.code === formData.paymentMethodCode)?.name || '-');
const currentOperatorName = computed(() => {
  const user = authStore.user as any;
  return user?.displayName || user?.username || user?.name || 'system';
});
const historyProductName = computed(() => historyProduct.value?.name || '-');
const purchaseHistoryHeaderItems = computed(() => [
  { label: t('field.product'), value: historyProductName.value },
  { label: t('field.supplier'), value: currentSupplierName.value, show: currentSupplierName.value !== '-' }
]);
const customerCategoryNameMap = computed(() => {
  const map = new Map<number, string>();
  for (const item of customerCategoryOptions.value) {
    if (item.id != null) {
      map.set(item.id, item.name);
    }
  }
  return map;
});
const priceHistoryTabState = computed<HistoryDialogTabState>(() => ({
  keyword: '',
  range: [],
  page: 1,
  size: 10,
  total: priceHistoryItems.value.length
}));
const purchaseHistoryTabState = computed<HistoryDialogTabState>(() => ({
  keyword: purchaseHistoryKeyword.value,
  range: purchaseHistoryRange.value,
  page: purchaseHistoryPage.value,
  size: purchaseHistorySize.value,
  total: purchaseHistoryTotal.value
}));
const saleHistoryTabState = computed<HistoryDialogTabState>(() => ({
  keyword: saleHistoryKeyword.value,
  range: saleHistoryRange.value,
  page: saleHistoryPage.value,
  size: saleHistorySize.value,
  total: saleHistoryTotal.value
}));
const purchaseHistoryTabs = computed(() => [
  {
    name: 'price',
    label: t('field.customerCategoryPrice'),
    data: priceHistoryItems.value,
    columns: [
      { prop: 'customerCategoryName', label: t('field.customerCategory'), minWidth: 160 },
      { label: t('field.price'), width: 120, formatter: (row: PriceHistoryItem) => formatMoney(row.salePrice) },
      { label: t('field.updatedTime'), width: 150, formatter: (row: PriceHistoryItem) => formatHistoryDate(row.updatedAt) }
    ],
    height: 320
  },
  {
    name: 'purchase',
    label: t('field.purchaseHistory'),
    data: purchaseHistoryItems.value,
    state: purchaseHistoryTabState.value,
    columns: [
      { prop: 'supplierName', label: t('field.supplierName'), minWidth: 180 },
      { prop: 'qty', label: t('field.quantity'), width: 100 },
      { label: t('field.price'), width: 120, formatter: (row: PurchaseHistoryItem) => formatMoney(Number(row.price || 0)) },
      { label: t('field.priceInclTax'), width: 140, formatter: (row: PurchaseHistoryItem) => formatMoney(Number(row.priceInclTax || 0)) },
      { label: t('field.orderTime'), width: 170, formatter: (row: PurchaseHistoryItem) => formatHistoryDate(row.orderAt) },
      { prop: 'orderNo', label: t('field.orderNo'), minWidth: 160, type: 'link', onClick: openPurchaseOrderHistory }
    ],
    height: 320
  },
  {
    name: 'sale-all',
    label: t('field.saleHistory'),
    data: saleHistoryItems.value,
    state: saleHistoryTabState.value,
    columns: [
      { prop: 'customerName', label: t('field.customerName'), minWidth: 160 },
      { prop: 'qty', label: t('field.quantity'), width: 100 },
      { label: t('field.price'), width: 120, formatter: (row: SaleHistoryItem) => formatMoney(Number(row.price || 0)) },
      { label: t('field.priceInclTax'), width: 140, formatter: (row: SaleHistoryItem) => formatMoney(Number(row.priceInclTax || 0)) },
      { label: t('field.orderTime'), width: 170, formatter: (row: SaleHistoryItem) => formatHistoryDate(row.orderAt) },
      { prop: 'orderNo', label: t('field.orderNo'), minWidth: 160, type: 'link', onClick: openSaleOrderHistory }
    ],
    height: 320
  }
]);
const isCreditSettlement = computed(() => {
  if (!formData.settlementMethod) return false;
  const code = String(formData.settlementMethod).toUpperCase();
  if (code === 'CREDIT' || code === 'ON_ACCOUNT' || code === 'AP') return true;
  const selected = settlementMethodOptions.value.find(item => item.code === formData.settlementMethod);
  if (selected?.fundInputMode === 'HIDDEN') return true;
  return !!selected?.name && String(selected.name).includes('挂账');
});

const hasPermission = (code: string) => authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);

const canApprove = computed(() => {
  return !isReadOnly.value && formData.status === 'DRAFT' && hasPermission('erp-purchase-draft:approve');
});

const shouldShowApproveButton = computed(() => {
  if (!hasPermission('erp-purchase-draft:approve') || isReadOnly.value) return false;
  if (canApprove.value) return true;
  return isInitializing.value || !isEditing.value || route.query.from === 'draft';
});

const canCopy = computed(() => {
  return isReadOnly.value
    && (formData.status === 'APPROVED' || formData.status === 'CANCELLED')
    && hasPermission('erp-purchase-approved:copy')
    && hasPermission('erp-purchase-draft:add');
});

const shouldShowCopyButton = computed(() => {
  if (!hasPermission('erp-purchase-approved:copy') || !hasPermission('erp-purchase-draft:add') || !isEditing.value) return false;
  if (canCopy.value) return true;
  return isInitializing.value && (route.query.mode === 'view' || route.query.from === 'approved');
});

const canPrint = computed(() => {
  return isEditing.value && hasPermission(isApprovedWorkspace.value ? 'erp-purchase-approved:print' : 'erp-purchase-draft:print');
});

const canRedFlush = computed(() => {
  return isApprovedWorkspace.value && isReadOnly.value && formData.status === 'APPROVED' && hasPermission('erp-purchase-approved:cancel');
});

const shouldShowRedFlushButton = computed(() => {
  if (!hasPermission('erp-purchase-approved:cancel') || !isEditing.value) return false;
  if (canRedFlush.value) return true;
  return isInitializing.value && (route.query.mode === 'view' || route.query.from === 'approved');
});

const canShowDiscountAllocated = computed(() => true);
const totalAmountBeforeDiscount = computed(() => formData.items.reduce((sum, item) => sum + calcLineAmount(item), 0));
const totalAmount = computed(() => Math.max(0, totalAmountBeforeDiscount.value - getDiscountAmount()));

const closePage = (redirectPath?: string) => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path, redirectPath } }));
  }
};

const closeTagByPath = (path: string) => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path } }));
  }
};

const getReturnPath = () => {
  const returnTo = typeof route.query.returnTo === 'string' ? route.query.returnTo.trim() : '';
  if (returnTo) return returnTo;
  if (route.query.from === 'draft') return draftBasePath;
  if (route.query.from === 'approved' || isApprovedWorkspace.value || route.query.mode === 'view' || formData.status === 'APPROVED' || formData.status === 'CANCELLED') {
    return approvedBasePath;
  }
  return draftBasePath;
};

const getApprovedReturnPath = () => approvedBasePath;

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const parseDecimal = (value: string | number | undefined, scale: number) => {
  if (value == null || value === '') return null;
  const raw = String(value).trim();
  const normalized = raw.endsWith('.') ? raw.slice(0, -1) : raw;
  if (!normalized) return null;
  const regex = new RegExp(`^\\d+(\\.\\d{1,${scale}})?$`);
  if (!regex.test(normalized)) return null;
  return Number(normalized);
};

const formatMoney = (value: number) => Number(value || 0).toFixed(2);

const formatPlainNumber = (value?: string | number) => {
  const parsed = parseDecimal(value, 4);
  if (parsed == null) return '-';
  return String(parsed);
};

const calcLineAmount = (row: PurchaseOrderItem) => {
  const qty = parseDecimal(row.qty, 4) || 0;
  const price = parseDecimal(row.price, 4) || 0;
  return qty * price;
};

const getDiscountAmount = () => {
  const discount = parseDecimal(formData.discountAmount, 2);
  if (discount == null) return 0;
  return Math.max(0, discount);
};

const calcLineDiscount = (row: PurchaseOrderItem) => {
  const subtotal = totalAmountBeforeDiscount.value;
  const discountAmount = getDiscountAmount();
  if (!subtotal || !discountAmount) return 0;
  const lineAmount = calcLineAmount(row);
  if (!lineAmount) return 0;
  return (lineAmount / subtotal) * discountAmount;
};

const extractRedFlushReason = (remark?: string) => {
  if (!remark) return '';
  const marker = '红冲原因：';
  const index = remark.indexOf(marker);
  if (index === -1) return '';
  return remark.slice(index + marker.length).trim();
};

const normalizeDateTimeValue = (value: any) => {
  if (!value) return '';
  if (value instanceof Date) {
    return formatDateTime(value);
  }
  const raw = String(value);
  if (!raw) return '';
  if (raw.includes('T')) {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
      return '';
    }
    return formatDateTime(parsed);
  }
  return raw;
};

const formatHistoryDate = (value: any) => normalizeDateTimeValue(value);

const normalizeArray = <T>(value: any): T[] => {
  if (Array.isArray(value)) return value as T[];
  if (Array.isArray(value?.items)) return value.items as T[];
  if (Array.isArray(value?.list)) return value.list as T[];
  return [];
};

const resolveProductLabel = (productId?: number) => productOptions.value.find(item => item.id === productId)?.name || '-';
const resolveWarehouseLabel = (warehouseId?: number) => warehouseOptions.value.find(item => item.id === warehouseId)?.name || '-';
const resolveLocationLabel = (locationId?: number) => locationOptions.value.find(item => item.id === locationId)?.name || '-';

const buildStockKey = (warehouseId: number | null | undefined, locationId: number | null | undefined) => {
  const w = warehouseId == null ? 0 : warehouseId;
  const l = locationId == null ? 0 : locationId;
  return `${w}:${l}`;
};

const getSelectableProductOptions = (currentProductId?: number | null) =>
  productOptions.value.filter(item => item.enabled !== false || item.id === currentProductId);

const getLocationOptions = (warehouseId?: number) => {
  if (!warehouseId) return [];
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const getRecentPurchaseItems = (productId?: number) => {
  if (!productId) return [];
  return productRecentPurchaseMap.value[productId] || [];
};

const fetchRecentPurchaseItems = async (productId?: number, force = false) => {
  if (!productId || !formData.supplierId) return;
  if (!force && productRecentPurchaseMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/purchase-orders/recent-items', {
      params: {
        supplierId: formData.supplierId,
        productId,
        limit: 10
      }
    });
    productRecentPurchaseMap.value = {
      ...productRecentPurchaseMap.value,
      [productId]: res.data.data || []
    };
  } catch (error) {
    notifyError(error);
  }
};

const applyPriceForRow = async (row: PurchaseOrderItem, force = false) => {
  if (!row.productId) return;
  if (!force && row.price != null && String(row.price).trim()) return;
  await fetchRecentPurchaseItems(row.productId);
  const recentPrice = getRecentPurchaseItems(row.productId).find(item => item.price != null)?.price;
  if (recentPrice != null) {
    row.price = String(recentPrice);
    return;
  }
  const product = productOptions.value.find(item => item.id === row.productId);
  if (product?.costPrice != null) {
    row.price = String(product.costPrice);
    return;
  }
  if (force) {
    row.price = '';
  }
};

const shouldRefreshPriceOnSupplierChange = (row: PurchaseOrderItem) => {
  if (!row.productId) return false;
  if (row.price == null || !String(row.price).trim()) return true;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (product?.costPrice == null) return false;
  return String(row.price).trim() === String(product.costPrice);
};

const applyProductDefaults = async (row: PurchaseOrderItem) => {
  if (!row.productId) return;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product) return;
  row.warehouseId = product.defaultWarehouseId ?? undefined;
  row.locationId = product.defaultLocationId ?? undefined;
  row.stockKey = buildStockKey(product.defaultWarehouseId ?? null, product.defaultLocationId ?? null);
  await Promise.all([
    ensureWarehouseOption(product.defaultWarehouseId),
    ensureLocationOption(product.defaultLocationId)
  ]);
};

const handleProductChange = async (row: PurchaseOrderItem) => {
  if (!formData.supplierId) {
    row.productId = undefined;
    row.warehouseId = undefined;
    row.locationId = undefined;
    row.stockKey = '';
    row.price = '';
    return;
  }
  if (!row.productId) {
    row.warehouseId = undefined;
    row.locationId = undefined;
    row.stockKey = '';
    row.price = '';
  } else {
    await applyProductDefaults(row);
  }
  await applyPriceForRow(row, true);
  await ensureNextItemAfterCompletedProduct(row);
};

const handleStockSelectionChange = (
  row: PurchaseOrderItem,
  payload: { stockKey: string; warehouseId: number | null; locationId: number | null }
) => {
  row.stockKey = payload.stockKey;
  row.warehouseId = payload.warehouseId ?? undefined;
  row.locationId = payload.locationId ?? undefined;
};

const handleItemSelectionChange = (items: PurchaseOrderItem[]) => {
  selectedItems.value = items;
};

const removeSelectedItems = () => {
  if (!selectedItems.value.length) return;
  const selectedSet = new Set(selectedItems.value);
  formData.items = formData.items.filter(item => !selectedSet.has(item));
  selectedItems.value = [];
  if (!formData.items.length) {
    addItem();
  }
};

const resetForm = () => {
  formData.orderNo = '';
  formData.orderAt = '';
  formData.status = '';
  formData.supplierId = null;
  formData.settlementMethod = '';
  formData.paymentMethodCode = '';
  formData.paidAmount = '';
  formData.discountAmount = '';
  formData.createdBy = '';
  formData.updatedBy = '';
  formData.remark = '';
  formData.items = [];
  selectedItems.value = [];
};

const addItem = () => {
  const item: PurchaseOrderItem = {
    productId: undefined,
    warehouseId: undefined,
    locationId: undefined,
    stockKey: '',
    qty: '',
    price: '',
    taxRate: '',
    remark: ''
  };
  formData.items.push(item);
  return item;
};

const setProductSelectRef = (el: any, index: number) => {
  productSelectRefs.value[index] = el;
};

const focusProductSelectAt = async (index: number) => {
  await nextTick();
  productSelectRefs.value[index]?.focus?.();
};

const ensureNextItemAfterCompletedProduct = async (row: PurchaseOrderItem) => {
  if (isReadOnly.value || !row.productId) return;
  const rowIndex = formData.items.indexOf(row);
  if (rowIndex === -1 || rowIndex !== formData.items.length - 1) return;
  addItem();
  await focusProductSelectAt(rowIndex + 1);
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
  if (!formData.items.length) {
    addItem();
  }
};

const getDefaultSettlementMethod = () => {
  if (!settlementMethodOptions.value.length) return '';
  const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
  return defaultItem?.code || '';
};

const resolveSettlementMethodCode = (value?: string) => {
  if (!value) return '';
  const normalized = String(value).trim();
  const matched = settlementMethodOptions.value.find(item => item.code === normalized || item.name === normalized);
  return matched?.code || normalized;
};

const getDefaultPaymentMethod = () => {
  if (!paymentMethodOptions.value.length) return '';
  const defaultItem = paymentMethodOptions.value.find(item => item.isDefault) ?? paymentMethodOptions.value[0];
  return defaultItem?.code || '';
};

const applyMethodsForSupplier = () => {
  const supplier = supplierOptions.value.find(item => item.id === formData.supplierId);
  const settlement = resolveSettlementMethodCode(supplier?.defaultSettlementMethodCode) || getDefaultSettlementMethod();
  const paymentMethod = supplier?.defaultPaymentMethodCode || getDefaultPaymentMethod();

  if (settlement) {
    formData.settlementMethod = settlement;
  }

  if (isCreditSettlement.value) {
    formData.paymentMethodCode = '';
    formData.paidAmount = '0';
    return;
  }

  if (paymentMethod) {
    formData.paymentMethodCode = paymentMethod;
  }
};

const applyDefaultMethods = () => {
  if (!formData.settlementMethod) {
    const defaultSettlement = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
    if (defaultSettlement) {
      formData.settlementMethod = defaultSettlement.code;
    }
  }
  if (!isCreditSettlement.value && !formData.paymentMethodCode) {
    const defaultPayment = paymentMethodOptions.value.find(item => item.isDefault) ?? paymentMethodOptions.value[0];
    if (defaultPayment) {
      formData.paymentMethodCode = defaultPayment.code;
    }
  } else if (isCreditSettlement.value) {
    formData.paymentMethodCode = '';
    formData.paidAmount = '0';
  }
};

const fetchSuppliers = async () => {
  try {
    supplierOptions.value = await getCachedSuppliers(tenantCacheKey.value);
    if (formData.supplierId) {
      applyMethodsForSupplier();
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchProducts = async () => {
  try {
    const products = await getCachedProductOptions(tenantCacheKey.value);
    productOptions.value = (products || []).map((product) => ({
      id: product.id,
      name: product.name,
      defaultWarehouseId: product.defaultWarehouseId,
      defaultLocationId: product.defaultLocationId,
      costPrice: product.costPrice,
      enabled: product.enabled
    }));
  } catch (error) {
    notifyError(error);
  }
};

const fetchCustomerCategories = async () => {
  try {
    customerCategoryOptions.value = await getCachedCustomerCategories(tenantCacheKey.value);
  } catch (error) {
    notifyError(error);
  }
};

const fetchWarehouses = async () => {
  try {
    warehouseOptions.value = await getCachedWarehouseOptions(tenantCacheKey.value);
  } catch (error) {
    notifyError(error);
  }
};

const fetchLocations = async () => {
  try {
    locationOptions.value = await getCachedLocationOptions(tenantCacheKey.value);
  } catch (error) {
    notifyError(error);
  }
};

const fetchSettlementMethods = async () => {
  try {
    settlementMethodOptions.value = await getCachedEnabledSettlementMethods(tenantCacheKey.value);
    if (formData.supplierId) {
      applyMethodsForSupplier();
    } else {
      applyDefaultMethods();
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchPaymentMethods = async () => {
  try {
    paymentMethodOptions.value = await getCachedEnabledPaymentMethods(tenantCacheKey.value);
    if (formData.supplierId) {
      applyMethodsForSupplier();
    } else {
      applyDefaultMethods();
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureProductOption = async (productId?: number | null) => {
  if (!productId || productOptions.value.some(item => item.id === productId)) return;
  try {
    const res: any = await request.get(`/erp/products/${productId}`);
    const product = res.data.data;
    if (product) {
      productOptions.value = mergeOptionById(productOptions.value, {
        id: product.id,
        name: product.name,
        defaultWarehouseId: product.defaultWarehouseId,
        defaultLocationId: product.defaultLocationId,
        costPrice: product.costPrice,
        enabled: product.enabled
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureWarehouseOption = async (warehouseId?: number | null) => {
  if (!warehouseId || warehouseOptions.value.some(item => item.id === warehouseId)) return;
  try {
    const res: any = await request.get(`/erp/warehouses/${warehouseId}`);
    const warehouse = res.data.data;
    if (warehouse) {
      warehouseOptions.value = mergeOptionById(warehouseOptions.value, {
        id: warehouse.id,
        name: warehouse.name
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureLocationOption = async (locationId?: number | null) => {
  if (!locationId || locationOptions.value.some(item => item.id === locationId)) return;
  try {
    const res: any = await request.get(`/erp/locations/${locationId}`);
    const location = res.data.data;
    if (location) {
      locationOptions.value = mergeOptionById(locationOptions.value, {
        id: location.id,
        name: location.name,
        warehouseId: location.warehouseId
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchNextOrderNo = async () => {
  try {
    const res: any = await request.get(`${draftApiBase}/next-order-no`);
    if (res.data.code === 200) {
      formData.orderNo = res.data.data || '';
    }
  } catch (error) {
    notifyError(error);
  }
};

const loadDetail = async () => {
  if (!route.path.startsWith('/erp/purchase-orders')) return;
  const currentSeq = ++detailLoadSeq.value;
  isInitializing.value = true;
  resetForm();
  productRecentPurchaseMap.value = {};
  try {
    if (!isEditing.value) {
      await fetchNextOrderNo();
      if (!isLatestDetailLoad(currentSeq)) return;
      formData.orderAt = formatDateTime(new Date());
      formData.status = 'DRAFT';
      applyDefaultMethods();
      addItem();
      return;
    }

    const res: any = await request.get(`${detailApiBase.value}/${route.params.id}`);
    if (!isLatestDetailLoad(currentSeq)) return;
    if (res.data.code === 200) {
      const data = res.data.data || {};
      const order = data.order || data;
      formData.orderNo = order.orderNo || '';
      formData.status = order.status || '';
      formData.supplierId = order.supplierId || null;
      formData.settlementMethod = order.settlementMethod || '';
      formData.paymentMethodCode = order.paymentMethodCode || '';
      formData.paidAmount = order.paidAmount == null ? '' : String(order.paidAmount);
      formData.discountAmount = order.discountAmount == null ? '' : String(order.discountAmount);
      formData.createdBy = order.createdBy || '';
      formData.updatedBy = order.updatedBy || formData.createdBy;
      formData.orderAt = formatDateTime(new Date(order.orderAt || order.createdAt || Date.now()));
      formData.remark = order.remark || '';
      formData.items = (data.items || order.items || []).map((item: any) => ({
        id: item.id,
        productId: item.productId,
        warehouseId: item.warehouseId,
        locationId: item.locationId,
        stockKey: buildStockKey(item.warehouseId ?? null, item.locationId ?? null),
        qty: item.qty == null ? '' : String(item.qty),
        price: item.price == null ? '' : String(item.price),
        taxRate: item.taxRate == null ? '' : String(item.taxRate),
        remark: item.remark || ''
      }));
      await Promise.all(formData.items.flatMap(item => [
        ensureProductOption(item.productId),
        ensureWarehouseOption(item.warehouseId),
        ensureLocationOption(item.locationId)
      ]));
      if (!isLatestDetailLoad(currentSeq)) return;
      if (!formData.items.length) {
        addItem();
      }
      applyDefaultMethods();
    }
  } catch (error) {
    if (isLatestDetailLoad(currentSeq)) {
      notifyError(error);
    }
  } finally {
    if (isLatestDetailLoad(currentSeq)) {
      isInitializing.value = false;
    }
  }
};

const resolveHistoryRange = (range: string[]) => {
  if (!range || range.length < 2) return null;
  const [start, end] = range;
  if (!start || !end) return null;
  const startDate = new Date(`${start}T00:00:00`);
  const endDate = new Date(`${end}T23:59:59.999`);
  if (Number.isNaN(startDate.getTime()) || Number.isNaN(endDate.getTime())) return null;
  return {
    startAt: startDate.toISOString(),
    endAt: endDate.toISOString()
  };
};

const buildHistoryParams = (range: string[], keyword: string, page: number, size: number, includeSupplier = false) => {
  const productId = historyProduct.value?.id;
  if (!productId) return null;
  const params: Record<string, any> = { productId, page, size };
  if (includeSupplier && formData.supplierId) {
    params.supplierId = formData.supplierId;
  }
  const normalized = keyword.trim();
  if (normalized) {
    params.keyword = normalized;
  }
  const resolved = resolveHistoryRange(range);
  if (resolved) {
    params.startAt = resolved.startAt;
    params.endAt = resolved.endAt;
  }
  return params;
};

let historyLoadingCount = 0;
const withHistoryLoading = async (task: () => Promise<void>) => {
  historyLoadingCount += 1;
  historyLoading.value = true;
  try {
    await task();
  } finally {
    historyLoadingCount -= 1;
    if (historyLoadingCount <= 0) {
      historyLoadingCount = 0;
      historyLoading.value = false;
    }
  }
};

const fetchPurchaseHistory = async (page = purchaseHistoryPage.value) => {
  const params = buildHistoryParams(
    purchaseHistoryRange.value,
    purchaseHistoryKeyword.value,
    page,
    purchaseHistorySize.value,
    true
  );
  if (!params) {
    purchaseHistoryItems.value = [];
    purchaseHistoryTotal.value = 0;
    return;
  }
  await withHistoryLoading(async () => {
    try {
      const res: any = await request.get('/erp/purchase-orders/product-history', { params });
      const data = res?.data?.data || {};
      purchaseHistoryItems.value = normalizeArray<PurchaseHistoryItem>(data);
      purchaseHistoryTotal.value = data.total || 0;
      purchaseHistoryPage.value = data.page || page;
      purchaseHistorySize.value = data.size || purchaseHistorySize.value;
    } catch (error) {
      purchaseHistoryItems.value = [];
      purchaseHistoryTotal.value = 0;
      notifyError(error);
    }
  });
};

const fetchSaleHistory = async (page = saleHistoryPage.value) => {
  const params = buildHistoryParams(
    saleHistoryRange.value,
    saleHistoryKeyword.value,
    page,
    saleHistorySize.value
  );
  if (!params) {
    saleHistoryItems.value = [];
    saleHistoryTotal.value = 0;
    return;
  }
  await withHistoryLoading(async () => {
    try {
      const res: any = await request.get('/erp/sale-orders/product-history', { params });
      const data = res?.data?.data || {};
      saleHistoryItems.value = normalizeArray<SaleHistoryItem>(data);
      saleHistoryTotal.value = data.total || 0;
      saleHistoryPage.value = data.page || page;
      saleHistorySize.value = data.size || saleHistorySize.value;
    } catch (error) {
      saleHistoryItems.value = [];
      saleHistoryTotal.value = 0;
      notifyError(error);
    }
  });
};

const fetchProductPrices = async () => {
  const productId = historyProduct.value?.id;
  if (!productId) {
    priceHistoryItems.value = [];
    return;
  }
  await withHistoryLoading(async () => {
    try {
      const res: any = await request.get('/erp/product-prices', { params: { productId } });
      const items = normalizeArray<any>(res?.data?.data);
      priceHistoryItems.value = items.map((item: any) => ({
        ...item,
        customerCategoryName: customerCategoryNameMap.value.get(item.customerCategoryId) || '-'
      }));
    } catch (error) {
      priceHistoryItems.value = [];
      notifyError(error);
    }
  });
};

const handleHistoryTabChange = (tabName: string | number) => {
  historyTab.value = String(tabName) as typeof historyTab.value;
  if (historyTab.value === 'price') {
    fetchProductPrices();
    return;
  }
  if (historyTab.value === 'purchase') {
    fetchPurchaseHistory(purchaseHistoryPage.value);
    return;
  }
  if (historyTab.value === 'sale-all') {
    fetchSaleHistory(saleHistoryPage.value);
  }
};

const handlePurchaseHistoryPageChange = (page: number) => {
  purchaseHistoryPage.value = page;
  fetchPurchaseHistory(page);
};

const handlePurchaseHistorySizeChange = (size: number) => {
  purchaseHistorySize.value = size;
  purchaseHistoryPage.value = 1;
  fetchPurchaseHistory(1);
};

const handleSaleHistoryPageChange = (page: number) => {
  saleHistoryPage.value = page;
  fetchSaleHistory(page);
};

const handleSaleHistorySizeChange = (size: number) => {
  saleHistorySize.value = size;
  saleHistoryPage.value = 1;
  fetchSaleHistory(1);
};

const handleHistoryDialogFilterChange = (payload: { tabName: string; keyword?: string; range?: string[] }) => {
  if (payload.tabName === 'purchase') {
    if (payload.keyword !== undefined) purchaseHistoryKeyword.value = payload.keyword;
    if (payload.range !== undefined) purchaseHistoryRange.value = payload.range;
    return;
  }
  if (payload.tabName === 'sale-all') {
    if (payload.keyword !== undefined) saleHistoryKeyword.value = payload.keyword;
    if (payload.range !== undefined) saleHistoryRange.value = payload.range;
  }
};

const handleHistoryDialogPageChange = (payload: { tabName: string; page: number }) => {
  if (payload.tabName === 'purchase') {
    handlePurchaseHistoryPageChange(payload.page);
    return;
  }
  if (payload.tabName === 'sale-all') {
    handleSaleHistoryPageChange(payload.page);
  }
};

const handleHistoryDialogSizeChange = (payload: { tabName: string; size: number }) => {
  if (payload.tabName === 'purchase') {
    handlePurchaseHistorySizeChange(payload.size);
    return;
  }
  if (payload.tabName === 'sale-all') {
    handleSaleHistorySizeChange(payload.size);
  }
};

const openPurchaseOrderHistory = (row: PurchaseHistoryItem) => {
  if (!row?.orderId) return;
  router.push({
    path: `${approvedBasePath}/${row.orderId}`,
    query: { mode: 'view', from: 'approved' }
  });
  historyDialogVisible.value = false;
};

const openSaleOrderHistory = (row: SaleHistoryItem) => {
  if (!row?.orderId) return;
  router.push({
    path: `/erp/sale-orders/${row.orderId}/edit`,
    query: { mode: 'view', from: 'approved' }
  });
  historyDialogVisible.value = false;
};

const openHistoryForRow = async (row: PurchaseOrderItem) => {
  if (!row.productId) {
    notifyWarning(t('message.selectProductFirst'));
    return;
  }
  historyProduct.value = productOptions.value.find(item => item.id === row.productId)
    || { id: row.productId, name: String(row.productId) };
  historyDialogVisible.value = true;
  historyTab.value = 'purchase';
  priceHistoryItems.value = [];
  saleHistoryItems.value = [];
  purchaseHistoryItems.value = [];
  saleHistoryKeyword.value = '';
  purchaseHistoryKeyword.value = '';
  saleHistoryRange.value = [];
  purchaseHistoryRange.value = [];
  saleHistoryPage.value = 1;
  saleHistoryTotal.value = 0;
  purchaseHistoryPage.value = 1;
  purchaseHistoryTotal.value = 0;
  await Promise.all([
    fetchProductPrices(),
    fetchPurchaseHistory(1),
    fetchSaleHistory(1)
  ]);
};

const openSaveSuccessDialog = (savedId: number | null, savedOrderNo?: string, mode: 'save' | 'approve' = 'save') => {
  saveSuccessDocId.value = savedId;
  saveSuccessOrderNo.value = savedOrderNo || formData.orderNo || '';
  saveSuccessDialogMode.value = mode;
  saveSuccessAction.value = null;
  saveSuccessDialogVisible.value = true;
};

const closeSaveSuccessDialog = () => {
  saveSuccessDialogVisible.value = false;
};

const isLatestDetailLoad = (seq: number) => detailLoadSeq.value === seq;

const navigateToApprovedView = async (savedId: number) => {
  await router.replace({
    path: `${approvedBasePath}/${savedId}`,
    query: {
      mode: 'view',
      from: 'approved',
      returnTo: approvedBasePath
    }
  });
};

const saveData = async (
  options: {
    silentSuccess?: boolean;
    showPostSaveDialog?: boolean;
    closeOnSuccess?: boolean;
    reloadAfterCreate?: boolean;
  } = {}
) => {
  const silentSuccess = options.silentSuccess === true;
  const showPostSaveDialog = options.showPostSaveDialog !== false;
  const closeOnSuccess = options.closeOnSuccess === true;

  if (!formData.supplierId) {
    notifyWarning(requiredFieldMessage(t('field.supplier')));
    return null;
  }

  const validItems = formData.items.filter(item => item.productId);
  if (!validItems.length) {
    notifyWarning(t('message.noItems'));
    return null;
  }

  for (const [index, item] of validItems.entries()) {
    const rowNumber = index + 1;
    if (item.stockKey && (!item.warehouseId || !item.locationId)) {
      const [warehouseRaw, locationRaw] = item.stockKey.split(':');
      const warehouseId = Number(warehouseRaw);
      const locationId = Number(locationRaw);
      item.warehouseId = Number.isNaN(warehouseId) || warehouseId === 0 ? undefined : warehouseId;
      item.locationId = Number.isNaN(locationId) || locationId === 0 ? undefined : locationId;
    }
    if (!item.warehouseId || !item.locationId) {
      notifyWarning(
        !item.warehouseId
          ? requiredRowFieldMessage(rowNumber, t('field.warehouse'))
          : requiredRowFieldMessage(rowNumber, t('field.location'))
      );
      return null;
    }
    const qtyValue = parseDecimal(item.qty, 4);
    if (qtyValue == null || qtyValue <= 0) {
      notifyWarning(positiveRowFieldMessage(rowNumber, t('field.quantity')));
      return null;
    }
    const priceValue = parseDecimal(item.price, 4);
    if (priceValue == null) {
      notifyWarning(invalidRowFieldMessage(rowNumber, t('field.price')));
      return null;
    }
  }

  const payload = {
    orderNo: formData.orderNo || undefined,
    orderAt: formData.orderAt || undefined,
    supplierId: formData.supplierId,
    settlementMethod: formData.settlementMethod || undefined,
    paymentMethodCode: isCreditSettlement.value ? undefined : (formData.paymentMethodCode || undefined),
    paidAmount: isCreditSettlement.value ? 0 : parseDecimal(formData.paidAmount, 2),
    discountAmount: parseDecimal(formData.discountAmount, 2),
    remark: formData.remark,
    items: validItems.map((item, index) => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: parseDecimal(item.qty, 4),
      price: parseDecimal(item.price, 4),
      taxRate: parseDecimal(item.taxRate, 4),
      remark: item.remark,
      sortNo: index + 1
    }))
  };

  try {
    isSaving.value = true;
    const res: any = isEditing.value
      ? await request.put(`${draftApiBase}/${route.params.id}`, payload)
      : await request.post(draftApiBase, payload);

    if (res.data.code === 200) {
      const data = res.data.data || {};
      const savedId = data.order?.id || data.id || Number(route.params.id || 0) || null;
      const savedOrderNo = data.order?.orderNo || data.orderNo || formData.orderNo || '';
      if (!isEditing.value && savedId && options.reloadAfterCreate) {
        await router.replace({
          path: `${draftBasePath}/${savedId}/edit`,
          query: { returnTo: getReturnPath(), from: 'draft' }
        });
      }
      if (savedId && showPostSaveDialog) {
        openSaveSuccessDialog(savedId, savedOrderNo, 'save');
        return savedId;
      }
      if (!silentSuccess) {
        notifySuccess(t('message.saveSuccess'));
      }
      if (closeOnSuccess) {
        closePage(getReturnPath());
      }
      return savedId;
    }
  } catch (error) {
    notifyError(error);
  } finally {
    isSaving.value = false;
  }
  return null;
};

const approveSavedOrder = async (savedId: number, savedOrderNo?: string) => {
  const sourcePath = route.path;
  try {
    isSaving.value = true;
    await request.post(`${draftApiBase}/${savedId}/approve`);
    formData.status = 'APPROVED';
    notifySuccess(t('message.approveSuccess'));
    await navigateToApprovedView(savedId);
    await nextTick();
    if (sourcePath !== route.path) {
      closeTagByPath(sourcePath);
    }
    await loadDetail();
    openSaveSuccessDialog(savedId, savedOrderNo, 'approve');
  } catch (error) {
    notifyError(error);
  } finally {
    isSaving.value = false;
  }
};

const handleSave = async () => {
  await saveData({ reloadAfterCreate: true });
};

const handleApprove = async () => {
  if (isReadOnly.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }

  const savedId = await saveData({
    silentSuccess: true,
    showPostSaveDialog: false,
    reloadAfterCreate: true
  });
  if (!savedId) return;
  await approveSavedOrder(savedId, formData.orderNo);
};

const handleBack = () => {
  closePage(getReturnPath());
};

const handlePrint = () => {
  const id = Number(route.params.id || saveSuccessDocId.value || 0);
  if (!id) return;
  printDocId.value = id;
  printDialogVisible.value = true;
};

const handleRedFlush = async () => {
  if (!isEditing.value) return;
  try {
    const { value } = await ElMessageBox.prompt(
      t('message.confirmRedFlush'),
      t('action.redFlush'),
      {
        inputPlaceholder: t('placeholder.required'),
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel')
      }
    );
    if (!value || !String(value).trim()) return;
    await request.post(`${approvedApiBase}/${route.params.id}/cancel`, { reason: String(value).trim() });
    notifySuccess();
    await loadDetail();
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleCopy = async () => {
  if (!isEditing.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmCopyOrder'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.copy'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }

  try {
    const createRes: any = await request.post(`${approvedApiBase}/${route.params.id}/copy`);
    if (createRes.data.code === 200) {
      const data = createRes.data.data || {};
      const newId = data.order?.id || data.id;
      notifySuccess();
      if (newId) {
        await router.push({
          path: `${draftBasePath}/${newId}/edit`,
          query: {
            from: 'draft',
            returnTo: draftBasePath
          }
        });
      }
    }
  } catch (error) {
    notifyError(error);
  }
};

const handleSupplierChange = async (value?: number | null) => {
  if (value !== undefined) {
    formData.supplierId = value;
  }
  applyMethodsForSupplier();
  productRecentPurchaseMap.value = {};
  for (const item of formData.items) {
    if (shouldRefreshPriceOnSupplierChange(item)) {
      await applyPriceForRow(item, true);
    }
  }
};

const handleContinueCreate = () => {
  saveSuccessAction.value = 'continue';
  closeSaveSuccessDialog();
};

const handleStayCurrent = () => {
  saveSuccessAction.value = 'stay';
  closeSaveSuccessDialog();
};

const handleBackToList = () => {
  saveSuccessAction.value = 'list';
  closeSaveSuccessDialog();
};

const handleSaveSuccessPrint = () => {
  if (!saveSuccessDocId.value) return;
  pendingPrintDocId.value = saveSuccessDocId.value;
  saveSuccessAction.value = 'print';
  closeSaveSuccessDialog();
};

const handleApproveFromSaveDialog = async () => {
  if (!saveSuccessDocId.value) return;
  const savedId = saveSuccessDocId.value;
  const savedOrderNo = saveSuccessOrderNo.value;
  saveSuccessDialogVisible.value = false;
  await approveSavedOrder(savedId, savedOrderNo);
};

const handleSaveSuccessDialogClosed = async () => {
  const action = saveSuccessAction.value;
  const dialogMode = saveSuccessDialogMode.value;
  saveSuccessAction.value = null;
  saveSuccessDocId.value = null;
  saveSuccessOrderNo.value = '';
  saveSuccessDialogMode.value = 'save';

  if (action === 'continue') {
    const createRoute = {
      path: `${draftBasePath}/create`,
      query: {
        from: 'draft',
        returnTo: draftBasePath
      }
    };
    const targetFullPath = router.resolve(createRoute).fullPath;
    if (route.fullPath !== targetFullPath) {
      await router.replace(createRoute);
    }
    await loadDetail();
    return;
  }

  if (action === 'list') {
    const target = dialogMode === 'approve' ? getApprovedReturnPath() : getReturnPath();
    closePage(target);
    return;
  }

  if (action === 'print') {
    if (pendingPrintDocId.value) {
      printDocId.value = pendingPrintDocId.value;
      printDialogVisible.value = true;
      pendingPrintDocId.value = null;
    }
    return;
  }
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

watch(
  () => route.fullPath,
  (newPath) => {
    if (newPath === lastRouteKey.value) return;
    if (!isPageActive.value) return;
    if (!route.path.startsWith('/erp/purchase-orders')) return;
    lastRouteKey.value = newPath;
    pagePath.value = route.path;
    loadDetail();
  }
);

watch(
  () => formData.settlementMethod,
  () => {
    if (isCreditSettlement.value) {
      formData.paymentMethodCode = '';
      formData.paidAmount = '0';
    } else if (!formData.paymentMethodCode) {
      const defaultPayment = paymentMethodOptions.value.find(item => item.isDefault) ?? paymentMethodOptions.value[0];
      formData.paymentMethodCode = defaultPayment?.code || '';
    }
  }
);

watch([purchaseHistoryKeyword, purchaseHistoryRange], () => {
  if (!historyDialogVisible.value) return;
  purchaseHistoryPage.value = 1;
  if (historyTab.value === 'purchase') {
    fetchPurchaseHistory(1);
  }
}, { deep: true });

watch([saleHistoryKeyword, saleHistoryRange], () => {
  if (!historyDialogVisible.value) return;
  saleHistoryPage.value = 1;
  if (historyTab.value === 'sale-all') {
    fetchSaleHistory(1);
  }
}, { deep: true });

onMounted(() => {
  isPageActive.value = true;
  pagePath.value = route.path;
  fetchSuppliers();
  fetchProducts();
  fetchCustomerCategories();
  fetchWarehouses();
  fetchLocations();
  fetchSettlementMethods();
  fetchPaymentMethods();
  loadDetail();
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('tags:close', handleTagClosing as EventListener);
  }
});

onActivated(() => {
  isPageActive.value = true;
  if (!route.path.startsWith('/erp/purchase-orders')) return;
  if (!needsReload.value) return;
  needsReload.value = false;
  loadDetail();
});

onDeactivated(() => {
  isPageActive.value = false;
});

onBeforeUnmount(() => {
  isPageActive.value = false;
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('tags:close', handleTagClosing as EventListener);
  }
  resetForm();
});
</script>

<style scoped>
:global(.content-area:has(.purchase-page-surface)) {
  background: #ffffff;
}

.purchase-page-surface {
  --purchase-page-bg: #ffffff;
  --purchase-card-bg: #ffffff;
  --purchase-card-border: #e3eaf4;
  --purchase-card-shadow: 0 16px 36px rgba(28, 45, 76, 0.08), 0 4px 12px rgba(28, 45, 76, 0.04);
  --purchase-card-radius: 12px;
  --purchase-text: #17233c;
  --purchase-muted: #6d7b91;
  --purchase-primary: #1677ff;
  --purchase-danger: #ff4d4f;
  --purchase-control-border: #d7e0ec;
  min-height: 100%;
  height: auto;
  padding: 16px 20px;
  box-sizing: border-box;
  background: transparent;
  color: var(--purchase-text);
}

.purchase-page-surface .page-title {
  color: var(--purchase-text);
  font-weight: 800;
  font-size: 24px;
  line-height: 32px;
}

.purchase-page-header {
  align-items: center !important;
  margin-bottom: 16px !important;
  gap: 14px;
}

.purchase-title-group {
  display: flex;
  align-items: center;
  gap: 18px;
  min-width: 0;
}

.purchase-breadcrumb {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  color: #7d889b;
  font-size: 13px;
  font-weight: 500;
  white-space: nowrap;
}

.purchase-breadcrumb__separator {
  color: #a8b2c1;
}

.purchase-page-toolbar__actions {
  justify-content: flex-end;
  gap: 16px;
}

.purchase-page-surface .purchase-header-card,
.purchase-page-surface .purchase-detail-card,
.purchase-page-surface .payment-card {
  border: 1px solid var(--purchase-card-border);
  border-radius: var(--purchase-card-radius);
  background: var(--purchase-card-bg);
  box-shadow: var(--purchase-card-shadow);
  flex: 0 0 auto;
  overflow: visible;
}

.purchase-page-surface .purchase-header-card {
  padding: 20px 22px;
}

.purchase-page-surface .purchase-detail-card {
  min-height: 0;
  margin-top: 18px;
  padding: 18px 22px;
}

.purchase-page-surface .payment-card {
  margin-top: 18px;
  padding: 18px 22px;
}

.card-section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
}

.card-section-header h4 {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  color: var(--purchase-text);
  font-size: 15px;
  font-weight: 700;
}

.card-section-header h4::before {
  content: '';
  width: 4px;
  height: 20px;
  border-radius: 999px;
  background: var(--purchase-primary);
}

.purchase-form :deep(.el-form-item) {
  margin-bottom: 4px;
}

.purchase-form--compact :deep(.el-form-item) {
  margin-bottom: 0;
}

.purchase-page-surface :deep(.el-form-item__label) {
  color: var(--purchase-muted);
  font-weight: 600;
  line-height: 18px;
  padding-bottom: 6px;
}

.purchase-header-body,
.purchase-detail-body,
.payment-card-body {
  padding: 0 !important;
  overflow: visible;
}

.purchase-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.form-grid {
  display: flex;
  flex-wrap: nowrap;
  gap: 12px;
  overflow-x: auto;
  padding-bottom: 4px;
}

.purchase-header-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(220px, 1fr));
  gap: 18px 32px;
  overflow: visible;
  padding-bottom: 0;
}

.form-group {
  min-width: 220px;
}

.purchase-page-surface .purchase-header-grid .form-group,
.payment-grid .form-group {
  min-width: 0;
}

.purchase-remark-item {
  width: calc(((100% - 64px) / 3) * 2 + 32px);
  max-width: 100%;
  margin-top: 18px;
}

.readonly-field,
.readonly-inline,
.readonly-cell {
  color: var(--purchase-text);
}

.readonly-field {
  min-height: 28px;
  display: flex;
  align-items: center;
  padding: 2px 0;
  font-size: 14px;
  line-height: 1.45;
  word-break: break-word;
}

.readonly-field--strong,
.readonly-inline {
  font-weight: 600;
}

.readonly-field--remark {
  min-height: 40px;
  white-space: pre-wrap;
}

.readonly-field--danger {
  color: #b4232a;
}

.readonly-inline {
  min-width: 92px;
  min-height: 28px;
  display: inline-flex;
  align-items: center;
}

.purchase-page-surface .action-button {
  min-width: 78px;
  height: 36px;
  border-radius: 8px;
  border-color: #d9e2ef;
  background: #ffffff;
  color: #26344f;
  font-size: 14px;
  box-shadow: none;
}

.purchase-page-surface .action-button:hover,
.purchase-page-surface .action-button:focus-visible {
  border-color: #9eb2ce;
  background: #f8fbff;
  color: #17233d;
}

.purchase-page-surface .action-button--secondary,
.purchase-page-surface .action-button--save {
  border-color: #b8d2ff;
  background: #f3f8ff;
  color: #155ec9;
}

.purchase-page-surface .action-button--secondary:hover,
.purchase-page-surface .action-button--secondary:focus-visible,
.purchase-page-surface .action-button--save:hover,
.purchase-page-surface .action-button--save:focus-visible {
  border-color: #7faeff;
  background: #eaf3ff;
  color: #0f56bd;
}

.purchase-page-surface .action-button--secondary.is-disabled,
.purchase-page-surface .action-button--secondary.is-disabled:hover,
.purchase-page-surface .action-button--save.is-disabled,
.purchase-page-surface .action-button--save.is-disabled:hover {
  border-color: #c9dcff;
  background: #f3f8ff;
  color: #6f95cf;
  opacity: 0.72;
}

.purchase-page-surface .action-button--primary.el-button--primary {
  background: #1677ff;
  border-color: #1677ff;
  color: #ffffff;
  box-shadow: 0 8px 18px rgba(22, 119, 255, 0.16);
}

.purchase-page-surface .action-button--primary.el-button--primary:hover,
.purchase-page-surface .action-button--primary.el-button--primary:focus-visible {
  background: #0f68e8;
  border-color: #0f68e8;
}

.purchase-page-surface .action-button--success.el-button--success.is-plain,
.dialog-approve-button.el-button--success.is-plain {
  background: #eef8ee;
  border-color: #b9dfb8;
  color: #2f7d32;
}

.purchase-page-surface .action-button--success.el-button--success.is-plain:hover,
.purchase-page-surface .action-button--success.el-button--success.is-plain:focus-visible,
.dialog-approve-button.el-button--success.is-plain:hover,
.dialog-approve-button.el-button--success.is-plain:focus-visible {
  background: #e1f2df;
  border-color: #8ecf8c;
  color: #256a28;
}

.purchase-page-surface .action-button--success.el-button--success.is-plain.is-disabled,
.purchase-page-surface .action-button--success.el-button--success.is-plain.is-disabled:hover,
.dialog-approve-button.el-button--success.is-plain.is-disabled,
.dialog-approve-button.el-button--success.is-plain.is-disabled:hover {
  background: #eef8ee;
  border-color: #c8e3c7;
  color: #6a9a6c;
  opacity: 0.72;
}

.purchase-page-surface .action-button--danger.el-button--danger.is-plain {
  background: #fff2f2;
  border-color: #f2b8b8;
  color: #b4232a;
}

.purchase-page-surface .action-button--danger.el-button--danger.is-plain:hover,
.purchase-page-surface .action-button--danger.el-button--danger.is-plain:focus-visible {
  background: #ffe4e4;
  border-color: #ec8f8f;
  color: #991b1f;
}

.purchase-page-surface .action-button--danger.el-button--danger.is-plain.is-disabled,
.purchase-page-surface .action-button--danger.el-button--danger.is-plain.is-disabled:hover {
  background: #fff2f2;
  border-color: #f2c7c7;
  color: #c56a6e;
  opacity: 0.72;
}

.purchase-page-surface :deep(.el-input__wrapper),
.purchase-page-surface :deep(.el-select__wrapper) {
  min-height: 36px;
  border-radius: 6px;
  background: #ffffff;
  box-shadow: 0 0 0 1px var(--purchase-control-border) inset;
}

.purchase-page-surface :deep(.el-input__wrapper:hover),
.purchase-page-surface :deep(.el-select__wrapper:hover) {
  box-shadow: 0 0 0 1px #a9c7f3 inset;
}

.purchase-page-surface :deep(.el-input__wrapper.is-focus),
.purchase-page-surface :deep(.el-select__wrapper.is-focused) {
  box-shadow: 0 0 0 1px var(--purchase-primary) inset, 0 0 0 3px rgba(22, 119, 255, 0.08);
}

.purchase-page-surface :deep(.el-input.is-disabled .el-input__wrapper) {
  background: #f7f9fc;
}

.purchase-page-surface :deep(.el-textarea__inner) {
  border-radius: 6px;
  border: none;
  background: #ffffff;
  box-shadow: 0 0 0 1px var(--purchase-control-border) inset;
  padding: 10px 12px;
  font-size: 14px;
  resize: vertical;
}

.purchase-page-surface :deep(.el-textarea__inner:focus) {
  box-shadow: 0 0 0 1px var(--purchase-primary) inset, 0 0 0 3px rgba(22, 119, 255, 0.08);
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 16px;
}

.detail-header {
  margin-bottom: 8px;
}

.detail-header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.detail-toolbar-button {
  height: 32px;
  border-radius: 6px;
  border-color: #d8e1ed;
  color: #4c5b70;
  font-weight: 600;
}

.detail-toolbar-button--primary {
  border-color: var(--purchase-primary);
  color: var(--purchase-primary);
  background: #ffffff;
}

.detail-table-wrapper {
  flex: 0 0 auto;
  min-height: 0;
  border: 1px solid #e1e9f4;
  border-radius: 10px;
  background: #fbfdff;
  overflow: auto;
}

.purchase-page-surface :deep(.el-table) {
  --el-table-border-color: #e1e9f4;
  --el-table-header-bg-color: #f8fafc;
  --el-table-row-hover-bg-color: #fbfdff;
  color: var(--purchase-text);
}

.purchase-page-surface :deep(.el-table th.el-table__cell) {
  background: #f8fafc;
  color: #26344f;
  font-weight: 700;
}

.purchase-page-surface :deep(.el-table td.el-table__cell) {
  height: 48px;
  color: #1f2b3d;
}

.purchase-page-surface :deep(.el-table .el-input__wrapper),
.purchase-page-surface :deep(.el-table .el-select__wrapper) {
  min-height: 34px;
}

.required-table-label::before {
  content: '*';
  margin-right: 4px;
  color: var(--purchase-danger);
  font-weight: 700;
}

.product-cell {
  display: flex;
  align-items: center;
  gap: 8px;
}

.product-cell__label,
.product-cell__select {
  flex: 1 1 auto;
  min-width: 0;
}

.history-inline {
  flex: 0 0 auto;
}

.history-tag {
  cursor: pointer;
  user-select: none;
}

.history-tag--inline {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  padding: 0;
  border-radius: 6px;
  line-height: 32px;
  background: #f7fbff;
}

.history-icon {
  font-size: 14px;
}

.history-tag.el-tag--info {
  cursor: not-allowed;
  opacity: 0.6;
}

.warehouse-location-editor {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 8px;
}

.row-delete-button {
  width: 32px;
  height: 32px;
  padding: 0;
  font-size: 18px;
}

.detail-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 18px;
  margin-top: 2px;
}

.detail-actions {
  display: flex;
  justify-content: flex-start;
}

.detail-add-item-button {
  height: 34px;
  border-radius: 6px;
  border-color: var(--purchase-primary);
  background: #ffffff;
  color: var(--purchase-primary);
  font-weight: 700;
}

.detail-summary {
  display: flex;
  align-items: baseline;
  gap: 26px;
  justify-content: flex-end;
  margin-left: auto;
  font-size: 14px;
  color: #26344f;
  font-weight: 600;
}

.summary-item {
  white-space: nowrap;
}

.summary-item--total strong {
  margin-left: 6px;
  color: var(--purchase-primary);
  font-size: 20px;
  font-weight: 800;
}

.payment-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(180px, 1fr));
  gap: 16px 24px;
  align-items: start;
}

.order-time-picker {
  width: 100%;
}

.order-time-picker :deep(.el-input__wrapper) {
  width: 100%;
  box-sizing: border-box;
}

.order-time-picker :deep(.el-input__inner) {
  width: 100%;
  padding-right: 48px;
}

.order-time-picker :deep(.el-input__suffix) {
  width: 44px;
  display: flex;
  justify-content: flex-end;
}

.save-success-dialog__content {
  display: flex;
  flex-direction: column;
  gap: 10px;
  line-height: 1.6;
}

.save-success-dialog__message {
  color: var(--el-text-color-primary);
}

.save-success-dialog__order-no {
  color: var(--el-text-color-regular);
  font-size: 13px;
}

.save-success-dialog__actions {
  display: flex;
  justify-content: flex-end;
  flex-wrap: wrap;
  gap: 10px;
}

.history-header {
  display: flex;
  align-items: center;
  gap: 24px;
  margin-bottom: 16px;
  color: #26344f;
}

.history-header__item {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.history-grid {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.history-toolbar {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.history-search {
  width: 260px;
  max-width: 100%;
}

.history-date {
  width: 320px;
  max-width: 100%;
}

.history-pagination {
  display: flex;
  justify-content: flex-end;
}

@media (max-width: 1280px) {
  .purchase-header-grid {
    grid-template-columns: repeat(2, minmax(220px, 1fr));
  }

  .purchase-remark-item {
    width: 100%;
  }

  .detail-footer {
    align-items: flex-start;
    flex-direction: column;
  }

  .detail-summary {
    justify-content: flex-start;
    margin-left: 0;
  }
}

@media (max-width: 1024px) {
  .payment-grid {
    grid-template-columns: repeat(2, minmax(220px, 1fr));
  }
}

@media (max-width: 768px) {
  .purchase-page-surface {
    padding: 16px;
  }

  .purchase-page-header,
  .purchase-title-group,
  .purchase-page-toolbar__actions {
    align-items: flex-start !important;
    flex-direction: column;
  }

  .purchase-page-toolbar__actions {
    width: 100%;
    margin-left: 0;
  }

  .purchase-page-surface .action-button {
    width: 100%;
  }

  .purchase-breadcrumb {
    flex-wrap: wrap;
    white-space: normal;
  }

  .history-header {
    align-items: flex-start;
    flex-direction: column;
    gap: 8px;
  }

  .purchase-header-grid,
  .payment-grid,
  .warehouse-location-editor {
    grid-template-columns: 1fr;
  }
}
</style>
