<template>
  <div class="page-shell page-shell--system purchase-theme" :class="{ 'purchase-theme--paper': themeMode === 'paper' }">
    <div class="page-header">
      <div class="page-title">{{ pageTitle }}</div>
      <div class="page-toolbar-card purchase-form-toolbar">
        <div class="table-toolbar purchase-form-toolbar__inner">
          <div class="purchase-form-toolbar__meta">
            <div v-if="!isReadOnly" class="theme-switch">
              <span class="theme-switch__label">{{ $t('field.theme') }}</span>
              <el-select v-model="themeMode" class="theme-switch__select">
                <el-option :label="$t('theme.default')" value="default" />
                <el-option :label="$t('theme.paper')" value="paper" />
              </el-select>
            </div>
          </div>
          <div class="table-actions purchase-form-toolbar__actions">
            <el-button @click="handleBack">{{ $t('action.back') }}</el-button>
            <el-button
              v-if="canCopy"
              type="primary"
              @click="handleCopy"
            >
              {{ $t('action.copy') }}
            </el-button>
            <el-button
              v-if="canPrint"
              type="primary"
              @click="handlePrint"
            >
              {{ $t('action.print') }}
            </el-button>
            <el-button
              v-if="canRedFlush"
              type="danger"
              plain
              class="action-button action-button--danger"
              @click="handleRedFlush"
            >
              {{ $t('action.redFlush') }}
            </el-button>
            <el-button
              v-if="canApprove"
              type="success"
              plain
              class="action-button action-button--success"
              @click="handleApprove"
            >
              {{ $t('action.approve') }}
            </el-button>
            <el-button v-if="!isReadOnly" @click="handleSave">{{ $t('action.save') }}</el-button>
            <el-button v-if="!isReadOnly" type="primary" @click="handleSaveAndBack">{{ $t('action.saveAndBack') }}</el-button>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card compact-card purchase-header-card">
      <div class="table-body purchase-header-body">
        <el-form :model="formData" label-position="top" class="purchase-form purchase-form--compact">
          <div class="form-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.orderNo')">
                <el-input v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.orderTime')">
                <el-date-picker
                  v-model="formData.orderAt"
                  type="datetime"
                  format="YYYY-MM-DD HH:mm:ss"
                  value-format="YYYY-MM-DD HH:mm:ss"
                  class="order-time-picker"
                  style="width: 100%"
                  :clearable="false"
                  :disabled="isReadOnly"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.supplier')" required>
                <FuzzyProductSelect
                  v-model="formData.supplierId"
                  :options="supplierOptions"
                  :placeholder="$t('field.supplier')"
                  style="width: 100%"
                  :disabled="isReadOnly"
                />
              </el-form-item>
            </div>
          </div>

          <el-form-item :label="$t('field.remark')">
            <el-input v-model="formData.remark" type="textarea" :disabled="isReadOnly" />
          </el-form-item>
          <el-form-item v-if="isReadOnly && formData.status === 'CANCELLED'" :label="$t('field.redFlushReason')">
            <span class="red-flush-reason">{{ extractRedFlushReason(formData.remark) || '-' }}</span>
          </el-form-item>
        </el-form>
      </div>
    </div>

    <div class="table-card purchase-detail-card">
      <div class="table-body purchase-detail-body">
        <div class="detail-section">
          <div class="detail-header">
            <h4>{{ $t('field.items') }}</h4>
          </div>
          <div class="detail-table-wrapper">
            <el-table :data="formData.items" style="width: 100%" border stripe>
              <el-table-column :label="$t('field.product')" min-width="200">
                <template #default="{ row }">
                  <el-select
                    v-model="row.productId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectProduct')"
                    :disabled="isReadOnly"
                  >
                    <el-option v-for="item in productOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.warehouse')" min-width="160">
                <template #default="{ row }">
                  <el-select
                    v-model="row.warehouseId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectWarehouse')"
                    :disabled="isReadOnly"
                    @change="() => (row.locationId = undefined)"
                  >
                    <el-option v-for="item in warehouseOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.location')" min-width="160">
                <template #default="{ row }">
                  <el-select
                    v-model="row.locationId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectLocation')"
                    :disabled="isReadOnly || !row.warehouseId"
                  >
                    <el-option
                      v-for="item in getLocationOptions(row.warehouseId)"
                      :key="item.id"
                      :label="item.name"
                      :value="item.id"
                    />
                  </el-select>
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.quantity')" width="140">
                <template #default="{ row }">
                  <DecimalInput v-model="row.qty" :scale="4" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.price')" width="140">
                <template #default="{ row }">
                  <DecimalInput v-model="row.price" :scale="4" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.taxRate')" width="140">
                <template #default="{ row }">
                  <DecimalInput v-model="row.taxRate" :scale="4" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.lineTotal')" width="140">
                <template #default="{ row }">
                  {{ formatMoney(calcLineAmount(row)) }}
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.remark')" min-width="160">
                <template #default="{ row }">
                  <el-input v-model="row.remark" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column label="" width="80" align="center">
                <template #default="{ $index }">
                  <el-button type="danger" circle size="small" :disabled="isReadOnly" @click="removeItem($index)">x</el-button>
                </template>
              </el-table-column>
            </el-table>
          </div>
          <div class="detail-actions">
            <el-button class="paper-add-item-button" type="primary" plain size="small" :disabled="isReadOnly" @click="addItem">
              + {{ $t('action.addItem') }}
            </el-button>
          </div>
          <div class="detail-summary">
            <div class="summary-item">{{ $t('field.totalAmount') }}: {{ formatMoney(totalAmount) }}</div>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card compact-card purchase-payment-card">
      <div class="table-body purchase-payment-body">
        <el-form :model="formData" label-position="left" label-width="70px" class="purchase-form purchase-form--compact purchase-form--inline">
          <div class="form-grid">
            <div class="form-group form-group--settlement">
              <el-form-item :label="$t('field.paymentMethod')">
                <el-select v-model="formData.paymentMethodCode" filterable clearable style="width: 150px" :disabled="isReadOnly">
                  <el-option v-for="item in paymentMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
            <div class="form-group form-group--amount">
              <el-form-item :label="$t('field.paidAmount')">
                <DecimalInput v-model="formData.paidAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
            <div class="form-group form-group--discount">
              <el-form-item :label="$t('field.discountAmount')">
                <DecimalInput v-model="formData.discountAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>

    <PrintPreviewDialog
      v-model="printDialogVisible"
      doc-type="PURCHASE_ORDER"
      :doc-id="printDocId"
      :title="$t('page.erpPurchaseOrderPrint')"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onActivated, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import PrintPreviewDialog from '@/components/PrintPreviewDialog.vue';
import { ElMessageBox } from 'element-plus';
import { useAuthStore } from '@/stores/auth';

interface OptionItem {
  id: number;
  name: string;
  warehouseId?: number;
}

interface MethodOption {
  code: string;
  name: string;
  isDefault?: boolean;
}

interface PurchaseOrderItem {
  id?: number;
  productId?: number;
  warehouseId?: number;
  locationId?: number;
  qty?: string | number;
  price?: string | number;
  taxRate?: string | number;
  remark?: string;
  sortNo?: number;
}

const { t } = useI18n();
const router = useRouter();
const route = useRoute();
const { notifyError, notifySuccess, notifyWarning } = useApiError();
const authStore = useAuthStore();

const isEditing = computed(() => Boolean(route.params.id));
const isReadOnly = computed(() => {
  if (route.query.mode === 'view') return true;
  if (!formData.status) return false;
  return formData.status !== 'DRAFT';
});

const canApprove = computed(() => {
  return !isReadOnly.value && formData.status === 'DRAFT' && hasPermission('erp-purchase:approve');
});

const canCopy = computed(() => {
  return isReadOnly.value
    && (formData.status === 'APPROVED' || formData.status === 'CANCELLED')
    && hasPermission('erp-purchase:add');
});

const canPrint = computed(() => {
  return isEditing.value && hasPermission('erp-purchase:view');
});

const canRedFlush = computed(() => {
  return isReadOnly.value && formData.status === 'APPROVED' && hasPermission('erp-purchase:cancel');
});

const pageTitle = computed(() => (isEditing.value ? t('page.erpPurchaseOrderEdit') : t('page.erpPurchaseOrderCreate')));
const themeMode = ref<'default' | 'paper'>('default');

const supplierOptions = ref<OptionItem[]>([]);
const productOptions = ref<OptionItem[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const paymentMethodOptions = ref<MethodOption[]>([]);

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  supplierId: null as number | null,
  paymentMethodCode: '',
  paidAmount: '',
  discountAmount: '',
  remark: '',
  items: [] as PurchaseOrderItem[]
});

const pagePath = ref(route.path);
const lastRouteKey = ref(route.fullPath);
const needsReload = ref(false);
const printDialogVisible = ref(false);
const printDocId = ref<number | null>(null);

const hasPermission = (code: string) => {
  return authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);
};

const closePage = () => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path } }));
  }
};

const handleBack = async () => {
  if (isEditing.value) {
    resetForm();
    closePage();
    return;
  }

  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    try {
      await ElMessageBox.confirm(
        t('message.confirmSaveDraft'),
        t('action.confirm'),
        {
          confirmButtonText: t('action.save'),
          cancelButtonText: t('action.cancel'),
          type: 'warning'
        }
      );
      await saveData();
    } catch {
      resetForm();
      closePage();
    }
    return;
  }

  try {
    await ElMessageBox.confirm(
      t('message.confirmClosePage'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    resetForm();
    closePage();
  } catch {
    return;
  }
};

const handleApprove = async () => {
  if (isReadOnly.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmSaveBeforeApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.save'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }

  const savedId = await saveData({ closeOnSuccess: false, reloadAfterCreate: true });
  if (!savedId) return;

  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    await request.post(`/erp/purchase-orders/${savedId}/approve`);
    formData.status = 'APPROVED';
    notifySuccess();
    closePage();
    await router.push('/erp/purchase-orders/draft');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handlePrint = () => {
  if (!isEditing.value) return;
  const id = route.params.id;
  if (!id) return;
  printDocId.value = Number(id);
  printDialogVisible.value = true;
};

const handleRedFlush = async () => {
  if (!isEditing.value) return;
  try {
    const { value } = await ElMessageBox.prompt(
      t('message.confirmRedFlush'),
      t('action.redFlush'),
      {
        inputPlaceholder: t('placeholder.required'),
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel')
      }
    );
    if (!value || !String(value).trim()) {
      return;
    }
    await request.post(`/erp/purchase-orders/${route.params.id}/cancel`, { reason: String(value).trim() });
    notifySuccess();
    closePage();
    await router.push('/erp/purchase-orders/approved');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleSave = async () => {
  await saveData({ closeOnSuccess: false });
};

const handleSaveAndBack = async () => {
  await saveData({ closeOnSuccess: true });
};

const handleCopy = async () => {
  if (!isEditing.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmCopyOrder'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.copy'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }
  try {
    const detailRes: any = await request.get(`/erp/purchase-orders/${route.params.id}`);
    const detail = detailRes.data?.data;
    if (!detail?.order) {
      notifyWarning(t('message.noItems'));
      return;
    }
    const order = detail.order;
    const items = (detail.items || []).map((item: any, index: number) => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: item.qty,
      price: item.price,
      taxRate: item.taxRate,
      remark: item.remark,
      sortNo: index + 1
    }));

    const orderNoRes: any = await request.get('/erp/purchase-orders/next-order-no');
    const orderNo = orderNoRes.data?.data || '';

    const payload = {
      orderNo,
      orderAt: formatDateTime(new Date()),
      supplierId: order.supplierId,
      paymentMethodCode: order.paymentMethodCode || '',
      paidAmount: order.paidAmount,
      discountAmount: order.discountAmount,
      remark: order.remark,
      items
    };
    const createRes: any = await request.post('/erp/purchase-orders', payload);
    if (createRes.data.code === 200) {
      const data = createRes.data.data || {};
      const newId = data.order?.id || data.id;
      notifySuccess();
      if (newId) {
        await router.push({ path: `/erp/purchase-orders/${newId}/edit`, query: { from: 'draft' } });
      }
    }
  } catch (error) {
    notifyError(error);
  }
};

const getLocationOptions = (warehouseId?: number) => {
  if (!warehouseId) return [];
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const fetchSuppliers = async () => {
  try {
    const res: any = await request.get('/erp/suppliers');
    supplierOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchProducts = async () => {
  try {
    const res: any = await request.get('/erp/products');
    productOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchWarehouses = async () => {
  try {
    const res: any = await request.get('/erp/warehouses/options');
    warehouseOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchLocations = async () => {
  try {
    const res: any = await request.get('/erp/locations/options');
    locationOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const applyDefaultPaymentMethod = () => {
  if (formData.paymentMethodCode) return;
  const defaultItem = paymentMethodOptions.value.find(item => item.isDefault);
  const candidate = defaultItem || paymentMethodOptions.value[0];
  if (candidate) {
    formData.paymentMethodCode = candidate.code;
  }
};

const fetchPaymentMethods = async () => {
  try {
    const res: any = await request.get('/erp/payment-methods');
    paymentMethodOptions.value = res.data.data || [];
    applyDefaultPaymentMethod();
  } catch (error) {
    notifyError(error);
  }
};

const fetchNextOrderNo = async () => {
  try {
    const res: any = await request.get('/erp/purchase-orders/next-order-no');
    if (res.data.code === 200) {
      formData.orderNo = res.data.data || '';
    }
  } catch (error) {
    notifyError(error);
  }
};

  const isPurchaseRoute = computed(() => route.path.startsWith('/erp/purchase-orders'));

  const loadDetail = async () => {
    if (!isPurchaseRoute.value) return;
    resetForm();
    if (!isEditing.value) {
    await fetchNextOrderNo();
    formData.orderAt = formatDateTime(new Date());
    formData.status = 'DRAFT';
    applyDefaultPaymentMethod();
    addItem();
    return;
  }
  try {
    const id = route.params.id;
    const res: any = await request.get(`/erp/purchase-orders/${id}`);
    if (res.data.code === 200) {
      const data = res.data.data || {};
      const order = data.order || data;
      formData.orderNo = order.orderNo || '';
      formData.status = order.status || '';
      formData.supplierId = order.supplierId || null;
      formData.paymentMethodCode = order.paymentMethodCode || '';
      formData.paidAmount = order.paidAmount == null ? '' : String(order.paidAmount);
      formData.discountAmount = order.discountAmount == null ? '' : String(order.discountAmount);
      formData.orderAt = formatDateTime(new Date(order.orderAt || order.createdAt || Date.now()));
      formData.remark = order.remark || '';
      formData.items = (data.items || order.items || []).map((item: any) => ({
        id: item.id,
        productId: item.productId,
        warehouseId: item.warehouseId,
        locationId: item.locationId,
        qty: item.qty == null ? '' : String(item.qty),
        price: item.price == null ? '' : String(item.price),
        taxRate: item.taxRate == null ? '' : String(item.taxRate),
        remark: item.remark
      }));
      if (!formData.items.length) addItem();
    }
  } catch (error) {
    notifyError(error);
  }
};

const addItem = () => {
  formData.items.push({
    productId: undefined,
    warehouseId: undefined,
    locationId: undefined,
    qty: '',
    price: '',
    taxRate: '',
    remark: ''
  });
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const resetForm = () => {
  formData.orderNo = '';
  formData.orderAt = '';
  formData.status = '';
  formData.supplierId = null;
  formData.paymentMethodCode = '';
  formData.paidAmount = '';
  formData.discountAmount = '';
  formData.remark = '';
  formData.items = [];
  themeMode.value = 'default';
};

const parseDecimal = (value: string | number | undefined, scale: number) => {
  if (value == null || value === '') return null;
  const raw = String(value).trim();
  const normalized = raw.endsWith('.') ? raw.slice(0, -1) : raw;
  if (!normalized) return null;
  const regex = new RegExp(`^\\d+(\\.\\d{1,${scale}})?$`);
  if (!regex.test(normalized)) {
    return null;
  }
  return Number(normalized);
};

const calcLineAmount = (row: PurchaseOrderItem) => {
  const qty = parseDecimal(row.qty, 4) || 0;
  const price = parseDecimal(row.price, 4) || 0;
  return qty * price;
};

const totalAmount = computed(() => {
  return formData.items.reduce((sum, item) => sum + calcLineAmount(item), 0);
});

const formatMoney = (value: number) => {
  return Number(value || 0).toFixed(2);
};

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const extractRedFlushReason = (remark?: string) => {
  if (!remark) return '';
  const marker = '红冲原因：';
  const index = remark.indexOf(marker);
  if (index === -1) return '';
  return remark.slice(index + marker.length).trim();
};

const saveData = async (options: { closeOnSuccess?: boolean; reloadAfterCreate?: boolean } = {}) => {
  const closeOnSuccess = options.closeOnSuccess !== false;
  if (!formData.supplierId) {
    notifyWarning(t('message.required'));
    return null;
  }
  const validItems = formData.items.filter(item => item.productId);
  if (!validItems.length) {
    notifyWarning(t('message.noItems'));
    return null;
  }
  for (const item of validItems) {
    const qtyValue = parseDecimal(item.qty, 4);
    if (qtyValue == null || qtyValue <= 0) {
      notifyWarning(t('message.mustBePositive'));
      return null;
    }
    const priceValue = parseDecimal(item.price, 4);
    if (priceValue == null) {
      notifyWarning(t('message.invalidNumber'));
      return null;
    }
  }

  const payload = {
    orderNo: formData.orderNo || undefined,
    orderAt: formData.orderAt || undefined,
    supplierId: formData.supplierId,
    paymentMethodCode: formData.paymentMethodCode || undefined,
    paidAmount: parseDecimal(formData.paidAmount, 2),
    discountAmount: parseDecimal(formData.discountAmount, 2),
    remark: formData.remark,
    items: validItems.map((item, index) => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: parseDecimal(item.qty, 4),
      price: parseDecimal(item.price, 4),
      taxRate: parseDecimal(item.taxRate, 4),
      remark: item.remark,
      sortNo: index + 1
    }))
  };

  try {
    const res: any = isEditing.value
      ? await request.put(`/erp/purchase-orders/${route.params.id}`, payload)
      : await request.post('/erp/purchase-orders', payload);

    if (res.data.code === 200) {
      const data = res.data.data || {};
      const savedId = data.order?.id || data.id || Number(route.params.id || 0) || null;
      notifySuccess();
      if (!isEditing.value && savedId && options.reloadAfterCreate) {
        await router.replace(`/erp/purchase-orders/${savedId}/edit`);
        await loadDetail();
      }
      if (closeOnSuccess) {
        closePage();
        await router.push('/erp/purchase-orders/draft');
      }
      return savedId;
    }
  } catch (error) {
    notifyError(error);
  }
  return null;
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

  watch(
    () => route.fullPath,
    (newPath) => {
      if (newPath === lastRouteKey.value) return;
      lastRouteKey.value = newPath;
      pagePath.value = route.path;
      if (!isPurchaseRoute.value) return;
      loadDetail();
    }
  );

onMounted(() => {
  pagePath.value = route.path;
  fetchSuppliers();
  fetchProducts();
  fetchWarehouses();
  fetchLocations();
  fetchPaymentMethods();
  loadDetail();
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('tags:close', handleTagClosing as EventListener);
  }
});

onActivated(() => {
  if (!needsReload.value) return;
  needsReload.value = false;
  loadDetail();
});

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('tags:close', handleTagClosing as EventListener);
  }
  resetForm();
});
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;600&family=Noto+Serif+SC:wght@600;700&display=swap');

.purchase-theme {
  background: transparent;
}

.purchase-form-toolbar {
  width: 100%;
}

.purchase-form-toolbar__inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
}

.purchase-form-toolbar__meta {
  display: flex;
  align-items: center;
  min-height: 32px;
  min-width: 0;
}

.purchase-form-toolbar__actions {
  margin-left: auto;
}

.theme-switch {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  min-height: 40px;
  padding: 6px 10px 6px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.9);
}

.theme-switch__label {
  font-size: 12px;
  color: #606266;
  font-weight: 600;
  white-space: nowrap;
  letter-spacing: 0.02em;
}

.theme-switch__select {
  width: 136px;
}

.theme-switch :deep(.el-select__wrapper) {
  min-height: 30px;
  border-radius: 8px;
  box-shadow: none;
  background: #ffffff;
}

.theme-switch :deep(.el-select__placeholder),
.theme-switch :deep(.el-select__selected-item) {
  color: #303133;
  font-weight: 500;
}

.action-button {
  min-width: 72px;
  font-weight: 600;
}

.action-button--success {
  background: #f0f9eb;
  border-color: #b7e1a1;
  color: #4e8f2b;
}

.action-button--success:hover,
.action-button--success:focus-visible {
  background: #e3f4d8;
  border-color: #95d475;
  color: #3f7d21;
}

.action-button--danger {
  background: #fef0f0;
  border-color: #f3b3b3;
  color: #c45656;
}

.action-button--danger:hover,
.action-button--danger:focus-visible {
  background: #fde2e2;
  border-color: #f08a8a;
  color: #b43c3c;
}

.purchase-theme--paper {
  --paper-ink: #2d2a26;
  --paper-muted: #7b6f65;
  --paper-accent: #c27c3f;
  --paper-accent-deep: #9b5b2b;
  --paper-card: #fffdfa;
  --paper-border: rgba(45, 42, 38, 0.12);
  --paper-shadow: 0 12px 24px rgba(45, 42, 38, 0.12);
  background: linear-gradient(135deg, #fbf7f1 0%, #f1e8dc 100%);
  border-radius: 20px;
  padding: 18px;
  font-family: 'Noto Sans SC', 'Segoe UI', sans-serif;
  color: var(--paper-ink);
  position: relative;
  overflow: hidden;
}

.purchase-theme--paper::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(rgba(45, 42, 38, 0.05) 1px, transparent 1px);
  background-size: 18px 18px;
  opacity: 0.3;
  pointer-events: none;
}

.purchase-theme--paper .page-title {
  font-family: 'Noto Serif SC', 'Noto Sans SC', serif;
  letter-spacing: 1px;
}

.purchase-theme--paper .table-card {
  border-radius: 16px;
  border: 1px solid var(--paper-border);
  background: var(--paper-card);
  box-shadow: var(--paper-shadow);
}

.purchase-theme--paper :deep(.el-input__wrapper),
.purchase-theme--paper :deep(.el-select__wrapper),
.purchase-theme--paper :deep(.el-textarea__inner) {
  border-radius: 10px;
  background: #fffaf5;
}

.purchase-theme--paper :deep(.el-button--primary) {
  background: var(--paper-accent);
  border-color: var(--paper-accent);
}

.purchase-theme--paper :deep(.el-button--primary:hover) {
  background: var(--paper-accent-deep);
  border-color: var(--paper-accent-deep);
}

.purchase-theme--paper :deep(.paper-add-item-button.el-button) {
  background: rgba(194, 124, 63, 0.12);
  border-color: rgba(194, 124, 63, 0.6);
  color: var(--paper-accent-deep);
  font-weight: 600;
}

.purchase-theme--paper :deep(.paper-add-item-button.el-button:hover) {
  background: rgba(194, 124, 63, 0.2);
  border-color: var(--paper-accent);
  color: var(--paper-accent-deep);
}

.purchase-theme--paper :deep(.paper-add-item-button.el-button:focus-visible) {
  outline: 2px solid rgba(194, 124, 63, 0.35);
  outline-offset: 1px;
}

.purchase-theme--paper :deep(.el-table th) {
  background: rgba(194, 124, 63, 0.08);
  color: var(--paper-ink);
  border-bottom: 1px solid rgba(45, 42, 38, 0.12);
}

.purchase-theme--paper :deep(.el-table td) {
  background: rgba(255, 253, 250, 0.9);
  border-color: rgba(45, 42, 38, 0.08);
}

.purchase-theme--paper :deep(.el-table__row:hover > td) {
  background: rgba(194, 124, 63, 0.06);
}

.purchase-theme--paper :deep(.el-table__body-wrapper) {
  background: rgba(255, 253, 250, 0.9);
}

.purchase-theme--paper .detail-table-wrapper {
  border: none;
  border-radius: 0;
  padding: 0;
  background: transparent;
}

.purchase-theme--paper :deep(.el-table) {
  border-radius: 14px;
  overflow: hidden;
}

.purchase-theme--paper :deep(.el-table__inner-wrapper) {
  border-radius: 14px;
  overflow: hidden;
}

.purchase-form :deep(.el-form-item) {
  margin-bottom: 4px;
}

.purchase-form--compact :deep(.el-form-item) {
  margin-bottom: 0;
}

.form-grid {
  display: flex;
  flex-wrap: nowrap;
  gap: 12px;
  overflow-x: auto;
  padding-bottom: 4px;
}

.compact-card .form-grid {
  padding-bottom: 0;
}

@media (max-width: 1200px) {
  .form-grid {
    gap: 4px;
  }
}

.form-group {
  min-width: 220px;
}

.compact-card .table-body {
  padding: 6px 12px;
}

.compact-card {
  flex: 0 0 auto;
}

.compact-card .table-body {
  flex: 0 0 auto;
  overflow: visible;
}

.purchase-header-body {
  padding: 12px 16px;
}

.purchase-detail-card {
  flex: 1 1 auto;
  min-height: 0;
}

.purchase-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
  padding: 12px 16px;
}

.purchase-payment-body {
  padding: 12px 16px;
}

.purchase-payment-card .form-grid {
  align-items: center;
  flex-wrap: nowrap;
  gap: 8px;
}

.purchase-payment-card .form-group {
  min-width: 0;
  flex: 0 0 auto;
}

.purchase-payment-card .form-group--settlement {
  min-width: 180px;
}

.purchase-payment-card .form-group--amount,
.purchase-payment-card .form-group--discount {
  width: auto;
}

.purchase-payment-card :deep(.el-form-item) {
  display: flex;
  align-items: center;
}

.purchase-payment-card :deep(.el-form-item__label) {
  padding-bottom: 0;
  display: inline-flex;
  align-items: center;
  height: 32px;
  line-height: 32px;
  margin-right: 4px;
  width: auto !important;
  padding-right: 2px;
  flex: 0 0 auto;
}

.purchase-payment-card :deep(.el-form-item__content) {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  min-height: 32px;
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 8px;
}

.detail-table-wrapper {
  flex: 1 1 auto;
  min-height: 0;
  overflow: auto;
}

.detail-actions {
  display: flex;
  justify-content: flex-start;
}

.detail-summary {
  display: flex;
  gap: 16px;
  justify-content: flex-end;
  font-size: 13px;
  color: #606266;
}

.summary-item {
  white-space: nowrap;
}

.table-card + .table-card {
  margin-top: 12px;
}

@media (max-width: 768px) {
  .purchase-form-toolbar__meta,
  .purchase-form-toolbar__actions {
    width: 100%;
  }

  .purchase-form-toolbar__actions {
    justify-content: flex-end;
    margin-left: 0;
  }
}

.order-time-picker {
  width: 100%;
}

.order-time-picker :deep(.el-input__wrapper) {
  width: 100%;
  box-sizing: border-box;
}

.order-time-picker :deep(.el-input__inner) {
  width: 100%;
  padding-right: 48px;
}

.order-time-picker :deep(.el-input__suffix) {
  width: 44px;
  display: flex;
  justify-content: flex-end;
}

.red-flush-reason {
  color: #f56c6c;
  font-weight: 600;
}
</style>
