<template>
  <div class="page-shell page-shell--system sale-theme" :class="{ 'sale-theme--paper': themeMode === 'paper' }">
    <div class="page-header">
      <div class="page-title">{{ pageTitle }}</div>
      <div class="page-toolbar-card purchase-return-header-card">
        <div class="purchase-return-toolbar">
          <div class="purchase-return-toolbar__meta">
            <div v-if="!isReadOnly" class="theme-switch">
              <span class="theme-switch__label">{{ $t('field.theme') }}</span>
              <el-select v-model="themeMode" class="theme-switch__select">
                <el-option :label="$t('theme.default')" value="default" />
                <el-option :label="$t('theme.paper')" value="paper" />
              </el-select>
            </div>
          </div>
          <div class="table-actions purchase-return-toolbar__actions">
            <el-button @click="handleBack">{{ $t('action.back') }}</el-button>
            <el-button
              v-if="canCopy"
              type="primary"
              @click="handleCopy"
            >
              {{ $t('action.copy') }}
            </el-button>
            <el-button
              v-if="canPrint"
              type="primary"
              @click="handlePrint"
            >
              {{ $t('action.print') }}
            </el-button>
            <el-button
              v-if="canApprove"
              type="success"
              plain
              class="action-button action-button--success"
              @click="handleApprove"
            >
              {{ $t('action.approve') }}
            </el-button>
            <el-button
              v-if="canRedFlush"
              type="danger"
              plain
              class="action-button action-button--danger"
              @click="handleRedFlush"
            >
              {{ $t('action.cancel') }}
            </el-button>
            <el-button v-if="!isReadOnly" @click="handleSave">{{ $t('action.save') }}</el-button>
            <el-button v-if="!isReadOnly" type="primary" @click="handleSaveAndBack">{{ $t('action.saveAndBack') }}</el-button>
          </div>
        </div>
        <div class="purchase-return-header-panel">
          <el-form :model="formData" label-position="top" class="sale-form sale-form--compact">
            <div class="form-grid">
              <div class="form-group">
                <el-form-item :label="$t('field.orderNo')">
                  <el-input v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
                </el-form-item>
              </div>
              <div class="form-group">
                <el-form-item :label="$t('field.orderTime')">
                  <el-date-picker
                    v-model="formData.orderAt"
                    type="datetime"
                    format="YYYY-MM-DD HH:mm:ss"
                    value-format="YYYY-MM-DD HH:mm:ss"
                    class="order-time-picker"
                    style="width: 100%"
                    :clearable="false"
                    :disabled="isReadOnly"
                  />
                </el-form-item>
              </div>
              <div class="form-group">
                <el-form-item :label="$t('field.supplier')" required>
                  <FuzzyProductSelect
                    v-model="formData.supplierId"
                    :options="supplierOptions"
                    :placeholder="$t('field.supplier')"
                    style="width: 100%"
                    :disabled="isReadOnly"
                    @change="handleSupplierChange"
                  />
                </el-form-item>
              </div>
              <div class="form-group">
                <el-form-item :label="$t('field.returnSource')" required>
                  <el-select
                    v-model="formData.returnSource"
                    style="width: 100%"
                    :disabled="isReadOnly || !formData.supplierId"
                    @change="handleReturnSourceChange"
                  >
                    <el-option :label="$t('returnSource.byProduct')" value="BY_PRODUCT" />
                    <el-option :label="$t('returnSource.byPurchaseOrder')" value="BY_PURCHASE_ORDER" />
                  </el-select>
                </el-form-item>
              </div>
              <div v-if="formData.returnSource === 'BY_PURCHASE_ORDER'" class="form-group">
                <el-form-item :label="$t('field.purchaseOrderNo')">
                  <el-select v-model="formData.purchaseOrderId" filterable clearable style="width: 100%" :disabled="isReadOnly" @change="handlePurchaseOrderChange">
                    <el-option v-for="item in purchaseOrderOptions" :key="item.id" :label="item.orderNo" :value="item.id" />
                  </el-select>
                </el-form-item>
              </div>
              <div class="form-group">
                <el-form-item :label="$t('field.returnType')" required>
                  <el-select v-model="formData.returnType" style="width: 100%" :disabled="isReadOnly">
                    <el-option :label="$t('purchaseReturnType.return')" value="RETURN" />
                    <el-option :label="$t('purchaseReturnType.scrap')" value="SCRAP" />
                  </el-select>
                </el-form-item>
              </div>
            </div>

            <el-form-item :label="$t('field.remark')">
              <el-input v-model="formData.remark" type="textarea" :disabled="isReadOnly" />
            </el-form-item>
            <div v-if="isReadOnly && formData.status === 'RED_FLUSHED' && formData.remark" class="red-flush-reason">
              {{ formData.remark }}
            </div>
          </el-form>
        </div>
      </div>
    </div>

    <div class="table-card sale-detail-card">
      <div class="table-body sale-detail-body">
        <div class="detail-section">
          <div class="detail-header">
            <h4>{{ $t('field.items') }}</h4>
          </div>
          <div class="detail-table-wrapper">
            <el-table :data="formData.items" style="width: 100%" border stripe>
              <el-table-column :label="$t('field.product')" min-width="200">
                <template #default="{ row }">
                  <el-select
                    v-model="row.productId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectProduct')"
                    :disabled="isReadOnly || !formData.supplierId"
                    @change="handleProductChange(row)"
                    @visible-change="(visible: boolean) => handleProductVisibleChange(row, visible)"
                  >
                    <el-option v-for="item in productOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                  <div
                    v-if="formData.returnSource === 'BY_PRODUCT' && row.productId"
                    class="recent-sale-hint"
                  >
                    <div class="recent-sale-hint__title">{{ $t('message.recentPurchaseHint') }}</div>
                    <div v-if="getRecentPurchaseItems(row.productId).length" class="recent-sale-hint__list">
                      <div
                        v-for="item in getRecentPurchaseItems(row.productId)"
                        :key="`${item.orderId}-${item.productId}`"
                        class="recent-sale-hint__item"
                      >
                        <span class="recent-sale-hint__no">{{ item.orderNo }}</span>
                        <span class="recent-sale-hint__meta">
                          {{ $t('field.quantity') }}: {{ item.qty }}
                        </span>
                        <span class="recent-sale-hint__meta">
                          {{ $t('field.price') }}: {{ item.price }}
                        </span>
                      </div>
                    </div>
                    <div v-else class="recent-sale-hint__empty">
                      {{ $t('message.noRecentPurchase') }}
                    </div>
                  </div>
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.warehouse')" min-width="160">
                <template #default="{ row }">
                  <el-select
                    v-model="row.warehouseId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectWarehouse')"
                    :disabled="isReadOnly || !row.productId"
                    @change="handleWarehouseChange(row)"
                  >
                    <el-option v-for="item in warehouseOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.location')" min-width="160">
                <template #default="{ row }">
                  <el-select
                    v-model="row.stockKey"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectLocation')"
                    :disabled="isReadOnly || !row.productId"
                    @change="handleStockLocationChange(row)"
                    @visible-change="(visible: boolean) => handleStockVisibleChange(row, visible)"
                  >
                    <el-option
                      v-for="item in getStockOptionsForRow(row)"
                      :key="item.key"
                      :label="item.searchLabel"
                      :value="item.key"
                    >
                      <div class="stock-option">
                        <span class="stock-option__name">{{ item.label }}</span>
                        <span class="stock-option__qty">
                          {{ $t('field.qtyOnHand') }}: {{ item.qtyOnHand }}
                          · {{ $t('field.qtyAvailable') }}: {{ item.qtyAvailable }}
                          · {{ $t('field.qtyLocked') }}: {{ item.qtyLocked }}
                        </span>
                      </div>
                    </el-option>
                  </el-select>
                </template>
              </el-table-column>
            <el-table-column :label="$t('field.quantity')" width="140">
              <template #default="{ row }">
                <DecimalInput v-model="row.qty" :scale="4" :disabled="isReadOnly" />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.price')" width="140">
              <template #default="{ row }">
                <DecimalInput v-model="row.price" :scale="4" :disabled="isReadOnly" />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.lineTotal')" width="140">
              <template #default="{ row }">
                {{ formatMoney(calcLineAmount(row)) }}
              </template>
            </el-table-column>
            <el-table-column v-if="canShowDiscountAllocated" :label="$t('field.discountAllocated')" width="140">
              <template #default="{ row }">
                {{ formatMoney(calcLineDiscount(row)) }}
              </template>
            </el-table-column>
            <el-table-column v-if="canShowProfit" :label="$t('field.profit')" min-width="160">
              <template #default="{ row }">
                {{ formatProfitCell(row) }}
              </template>
            </el-table-column>

              <el-table-column :label="$t('field.remark')" min-width="160">
                <template #default="{ row }">
                  <el-input v-model="row.remark" :disabled="isReadOnly" />
                </template>
              </el-table-column>
              <el-table-column label="" width="80" align="center">
                <template #default="{ $index }">
                  <el-button type="danger" circle size="small" :disabled="isReadOnly" @click="removeItem($index)">x</el-button>
                </template>
            </el-table-column>
          </el-table>
          </div>
          <div class="detail-actions">
            <el-button class="paper-add-item-button" type="primary" plain size="small" :disabled="isReadOnly" @click="addItem">
              + {{ $t('action.addItem') }}
            </el-button>
          </div>
          <div class="detail-summary">
            <div class="summary-item">{{ $t('field.totalAmount') }}: {{ formatMoney(totalSummary.amount) }}</div>
            <div class="summary-item" v-if="canShowProfit">{{ $t('field.totalProfit') }}: {{ totalProfitText }}</div>
            <div class="summary-item" v-if="canShowProfit">{{ $t('field.totalProfitRate') }}: {{ totalProfitRateText }}</div>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card compact-card compact-card--inline payment-card">
      <div class="table-body compact-card-body payment-card-body">
        <el-form :model="formData" label-position="left" label-width="70px" class="sale-form sale-form--compact sale-form--inline">
          <div class="form-grid">
            <div class="form-group form-group--settlement">
              <el-form-item :label="$t('field.settlementMethod')" required>
                <el-select v-model="formData.settlementMethod" style="width: 150px" :disabled="isReadOnly">
                  <el-option v-for="item in settlementMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
            <div v-if="formData.settlementMethod" class="form-group form-group--amount">
              <el-form-item :label="$t('field.paidAmount')">
                <DecimalInput v-model="formData.paidAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
            <div v-if="formData.settlementMethod" class="form-group form-group--discount">
              <el-form-item :label="$t('field.discountAmount')">
                <DecimalInput v-model="formData.discountAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>

    <el-dialog
      v-model="showPurchaseOrderDialog"
      :title="$t('message.selectPurchaseReturnItems')"
      width="780px"
      :close-on-click-modal="false"
      :close-on-press-escape="false"
    >
      <el-table
        :data="purchaseOrderDetailItems"
        style="width: 100%"
        border
        @selection-change="handlePurchaseOrderSelectionChange"
      >
        <el-table-column type="selection" width="50" />
        <el-table-column :label="$t('field.product')" min-width="180">
          <template #default="{ row }">
            {{ row.productName || row.productCode }}
          </template>
        </el-table-column>
        <el-table-column :label="$t('field.quantity')" width="120">
          <template #default="{ row }">{{ row.qty }}</template>
        </el-table-column>
        <el-table-column :label="$t('field.price')" width="120">
          <template #default="{ row }">{{ row.price }}</template>
        </el-table-column>
        <el-table-column :label="$t('field.warehouse')" min-width="140">
          <template #default="{ row }">
            {{ resolveWarehouseLabel(row.warehouseId) }}
          </template>
        </el-table-column>
        <el-table-column :label="$t('field.location')" min-width="140">
          <template #default="{ row }">
            {{ resolveLocationLabel(row.locationId) }}
          </template>
        </el-table-column>
      </el-table>
      <template #footer>
        <el-button @click="showPurchaseOrderDialog = false">{{ $t('action.cancel') }}</el-button>
        <el-button type="primary" @click="applyPurchaseOrderSelection">{{ $t('action.confirm') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog
      v-model="showSupplierChangeDialog"
      :title="$t('message.confirmSupplierChangeTitle')"
      width="420px"
      :close-on-click-modal="false"
      :close-on-press-escape="false"
    >
      <div>{{ $t('message.confirmSupplierChange') }}</div>
      <template #footer>
        <el-button @click="applySupplierChange('cancel')">{{ $t('action.cancel') }}</el-button>
        <el-button @click="applySupplierChange('clear')">{{ $t('action.clearItems') }}</el-button>
        <el-button type="primary" @click="applySupplierChange('price')">{{ $t('action.updatePrice') }}</el-button>
      </template>
    </el-dialog>

    <PrintPreviewDialog
      v-model="printDialogVisible"
      doc-type="PURCHASE_RETURN"
      :doc-id="printDocId"
      :title="$t('page.erpPurchaseReturnPrint')"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, onActivated, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import PrintPreviewDialog from '@/components/PrintPreviewDialog.vue';
import { ElMessageBox } from 'element-plus';
import { useAuthStore } from '@/stores/auth';
import { mergeOptionById } from '@/utils/erpMasterData';

interface OptionItem {
  id: number;
  name: string;
  warehouseId?: number;
  categoryId?: number;
  paymentTerms?: string;
}

interface PurchaseOrderOption {
  id: number;
  orderNo: string;
  supplierId?: number;
}

interface PurchaseOrderDetailItem {
  id?: number;
  productId?: number;
  productCode?: string;
  productName?: string;
  warehouseId?: number;
  locationId?: number;
  qty?: number;
  price?: number;
  taxRate?: number;
}

interface ProductOption {
  id: number;
  name: string;
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  salePrice?: number;
  costPrice?: number;
}

interface RecentPurchaseItem {
  orderId: number;
  orderNo: string;
  orderAt?: string;
  productId: number;
  qty: number;
  price: number;
}

interface StockOption {
  key: string;
  warehouseId: number | null;
  warehouseName: string;
  locationId: number | null;
  locationName: string;
  qtyOnHand: number;
  qtyAvailable: number;
  qtyLocked: number;
  label: string;
  searchLabel: string;
}

interface CodeOptionItem {
  id: number;
  code: string;
  name: string;
  isDefault?: boolean;
}

interface PurchaseReturnItem {
  id?: number;
  productId?: number;
  warehouseId?: number;
  locationId?: number;
  stockKey?: string;
  qty?: string | number;
  price?: string | number;
  taxRate?: number;
  remark?: string;
  sortNo?: number;
}

const { t } = useI18n();
const router = useRouter();
const route = useRoute();
const { notifyError, notifySuccess, notifyWarning } = useApiError();
const authStore = useAuthStore();

const isEditing = computed(() => Boolean(route.params.id));
const isReadOnly = computed(() => {
  if (route.query.mode === 'view') return true;
  if (!formData.status) return false;
  return formData.status !== 'DRAFT';
});

const canCopy = computed(() => {
  return isReadOnly.value && ['APPROVED', 'RED_FLUSHED'].includes(formData.status) && hasPermission('erp-purchase-return:add');
});

const canPrint = computed(() => {
  return isEditing.value && hasPermission('erp-purchase-return:view');
});

const pageTitle = computed(() => (isEditing.value ? t('page.erpPurchaseReturnEdit') : t('page.erpPurchaseReturnCreate')));
const themeMode = ref<'default' | 'paper'>('default');

const supplierOptions = ref<OptionItem[]>([]);
const purchaseOrderOptions = ref<PurchaseOrderOption[]>([]);
const productOptions = ref<ProductOption[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const settlementMethodOptions = ref<CodeOptionItem[]>([]);
const productStockMap = ref<Record<number, StockOption[]>>({});
const productRecentPurchaseMap = ref<Record<number, RecentPurchaseItem[]>>({});
const purchaseOrderDetailItems = ref<PurchaseOrderDetailItem[]>([]);
const selectedPurchaseOrderItems = ref<PurchaseOrderDetailItem[]>([]);
const showPurchaseOrderDialog = ref(false);

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  returnType: 'RETURN',
  returnSource: 'BY_PRODUCT',
  supplierId: null as number | null,
  purchaseOrderId: null as number | null,
  settlementMethod: '',
  paidAmount: '',
  discountAmount: '',
  remark: '',
  items: [] as PurchaseReturnItem[]
});

const pagePath = ref(route.path);
const lastRouteKey = ref(route.fullPath);
const showSupplierChangeDialog = ref(false);
const pendingSupplierId = ref<number | null>(null);
const lastSupplierId = ref<number | null>(null);
const isInitializing = ref(false);
const needsReload = ref(false);
const printDialogVisible = ref(false);
const printDocId = ref<number | null>(null);
const isPurchaseReturnRoute = computed(() => route.path.startsWith('/erp/purchase-returns'));

const hasPermission = (code: string) => {
  return authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);
};

const canApprove = computed(() => {
  return !isReadOnly.value && formData.status === 'DRAFT' && hasPermission('erp-purchase-return:approve');
});

const canRedFlush = computed(() => {
  return isReadOnly.value && formData.status === 'APPROVED' && hasPermission('erp-purchase-return:cancel');
});

const canShowProfit = computed(() => false);
const canShowDiscountAllocated = computed(() => false);

const isTypingTarget = (target: EventTarget | null) => {
  if (!target || !(target instanceof HTMLElement)) return false;
  const tag = target.tagName.toLowerCase();
  if (tag === 'input' || tag === 'textarea' || tag === 'select') return true;
  return target.isContentEditable;
};

const handleKeydown = (event: KeyboardEvent) => {
  if (isTypingTarget(event.target)) return;
};

const closePage = () => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path } }));
  }
};

const handleBack = async () => {
  if (isEditing.value) {
    resetForm();
    closePage();
    return;
  }

  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    try {
      await ElMessageBox.confirm(
        t('message.confirmSaveDraft'),
        t('action.confirm'),
        {
          confirmButtonText: t('action.save'),
          cancelButtonText: t('action.cancel'),
          type: 'warning'
        }
      );
      await saveData();
    } catch {
      resetForm();
      closePage();
    }
    return;
  }

  try {
    await ElMessageBox.confirm(
      t('message.confirmClosePage'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    resetForm();
    closePage();
  } catch {
    return;
  }
};

const handleApprove = async () => {
  if (isReadOnly.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmSaveBeforeApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.save'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }

  const savedId = await saveData({ closeOnSuccess: false, reloadAfterCreate: true });
  if (!savedId) return;

  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    await request.post(`/erp/purchase-returns/${savedId}/approve`);
    formData.status = 'APPROVED';
    notifySuccess();
    closePage();
    await router.push('/erp/purchase-returns/draft');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleSave = async () => {
  await saveData({ closeOnSuccess: false });
};

  const handleSaveAndBack = async () => {
    await saveData({ closeOnSuccess: true });
  };

  const parseStockKey = (stockKey?: string) => {
    if (!stockKey) return { warehouseId: undefined, locationId: undefined };
    const [warehouseRaw, locationRaw] = stockKey.split(':');
    const warehouseId = Number(warehouseRaw);
    const locationId = Number(locationRaw);
    return {
      warehouseId: Number.isNaN(warehouseId) || warehouseId === 0 ? undefined : warehouseId,
      locationId: Number.isNaN(locationId) || locationId === 0 ? undefined : locationId
    };
  };

  const ensureStockBinding = (row: PurchaseReturnItem) => {
    if (!row.stockKey || !row.productId) return;
    const options = productStockMap.value[row.productId] || [];
    const selected = options.find(item => item.key === row.stockKey);
    if (selected) {
      row.warehouseId = selected.warehouseId ?? undefined;
      row.locationId = selected.locationId ?? undefined;
      return;
    }
    const parsed = parseStockKey(row.stockKey);
    if (row.warehouseId == null) {
      row.warehouseId = parsed.warehouseId;
    }
    if (row.locationId == null) {
      row.locationId = parsed.locationId;
    }
  };

  const handleCopy = async () => {
    if (!formData.supplierId || !formData.items.length) {
      notifyWarning(t('message.noItems'));
      return;
    }
  try {
    await ElMessageBox.confirm(
      t('message.confirmCopyOrder'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.copy'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }
    try {
      const orderNoRes: any = await request.get('/erp/purchase-returns/next-no');
      const orderNo = orderNoRes.data?.data || '';
      const items = formData.items
        .filter(item => item.productId)
        .map((item, index) => {
          ensureStockBinding(item);
          return {
            productId: item.productId,
            warehouseId: item.warehouseId,
            locationId: item.locationId,
            qty: parseDecimal(item.qty, 4),
            price: parseDecimal(item.price, 4),
            taxRate: item.taxRate,
            remark: item.remark,
            sortNo: index + 1
          };
        });
    const payload = {
      orderNo,
      orderAt: formatDateTime(new Date()),
      returnType: formData.returnType || 'RETURN',
      supplierId: formData.supplierId,
      purchaseOrderId: formData.purchaseOrderId || undefined,
      settlementMethod: formData.settlementMethod,
      paidAmount: parseAmount(formData.paidAmount),
      discountAmount: parseAmount(formData.discountAmount),
      remark: formData.remark,
      items
    };
    const res: any = await request.post('/erp/purchase-returns', payload);
    if (res.data.code === 200) {
      const data = res.data.data || {};
      const newId = data.order?.id || data.id;
      notifySuccess();
      if (newId) {
        await router.push({ path: `/erp/purchase-returns/${newId}/edit`, query: { from: 'draft' } });
        await loadDetail();
      }
    }
  } catch (error) {
    notifyError(error);
  }
};

const getLocationOptions = (warehouseId?: number) => {
  if (!warehouseId) return locationOptions.value;
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const buildStockKey = (warehouseId: number | null | undefined, locationId: number | null | undefined) => {
  const w = warehouseId == null ? 0 : warehouseId;
  const l = locationId == null ? 0 : locationId;
  return `${w}:${l}`;
};

const buildStockOptionLabel = (option: StockOption) => {
  return `${option.warehouseName} / ${option.locationName}`;
};

const buildFallbackStockOption = (row: PurchaseReturnItem): StockOption | null => {
  if (!row.warehouseId && !row.locationId) return null;
  const warehouseName = warehouseOptions.value.find(item => item.id === row.warehouseId)?.name || '-';
  const locationName = row.locationId
    ? (locationOptions.value.find(item => item.id === row.locationId)?.name || '-')
    : t('field.unassignedLocation');
  const baseLabel = `${warehouseName} / ${locationName}`;
  return {
    key: buildStockKey(row.warehouseId ?? null, row.locationId ?? null),
    warehouseId: row.warehouseId ?? null,
    locationId: row.locationId ?? null,
    warehouseName,
    locationName,
    qtyOnHand: 0,
    qtyAvailable: 0,
    qtyLocked: 0,
    label: baseLabel,
    searchLabel: `${baseLabel} 0 0 0`
  };
};

const normalizeStockOption = (option: any): StockOption => {
  const warehouseId = option.warehouseId ?? null;
  const locationId = option.locationId ?? null;
  const warehouseName = option.warehouseName || '-';
  const locationName = option.locationName || t('field.unassignedLocation');
  const qtyOnHand = Number(option.qtyOnHand ?? 0);
  const qtyAvailable = Number(option.qtyAvailable ?? qtyOnHand);
  const qtyLocked = Number(option.qtyLocked ?? 0);
  const baseLabel = `${warehouseName} / ${locationName}`;
  return {
    key: buildStockKey(warehouseId, locationId),
    warehouseId,
    locationId,
    warehouseName,
    locationName,
    qtyOnHand,
    qtyAvailable,
    qtyLocked,
    label: baseLabel,
    searchLabel: `${baseLabel} ${qtyOnHand} ${qtyAvailable} ${qtyLocked}`
  };
};

const fetchStockOptions = async (productId?: number, force = false) => {
  if (!productId) return;
  if (!force && productStockMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/stock/balances/by-product', { params: { productId } });
    const data = res.data.data || [];
    productStockMap.value[productId] = data.map(normalizeStockOption);
  } catch (error) {
    notifyError(error);
  }
};

const getStockOptionsForRow = (row: PurchaseReturnItem) => {
  if (!row.productId) return [];
  const options = productStockMap.value[row.productId] || [];
  const result = [...options];
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
  if ((row.warehouseId || row.locationId) && !options.find(item => item.key === key)) {
    const fallback = buildFallbackStockOption(row);
    if (fallback) {
      result.unshift(fallback);
    }
  }
  return result;
};

  const syncStockKey = (row: PurchaseReturnItem) => {
    if (!row.productId) {
      row.stockKey = '';
      return;
    }
  const options = productStockMap.value[row.productId] || [];
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
    const matched = options.find(item => item.key === key);
    if (matched) {
      row.stockKey = key;
      return;
    }
    if (row.warehouseId || row.locationId) {
      row.stockKey = key;
      return;
    }
    row.stockKey = '';
  };

const applyProductDefaults = (row: PurchaseReturnItem, force = true) => {
  if (!row.productId) return;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product) return;
  if (product.defaultWarehouseId && (force || !row.warehouseId)) {
    row.warehouseId = product.defaultWarehouseId;
  }
  if (product.defaultLocationId && (force || !row.locationId)) {
    row.locationId = product.defaultLocationId;
  }
  if (row.locationId && row.warehouseId) {
    const location = locationOptions.value.find(item => item.id === row.locationId);
    if (location && location.warehouseId && location.warehouseId !== row.warehouseId) {
      row.locationId = undefined;
    }
  }
};

const applyPriceForRow = async (row: PurchaseReturnItem, force = false) => {
  if (!row.productId) return;
  if (!force && row.price) return;
  const recentItems = getRecentPurchaseItems(row.productId);
  const recentPrice = recentItems.find(item => item.price != null)?.price;
  if (recentPrice != null) {
    row.price = String(recentPrice);
    return;
  }
  const product = productOptions.value.find(item => item.id === row.productId);
  if (product && product.costPrice != null) {
    row.price = String(product.costPrice);
  }
};

const handleRedFlush = async () => {
  if (!isEditing.value) return;
  try {
    const { value } = await ElMessageBox.prompt(
      t('message.enterRedFlushReason'),
      t('action.cancel'),
      {
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel'),
        inputPattern: /\S+/,
        inputErrorMessage: t('message.enterRedFlushReason'),
        type: 'warning'
      }
    );
    await request.post(`/erp/purchase-returns/${route.params.id}/cancel`, { reason: value });
    notifySuccess();
    closePage();
    await router.push('/erp/purchase-returns/approved');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handlePrint = () => {
  if (!isEditing.value) return;
  const id = route.params.id;
  if (!id) return;
  printDocId.value = Number(id);
  printDialogVisible.value = true;
};

const getProductCost = (row: PurchaseReturnItem) => {
  if (!row.productId) return null;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product || product.costPrice == null) return null;
  return Number(product.costPrice);
};

const calcLineAmount = (row: PurchaseReturnItem) => {
  const qty = parseDecimal(row.qty, 4);
  const price = parseDecimal(row.price, 4);
  if (qty == null || price == null) return null;
  return qty * price;
};

const totalAmountBeforeDiscount = computed(() => {
  let amount = 0;
  formData.items.forEach((row) => {
    const lineAmount = calcLineAmount(row);
    if (lineAmount == null) return;
    amount += lineAmount;
  });
  return amount;
});

const getDiscountAmount = () => {
  const discount = parseAmount(formData.discountAmount || '');
  if (discount == null) return 0;
  return Math.max(0, discount);
};

const calcLineDiscount = (row: PurchaseReturnItem) => {
  const totalAmount = totalAmountBeforeDiscount.value;
  const discountAmount = getDiscountAmount();
  if (!totalAmount || !discountAmount) return 0;
  const lineAmount = calcLineAmount(row);
  if (lineAmount == null) return 0;
  return (lineAmount / totalAmount) * discountAmount;
};

const calcLineNetAmount = (row: PurchaseReturnItem) => {
  const amount = calcLineAmount(row);
  if (amount == null) return null;
  return amount - calcLineDiscount(row);
};

const calcLineProfit = (row: PurchaseReturnItem) => {
  const amount = calcLineNetAmount(row);
  if (amount == null) return null;
  const cost = getProductCost(row);
  if (cost == null) return null;
  return amount - (cost * (parseDecimal(row.qty, 4) || 0));
};

const formatMoney = (value: number | null) => {
  if (value == null || Number.isNaN(value)) return '-';
  return value.toFixed(2);
};

const formatRate = (value: number | null) => {
  if (value == null || Number.isNaN(value)) return '-';
  return `${(value * 100).toFixed(2)}%`;
};

const formatProfitCell = (row: PurchaseReturnItem) => {
  const profit = calcLineProfit(row);
  const amount = calcLineNetAmount(row);
  if (profit == null || amount == null || amount === 0) return '-';
  return `${formatMoney(profit)} (${formatRate(profit / amount)})`;
};

const totalSummary = computed(() => {
  let amount = 0;
  let netAmount = 0;
  let profit = 0;
  let hasMissingCost = false;
  formData.items.forEach((row) => {
    const lineAmount = calcLineAmount(row);
    if (lineAmount == null) return;
    amount += lineAmount;
    const lineNetAmount = calcLineNetAmount(row);
    if (lineNetAmount != null) {
      netAmount += lineNetAmount;
    }
    const lineProfit = calcLineProfit(row);
    if (lineProfit == null) {
      if (row.productId) {
        hasMissingCost = true;
      }
      return;
    }
    profit += lineProfit;
  });
  const rate = netAmount ? profit / netAmount : null;
  return { amount, netAmount, profit, rate, hasMissingCost };
});

const totalProfitText = computed(() => {
  if (totalSummary.value.hasMissingCost) return '-';
  return formatMoney(totalSummary.value.profit);
});

const totalProfitRateText = computed(() => {
  if (totalSummary.value.hasMissingCost) return '-';
  return formatRate(totalSummary.value.rate);
});

const getDefaultSettlementMethod = () => {
  if (!settlementMethodOptions.value.length) return '';
  const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
  return defaultItem?.code || '';
};

const applyMethodsForSupplier = () => {
  const supplier = supplierOptions.value.find(item => item.id === formData.supplierId);
  const settlement = supplier?.paymentTerms || getDefaultSettlementMethod();
  if (settlement) {
    formData.settlementMethod = settlement;
  }
};

const resolveWarehouseLabel = (id?: number) => {
  if (!id) return '-';
  return warehouseOptions.value.find(item => item.id === id)?.name || '-';
};

const resolveLocationLabel = (id?: number) => {
  if (!id) return '-';
  return locationOptions.value.find(item => item.id === id)?.name || '-';
};

const handleProductChange = async (row: PurchaseReturnItem) => {
  row.warehouseId = undefined;
  row.locationId = undefined;
  row.stockKey = '';
  row.price = '';
  applyProductDefaults(row, true);
  await fetchStockOptions(row.productId, true);
  await fetchRecentPurchaseItems(row.productId);
  syncStockKey(row);
  await applyPriceForRow(row, true);
};

const handleProductVisibleChange = async (row: PurchaseReturnItem, visible: boolean) => {
  if (!visible || !row.productId) return;
  await fetchRecentPurchaseItems(row.productId);
};

const fetchRecentPurchaseItems = async (productId?: number) => {
  if (!productId || !formData.supplierId) return;
  if (productRecentPurchaseMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/purchase-orders/recent-items', {
      params: {
        supplierId: formData.supplierId,
        productId,
        limit: 10
      }
    });
    productRecentPurchaseMap.value[productId] = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const getRecentPurchaseItems = (productId?: number) => {
  if (!productId) return [];
  return productRecentPurchaseMap.value[productId] || [];
};

const handleWarehouseChange = (row: PurchaseReturnItem) => {
  if (row.stockKey) {
    const keyWarehouse = row.stockKey.split(':')[0];
    if (String(row.warehouseId ?? 0) !== keyWarehouse) {
      row.locationId = undefined;
      row.stockKey = '';
    }
  }
  if (!row.locationId) return;
  const location = locationOptions.value.find(item => item.id === row.locationId);
  if (location && row.warehouseId && location.warehouseId !== row.warehouseId) {
    row.locationId = undefined;
  }
};

const handleStockLocationChange = (row: PurchaseReturnItem) => {
  if (!row.productId || !row.stockKey) {
    row.locationId = undefined;
    return;
  }
  const options = productStockMap.value[row.productId] || [];
  const selected = options.find(item => item.key === row.stockKey);
  if (!selected) {
    row.locationId = undefined;
    return;
  }
  row.warehouseId = selected.warehouseId ?? undefined;
  row.locationId = selected.locationId ?? undefined;
};

const handleStockVisibleChange = async (row: PurchaseReturnItem, visible: boolean) => {
  if (!visible || !row.productId) return;
  await fetchStockOptions(row.productId, true);
  syncStockKey(row);
};

const handleSupplierChange = (value: number | null) => {
  if (isInitializing.value) {
    lastSupplierId.value = value;
    return;
  }
  if (value === lastSupplierId.value) return;
  productRecentPurchaseMap.value = {};
  formData.purchaseOrderId = null;
  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    pendingSupplierId.value = value;
    showSupplierChangeDialog.value = true;
    return;
  }
  lastSupplierId.value = value;
  applyMethodsForSupplier();
  fetchPurchaseOrders();
};

const handleReturnSourceChange = () => {
  if (formData.returnSource === 'BY_PURCHASE_ORDER') {
    formData.items = [];
    addItem();
    if (formData.supplierId) {
      fetchPurchaseOrders();
    }
    return;
  }
  formData.purchaseOrderId = null;
  purchaseOrderDetailItems.value = [];
  selectedPurchaseOrderItems.value = [];
};

const handlePurchaseOrderChange = (value: number | null) => {
  if (isReadOnly.value) return;
  if (!value) return;
  if (formData.returnSource !== 'BY_PURCHASE_ORDER') return;
  const selected = purchaseOrderOptions.value.find(item => item.id === value);
  if (!selected) return;
  if (selected.supplierId && selected.supplierId !== formData.supplierId) {
    formData.supplierId = selected.supplierId;
    lastSupplierId.value = selected.supplierId;
    productRecentPurchaseMap.value = {};
    applyMethodsForSupplier();
  } else {
    applyMethodsForSupplier();
  }
  openPurchaseOrderDetail(value);
};

const openPurchaseOrderDetail = async (orderId: number) => {
  if (!orderId) return;
  try {
    const res: any = await request.get(`/erp/purchase-orders/${orderId}`);
    const data = res.data.data || {};
    purchaseOrderDetailItems.value = (data.items || []).map((item: any) => ({
      id: item.id,
      productId: item.productId,
      productCode: item.productCode,
      productName: item.productName,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: Number(item.qty || 0),
      price: Number(item.price || 0),
      taxRate: Number(item.taxRate || 0)
    }));
    selectedPurchaseOrderItems.value = [...purchaseOrderDetailItems.value];
    showPurchaseOrderDialog.value = true;
  } catch (error) {
    notifyError(error);
  }
};

const handlePurchaseOrderSelectionChange = (rows: PurchaseOrderDetailItem[]) => {
  selectedPurchaseOrderItems.value = rows;
};

const applyPurchaseOrderSelection = () => {
  if (!selectedPurchaseOrderItems.value.length) {
    notifyWarning(t('message.noItems'));
    return;
  }
  formData.items = selectedPurchaseOrderItems.value.map((item, index) => ({
    productId: item.productId,
    warehouseId: item.warehouseId,
    locationId: item.locationId,
    stockKey: '',
    qty: item.qty == null ? '' : String(item.qty),
    price: item.price == null ? '' : String(item.price),
    taxRate: item.taxRate || 0,
    remark: '',
    sortNo: index + 1
  }));
  formData.items.forEach(async (row) => {
    await fetchStockOptions(row.productId);
    syncStockKey(row);
  });
  showPurchaseOrderDialog.value = false;
};

const applySupplierChange = async (action: 'price' | 'clear' | 'cancel') => {
  const targetSupplierId = pendingSupplierId.value;
  showSupplierChangeDialog.value = false;
  if (action === 'cancel') {
    formData.supplierId = lastSupplierId.value;
    pendingSupplierId.value = null;
    return;
  }
  lastSupplierId.value = targetSupplierId;
  pendingSupplierId.value = null;
  if (action === 'clear') {
    formData.items = [];
    addItem();
    applyMethodsForSupplier();
    fetchPurchaseOrders();
    return;
  }
  for (const item of formData.items) {
    applyPriceForRow(item, true);
  }
  applyMethodsForSupplier();
  fetchPurchaseOrders();
};

const fetchSuppliers = async () => {
  try {
    const res: any = await request.get('/erp/suppliers');
    supplierOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchPurchaseOrders = async () => {
  try {
    const params: Record<string, any> = { status: 'APPROVED', page: 1, size: 200 };
    if (formData.supplierId) {
      params.supplierId = formData.supplierId;
    }
    const res: any = await request.get('/erp/purchase-orders/page', { params });
    const items = res.data.data?.items || [];
    purchaseOrderOptions.value = items.map((item: any) => ({
      id: item.id,
      orderNo: item.orderNo,
      supplierId: item.supplierId
    }));
  } catch (error) {
    notifyError(error);
  }
};

const fetchProducts = async () => {
  try {
    const res: any = await request.get('/erp/products');
    productOptions.value = res.data.data || [];
    for (const item of formData.items) {
      await fetchStockOptions(item.productId);
      applyProductDefaults(item, false);
      syncStockKey(item);
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchWarehouses = async () => {
  try {
    const res: any = await request.get('/erp/warehouses/options');
    warehouseOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchLocations = async () => {
  try {
    const res: any = await request.get('/erp/locations/options');
    locationOptions.value = res.data.data || [];
    formData.items.forEach(item => applyProductDefaults(item, false));
  } catch (error) {
    notifyError(error);
  }
};

const ensureWarehouseOption = async (warehouseId?: number | null) => {
  if (!warehouseId || warehouseOptions.value.some(item => item.id === warehouseId)) return;
  try {
    const res: any = await request.get(`/erp/warehouses/${warehouseId}`);
    const warehouse = res.data.data;
    if (warehouse) {
      warehouseOptions.value = mergeOptionById(warehouseOptions.value, {
        id: warehouse.id,
        name: warehouse.name
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureLocationOption = async (locationId?: number | null) => {
  if (!locationId || locationOptions.value.some(item => item.id === locationId)) return;
  try {
    const res: any = await request.get(`/erp/locations/${locationId}`);
    const location = res.data.data;
    if (location) {
      locationOptions.value = mergeOptionById(locationOptions.value, {
        id: location.id,
        name: location.name,
        warehouseId: location.warehouseId
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const loadDetail = async () => {
  if (!isPurchaseReturnRoute.value) return;
  isInitializing.value = true;
  resetForm();
  if (!isEditing.value) {
    await fetchNextOrderNo();
    formData.orderAt = formatDateTime(new Date());
    formData.status = 'DRAFT';
    addItem();
    applyDefaultMethods();
    lastSupplierId.value = formData.supplierId;
    isInitializing.value = false;
    return;
  }
  try {
    const id = route.params.id;
    const res: any = await request.get(`/erp/purchase-returns/${id}`);
    if (res.data.code === 200) {
      const data = res.data.data || {};
      formData.orderNo = data.order?.orderNo || data.orderNo || '';
      formData.status = data.order?.status || data.status || '';
      formData.returnType = data.order?.returnType || data.returnType || 'RETURN';
      formData.supplierId = data.order?.supplierId || data.supplierId || null;
      formData.purchaseOrderId = data.order?.purchaseOrderId || data.purchaseOrderId || null;
      formData.returnSource = formData.purchaseOrderId ? 'BY_PURCHASE_ORDER' : 'BY_PRODUCT';
      formData.orderAt = normalizeDateTimeValue(data.order?.orderAt || data.orderAt) || formatDateTime(new Date());
      formData.remark = data.order?.remark || data.remark || '';
      formData.settlementMethod = data.order?.settlementMethod || data.settlementMethod || '';
      formData.paidAmount = String(data.order?.paidAmount ?? data.paidAmount ?? '');
      formData.discountAmount = String(data.order?.discountAmount ?? data.discountAmount ?? '');
      formData.items = (data.items || data.order?.items || []).map((item: any) => ({
        id: item.id,
        productId: item.productId,
        warehouseId: item.warehouseId,
        locationId: item.locationId,
        stockKey: '',
        qty: item.qty == null ? '' : String(item.qty),
        price: item.price == null ? '' : String(item.price),
        taxRate: item.taxRate,
        remark: item.remark
      }));
      await Promise.all(formData.items.flatMap(item => [
        ensureWarehouseOption(item.warehouseId),
        ensureLocationOption(item.locationId)
      ]));
      for (const item of formData.items) {
        await fetchStockOptions(item.productId);
        syncStockKey(item);
      }
      if (!formData.items.length) addItem();
      lastSupplierId.value = formData.supplierId;
    }
  } catch (error) {
    notifyError(error);
  } finally {
    isInitializing.value = false;
  }
};

const addItem = () => {
  formData.items.push({
    productId: undefined,
    warehouseId: undefined,
    locationId: undefined,
    stockKey: '',
    qty: '',
    price: '',
    taxRate: 0,
    remark: ''
  });
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const resetForm = () => {
  formData.orderNo = '';
  formData.orderAt = '';
  formData.status = '';
  formData.returnType = 'RETURN';
  formData.returnSource = 'BY_PRODUCT';
  formData.supplierId = null;
  formData.purchaseOrderId = null;
  formData.settlementMethod = '';
  formData.paidAmount = '';
  formData.discountAmount = '';
  formData.remark = '';
  formData.items = [];
  themeMode.value = 'default';
  productRecentPurchaseMap.value = {};
  purchaseOrderDetailItems.value = [];
  selectedPurchaseOrderItems.value = [];
};

const fetchSettlementMethods = async () => {
  try {
    const res: any = await request.get('/erp/settlement-methods', { params: { enabled: true } });
    settlementMethodOptions.value = res.data.data || [];
    applyDefaultMethods();
  } catch (error) {
    notifyError(error);
  }
};

const applyDefaultMethods = () => {
  if (isEditing.value) return;
  if (!formData.settlementMethod && settlementMethodOptions.value.length) {
    const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
    if (defaultItem) {
      formData.settlementMethod = defaultItem.code;
    }
  }
  if (!formData.returnType) {
    formData.returnType = 'RETURN';
  }
  if (!formData.returnSource) {
    formData.returnSource = 'BY_PRODUCT';
  }
};

const fetchNextOrderNo = async () => {
  try {
    const res: any = await request.get('/erp/purchase-returns/next-no');
    if (res.data.code === 200) {
      formData.orderNo = res.data.data || '';
    }
  } catch (error) {
    notifyError(error);
  }
};

  const saveData = async (options: { closeOnSuccess?: boolean; reloadAfterCreate?: boolean } = {}) => {
    const closeOnSuccess = options.closeOnSuccess !== false;
    if (!formData.supplierId) {
      notifyWarning(t('message.required'));
    return;
  }
  if (!formData.returnType) {
    notifyWarning(t('message.required'));
    return;
  }
  if (formData.returnSource === 'BY_PURCHASE_ORDER' && !formData.purchaseOrderId) {
    notifyWarning(t('message.required'));
    return;
  }
  if (!formData.settlementMethod) {
    notifyWarning(t('message.required'));
    return;
  }
  const validItems = formData.items.filter(item => item.productId);
  if (!validItems.length) {
    notifyWarning(t('message.noItems'));
    return;
  }
  for (const item of validItems) {
    const qtyValue = parseDecimal(item.qty, 4);
    if (qtyValue == null || qtyValue <= 0) {
      notifyWarning(t('message.mustBePositive'));
      return;
    }
    const priceValue = parseDecimal(item.price, 4);
    if (priceValue == null) {
      notifyWarning(t('message.invalidNumber'));
      return;
    }
  }

  const paidAmount = parseAmount(formData.paidAmount);
  const discountAmount = parseAmount(formData.discountAmount);
  if (paidAmount == null || discountAmount == null) {
    notifyWarning(t('message.invalidNumber'));
    return;
  }

    const payload = {
      orderNo: formData.orderNo || undefined,
      orderAt: formData.orderAt || undefined,
      returnType: formData.returnType || 'RETURN',
      supplierId: formData.supplierId,
      purchaseOrderId: formData.purchaseOrderId || undefined,
      settlementMethod: formData.settlementMethod,
      paidAmount,
      discountAmount,
      remark: formData.remark,
      items: validItems.map((item, index) => {
        ensureStockBinding(item);
        return {
          productId: item.productId,
          warehouseId: item.warehouseId,
          locationId: item.locationId,
          qty: parseDecimal(item.qty, 4),
          price: parseDecimal(item.price, 4),
          taxRate: item.taxRate,
          remark: item.remark,
          sortNo: index + 1
        };
      })
    };

  try {
    const res: any = isEditing.value
      ? await request.put(`/erp/purchase-returns/${route.params.id}`, payload)
      : await request.post('/erp/purchase-returns', payload);

    if (res.data.code === 200) {
      const data = res.data.data || {};
      const savedId = data.order?.id || data.id || Number(route.params.id || 0) || null;
      notifySuccess();
      if (!isEditing.value && savedId && options.reloadAfterCreate) {
        await router.replace(`/erp/purchase-returns/${savedId}/edit`);
        await loadDetail();
      }
      if (closeOnSuccess) {
        closePage();
        await router.push('/erp/purchase-returns/draft');
      }
      return savedId;
    }
  } catch (error) {
    notifyError(error);
  }
  return null;
};

const parseDecimal = (value: string | number | undefined, scale: number) => {
  if (value == null || value === '') return 0;
  const raw = String(value);
  const normalized = raw.endsWith('.') ? raw.slice(0, -1) : raw;
  if (!normalized) return 0;
  const regex = new RegExp(`^\\d+(\\.\\d{1,${scale}})?$`);
  if (!regex.test(normalized)) {
    return null;
  }
  return Number(normalized);
};

const parseAmount = (value: string) => parseDecimal(value, 2);

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const normalizeDateTimeValue = (value: any) => {
  if (!value) return '';
  if (value instanceof Date) {
    return formatDateTime(value);
  }
  const raw = String(value);
  if (!raw) return '';
  if (raw.includes('T')) {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
      return '';
    }
    return formatDateTime(parsed);
  }
  return raw;
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

watch(
  () => route.fullPath,
  (newPath) => {
    if (newPath === lastRouteKey.value) return;
    lastRouteKey.value = newPath;
    pagePath.value = route.path;
    if (!isPurchaseReturnRoute.value) return;
    loadDetail();
  }
);

onMounted(() => {
  pagePath.value = route.path;
  fetchSuppliers();
  fetchPurchaseOrders();
  fetchProducts();
  fetchWarehouses();
  fetchLocations();
  fetchSettlementMethods();
  loadDetail();
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('tags:close', handleTagClosing as EventListener);
    window.addEventListener('keydown', handleKeydown);
  }
});

onActivated(() => {
  if (!needsReload.value) return;
  needsReload.value = false;
  if (!isPurchaseReturnRoute.value) return;
  loadDetail();
});

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('tags:close', handleTagClosing as EventListener);
    window.removeEventListener('keydown', handleKeydown);
  }
  resetForm();
});
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;600&family=Noto+Serif+SC:wght@600;700&display=swap');

.sale-theme {
  background: transparent;
}

.theme-switch {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  min-height: 40px;
  padding: 6px 10px 6px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.9);
}

.theme-switch__label {
  font-size: 12px;
  color: #606266;
  font-weight: 600;
  white-space: nowrap;
  letter-spacing: 0.02em;
}

.theme-switch__select {
  width: 136px;
}

.theme-switch :deep(.el-select__wrapper) {
  min-height: 30px;
  border-radius: 8px;
  box-shadow: none;
  background: #ffffff;
}

.theme-switch :deep(.el-select__placeholder),
.theme-switch :deep(.el-select__selected-item) {
  color: #303133;
  font-weight: 500;
}

.action-button {
  min-width: 72px;
  font-weight: 600;
}

.action-button--success {
  background: #f0f9eb;
  border-color: #b7e1a1;
  color: #4e8f2b;
}

.action-button--success:hover,
.action-button--success:focus-visible {
  background: #e3f4d8;
  border-color: #95d475;
  color: #3f7d21;
}

.sale-theme--paper {
  --paper-ink: #2d2a26;
  --paper-muted: #7b6f65;
  --paper-accent: #c27c3f;
  --paper-accent-deep: #9b5b2b;
  --paper-card: #fffdfa;
  --paper-border: rgba(45, 42, 38, 0.12);
  --paper-shadow: 0 12px 24px rgba(45, 42, 38, 0.12);
  background: linear-gradient(135deg, #fbf7f1 0%, #f1e8dc 100%);
  font-family: 'Noto Sans SC', 'Segoe UI', sans-serif;
  color: var(--paper-ink);
  position: relative;
  overflow: hidden;
}

.sale-theme--paper::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(rgba(45, 42, 38, 0.05) 1px, transparent 1px);
  background-size: 18px 18px;
  opacity: 0.3;
  pointer-events: none;
}

.sale-theme--paper .page-title {
  font-family: 'Noto Serif SC', 'Noto Sans SC', serif;
  letter-spacing: 1px;
}

.sale-theme--paper .page-toolbar-card {
  background: rgba(255, 253, 250, 0.96);
  border-color: var(--paper-border);
  box-shadow: var(--paper-shadow);
}

.sale-theme--paper .table-card {
  border-radius: 16px;
  border: 1px solid var(--paper-border);
  background: var(--paper-card);
  box-shadow: var(--paper-shadow);
}

.sale-theme--paper :deep(.el-input__wrapper),
.sale-theme--paper :deep(.el-select__wrapper),
.sale-theme--paper :deep(.el-textarea__inner) {
  border-radius: 10px;
  background: #fffaf5;
}

.sale-theme--paper :deep(.el-button--primary) {
  background: var(--paper-accent);
  border-color: var(--paper-accent);
}

.sale-theme--paper :deep(.el-button--primary:hover) {
  background: var(--paper-accent-deep);
  border-color: var(--paper-accent-deep);
}

.sale-theme--paper :deep(.el-button--success) {
  background: #b46a32;
  border-color: #b46a32;
}

.sale-theme--paper :deep(.paper-add-item-button.el-button) {
  background: rgba(194, 124, 63, 0.12);
  border-color: rgba(194, 124, 63, 0.6);
  color: var(--paper-accent-deep);
  font-weight: 600;
}

.sale-theme--paper :deep(.paper-add-item-button.el-button:hover) {
  background: rgba(194, 124, 63, 0.2);
  border-color: var(--paper-accent);
  color: var(--paper-accent-deep);
}

.sale-theme--paper :deep(.paper-add-item-button.el-button:focus-visible) {
  outline: 2px solid rgba(194, 124, 63, 0.35);
  outline-offset: 1px;
}

.sale-theme--paper :deep(.el-table th) {
  background: rgba(194, 124, 63, 0.08);
  color: var(--paper-ink);
  border-bottom: 1px solid rgba(45, 42, 38, 0.12);
}

.sale-theme--paper :deep(.el-table td) {
  background: rgba(255, 253, 250, 0.9);
  border-color: rgba(45, 42, 38, 0.08);
}

.sale-theme--paper :deep(.el-table__row:hover > td) {
  background: rgba(194, 124, 63, 0.06);
}

.sale-theme--paper :deep(.el-table__body-wrapper) {
  background: rgba(255, 253, 250, 0.9);
}

.sale-theme--paper .detail-table-wrapper {
  border: none;
  border-radius: 0;
  padding: 0;
  background: transparent;
}

.sale-theme--paper :deep(.el-table) {
  border-radius: 14px;
  overflow: hidden;
}

.sale-theme--paper :deep(.el-table__inner-wrapper) {
  border-radius: 14px;
  overflow: hidden;
}

.sale-form :deep(.el-form-item) {
  margin-bottom: 4px;
}

.sale-form--compact :deep(.el-form-item) {
  margin-bottom: 0;
}

.form-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  overflow-x: visible;
  padding-bottom: 0;
}

.compact-card .form-grid {
  padding-bottom: 0;
}

@media (max-width: 1200px) {
  .form-grid {
    gap: 4px;
  }
}

.form-group {
  min-width: 220px;
}

.compact-card .table-body {
  padding: 6px 12px;
}

.compact-card {
  flex: 0 0 auto;
}

.purchase-return-header-card {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.purchase-return-toolbar {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  align-items: center;
  gap: 12px;
}

.purchase-return-toolbar__meta {
  display: flex;
  align-items: center;
  min-height: 32px;
  min-width: 0;
}

.purchase-return-toolbar__actions {
  margin-left: auto;
  justify-content: flex-end;
  flex-wrap: nowrap;
}

.purchase-return-header-panel {
  border: 1px solid #e5e5e5;
  border-radius: 8px;
  background: #ffffff;
}

.compact-card .table-body {
  flex: 0 0 auto;
  overflow: visible;
}

.purchase-return-header-panel .sale-form {
  padding: 12px 16px;
}

.sale-detail-card {
  flex: 1 1 auto;
  min-height: 0;
}

.sale-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
  padding: 12px 16px;
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 8px;
}

.detail-table-wrapper {
  flex: 1 1 auto;
  min-height: 0;
  overflow: auto;
}

.detail-actions {
  display: flex;
  justify-content: flex-start;
}

.detail-summary {
  display: flex;
  gap: 16px;
  justify-content: flex-end;
  font-size: 13px;
  color: #606266;
}

.summary-item {
  white-space: nowrap;
}

.recent-sale-hint {
  margin-top: 6px;
  padding: 6px 8px;
  background: #f8fafc;
  border: 1px dashed #dcdfe6;
  border-radius: 8px;
  font-size: 12px;
  color: #606266;
}

.recent-sale-hint__title {
  font-weight: 600;
  margin-bottom: 4px;
  color: #409eff;
}

.recent-sale-hint__list {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.recent-sale-hint__item {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  line-height: 1.4;
}

.recent-sale-hint__no {
  font-weight: 600;
  color: #303133;
}

.recent-sale-hint__meta {
  color: #909399;
}

.recent-sale-hint__empty {
  color: #909399;
}

.payment-card-body {
  padding: 12px 16px !important;
}

.payment-card .form-grid {
  align-items: center;
  flex-wrap: nowrap;
  gap: 8px;
}

.payment-card .form-group {
  min-width: 0;
  flex: 0 0 auto;
}

.payment-card .form-group--settlement {
  min-width: 180px;
}

.payment-card .form-group--amount,
.payment-card .form-group--discount {
  width: auto;
}

.payment-card :deep(.el-form-item) {
  display: flex;
  align-items: center;
}

.payment-card :deep(.el-form-item__label) {
  padding-bottom: 0;
  display: inline-flex;
  align-items: center;
  height: 32px;
  line-height: 32px;
  margin-right: 4px;
  width: auto !important;
  padding-right: 2px;
  flex: 0 0 auto;
}

.payment-card :deep(.el-form-item__content) {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  min-height: 32px;
}

.table-card + .table-card {
  margin-top: 12px;
}

.order-time-picker {
  width: 100%;
}

.order-time-picker :deep(.el-input__wrapper) {
  width: 100%;
  box-sizing: border-box;
}

.order-time-picker :deep(.el-input__inner) {
  width: 100%;
  padding-right: 48px;
}

.order-time-picker :deep(.el-input__suffix) {
  width: 44px;
  display: flex;
  justify-content: flex-end;
}

.red-flush-reason {
  margin-top: 8px;
  color: #b42318;
  font-size: 13px;
  line-height: 1.6;
  white-space: pre-wrap;
}

.table-card.compact-card--inline {
  flex: 0 0 auto !important;
  height: auto !important;
  min-height: 0 !important;
}

.table-card.compact-card--inline .compact-card-body {
  flex: 0 0 auto !important;
  height: auto !important;
  min-height: 0 !important;
  padding: 6px 12px !important;
  overflow: visible !important;
}

.sale-form--inline .form-grid {
  align-items: center;
}

.sale-form--inline :deep(.el-form-item__label) {
  line-height: 20px;
  padding-bottom: 2px;
}

.sale-form--inline :deep(.el-form-item__content) {
  line-height: 28px;
}

@media (max-width: 1280px) {
  .purchase-return-toolbar {
    grid-template-columns: minmax(0, 1fr);
  }

  .purchase-return-toolbar__meta,
  .purchase-return-toolbar__actions {
    width: 100%;
  }

  .purchase-return-toolbar__actions {
    justify-content: flex-end;
    margin-left: 0;
  }
}

@media (max-width: 768px) {
  .purchase-return-toolbar__actions {
    width: 100%;
    flex-wrap: wrap;
    justify-content: flex-end;
  }

  .theme-switch {
    width: 100%;
    justify-content: space-between;
  }

  .theme-switch__select {
    width: 100%;
    max-width: 180px;
  }
}
</style>
