<template>
  <div class="page-shell sale-preview">
    <div class="page-header preview-header">
      <div class="preview-header__title">
        <h2 class="page-title">{{ pageTitle }}</h2>
        <span class="preview-header__badge">{{ $t('status.draft') }}</span>
      </div>
      <div class="table-toolbar">
        <el-button @click="handleBack">{{ $t('action.back') }}</el-button>
        <el-button
          v-if="canCopy"
          type="primary"
          @click="handleCopy"
        >
          {{ $t('action.copy') }}
        </el-button>
        <el-button
          v-if="canRedFlush"
          type="danger"
          @click="handleRedFlush"
        >
          {{ $t('action.redFlush') }}
        </el-button>
        <el-button
          v-if="canApprove"
          type="success"
          @click="handleApprove"
        >
          {{ $t('action.approve') }}
        </el-button>
        <el-button v-if="!isReadOnly" @click="handleSave">{{ $t('action.save') }}</el-button>
        <el-button v-if="!isReadOnly" type="primary" @click="handleSaveAndBack">{{ $t('action.saveAndBack') }}</el-button>
      </div>
    </div>

    <div class="preview-hero">
      <div class="preview-hero__content">
        <span class="preview-chip">{{ $t('page.erpSaleOrderCreatePreviewAlt') }}</span>
        <h3 class="preview-title">{{ $t('page.erpSaleOrderCreate') }}</h3>
        <p class="preview-subtitle">{{ $t('message.saleOrderPreviewAltHint') }}</p>
      </div>
      <div class="preview-hero__meta">
        <div class="preview-hero__meta-item">
          <span>{{ $t('field.orderNo') }}</span>
          <strong>{{ formData.orderNo || $t('placeholder.autoGenerated') }}</strong>
        </div>
        <div class="preview-hero__meta-item">
          <span>{{ $t('field.orderTime') }}</span>
          <strong>{{ formData.orderAt || '-' }}</strong>
        </div>
        <div class="preview-hero__meta-item">
          <span>{{ $t('field.customer') }}</span>
          <strong>{{ customerOptions.find((item) => item.id === formData.customerId)?.name || '-' }}</strong>
        </div>
      </div>
    </div>

    <div class="table-card compact-card sale-header-card preview-card">
      <div class="table-body sale-header-body">
        <el-form :model="formData" label-position="top" class="sale-form sale-form--compact">
          <div class="form-grid">
            <div class="form-group">
              <el-form-item :label="$t('field.orderNo')">
                <el-input v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.orderTime')">
                <el-date-picker
                  v-model="formData.orderAt"
                  type="datetime"
                  format="YYYY-MM-DD HH:mm:ss"
                  value-format="YYYY-MM-DD HH:mm:ss"
                  class="order-time-picker"
                  style="width: 100%"
                  :clearable="false"
                  :disabled="isReadOnly"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.customer')" required>
                <FuzzyProductSelect
                  v-model="formData.customerId"
                  :options="customerOptions"
                  :placeholder="$t('field.customer')"
                  style="width: 100%"
                  :disabled="isReadOnly"
                  @change="handleCustomerChange"
                />
              </el-form-item>
            </div>
            <div class="form-group">
              <el-form-item :label="$t('field.deliveryMethod')">
                <el-select v-model="formData.deliveryMethod" clearable style="width: 100%" :disabled="isReadOnly">
                  <el-option v-for="item in deliveryMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
          </div>

          <el-form-item :label="$t('field.remark')">
            <el-input v-model="formData.remark" type="textarea" :disabled="isReadOnly" />
          </el-form-item>
        </el-form>

      </div>
    </div>

    <div class="table-card sale-detail-card preview-card">
      <div class="table-body sale-detail-body">
        <div class="detail-section">
          <div class="detail-header">
            <h4>{{ $t('field.items') }}</h4>
          </div>
          <div class="detail-table-wrapper">
            <ErpDataTable :data="formData.items" style="width: 100%" border stripe table-key="erp-sale-order-form-preview-alt">
              <ErpDataTableColumn :label="$t('field.product')" min-width="200" column-key="product">
                <template #default="{ row }">
                  <el-select
                    v-model="row.productId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectProduct')"
                    :disabled="isReadOnly || !formData.customerId"
                    @change="handleProductChange(row)"
                  >
                    <el-option v-for="item in productOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.warehouse')" min-width="160" column-key="warehouse">
                <template #default="{ row }">
                  <el-select
                    v-model="row.warehouseId"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectWarehouse')"
                    :disabled="isReadOnly || !row.productId"
                    @change="handleWarehouseChange(row)"
                  >
                    <el-option v-for="item in warehouseOptions" :key="item.id" :label="item.name" :value="item.id" />
                  </el-select>
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn :label="$t('field.location')" min-width="160" column-key="location">
                <template #default="{ row }">
                  <el-select
                    v-model="row.stockKey"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectLocation')"
                    :disabled="isReadOnly || !row.productId"
                    @change="handleStockLocationChange(row)"
                    @visible-change="(visible: boolean) => handleStockVisibleChange(row, visible)"
                  >
                    <el-option
                      v-for="item in getStockOptionsForRow(row)"
                      :key="item.key"
                      :label="item.searchLabel"
                      :value="item.key"
                    >
                      <div class="stock-option">
                        <span class="stock-option__name">{{ item.label }}</span>
                        <span class="stock-option__qty">
                          {{ $t('field.qtyOnHand') }}: {{ item.qtyOnHand }}
                          · {{ $t('field.qtyAvailable') }}: {{ item.qtyAvailable }}
                          · {{ $t('field.qtyLocked') }}: {{ item.qtyLocked }}
                        </span>
                      </div>
                    </el-option>
                  </el-select>
                </template>
              </ErpDataTableColumn>
            <ErpDataTableColumn :label="$t('field.quantity')" width="140" column-key="quantity">
              <template #default="{ row }">
                <DecimalInput v-model="row.qty" :scale="4" :disabled="isReadOnly" />
              </template>
            </ErpDataTableColumn>
            <ErpDataTableColumn :label="$t('field.price')" width="140" column-key="price">
              <template #default="{ row }">
                <DecimalInput v-model="row.price" :scale="4" :disabled="isReadOnly" />
              </template>
            </ErpDataTableColumn>
            <ErpDataTableColumn :label="$t('field.lineTotal')" width="140" column-key="lineAmount">
              <template #default="{ row }">
                {{ formatMoney(calcLineAmount(row)) }}
              </template>
            </ErpDataTableColumn>
            <ErpDataTableColumn v-if="canShowDiscountAllocated" :label="$t('field.discountAllocated')" width="140" column-key="discountAllocated">
              <template #default="{ row }">
                {{ formatMoney(calcLineDiscount(row)) }}
              </template>
            </ErpDataTableColumn>
            <ErpDataTableColumn v-if="canShowProfit" :label="$t('field.profit')" min-width="160" column-key="profit">
              <template #default="{ row }">
                {{ formatProfitCell(row) }}
              </template>
            </ErpDataTableColumn>

              <ErpDataTableColumn :label="$t('field.remark')" min-width="160" column-key="remark">
                <template #default="{ row }">
                  <el-input v-model="row.remark" :disabled="isReadOnly" />
                </template>
              </ErpDataTableColumn>
              <ErpDataTableColumn label="" width="80" align="center" column-key="actions">
                <template #default="{ $index }">
                  <el-button type="danger" circle size="small" :disabled="isReadOnly" @click="removeItem($index)">x</el-button>
                </template>
            </ErpDataTableColumn>
          </ErpDataTable>
          </div>
          <div class="detail-actions">
            <el-button type="primary" plain size="small" :disabled="isReadOnly" @click="addItem">+ {{ $t('action.addItem') }}</el-button>
          </div>
          <div class="detail-summary">
            <div class="summary-item">{{ $t('field.totalAmount') }}: {{ formatMoney(totalSummary.amount) }}</div>
            <div class="summary-item" v-if="canShowProfit">{{ $t('field.totalProfit') }}: {{ totalProfitText }}</div>
            <div class="summary-item" v-if="canShowProfit">{{ $t('field.totalProfitRate') }}: {{ totalProfitRateText }}</div>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card compact-card compact-card--inline payment-card preview-card">
      <div class="table-body compact-card-body payment-card-body">
        <el-form :model="formData" label-position="left" label-width="70px" class="sale-form sale-form--compact sale-form--inline">
          <div class="form-grid">
            <div class="form-group form-group--settlement">
              <el-form-item :label="$t('field.settlementMethod')" required>
                <el-select v-model="formData.settlementMethod" style="width: 150px" :disabled="isReadOnly">
                  <el-option v-for="item in settlementMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
            <div v-if="formData.settlementMethod" class="form-group form-group--amount">
              <el-form-item :label="$t('field.paidAmount')">
                <DecimalInput v-model="formData.paidAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
            <div v-if="formData.settlementMethod" class="form-group form-group--discount">
              <el-form-item :label="$t('field.discountAmount')">
                <DecimalInput v-model="formData.discountAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>

    <el-dialog
      v-model="showCustomerChangeDialog"
      :title="$t('message.confirmCustomerChangeTitle')"
      width="420px"
      :close-on-click-modal="false"
      :close-on-press-escape="false"
    >
      <div>{{ $t('message.confirmCustomerChange') }}</div>
      <template #footer>
        <el-button @click="applyCustomerChange('cancel')">{{ $t('action.cancel') }}</el-button>
        <el-button @click="applyCustomerChange('clear')">{{ $t('action.clearItems') }}</el-button>
        <el-button type="primary" @click="applyCustomerChange('price')">{{ $t('action.updatePrice') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, onActivated, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import { ElMessageBox } from 'element-plus';
import { useAuthStore } from '@/stores/auth';

interface OptionItem {
  id: number;
  name: string;
  warehouseId?: number;
  categoryId?: number;
  defaultSettlementMethodCode?: string;
  deliveryMethodCode?: string;
}

interface ProductOption {
  id: number;
  name: string;
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  salePrice?: number;
  costPrice?: number;
}

interface StockOption {
  key: string;
  warehouseId: number | null;
  warehouseName: string;
  locationId: number | null;
  locationName: string;
  qtyOnHand: number;
  qtyAvailable: number;
  qtyLocked: number;
  label: string;
  searchLabel: string;
}

interface CodeOptionItem {
  id: number;
  code: string;
  name: string;
  isDefault?: boolean;
}

interface SaleOrderItem {
  id?: number;
  productId?: number;
  warehouseId?: number;
  locationId?: number;
  stockKey?: string;
  qty?: string | number;
  price?: string | number;
  taxRate?: number;
  remark?: string;
  sortNo?: number;
}

const { t } = useI18n();
const router = useRouter();
const route = useRoute();
const { notifyError, notifySuccess, notifyWarning } = useApiError();
const authStore = useAuthStore();

const isEditing = computed(() => Boolean(route.params.id));
const isReadOnly = computed(() => {
  if (route.query.mode === 'view') return true;
  if (!formData.status) return false;
  return formData.status !== 'DRAFT';
});

const canCopy = computed(() => {
  return isReadOnly.value
    && (formData.status === 'APPROVED' || formData.status === 'RED_FLUSHED')
    && hasPermission('erp-sale:add');
});

const canRedFlush = computed(() => {
  return isReadOnly.value && formData.status === 'APPROVED' && hasPermission('erp-sale:redflush');
});

const pageTitle = computed(() => (isEditing.value ? t('page.erpSaleOrderEdit') : t('page.erpSaleOrderCreatePreviewAlt')));

const customerOptions = ref<OptionItem[]>([]);
const productOptions = ref<ProductOption[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const settlementMethodOptions = ref<CodeOptionItem[]>([]);
const deliveryMethodOptions = ref<CodeOptionItem[]>([]);
const productStockMap = ref<Record<number, StockOption[]>>({});

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  customerId: null as number | null,
  settlementMethod: '',
  deliveryMethod: '',
  paidAmount: '',
  discountAmount: '',
  remark: '',
  items: [] as SaleOrderItem[]
});

const pagePath = ref(route.path);
const showCustomerChangeDialog = ref(false);
const pendingCustomerId = ref<number | null>(null);
const lastCustomerId = ref<number | null>(null);
const isInitializing = ref(false);
const needsReload = ref(false);
const showProfitColumn = ref(false);

const hasPermission = (code: string) => {
  return authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);
};

const canApprove = computed(() => {
  return !isReadOnly.value && formData.status === 'DRAFT' && hasPermission('erp-sale:approve');
});

const canViewProfit = computed(() => {
  return hasPermission('column:erp-sale-form:profit')
    && (hasPermission('erp-product:cost:view') || hasPermission('erp-product:cost:edit'));
});

const canShowProfit = computed(() => canViewProfit.value && showProfitColumn.value);
const canShowDiscountAllocated = computed(() => hasPermission('column:erp-sale-form:discountAllocated'));

const isTypingTarget = (target: EventTarget | null) => {
  if (!target || !(target instanceof HTMLElement)) return false;
  const tag = target.tagName.toLowerCase();
  if (tag === 'input' || tag === 'textarea' || tag === 'select') return true;
  return target.isContentEditable;
};

const handleKeydown = (event: KeyboardEvent) => {
  if (!canViewProfit.value) return;
  if (isTypingTarget(event.target)) return;
  if (event.key && event.key.toLowerCase() === 'u') {
    if (event.repeat) return;
    event.preventDefault();
    showProfitColumn.value = !showProfitColumn.value;
  }
};

const closePage = () => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path } }));
  }
};

const handleBack = async () => {
  if (isEditing.value) {
    resetForm();
    closePage();
    return;
  }

  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    try {
      await ElMessageBox.confirm(
        t('message.confirmSaveDraft'),
        t('action.confirm'),
        {
          confirmButtonText: t('action.save'),
          cancelButtonText: t('action.cancel'),
          type: 'warning'
        }
      );
      await saveData();
    } catch {
      resetForm();
      closePage();
    }
    return;
  }

  try {
    await ElMessageBox.confirm(
      t('message.confirmClosePage'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    resetForm();
    closePage();
  } catch {
    return;
  }
};

const handleApprove = async () => {
  if (isReadOnly.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmSaveBeforeApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.save'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }

  const savedId = await saveData({ closeOnSuccess: false, reloadAfterCreate: true });
  if (!savedId) return;

  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    await request.post(`/erp/sale-orders/${savedId}/approve`);
    formData.status = 'APPROVED';
    notifySuccess();
    closePage();
    await router.push('/erp/sale-orders/draft');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleRedFlush = async () => {
  if (!isEditing.value) return;
  try {
    const { value } = await ElMessageBox.prompt(
      t('message.confirmRedFlush'),
      t('action.redFlush'),
      {
        inputPlaceholder: t('placeholder.required'),
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel')
      }
    );
    if (!value || !String(value).trim()) {
      return;
    }
    await request.post(`/erp/sale-orders/${route.params.id}/red-flush`, { reason: String(value).trim() });
    notifySuccess();
    closePage();
    await router.push('/erp/sale-orders/approved');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleSave = async () => {
  await saveData({ closeOnSuccess: false });
};

const handleSaveAndBack = async () => {
  await saveData({ closeOnSuccess: true });
};

const handleCopy = async () => {
  if (!formData.customerId || !formData.items.length) {
    notifyWarning(t('message.noItems'));
    return;
  }
  try {
    await ElMessageBox.confirm(
      t('message.confirmCopyOrder'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.copy'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }
  try {
    const orderNoRes: any = await request.get('/erp/sale-orders/next-order-no');
    const orderNo = orderNoRes.data?.data || '';
    const items = formData.items.filter(item => item.productId).map((item, index) => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: parseDecimal(item.qty, 4),
      price: parseDecimal(item.price, 4),
      taxRate: item.taxRate,
      remark: item.remark,
      sortNo: index + 1
    }));
    const payload = {
      orderNo,
      orderAt: formatDateTime(new Date()),
      customerId: formData.customerId,
      settlementMethod: formData.settlementMethod,
      deliveryMethod: formData.deliveryMethod || undefined,
      paidAmount: parseAmount(formData.paidAmount),
      discountAmount: parseAmount(formData.discountAmount),
      remark: formData.remark,
      items
    };
    const res: any = await request.post('/erp/sale-orders', payload);
    if (res.data.code === 200) {
      const data = res.data.data || {};
      const newId = data.order?.id || data.id;
      notifySuccess();
      if (newId) {
        await router.push({ path: `/erp/sale-orders/${newId}/edit`, query: { from: 'draft' } });
        await loadDetail();
      }
    }
  } catch (error) {
    notifyError(error);
  }
};

const getLocationOptions = (warehouseId?: number) => {
  if (!warehouseId) return locationOptions.value;
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const buildStockKey = (warehouseId: number | null | undefined, locationId: number | null | undefined) => {
  const w = warehouseId == null ? 0 : warehouseId;
  const l = locationId == null ? 0 : locationId;
  return `${w}:${l}`;
};

const buildStockOptionLabel = (option: StockOption) => {
  return `${option.warehouseName} / ${option.locationName}`;
};

const normalizeStockOption = (option: any): StockOption => {
  const warehouseId = option.warehouseId ?? null;
  const locationId = option.locationId ?? null;
  const warehouseName = option.warehouseName || '-';
  const locationName = option.locationName || t('field.unassignedLocation');
  const qtyOnHand = Number(option.qtyOnHand ?? 0);
  const qtyAvailable = Number(option.qtyAvailable ?? qtyOnHand);
  const qtyLocked = Number(option.qtyLocked ?? 0);
  const baseLabel = `${warehouseName} / ${locationName}`;
  return {
    key: buildStockKey(warehouseId, locationId),
    warehouseId,
    locationId,
    warehouseName,
    locationName,
    qtyOnHand,
    qtyAvailable,
    qtyLocked,
    label: baseLabel,
    searchLabel: `${baseLabel} ${qtyOnHand} ${qtyAvailable} ${qtyLocked}`
  };
};

const fetchStockOptions = async (productId?: number, force = false) => {
  if (!productId) return;
  if (!force && productStockMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/stock/balances/by-product', { params: { productId } });
    const data = res.data.data || [];
    productStockMap.value[productId] = data.map(normalizeStockOption);
  } catch (error) {
    notifyError(error);
  }
};

const getStockOptionsForRow = (row: SaleOrderItem) => {
  if (!row.productId) return [];
  const options = productStockMap.value[row.productId] || [];
  if (!options.length) return [];
  return options;
};

const syncStockKey = (row: SaleOrderItem) => {
  if (!row.productId) {
    row.stockKey = '';
    return;
  }
  const options = productStockMap.value[row.productId] || [];
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
  const matched = options.find(item => item.key === key);
  row.stockKey = matched ? key : '';
};

const applyProductDefaults = (row: SaleOrderItem, force = true) => {
  if (!row.productId) return;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product) return;
  if (product.defaultWarehouseId && (force || !row.warehouseId)) {
    row.warehouseId = product.defaultWarehouseId;
  }
  if (product.defaultLocationId && (force || !row.locationId)) {
    row.locationId = product.defaultLocationId;
  }
  if (row.locationId && row.warehouseId) {
    const location = locationOptions.value.find(item => item.id === row.locationId);
    if (location && location.warehouseId && location.warehouseId !== row.warehouseId) {
      row.locationId = undefined;
    }
  }
};

const getCurrentCustomerCategoryId = () => {
  if (!formData.customerId) return undefined;
  return customerOptions.value.find(item => item.id === formData.customerId)?.categoryId;
};

const applyPriceForRow = async (row: SaleOrderItem, force = false) => {
  if (!row.productId) return;
  if (!force && row.price) return;
  const categoryId = getCurrentCustomerCategoryId();
  if (categoryId) {
    try {
      const res: any = await request.get('/erp/product-prices/resolve', {
        params: { productId: row.productId, customerCategoryId: categoryId }
      });
      const resolved = res.data.data?.salePrice;
      if (resolved != null && resolved !== '') {
        row.price = String(resolved);
        return;
      }
    } catch (error) {
      notifyError(error);
    }
  }
  const product = productOptions.value.find(item => item.id === row.productId);
  if (product && product.salePrice != null) {
    row.price = String(product.salePrice);
  }
};

const getProductCost = (row: SaleOrderItem) => {
  if (!row.productId) return null;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product || product.costPrice == null) return null;
  return Number(product.costPrice);
};

const calcLineAmount = (row: SaleOrderItem) => {
  const qty = parseDecimal(row.qty, 4);
  const price = parseDecimal(row.price, 4);
  if (qty == null || price == null) return null;
  return qty * price;
};

const totalAmountBeforeDiscount = computed(() => {
  let amount = 0;
  formData.items.forEach((row) => {
    const lineAmount = calcLineAmount(row);
    if (lineAmount == null) return;
    amount += lineAmount;
  });
  return amount;
});

const getDiscountAmount = () => {
  const discount = parseAmount(formData.discountAmount || '');
  if (discount == null) return 0;
  return Math.max(0, discount);
};

const calcLineDiscount = (row: SaleOrderItem) => {
  const totalAmount = totalAmountBeforeDiscount.value;
  const discountAmount = getDiscountAmount();
  if (!totalAmount || !discountAmount) return 0;
  const lineAmount = calcLineAmount(row);
  if (lineAmount == null) return 0;
  return (lineAmount / totalAmount) * discountAmount;
};

const calcLineNetAmount = (row: SaleOrderItem) => {
  const amount = calcLineAmount(row);
  if (amount == null) return null;
  return amount - calcLineDiscount(row);
};

const calcLineProfit = (row: SaleOrderItem) => {
  const amount = calcLineNetAmount(row);
  if (amount == null) return null;
  const cost = getProductCost(row);
  if (cost == null) return null;
  return amount - (cost * (parseDecimal(row.qty, 4) || 0));
};

const formatMoney = (value: number | null) => {
  if (value == null || Number.isNaN(value)) return '-';
  return value.toFixed(2);
};

const formatRate = (value: number | null) => {
  if (value == null || Number.isNaN(value)) return '-';
  return `${(value * 100).toFixed(2)}%`;
};

const formatProfitCell = (row: SaleOrderItem) => {
  const profit = calcLineProfit(row);
  const amount = calcLineNetAmount(row);
  if (profit == null || amount == null || amount === 0) return '-';
  return `${formatMoney(profit)} (${formatRate(profit / amount)})`;
};

const totalSummary = computed(() => {
  let amount = 0;
  let netAmount = 0;
  let profit = 0;
  let hasMissingCost = false;
  formData.items.forEach((row) => {
    const lineAmount = calcLineAmount(row);
    if (lineAmount == null) return;
    amount += lineAmount;
    const lineNetAmount = calcLineNetAmount(row);
    if (lineNetAmount != null) {
      netAmount += lineNetAmount;
    }
    const lineProfit = calcLineProfit(row);
    if (lineProfit == null) {
      if (row.productId) {
        hasMissingCost = true;
      }
      return;
    }
    profit += lineProfit;
  });
  const rate = netAmount ? profit / netAmount : null;
  return { amount, netAmount, profit, rate, hasMissingCost };
});

const totalProfitText = computed(() => {
  if (totalSummary.value.hasMissingCost) return '-';
  return formatMoney(totalSummary.value.profit);
});

const totalProfitRateText = computed(() => {
  if (totalSummary.value.hasMissingCost) return '-';
  return formatRate(totalSummary.value.rate);
});

const getDefaultSettlementMethod = () => {
  if (!settlementMethodOptions.value.length) return '';
  const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
  return defaultItem?.code || '';
};

const getDefaultDeliveryMethod = () => {
  if (!deliveryMethodOptions.value.length) return '';
  const defaultItem = deliveryMethodOptions.value.find(item => item.isDefault) ?? deliveryMethodOptions.value[0];
  return defaultItem?.code || '';
};

const applyMethodsForCustomer = () => {
  const customer = customerOptions.value.find(item => item.id === formData.customerId);
  const settlement = customer?.defaultSettlementMethodCode || getDefaultSettlementMethod();
  const delivery = customer?.deliveryMethodCode || getDefaultDeliveryMethod();
  if (settlement) {
    formData.settlementMethod = settlement;
  }
  if (delivery) {
    formData.deliveryMethod = delivery;
  }
};

const handleProductChange = async (row: SaleOrderItem) => {
  row.warehouseId = undefined;
  row.locationId = undefined;
  row.stockKey = '';
  row.price = '';
  applyProductDefaults(row, true);
  await fetchStockOptions(row.productId, true);
  syncStockKey(row);
  await applyPriceForRow(row, true);
};

const handleWarehouseChange = (row: SaleOrderItem) => {
  if (row.stockKey) {
    const keyWarehouse = row.stockKey.split(':')[0];
    if (String(row.warehouseId ?? 0) !== keyWarehouse) {
      row.locationId = undefined;
      row.stockKey = '';
    }
  }
  if (!row.locationId) return;
  const location = locationOptions.value.find(item => item.id === row.locationId);
  if (location && row.warehouseId && location.warehouseId !== row.warehouseId) {
    row.locationId = undefined;
  }
};

const handleStockLocationChange = (row: SaleOrderItem) => {
  if (!row.productId || !row.stockKey) {
    row.locationId = undefined;
    return;
  }
  const options = productStockMap.value[row.productId] || [];
  const selected = options.find(item => item.key === row.stockKey);
  if (!selected) {
    row.locationId = undefined;
    return;
  }
  row.warehouseId = selected.warehouseId ?? undefined;
  row.locationId = selected.locationId ?? undefined;
};

const handleStockVisibleChange = async (row: SaleOrderItem, visible: boolean) => {
  if (!visible || !row.productId) return;
  await fetchStockOptions(row.productId, true);
  syncStockKey(row);
};

const handleCustomerChange = (value: number | null) => {
  if (isInitializing.value) {
    lastCustomerId.value = value;
    return;
  }
  if (value === lastCustomerId.value) return;
  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    pendingCustomerId.value = value;
    showCustomerChangeDialog.value = true;
    return;
  }
  lastCustomerId.value = value;
  applyMethodsForCustomer();
};

const applyCustomerChange = async (action: 'price' | 'clear' | 'cancel') => {
  const targetCustomerId = pendingCustomerId.value;
  showCustomerChangeDialog.value = false;
  if (action === 'cancel') {
    formData.customerId = lastCustomerId.value;
    pendingCustomerId.value = null;
    return;
  }
  lastCustomerId.value = targetCustomerId;
  pendingCustomerId.value = null;
  if (action === 'clear') {
    formData.items = [];
    addItem();
    applyMethodsForCustomer();
    return;
  }
  for (const item of formData.items) {
    await applyPriceForRow(item, true);
  }
  applyMethodsForCustomer();
};

const fetchCustomers = async () => {
  try {
    const res: any = await request.get('/erp/customers');
    customerOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchProducts = async () => {
  try {
    const res: any = await request.get('/erp/products');
    productOptions.value = res.data.data || [];
    for (const item of formData.items) {
      await fetchStockOptions(item.productId);
      applyProductDefaults(item, false);
      syncStockKey(item);
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchWarehouses = async () => {
  try {
    const res: any = await request.get('/erp/warehouses/options');
    warehouseOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchLocations = async () => {
  try {
    const res: any = await request.get('/erp/locations/options');
    locationOptions.value = res.data.data || [];
    formData.items.forEach(item => applyProductDefaults(item, false));
  } catch (error) {
    notifyError(error);
  }
};

const loadDetail = async () => {
  isInitializing.value = true;
  resetForm();
  if (!isEditing.value) {
    await fetchNextOrderNo();
    formData.orderAt = formatDateTime(new Date());
    formData.status = 'DRAFT';
    addItem();
    applyDefaultMethods();
    lastCustomerId.value = formData.customerId;
    isInitializing.value = false;
    return;
  }
  try {
    const id = route.params.id;
    const res: any = await request.get(`/erp/sale-orders/${id}`);
    if (res.data.code === 200) {
      const data = res.data.data || {};
      formData.orderNo = data.order?.orderNo || data.orderNo || '';
      formData.status = data.order?.status || data.status || '';
      formData.customerId = data.order?.customerId || data.customerId || null;
      formData.orderAt = normalizeDateTimeValue(data.order?.orderAt || data.orderAt) || formatDateTime(new Date());
      formData.remark = data.order?.remark || data.remark || '';
      formData.settlementMethod = data.order?.settlementMethod || data.settlementMethod || '';
      formData.deliveryMethod = data.order?.deliveryMethod || data.deliveryMethod || '';
      formData.paidAmount = String(data.order?.paidAmount ?? data.paidAmount ?? '');
      formData.discountAmount = String(data.order?.discountAmount ?? data.discountAmount ?? '');
      formData.items = (data.items || data.order?.items || []).map((item: any) => ({
        id: item.id,
        productId: item.productId,
        warehouseId: item.warehouseId,
        locationId: item.locationId,
        stockKey: '',
        qty: item.qty == null ? '' : String(item.qty),
        price: item.price == null ? '' : String(item.price),
        taxRate: item.taxRate,
        remark: item.remark
      }));
      for (const item of formData.items) {
        await fetchStockOptions(item.productId);
        syncStockKey(item);
      }
      if (!formData.items.length) addItem();
      lastCustomerId.value = formData.customerId;
    }
  } catch (error) {
    notifyError(error);
  } finally {
    isInitializing.value = false;
  }
};

const addItem = () => {
  formData.items.push({
    productId: undefined,
    warehouseId: undefined,
    locationId: undefined,
    stockKey: '',
    qty: '',
    price: '',
    taxRate: 0,
    remark: ''
  });
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const resetForm = () => {
  formData.orderNo = '';
  formData.orderAt = '';
  formData.status = '';
  formData.customerId = null;
  formData.settlementMethod = '';
  formData.deliveryMethod = '';
  formData.paidAmount = '';
  formData.discountAmount = '';
  formData.remark = '';
  formData.items = [];
};

const fetchSettlementMethods = async () => {
  try {
    const res: any = await request.get('/erp/settlement-methods', { params: { enabled: true } });
    settlementMethodOptions.value = res.data.data || [];
    applyDefaultMethods();
  } catch (error) {
    notifyError(error);
  }
};

const fetchDeliveryMethods = async () => {
  try {
    const res: any = await request.get('/erp/delivery-methods', { params: { enabled: true } });
    deliveryMethodOptions.value = res.data.data || [];
    applyDefaultMethods();
  } catch (error) {
    notifyError(error);
  }
};

const applyDefaultMethods = () => {
  if (isEditing.value) return;
  if (!formData.settlementMethod && settlementMethodOptions.value.length) {
    const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
    if (defaultItem) {
      formData.settlementMethod = defaultItem.code;
    }
  }
  if (!formData.deliveryMethod && deliveryMethodOptions.value.length) {
    const defaultItem = deliveryMethodOptions.value.find(item => item.isDefault) ?? deliveryMethodOptions.value[0];
    if (defaultItem) {
      formData.deliveryMethod = defaultItem.code;
    }
  }
};

const fetchNextOrderNo = async () => {
  try {
    const res: any = await request.get('/erp/sale-orders/next-order-no');
    if (res.data.code === 200) {
      formData.orderNo = res.data.data || '';
    }
  } catch (error) {
    notifyError(error);
  }
};

const saveData = async (options: { closeOnSuccess?: boolean; reloadAfterCreate?: boolean } = {}) => {
  const closeOnSuccess = options.closeOnSuccess !== false;
  if (!formData.customerId) {
    notifyWarning(t('message.required'));
    return;
  }
  if (!formData.settlementMethod) {
    notifyWarning(t('message.required'));
    return;
  }
  const validItems = formData.items.filter(item => item.productId);
  if (!validItems.length) {
    notifyWarning(t('message.noItems'));
    return;
  }
  for (const item of validItems) {
    const qtyValue = parseDecimal(item.qty, 4);
    if (qtyValue == null || qtyValue <= 0) {
      notifyWarning(t('message.mustBePositive'));
      return;
    }
    const priceValue = parseDecimal(item.price, 4);
    if (priceValue == null) {
      notifyWarning(t('message.invalidNumber'));
      return;
    }
  }

  const paidAmount = parseAmount(formData.paidAmount);
  const discountAmount = parseAmount(formData.discountAmount);
  if (paidAmount == null || discountAmount == null) {
    notifyWarning(t('message.invalidNumber'));
    return;
  }

  const payload = {
    orderNo: formData.orderNo || undefined,
    orderAt: formData.orderAt || undefined,
    customerId: formData.customerId,
    settlementMethod: formData.settlementMethod,
    deliveryMethod: formData.deliveryMethod || undefined,
    paidAmount,
    discountAmount,
    remark: formData.remark,
    items: validItems.map((item, index) => ({
      productId: item.productId,
      warehouseId: item.warehouseId,
      locationId: item.locationId,
      qty: parseDecimal(item.qty, 4),
      price: parseDecimal(item.price, 4),
      taxRate: item.taxRate,
      remark: item.remark,
      sortNo: index + 1
    }))
  };

  try {
    const res: any = isEditing.value
      ? await request.put(`/erp/sale-orders/${route.params.id}`, payload)
      : await request.post('/erp/sale-orders', payload);

    if (res.data.code === 200) {
      const data = res.data.data || {};
      const savedId = data.order?.id || data.id || Number(route.params.id || 0) || null;
      notifySuccess();
      if (!isEditing.value && savedId && options.reloadAfterCreate) {
        await router.replace(`/erp/sale-orders/${savedId}/edit`);
        await loadDetail();
      }
      if (closeOnSuccess) {
        closePage();
        await router.push('/erp/sale-orders/draft');
      }
      return savedId;
    }
  } catch (error) {
    notifyError(error);
  }
  return null;
};

const parseDecimal = (value: string | number | undefined, scale: number) => {
  if (value == null || value === '') return 0;
  const raw = String(value);
  const normalized = raw.endsWith('.') ? raw.slice(0, -1) : raw;
  if (!normalized) return 0;
  const regex = new RegExp(`^\\d+(\\.\\d{1,${scale}})?$`);
  if (!regex.test(normalized)) {
    return null;
  }
  return Number(normalized);
};

const parseAmount = (value: string) => parseDecimal(value, 2);

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const normalizeDateTimeValue = (value: any) => {
  if (!value) return '';
  if (value instanceof Date) {
    return formatDateTime(value);
  }
  const raw = String(value);
  if (!raw) return '';
  if (raw.includes('T')) {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
      return '';
    }
    return formatDateTime(parsed);
  }
  return raw;
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

onMounted(() => {
  pagePath.value = route.path;
  fetchCustomers();
  fetchProducts();
  fetchWarehouses();
  fetchLocations();
  fetchSettlementMethods();
  fetchDeliveryMethods();
  loadDetail();
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('keydown', handleKeydown);
  }
});

onActivated(() => {
  if (!needsReload.value) return;
  needsReload.value = false;
  loadDetail();
});

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('keydown', handleKeydown);
  }
  resetForm();
});
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;600&family=Noto+Serif+SC:wght@600;700&display=swap');

.sale-preview {
  --preview-ink: #1f2a44;
  --preview-soft: #f6f1ea;
  --preview-accent: #2a7f6f;
  --preview-accent-strong: #1a5c51;
  --preview-card: #ffffff;
  --preview-border: rgba(31, 42, 68, 0.12);
  --preview-shadow: 0 18px 40px rgba(31, 42, 68, 0.12);
  background: radial-gradient(1200px 600px at 20% -20%, #ffffff 0%, #f3efe7 40%, #ede7dd 100%);
  border-radius: 18px;
  padding: 20px;
  font-family: 'Noto Sans SC', 'Segoe UI', sans-serif;
  color: var(--preview-ink);
  animation: previewFade 0.5s ease-out;
}

@keyframes previewFade {
  from {
    opacity: 0;
    transform: translateY(6px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.preview-header {
  align-items: center;
  gap: 12px;
}

.preview-header__title {
  display: flex;
  align-items: center;
  gap: 12px;
}

.preview-header__badge {
  background: rgba(42, 127, 111, 0.12);
  color: var(--preview-accent-strong);
  font-size: 12px;
  padding: 4px 10px;
  border-radius: 999px;
  font-weight: 600;
  letter-spacing: 0.5px;
  text-transform: uppercase;
}

.sale-preview .page-title {
  font-family: 'Noto Serif SC', 'Noto Sans SC', serif;
  letter-spacing: 1px;
}

.preview-hero {
  display: flex;
  gap: 20px;
  align-items: flex-end;
  justify-content: space-between;
  padding: 18px 20px;
  border-radius: 18px;
  background: linear-gradient(135deg, rgba(31, 42, 68, 0.92), rgba(17, 28, 49, 0.96));
  color: #fff;
  box-shadow: var(--preview-shadow);
}

.preview-hero__content {
  max-width: 520px;
}

.preview-chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.14);
  font-size: 12px;
  letter-spacing: 0.6px;
  text-transform: uppercase;
}

.preview-title {
  font-size: 22px;
  margin: 12px 0 6px;
  font-family: 'Noto Serif SC', 'Noto Sans SC', serif;
}

.preview-subtitle {
  margin: 0;
  opacity: 0.82;
  font-size: 13px;
  line-height: 1.6;
}

.preview-hero__meta {
  display: grid;
  gap: 8px;
  min-width: 220px;
}

.preview-hero__meta-item {
  display: flex;
  flex-direction: column;
  gap: 2px;
  font-size: 12px;
  opacity: 0.8;
}

.preview-hero__meta-item strong {
  font-size: 14px;
  font-weight: 600;
  color: #fff;
}

.preview-card {
  border-radius: 16px;
  border: 1px solid var(--preview-border);
  box-shadow: 0 8px 18px rgba(31, 42, 68, 0.06);
  background: var(--preview-card);
}

.preview-card .table-body {
  background: transparent;
}

.sale-preview .table-card + .table-card {
  margin-top: 16px;
}

.sale-preview .detail-summary {
  font-size: 12px;
  color: rgba(31, 42, 68, 0.72);
}

.sale-preview :deep(.el-input__wrapper),
.sale-preview :deep(.el-select__wrapper),
.sale-preview :deep(.el-textarea__inner) {
  border-radius: 10px;
}

.sale-preview :deep(.el-button--primary) {
  background: var(--preview-accent);
  border-color: var(--preview-accent);
}

.sale-preview :deep(.el-button--primary:hover) {
  background: var(--preview-accent-strong);
  border-color: var(--preview-accent-strong);
}

.sale-preview :deep(.el-button--success) {
  background: #45a08b;
  border-color: #45a08b;
}

.sale-preview :deep(.el-table) {
  border-radius: 12px;
  overflow: hidden;
}

.sale-preview :deep(.el-table th) {
  background: rgba(31, 42, 68, 0.04);
  color: var(--preview-ink);
}

.sale-preview :deep(.el-table td) {
  background: #fff;
}

.sale-form :deep(.el-form-item) {
  margin-bottom: 4px;
}

.sale-form--compact :deep(.el-form-item) {
  margin-bottom: 0;
}

.form-grid {
  display: flex;
  flex-wrap: nowrap;
  gap: 12px;
  overflow-x: auto;
  padding-bottom: 4px;
}

.compact-card .form-grid {
  padding-bottom: 0;
}

@media (max-width: 1200px) {
  .form-grid {
    gap: 4px;
  }
}

.form-group {
  min-width: 220px;
}

.compact-card .table-body {
  padding: 6px 12px;
}

.compact-card {
  flex: 0 0 auto;
}

.compact-card .table-body {
  flex: 0 0 auto;
  overflow: visible;
}

.sale-header-body {
  padding: 12px 16px;
}

.sale-detail-card {
  flex: 1 1 auto;
  min-height: 0;
}

.sale-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
  padding: 12px 16px;
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 8px;
}

.detail-table-wrapper {
  flex: 1 1 auto;
  min-height: 0;
  overflow: auto;
}

.detail-actions {
  display: flex;
  justify-content: flex-start;
}

.detail-summary {
  display: flex;
  gap: 16px;
  justify-content: flex-end;
  font-size: 13px;
  color: #606266;
}

.summary-item {
  white-space: nowrap;
}

.payment-card-body {
  padding: 12px 16px !important;
}

.payment-card .form-grid {
  align-items: center;
  flex-wrap: nowrap;
  gap: 8px;
}

.payment-card .form-group {
  min-width: 0;
  flex: 0 0 auto;
}

.payment-card .form-group--settlement {
  min-width: 180px;
}

.payment-card .form-group--amount,
.payment-card .form-group--discount {
  width: auto;
}

.payment-card :deep(.el-form-item) {
  display: flex;
  align-items: center;
}

.payment-card :deep(.el-form-item__label) {
  padding-bottom: 0;
  display: inline-flex;
  align-items: center;
  height: 32px;
  line-height: 32px;
  margin-right: 4px;
  width: auto !important;
  padding-right: 2px;
  flex: 0 0 auto;
}

.payment-card :deep(.el-form-item__content) {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  min-height: 32px;
}

.page-header + .table-card {
  margin-top: 12px;
}

.table-card + .table-card {
  margin-top: 12px;
}

.order-time-picker {
  width: 100%;
}

.order-time-picker :deep(.el-input__wrapper) {
  width: 100%;
  box-sizing: border-box;
}

.order-time-picker :deep(.el-input__inner) {
  width: 100%;
  padding-right: 48px;
}

.order-time-picker :deep(.el-input__suffix) {
  width: 44px;
  display: flex;
  justify-content: flex-end;
}

.table-card.compact-card--inline {
  flex: 0 0 auto !important;
  height: auto !important;
  min-height: 0 !important;
}

.table-card.compact-card--inline .compact-card-body {
  flex: 0 0 auto !important;
  height: auto !important;
  min-height: 0 !important;
  padding: 6px 12px !important;
  overflow: visible !important;
}

.sale-form--inline .form-grid {
  align-items: center;
}

.sale-form--inline :deep(.el-form-item__label) {
  line-height: 20px;
  padding-bottom: 2px;
}

.sale-form--inline :deep(.el-form-item__content) {
  line-height: 28px;
}
</style>
