<template>
  <div class="page-shell page-shell--system sale-theme" :class="{ 'sale-theme--paper': themeMode === 'paper' }">
    <div class="page-header sale-page-header">
      <div class="page-title">{{ pageTitle }}</div>
      <div class="page-toolbar-card sale-header-card">
        <div class="sale-header-stack">
          <div class="table-toolbar sale-page-toolbar">
            <div class="table-filters sale-page-toolbar__filters">
              <div v-if="!isReadOnly" class="theme-switch">
                <span class="theme-switch__label">{{ $t('field.theme') }}</span>
                <el-select v-model="themeMode" class="theme-switch__select">
                  <el-option :label="$t('theme.default')" value="default" />
                  <el-option :label="$t('theme.paper')" value="paper" />
                </el-select>
              </div>
            </div>
            <div class="table-actions sale-page-toolbar__actions">
              <el-button class="action-button" @click="handleBack">{{ $t('action.back') }}</el-button>
              <el-button
                v-if="canCopy"
                class="action-button"
                type="primary"
                @click="handleCopy"
              >
                {{ $t('action.copy') }}
              </el-button>
              <el-button
                v-if="canPrint"
                class="action-button"
                type="primary"
                @click="handlePrint"
              >
                {{ $t('action.print') }}
              </el-button>
              <el-button
                v-if="canRedFlush"
                type="danger"
                plain
                class="action-button action-button--danger"
                @click="handleRedFlush"
              >
                {{ $t('action.redFlush') }}
              </el-button>
              <el-button v-if="canApprove" type="success" plain class="action-button action-button--success" :loading="isSaving" :disabled="isSaving" @click="handleApprove">{{ $t('action.approve') }}</el-button>
              <el-button v-if="!isReadOnly" class="action-button" :loading="isSaving" :disabled="isSaving" @click="handleSave">{{ $t('action.save') }}</el-button>
              <el-button v-if="!isReadOnly" type="primary" class="action-button" :loading="isSaving" :disabled="isSaving" @click="handleSaveAndBack">{{ $t('action.saveAndBack') }}</el-button>
            </div>
          </div>

          <div class="sale-header-body">
            <el-form :model="formData" label-position="top" class="sale-form sale-form--compact">
              <div class="form-grid">
                <div class="form-group">
                  <el-form-item :label="$t('field.orderNo')">
                    <el-input v-model="formData.orderNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
                  </el-form-item>
                </div>
                <div class="form-group">
                  <el-form-item :label="$t('field.orderTime')">
                    <el-date-picker
                      v-model="formData.orderAt"
                      type="datetime"
                      format="YYYY-MM-DD HH:mm:ss"
                      value-format="YYYY-MM-DD HH:mm:ss"
                      class="order-time-picker"
                      style="width: 100%"
                      :clearable="false"
                      :disabled="isReadOnly"
                    />
                  </el-form-item>
                </div>
                <div class="form-group">
                  <el-form-item :label="$t('field.customer')" required>
                    <FuzzyProductSelect
                      v-model="formData.customerId"
                      :options="customerOptions"
                      :placeholder="$t('field.customer')"
                      style="width: 100%"
                      :disabled="isReadOnly"
                      @change="handleCustomerChange"
                    />
                  </el-form-item>
                </div>
                <div class="form-group">
                  <el-form-item :label="$t('field.deliveryMethod')">
                    <el-select v-model="formData.deliveryMethod" clearable style="width: 100%" :disabled="isReadOnly">
                      <el-option v-for="item in deliveryMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                    </el-select>
                  </el-form-item>
                </div>
              </div>

              <el-form-item :label="$t('field.remark')">
                <el-input v-model="formData.remark" type="textarea" :disabled="isReadOnly" />
              </el-form-item>
            </el-form>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card sale-detail-card">
      <div class="table-body sale-detail-body">
        <div class="detail-section">
          <div class="detail-header">
            <h4>{{ $t('field.items') }}</h4>
          </div>
          <div class="detail-table-wrapper">
            <el-table :data="formData.items" style="width: 100%" border stripe @row-click="handleRowClick" :header-cell-style="{ textAlign: 'center' }">
              <el-table-column label="" width="40" align="center">
                <template #default="{ $index }">
                  <el-button class="delete-icon-btn" type="danger" circle size="small" :disabled="isReadOnly" @click="removeItem($index)">
                    <el-icon><Close /></el-icon>
                  </el-button>
                </template>
              </el-table-column>
              <el-table-column type="index" :label="$t('table.index')" width="55" align="center" />
              <el-table-column :label="$t('field.product')" min-width="240">
                <template #default="{ row }">
                  <div class="product-cell">
                    <span v-if="isReadOnly" class="product-cell__label">{{ resolveProductLabel(row) }}</span>
                    <el-select
                      v-else
                      v-model="row.productId"
                      filterable
                      clearable
                      class="product-cell__select"
                      :placeholder="$t('placeholder.selectProduct')"
                      :disabled="!formData.customerId"
                      @change="handleProductChange(row)"
                    >
                      <el-option v-for="item in productOptions" :key="item.id" :label="item.name" :value="item.id" />
                    </el-select>
                    <el-tag
                      class="history-inline history-tag history-tag--inline"
                      size="small"
                      :type="row.productId ? 'primary' : 'info'"
                      :title="$t('action.detail')"
                      @click.stop="row.productId && openHistoryForRow(row)"
                    >
                      <el-icon class="history-icon"><View /></el-icon>
                    </el-tag>
                  </div>
                </template>
              </el-table-column>
              <el-table-column :label="$t('field.warehouseLocation')" min-width="220">
                <template #default="{ row }">
                  <span v-if="isReadOnly">
                    {{ resolveWarehouseLabel(row) }} / {{ resolveLocationLabel(row) }}
                  </span>
                  <el-select
                    v-else
                    v-model="row.stockKey"
                    filterable
                    clearable
                    style="width: 100%"
                    :placeholder="$t('placeholder.selectLocation')"
                    :disabled="!row.productId"
                    @change="handleStockLocationChange(row)"
                  >
                    <el-option
                      v-for="item in getStockOptionsForRow(row)"
                      :key="item.key"
                      :label="item.searchLabel"
                      :value="item.key"
                    >
                      <div class="stock-option">
                        <span class="stock-option__name">{{ item.label }}</span>
                        <span class="stock-option__qty">
                          {{ $t('field.qtyOnHand') }}: {{ item.qtyOnHand }}
                          · {{ $t('field.qtyAvailable') }}: {{ item.qtyAvailable }}
                          · {{ $t('field.qtyLocked') }}: {{ item.qtyLocked }}
                        </span>
                      </div>
                    </el-option>
                  </el-select>
                </template>
              </el-table-column>
            <el-table-column :label="$t('field.quantity')" width="140">
              <template #default="{ row }">
                <DecimalInput v-model="row.qty" :scale="4" :disabled="isReadOnly" />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.price')" width="140">
              <template #default="{ row }">
                <DecimalInput v-model="row.price" :scale="4" :disabled="isReadOnly" />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.lineTotal')" width="140">
              <template #default="{ row }">
                {{ formatMoney(calcLineAmount(row)) }}
              </template>
            </el-table-column>
            <el-table-column v-if="canShowDiscountAllocated" :label="$t('field.discountAllocated')" width="140">
              <template #default="{ row }">
                {{ formatMoney(calcLineDiscount(row)) }}
              </template>
            </el-table-column>
            <el-table-column v-if="canShowProfit" :label="$t('field.profit')" min-width="160">
              <template #default="{ row }">
                {{ formatProfitCell(row) }}
              </template>
            </el-table-column>

              <el-table-column :label="$t('field.remark')" min-width="160">
                <template #default="{ row }">
                  <el-input v-model="row.remark" :disabled="isReadOnly" />
                </template>
              </el-table-column>

          </el-table>
          </div>
          <div class="detail-actions">
            <el-button class="paper-add-item-button" type="primary" plain size="small" :disabled="isReadOnly" @click="addItem">
              + {{ $t('action.addItem') }}
            </el-button>
          </div>
          <div class="detail-summary">
            <div class="summary-item">{{ $t('field.totalAmount') }}: {{ formatMoney(totalSummary.amount) }}</div>
            <div class="summary-item" v-if="canShowProfit">{{ $t('field.totalProfit') }}: {{ totalProfitText }}</div>
            <div class="summary-item" v-if="canShowProfit">{{ $t('field.totalProfitRate') }}: {{ totalProfitRateText }}</div>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card compact-card compact-card--inline payment-card">
      <div class="table-body compact-card-body payment-card-body">
        <el-form :model="formData" label-position="left" label-width="70px" class="sale-form sale-form--compact sale-form--inline">
          <div class="form-grid">
            <div class="form-group form-group--settlement">
              <el-form-item :label="$t('field.settlementMethod')" required>
                <el-select v-model="formData.settlementMethod" style="width: 150px" :disabled="isReadOnly">
                  <el-option v-for="item in settlementMethodOptions" :key="item.code" :label="item.name" :value="item.code" />
                </el-select>
              </el-form-item>
            </div>
            <div v-if="formData.settlementMethod && !isCreditSettlement" class="form-group form-group--amount">
              <el-form-item :label="$t('field.paidAmount')">
                <DecimalInput v-model="formData.paidAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
            <div v-if="formData.settlementMethod" class="form-group form-group--discount">
              <el-form-item :label="$t('field.discountAmount')">
                <DecimalInput v-model="formData.discountAmount" :scale="2" :disabled="isReadOnly" style="width: 150px" />
              </el-form-item>
            </div>
          </div>
        </el-form>
      </div>
    </div>

      <el-dialog
        v-model="historyDialogVisible"
        :title="$t('action.productHistory')"
        width="980px"
        class="history-dialog"
      >
      <div class="history-header">
        <div class="history-header__item">
          <span>{{ $t('field.product') }}：</span>
          <strong>{{ historyProductName }}</strong>
        </div>
        <div class="history-header__hint">{{ $t('message.historyShortcutHint') }}</div>
      </div>
        <div v-loading="historyLoading" class="history-grid history-grid--tabs">
          <el-tabs v-model="historyTab" type="card" class="history-tabs" @tab-change="handleHistoryTabChange">
            <el-tab-pane :label="$t('field.customerCategoryPrice')" name="price">
              <el-table
                :data="priceHistoryItems"
                stripe
                :empty-text="$t('table.empty')"
                height="260"
              >
                <el-table-column prop="customerCategoryName" :label="$t('field.customerCategory')" min-width="160" />
                <el-table-column :label="$t('field.price')" width="120">
                  <template #default="{ row }">{{ formatMoney(row.salePrice) }}</template>
                </el-table-column>
                <el-table-column :label="$t('field.updatedTime')" width="150">
                  <template #default="{ row }">{{ formatHistoryDate(row.updatedAt) }}</template>
                </el-table-column>
              </el-table>
            </el-tab-pane>
            <el-tab-pane :label="$t('field.purchaseHistory')" name="purchase">
              <div class="history-toolbar">
                <el-input v-model="purchaseHistoryKeyword" :placeholder="$t('placeholder.keyword')" clearable class="history-search" />
                <el-date-picker
                v-model="purchaseHistoryRange"
                type="daterange"
                format="YYYY-MM-DD"
                value-format="YYYY-MM-DD"
                :range-separator="$t('separator.to')"
                :start-placeholder="$t('field.startTime')"
                :end-placeholder="$t('field.endTime')"
                class="history-date"
                clearable
              />
            </div>
              <el-table
                :data="purchaseHistoryItems"
                stripe
                :empty-text="$t('table.empty')"
                height="260"
              >
              <el-table-column prop="supplierName" :label="$t('field.supplierName')" min-width="160" />
              <el-table-column prop="qty" :label="$t('field.quantity')" width="90" />
              <el-table-column :label="$t('field.price')" width="110">
                <template #default="{ row }">{{ formatMoney(row.price) }}</template>
              </el-table-column>
              <el-table-column :label="$t('field.priceInclTax')" width="130">
                <template #default="{ row }">{{ formatMoney(row.priceInclTax) }}</template>
              </el-table-column>
                <el-table-column :label="$t('field.orderTime')" width="150">
                  <template #default="{ row }">{{ formatHistoryDate(row.orderAt) }}</template>
                </el-table-column>
                <el-table-column prop="orderNo" :label="$t('field.orderNo')" min-width="160">
                  <template #default="{ row }">
                    <el-button link type="primary" @click="openPurchaseOrderHistory(row)">{{ row.orderNo }}</el-button>
                  </template>
                </el-table-column>
              </el-table>
              <el-pagination
                class="history-pagination"
                background
                layout="total, sizes, prev, pager, next"
                :total="purchaseHistoryTotal"
                :current-page="purchaseHistoryPage"
                :page-size="purchaseHistorySize"
                :page-sizes="[5, 10, 20, 50]"
                @current-change="handlePurchaseHistoryPageChange"
                @size-change="handlePurchaseHistorySizeChange"
              />
            </el-tab-pane>
            <el-tab-pane :label="$t('field.saleHistory')" name="sale-all">
              <div class="history-toolbar">
                <el-input v-model="saleHistoryKeyword" :placeholder="$t('placeholder.keyword')" clearable class="history-search" />
                <el-date-picker
                v-model="saleHistoryRange"
                type="daterange"
                format="YYYY-MM-DD"
                value-format="YYYY-MM-DD"
                :range-separator="$t('separator.to')"
                :start-placeholder="$t('field.startTime')"
                :end-placeholder="$t('field.endTime')"
                class="history-date"
                clearable
              />
            </div>
              <el-table
                :data="saleHistoryItems"
                stripe
                :empty-text="$t('table.empty')"
                height="260"
              >
              <el-table-column prop="customerName" :label="$t('field.customerName')" min-width="160" />
              <el-table-column prop="qty" :label="$t('field.quantity')" width="90" />
              <el-table-column :label="$t('field.price')" width="110">
                <template #default="{ row }">{{ formatMoney(row.price) }}</template>
              </el-table-column>
              <el-table-column :label="$t('field.priceInclTax')" width="130">
                <template #default="{ row }">{{ formatMoney(row.priceInclTax) }}</template>
              </el-table-column>
                <el-table-column :label="$t('field.orderTime')" width="150">
                  <template #default="{ row }">{{ formatHistoryDate(row.orderAt) }}</template>
                </el-table-column>
                <el-table-column prop="orderNo" :label="$t('field.orderNo')" min-width="160">
                  <template #default="{ row }">
                    <el-button link type="primary" @click="openSaleOrderHistory(row)">{{ row.orderNo }}</el-button>
                  </template>
                </el-table-column>
              </el-table>
              <el-pagination
                class="history-pagination"
                background
                layout="total, sizes, prev, pager, next"
                :total="saleHistoryTotal"
                :current-page="saleHistoryPage"
                :page-size="saleHistorySize"
                :page-sizes="[5, 10, 20, 50]"
                @current-change="handleSaleHistoryPageChange"
                @size-change="handleSaleHistorySizeChange"
              />
            </el-tab-pane>
            <el-tab-pane :label="$t('field.customerSaleHistory')" name="sale-customer">
              <div class="history-toolbar">
                <el-input v-model="customerSaleHistoryKeyword" :placeholder="$t('placeholder.keyword')" clearable class="history-search" />
                <el-date-picker
                v-model="customerSaleHistoryRange"
                type="daterange"
                format="YYYY-MM-DD"
                value-format="YYYY-MM-DD"
                :range-separator="$t('separator.to')"
                :start-placeholder="$t('field.startTime')"
                :end-placeholder="$t('field.endTime')"
                class="history-date"
                clearable
              />
            </div>
              <el-table
                :data="customerSaleHistoryItems"
                stripe
                :empty-text="$t('table.empty')"
                height="260"
              >
              <el-table-column prop="customerName" :label="$t('field.customerName')" min-width="160" />
              <el-table-column prop="qty" :label="$t('field.quantity')" width="90" />
              <el-table-column :label="$t('field.price')" width="110">
                <template #default="{ row }">{{ formatMoney(row.price) }}</template>
              </el-table-column>
              <el-table-column :label="$t('field.priceInclTax')" width="130">
                <template #default="{ row }">{{ formatMoney(row.priceInclTax) }}</template>
              </el-table-column>
                <el-table-column :label="$t('field.orderTime')" width="150">
                  <template #default="{ row }">{{ formatHistoryDate(row.orderAt) }}</template>
                </el-table-column>
                <el-table-column prop="orderNo" :label="$t('field.orderNo')" min-width="160">
                  <template #default="{ row }">
                    <el-button link type="primary" @click="openSaleOrderHistory(row)">{{ row.orderNo }}</el-button>
                  </template>
                </el-table-column>
              </el-table>
              <el-pagination
                class="history-pagination"
                background
                layout="total, sizes, prev, pager, next"
                :total="customerSaleHistoryTotal"
                :current-page="customerSaleHistoryPage"
                :page-size="customerSaleHistorySize"
                :page-sizes="[5, 10, 20, 50]"
                @current-change="handleCustomerSaleHistoryPageChange"
                @size-change="handleCustomerSaleHistorySizeChange"
              />
            </el-tab-pane>
          </el-tabs>
        </div>
      </el-dialog>

      <el-dialog
        v-model="historyOrderDialogVisible"
        :title="historyOrderDialogTitle"
        width="92vw"
        class="history-order-dialog"
        append-to-body
      >
        <iframe v-if="historyOrderDialogUrl" :src="historyOrderDialogUrl" class="history-order-frame" />
      </el-dialog>

    <el-dialog
      v-model="showCustomerChangeDialog"
      :title="$t('message.confirmCustomerChangeTitle')"
      width="420px"
      :close-on-click-modal="false"
      :close-on-press-escape="false"
    >
      <div>{{ $t('message.confirmCustomerChange') }}</div>
      <template #footer>
        <el-button @click="applyCustomerChange('cancel')">{{ $t('action.cancel') }}</el-button>
        <el-button @click="applyCustomerChange('clear')">{{ $t('action.clearItems') }}</el-button>
        <el-button type="primary" @click="applyCustomerChange('price')">{{ $t('action.updatePrice') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog
      v-model="saveErrorDialogVisible"
      :title="$t('message.saveFailed')"
      width="420px"
      append-to-body
    >
      <div class="save-error-dialog__content">{{ saveErrorMessage }}</div>
      <template #footer>
        <el-button type="primary" @click="saveErrorDialogVisible = false">{{ $t('action.confirm') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog
      v-model="saveSuccessDialogVisible"
      :title="$t('message.saveSuccess')"
      width="460px"
      append-to-body
      :close-on-click-modal="false"
      :close-on-press-escape="false"
      :show-close="false"
    >
      <div class="save-success-dialog__content">
        <div class="save-success-dialog__message">{{ $t('message.saveSuccessNextStep') }}</div>
        <div v-if="saveSuccessOrderNo" class="save-success-dialog__order-no">
          {{ $t('message.saveSuccessOrderNo', { orderNo: saveSuccessOrderNo }) }}
        </div>
      </div>
      <template #footer>
        <el-button @click="handleContinueCreate">{{ $t('action.continueCreate') }}</el-button>
        <el-button @click="handleStayOnCurrentOrder">{{ $t('action.stayCurrent') }}</el-button>
        <el-button v-if="canApproveSavedOrder" type="primary" @click="handleApproveSavedOrder">{{ $t('action.approve') }}</el-button>
      </template>
    </el-dialog>

    <PrintPreviewDialog
      v-model="printDialogVisible"
      doc-type="SALE_ORDER"
      :doc-id="printDocId"
      :title="$t('page.erpSaleOrderPrint')"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, onActivated, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import PrintPreviewDialog from '@/components/PrintPreviewDialog.vue';
import { ElMessageBox } from 'element-plus';
import { Close, View } from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';

interface OptionItem {
  id: number;
  name: string;
  warehouseId?: number;
  categoryId?: number;
  paymentTerms?: string;
  deliveryMethodCode?: string;
}

interface ProductOption {
  id: number;
  name: string;
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  salePrice?: number;
  costPrice?: number;
}

interface StockOption {
  key: string;
  warehouseId: number | null;
  warehouseName: string;
  locationId: number | null;
  locationName: string;
  qtyOnHand: number;
  qtyAvailable: number;
  qtyLocked: number;
  label: string;
  searchLabel: string;
}

interface CodeOptionItem {
  id: number;
  code: string;
  name: string;
  isDefault?: boolean;
}

interface SaleHistoryItem {
  orderId: number;
  orderNo: string;
  orderAt: string;
  productId: number;
  qty: number;
  price: number;
  priceInclTax: number;
  customerId: number;
  customerName: string;
}

interface PurchaseHistoryItem {
  orderId: number;
  orderNo: string;
  orderAt: string;
  productId: number;
  qty: number;
  price: number;
  priceInclTax: number;
  supplierId: number;
  supplierName: string;
}

interface SaleOrderItem {
  id?: number;
  productId?: number;
  productName?: string;
  warehouseId?: number;
  locationId?: number;
  stockKey?: string;
  qty?: string | number;
  price?: string | number;
  taxRate?: number;
  remark?: string;
  sortNo?: number;
}

const { t } = useI18n();
const router = useRouter();
const route = useRoute();
const isSaleOrderRoute = () => route.path.startsWith('/erp/sale-orders');
const { notifyError, notifySuccess, notifyWarning } = useApiError();
const authStore = useAuthStore();
const isSaving = ref(false);

const isEditing = computed(() => Boolean(route.params.id));
const isReadOnly = computed(() => {
  if (route.query.mode === 'view') return true;
  if (!formData.status) return false;
  return formData.status !== 'DRAFT';
});

const canCopy = computed(() => {
  return isReadOnly.value
    && (formData.status === 'APPROVED' || formData.status === 'RED_FLUSHED')
    && hasPermission('erp-sale:add');
});

const canPrint = computed(() => {
  return isEditing.value && hasPermission('erp-sale:view');
});

const canRedFlush = computed(() => {
  return isReadOnly.value && formData.status === 'APPROVED' && hasPermission('erp-sale:redflush');
});

const pageTitle = computed(() => (isEditing.value ? t('page.erpSaleOrderEdit') : t('page.erpSaleOrderCreate')));
const themeMode = ref<'default' | 'paper'>('default');

const customerOptions = ref<OptionItem[]>([]);
const productOptions = ref<ProductOption[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);
const settlementMethodOptions = ref<CodeOptionItem[]>([]);
const deliveryMethodOptions = ref<CodeOptionItem[]>([]);
const productStockMap = ref<Record<number, StockOption[]>>({});

const formData = reactive({
  orderNo: '',
  orderAt: '',
  status: '',
  customerId: null as number | null,
  settlementMethod: '',
  deliveryMethod: '',
  paidAmount: '',
  discountAmount: '',
  remark: '',
  items: [] as SaleOrderItem[]
});

const pagePath = ref(route.path);
const lastRouteKey = ref(route.fullPath);
let loadDetailSeq = 0;
const showCustomerChangeDialog = ref(false);
const pendingCustomerId = ref<number | null>(null);
const lastCustomerId = ref<number | null>(null);
const isInitializing = ref(false);
const needsReload = ref(false);
const showProfitColumn = ref(false);
const printDialogVisible = ref(false);
const printDocId = ref<number | null>(null);
const saveErrorDialogVisible = ref(false);
const saveErrorMessage = ref('');
const saveSuccessDialogVisible = ref(false);
const saveSuccessOrderId = ref<number | null>(null);
const saveSuccessOrderNo = ref('');
const historyDialogVisible = ref(false);
const historyLoading = ref(false);
const historyProduct = ref<ProductOption | null>(null);
const historyTab = ref<'price' | 'purchase' | 'sale-all' | 'sale-customer'>('purchase');
const saleHistoryItems = ref<SaleHistoryItem[]>([]);
const customerSaleHistoryItems = ref<SaleHistoryItem[]>([]);
const purchaseHistoryItems = ref<PurchaseHistoryItem[]>([]);
const priceHistoryItems = ref<any[]>([]);
const purchaseHistoryKeyword = ref('');
const saleHistoryKeyword = ref('');
const customerSaleHistoryKeyword = ref('');
const purchaseHistoryRange = ref<string[]>([]);
const saleHistoryRange = ref<string[]>([]);
const customerSaleHistoryRange = ref<string[]>([]);
const purchaseHistoryPage = ref(1);
const purchaseHistorySize = ref(10);
const purchaseHistoryTotal = ref(0);
const saleHistoryPage = ref(1);
const saleHistorySize = ref(10);
const saleHistoryTotal = ref(0);
const customerSaleHistoryPage = ref(1);
const customerSaleHistorySize = ref(10);
const customerSaleHistoryTotal = ref(0);
const historyOrderDialogVisible = ref(false);
const historyOrderDialogTitle = ref('');
const historyOrderDialogUrl = ref('');
const activeRowIndex = ref<number | null>(null);
const customerCategoryOptions = ref<OptionItem[]>([]);

const hasPermission = (code: string) => {
  return authStore.hasPermission(code) || authStore.hasPermission(`PERM_${code}`);
};

const canApprove = computed(() => {
  return !isReadOnly.value && formData.status === 'DRAFT' && hasPermission('erp-sale:approve');
});

const canApproveSavedOrder = computed(() => {
  return Boolean(saveSuccessOrderId.value) && hasPermission('erp-sale:approve');
});

const canViewProfit = computed(() => {
  return hasPermission('column:erp-sale:profit')
    && (hasPermission('erp-product:cost:view') || hasPermission('erp-product:cost:edit'));
});

const canShowProfit = computed(() => canViewProfit.value && showProfitColumn.value);
const canShowDiscountAllocated = computed(() => hasPermission('column:erp-sale:discountAllocated'));
const isCreditSettlement = computed(() => {
  if (!formData.settlementMethod) return false;
  const code = String(formData.settlementMethod).toUpperCase();
  if (code === 'CREDIT' || code === 'ON_ACCOUNT' || code === 'AR') return true;
  const selected = settlementMethodOptions.value.find(item => item.code === formData.settlementMethod);
  if (!selected || !selected.name) return false;
  return String(selected.name).includes('挂账');
});

const isTypingTarget = (target: EventTarget | null) => {
  if (!target || !(target instanceof HTMLElement)) return false;
  const tag = target.tagName.toLowerCase();
  if (tag === 'input' || tag === 'textarea' || tag === 'select') return true;
  return target.isContentEditable;
};

const handleKeydown = (event: KeyboardEvent) => {
  if (isTypingTarget(event.target)) return;
  if (event.key && event.key.toLowerCase() === 'h' && (event.ctrlKey || event.metaKey)) {
    event.preventDefault();
    if (activeRowIndex.value == null) return;
    const row = formData.items[activeRowIndex.value];
    if (row) {
      openHistoryForRow(row);
    }
    return;
  }
  if (!canViewProfit.value) return;
  if (event.key && event.key.toLowerCase() === 'u') {
    showProfitColumn.value = !showProfitColumn.value;
  }
};

const historyProductName = computed(() => {
  if (historyProduct.value?.name) return historyProduct.value.name;
  return '-';
});

const historyCustomerName = computed(() => {
  if (!formData.customerId) return '';
  return customerOptions.value.find(item => item.id === formData.customerId)?.name || '';
});

const customerCategoryNameMap = computed(() => {
  const map = new Map<number, string>();
  for (const item of customerCategoryOptions.value) {
    if (item.id != null) {
      map.set(item.id, item.name);
    }
  }
  return map;
});

const formatHistoryDate = (value: any) => {
  return normalizeDateTimeValue(value);
};

const normalizeHistoryKeyword = (value: string) => value.trim();

const normalizeArray = <T>(value: any): T[] => {
  if (Array.isArray(value)) return value as T[];
  if (Array.isArray(value?.items)) return value.items as T[];
  if (Array.isArray(value?.list)) return value.list as T[];
  return [];
};

const resolveHistoryRange = (range: string[]) => {
  if (!range || range.length < 2) return null;
  const [start, end] = range;
  if (!start || !end) return null;
  const startDate = new Date(`${start}T00:00:00`);
  const endDate = new Date(`${end}T23:59:59.999`);
  if (Number.isNaN(startDate.getTime()) || Number.isNaN(endDate.getTime())) return null;
  return {
    startAt: startDate.toISOString(),
    endAt: endDate.toISOString()
  };
};

const buildHistoryParams = (range: string[], keyword: string, page: number, size: number) => {
  const productId = historyProduct.value?.id;
  if (!productId) return null;
  const params: Record<string, any> = { productId, page, size };
  const normalized = normalizeHistoryKeyword(keyword);
  if (normalized) params.keyword = normalized;
  const resolved = resolveHistoryRange(range);
  if (resolved) {
    params.startAt = resolved.startAt;
    params.endAt = resolved.endAt;
  }
  return params;
};

let historyLoadingCount = 0;
const withHistoryLoading = async (task: () => Promise<void>) => {
  historyLoadingCount += 1;
  historyLoading.value = true;
  try {
    await task();
  } finally {
    historyLoadingCount -= 1;
    if (historyLoadingCount <= 0) {
      historyLoading.value = false;
      historyLoadingCount = 0;
    }
  }
};

const fetchPurchaseHistory = async (page = purchaseHistoryPage.value) => {
  const params = buildHistoryParams(purchaseHistoryRange.value, purchaseHistoryKeyword.value, page, purchaseHistorySize.value);
  if (!params) {
    purchaseHistoryItems.value = [];
    purchaseHistoryTotal.value = 0;
    return;
  }
  await withHistoryLoading(async () => {
    try {
      const res: any = await request.get('/erp/purchase-orders/product-history', { params });
      const data = res?.data?.data || {};
      purchaseHistoryItems.value = normalizeArray<PurchaseHistoryItem>(data);
      purchaseHistoryTotal.value = data.total || 0;
      purchaseHistoryPage.value = data.page || page;
      purchaseHistorySize.value = data.size || purchaseHistorySize.value;
    } catch (error) {
      purchaseHistoryItems.value = [];
      purchaseHistoryTotal.value = 0;
      notifyError(error);
    }
  });
};

const fetchSaleHistory = async (page = saleHistoryPage.value) => {
  const params = buildHistoryParams(saleHistoryRange.value, saleHistoryKeyword.value, page, saleHistorySize.value);
  if (!params) {
    saleHistoryItems.value = [];
    saleHistoryTotal.value = 0;
    return;
  }
  await withHistoryLoading(async () => {
    try {
      const res: any = await request.get('/erp/sale-orders/product-history', { params });
      const data = res?.data?.data || {};
      saleHistoryItems.value = normalizeArray<SaleHistoryItem>(data);
      saleHistoryTotal.value = data.total || 0;
      saleHistoryPage.value = data.page || page;
      saleHistorySize.value = data.size || saleHistorySize.value;
    } catch (error) {
      saleHistoryItems.value = [];
      saleHistoryTotal.value = 0;
      notifyError(error);
    }
  });
};

const fetchCustomerSaleHistory = async (page = customerSaleHistoryPage.value) => {
  const baseParams = buildHistoryParams(
    customerSaleHistoryRange.value,
    customerSaleHistoryKeyword.value,
    page,
    customerSaleHistorySize.value
  );
  if (!baseParams || !formData.customerId) {
    customerSaleHistoryItems.value = [];
    customerSaleHistoryTotal.value = 0;
    return;
  }
  const params = { ...baseParams, customerId: formData.customerId };
  await withHistoryLoading(async () => {
    try {
      const res: any = await request.get('/erp/sale-orders/product-history', { params });
      const data = res?.data?.data || {};
      customerSaleHistoryItems.value = normalizeArray<SaleHistoryItem>(data);
      customerSaleHistoryTotal.value = data.total || 0;
      customerSaleHistoryPage.value = data.page || page;
      customerSaleHistorySize.value = data.size || customerSaleHistorySize.value;
    } catch (error) {
      customerSaleHistoryItems.value = [];
      customerSaleHistoryTotal.value = 0;
      notifyError(error);
    }
  });
};

const fetchProductPrices = async () => {
  const productId = historyProduct.value?.id;
  if (!productId) {
    priceHistoryItems.value = [];
    return;
  }
  try {
    const res: any = await request.get('/erp/product-prices', { params: { productId } });
    const items = normalizeArray<any>(res?.data?.data);
    priceHistoryItems.value = items.map((item: any) => ({
      ...item,
      customerCategoryName: customerCategoryNameMap.value.get(item.customerCategoryId) || '-'
    }));
  } catch (error) {
    notifyError(error);
  }
};

const handleHistoryTabChange = (tabName: string | number) => {
  historyTab.value = String(tabName) as typeof historyTab.value;
  if (historyTab.value === 'price') {
    fetchProductPrices();
  } else if (historyTab.value === 'purchase') {
    fetchPurchaseHistory(purchaseHistoryPage.value);
  } else if (historyTab.value === 'sale-all') {
    fetchSaleHistory(saleHistoryPage.value);
  } else if (historyTab.value === 'sale-customer') {
    fetchCustomerSaleHistory(customerSaleHistoryPage.value);
  }
};

const handlePurchaseHistoryPageChange = (page: number) => {
  purchaseHistoryPage.value = page;
  fetchPurchaseHistory(page);
};

const handlePurchaseHistorySizeChange = (size: number) => {
  purchaseHistorySize.value = size;
  purchaseHistoryPage.value = 1;
  fetchPurchaseHistory(1);
};

const handleSaleHistoryPageChange = (page: number) => {
  saleHistoryPage.value = page;
  fetchSaleHistory(page);
};

const handleSaleHistorySizeChange = (size: number) => {
  saleHistorySize.value = size;
  saleHistoryPage.value = 1;
  fetchSaleHistory(1);
};

const handleCustomerSaleHistoryPageChange = (page: number) => {
  customerSaleHistoryPage.value = page;
  fetchCustomerSaleHistory(page);
};

const handleCustomerSaleHistorySizeChange = (size: number) => {
  customerSaleHistorySize.value = size;
  customerSaleHistoryPage.value = 1;
  fetchCustomerSaleHistory(1);
};

const openSaleOrderHistory = (row: SaleHistoryItem) => {
  if (!row?.orderId) return;
  const resolved = router.resolve({ path: `/erp/sale-orders/${row.orderId}/edit`, query: { mode: 'view', embed: '1' } });
  historyOrderDialogTitle.value = `${t('page.erpSaleOrder')} · ${row.orderNo}`;
  historyOrderDialogUrl.value = resolved.href;
  historyOrderDialogVisible.value = true;
};

const openPurchaseOrderHistory = (row: PurchaseHistoryItem) => {
  if (!row?.orderId) return;
  const resolved = router.resolve({ path: `/erp/purchase-orders/${row.orderId}/edit`, query: { mode: 'view', embed: '1' } });
  historyOrderDialogTitle.value = `${t('page.erpPurchaseOrder')} · ${row.orderNo}`;
  historyOrderDialogUrl.value = resolved.href;
  historyOrderDialogVisible.value = true;
};

watch([purchaseHistoryKeyword, purchaseHistoryRange], () => {
  purchaseHistoryPage.value = 1;
  if (historyDialogVisible.value) {
    fetchPurchaseHistory(1);
  }
}, { deep: true });

watch([saleHistoryKeyword, saleHistoryRange], () => {
  saleHistoryPage.value = 1;
  if (historyDialogVisible.value) {
    fetchSaleHistory(1);
  }
}, { deep: true });

watch([customerSaleHistoryKeyword, customerSaleHistoryRange], () => {
  customerSaleHistoryPage.value = 1;
  if (historyDialogVisible.value) {
    fetchCustomerSaleHistory(1);
  }
}, { deep: true });

watch(() => formData.customerId, () => {
  customerSaleHistoryPage.value = 1;
  if (historyDialogVisible.value && historyTab.value === 'sale-customer') {
    fetchCustomerSaleHistory(1);
  }
});

const closePage = () => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('tags:close', { detail: { path: route.path } }));
  }
};

const handleBack = async () => {
  if (isEditing.value) {
    resetForm();
    closePage();
    return;
  }

  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    try {
      await ElMessageBox.confirm(
        t('message.confirmSaveDraft'),
        t('action.confirm'),
        {
          confirmButtonText: t('action.save'),
          cancelButtonText: t('action.cancel'),
          type: 'warning'
        }
      );
      await saveData();
    } catch {
      resetForm();
      closePage();
    }
    return;
  }

  try {
    await ElMessageBox.confirm(
      t('message.confirmClosePage'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    resetForm();
    closePage();
  } catch {
    return;
  }
};

const handleApprove = async () => {
  if (isSaving.value) return;
  if (isReadOnly.value) return;
  try {
    await ElMessageBox.confirm(
      t('message.confirmSaveBeforeApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.save'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }

  const savedId = await saveData({ closeOnSuccess: false, reloadAfterCreate: true });
  if (!savedId) return;

  try {
    await ElMessageBox.confirm(
      t('message.confirmApprove'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.approve'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
    await request.post(`/erp/sale-orders/${savedId}/approve`);
    formData.status = 'APPROVED';
    notifySuccess();
    closePage();
    await router.push('/erp/sale-orders/draft');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handlePrint = () => {
  if (!isEditing.value) return;
  const id = route.params.id;
  if (!id) return;
  printDocId.value = Number(id);
  printDialogVisible.value = true;
};

const handleRedFlush = async () => {
  if (!isEditing.value) return;
  try {
    const { value } = await ElMessageBox.prompt(
      t('message.confirmRedFlush'),
      t('action.redFlush'),
      {
        inputPlaceholder: t('placeholder.required'),
        confirmButtonText: t('action.confirm'),
        cancelButtonText: t('action.cancel')
      }
    );
    if (!value || !String(value).trim()) {
      return;
    }
    await request.post(`/erp/sale-orders/${route.params.id}/red-flush`, { reason: String(value).trim() });
    notifySuccess();
    closePage();
    await router.push('/erp/sale-orders/approved');
  } catch (error) {
    if (error && error !== 'cancel' && error !== 'close') {
      notifyError(error);
    }
  }
};

const handleSave = async () => {
  if (isSaving.value) return;
  await saveData({ closeOnSuccess: false, showPostSaveDialog: !isEditing.value });
};

  const handleSaveAndBack = async () => {
    if (isSaving.value) return;
    await saveData({ closeOnSuccess: true });
  };

const resolveSaveErrorMessage = (error: unknown) => {
  const payload = (error as any)?.response?.data;
  if (typeof payload?.message === 'string' && payload.message.trim()) {
    return payload.message.trim();
  }
  if (typeof payload?.errorMessage === 'string' && payload.errorMessage.trim()) {
    return payload.errorMessage.trim();
  }
  if (error instanceof Error && error.message.trim()) {
    return error.message.trim();
  }
  return t('message.networkError');
};

const showSaveErrorDialog = async (error: unknown) => {
  saveErrorMessage.value = resolveSaveErrorMessage(error);
  saveErrorDialogVisible.value = true;
};

const openSaveSuccessDialog = (savedId: number | null, savedOrderNo?: string) => {
  saveSuccessOrderId.value = savedId;
  saveSuccessOrderNo.value = savedOrderNo || formData.orderNo || '';
  saveSuccessDialogVisible.value = true;
};

const closeSaveSuccessDialog = () => {
  saveSuccessDialogVisible.value = false;
  saveSuccessOrderId.value = null;
  saveSuccessOrderNo.value = '';
};

const handleContinueCreate = async () => {
  closeSaveSuccessDialog();
  await loadDetail();
};

const handleStayOnCurrentOrder = async () => {
  const savedId = saveSuccessOrderId.value;
  closeSaveSuccessDialog();
  if (!savedId) return;
  await router.replace(`/erp/sale-orders/${savedId}/edit`);
};

const handleApproveSavedOrder = async () => {
  const savedId = saveSuccessOrderId.value;
  if (!savedId) return;
  try {
    await request.post(`/erp/sale-orders/${savedId}/approve`);
    closeSaveSuccessDialog();
    notifySuccess();
    await router.replace(`/erp/sale-orders/${savedId}/edit`);
  } catch (error) {
    notifyError(error);
  }
};

  const parseStockKey = (stockKey?: string) => {
    if (!stockKey) return { warehouseId: undefined, locationId: undefined };
    const [warehouseRaw, locationRaw] = stockKey.split(':');
    const warehouseId = Number(warehouseRaw);
    const locationId = Number(locationRaw);
    return {
      warehouseId: Number.isNaN(warehouseId) || warehouseId === 0 ? undefined : warehouseId,
      locationId: Number.isNaN(locationId) || locationId === 0 ? undefined : locationId
    };
  };

  const resolveOptionName = (list: OptionItem[], id?: number) => {
    if (!id) return '-';
    return list.find(item => item.id === id)?.name || '-';
  };

  const resolveProductLabel = (row: SaleOrderItem) => {
    return row.productName || resolveOptionName(productOptions.value, row.productId);
  };

  const resolveWarehouseLabel = (row: SaleOrderItem) => {
    return resolveOptionName(warehouseOptions.value, row.warehouseId);
  };

  const resolveLocationLabel = (row: SaleOrderItem) => {
    if (row.locationId) {
      return resolveOptionName(locationOptions.value, row.locationId);
    }
    if (row.stockKey) {
      const { locationId } = parseStockKey(row.stockKey);
      return resolveOptionName(locationOptions.value, locationId);
    }
    return '-';
  };

  const ensureStockBinding = (row: SaleOrderItem) => {
    if (!row.stockKey || !row.productId) return;
    const options = productStockMap.value[row.productId] || [];
    const selected = options.find(item => item.key === row.stockKey);
    if (selected) {
      row.warehouseId = selected.warehouseId ?? undefined;
      row.locationId = selected.locationId ?? undefined;
      return;
    }
    const parsed = parseStockKey(row.stockKey);
    if (row.warehouseId == null) {
      row.warehouseId = parsed.warehouseId;
    }
    if (row.locationId == null) {
      row.locationId = parsed.locationId;
    }
  };

  const handleCopy = async () => {
    if (!formData.customerId || !formData.items.length) {
      notifyWarning(t('message.noItems'));
      return;
    }
  try {
    await ElMessageBox.confirm(
      t('message.confirmCopyOrder'),
      t('action.confirm'),
      {
        confirmButtonText: t('action.copy'),
        cancelButtonText: t('action.cancel'),
        type: 'warning'
      }
    );
  } catch {
    return;
  }
    try {
      const orderNoRes: any = await request.get('/erp/sale-orders/next-order-no');
      const orderNo = orderNoRes.data?.data || '';
      const items = formData.items
        .filter(item => item.productId)
        .map((item, index) => {
          ensureStockBinding(item);
          return {
            productId: item.productId,
            warehouseId: item.warehouseId,
            locationId: item.locationId,
            qty: parseDecimal(item.qty, 4),
            price: parseDecimal(item.price, 4),
            taxRate: item.taxRate,
            remark: item.remark,
            sortNo: index + 1
          };
        });
    const payload = {
      orderNo,
      orderAt: formatDateTime(new Date()),
      customerId: formData.customerId,
      settlementMethod: formData.settlementMethod,
      deliveryMethod: formData.deliveryMethod || undefined,
      paidAmount: parseAmount(formData.paidAmount),
      discountAmount: parseAmount(formData.discountAmount),
      remark: formData.remark,
      items
    };
    const res: any = await request.post('/erp/sale-orders', payload);
    if (res.data.code === 200) {
      const data = res.data.data || {};
      const newId = data.order?.id || data.id;
      notifySuccess();
      if (newId) {
        await router.push({ path: `/erp/sale-orders/${newId}/edit`, query: { from: 'draft' } });
      }
    }
  } catch (error) {
    notifyError(error);
  }
};

const getLocationOptions = (warehouseId?: number) => {
  if (!warehouseId) return locationOptions.value;
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const buildStockKey = (warehouseId: number | null | undefined, locationId: number | null | undefined) => {
  const w = warehouseId == null ? 0 : warehouseId;
  const l = locationId == null ? 0 : locationId;
  return `${w}:${l}`;
};

const buildStockOptionLabel = (option: StockOption) => {
  return `${option.warehouseName} / ${option.locationName}`;
};

const normalizeStockOption = (option: any): StockOption => {
  const warehouseId = option.warehouseId ?? null;
  const locationId = option.locationId ?? null;
  const warehouseName = option.warehouseName || '-';
  const locationName = option.locationName || t('field.unassignedLocation');
  const qtyOnHand = Number(option.qtyOnHand ?? 0);
  const qtyAvailable = Number(option.qtyAvailable ?? qtyOnHand);
  const qtyLocked = Number(option.qtyLocked ?? 0);
  const baseLabel = `${warehouseName} / ${locationName}`;
  return {
    key: buildStockKey(warehouseId, locationId),
    warehouseId,
    locationId,
    warehouseName,
    locationName,
    qtyOnHand,
    qtyAvailable,
    qtyLocked,
    label: baseLabel,
    searchLabel: `${baseLabel} ${qtyOnHand} ${qtyAvailable} ${qtyLocked}`
  };
};

const fetchStockOptions = async (productId?: number, force = false) => {
  if (!productId) return;
  if (!force && productStockMap.value[productId]) return;
  try {
    const res: any = await request.get('/erp/stock/balances/by-product', { params: { productId } });
    const data = res.data.data || [];
    productStockMap.value[productId] = data.map(normalizeStockOption);
  } catch (error) {
    notifyError(error);
  }
};

const buildLocationOnlyOptions = (warehouseId: number): StockOption[] => {
  const warehouse = warehouseOptions.value.find(item => item.id === warehouseId);
  const warehouseName = warehouse?.name || '-';
  const locations = locationOptions.value.filter(item => item.warehouseId === warehouseId);
  return locations.map(location => {
    const baseLabel = `${warehouseName} / ${location.name}`;
    return {
      key: buildStockKey(warehouseId, location.id),
      warehouseId,
      locationId: location.id,
      warehouseName,
      locationName: location.name,
      qtyOnHand: 0,
      qtyAvailable: 0,
      qtyLocked: 0,
      label: baseLabel,
      searchLabel: `${baseLabel} 0 0 0`
    };
  });
};

const getStockOptionsForRow = (row: SaleOrderItem) => {
  if (!row.productId) return [];
  const allOptions = productStockMap.value[row.productId] || [];
  let options = [...allOptions];
  if (!row.warehouseId && !row.locationId) return options;
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
  if (options.some(item => item.key === key)) {
    return options;
  }
  const fallback = buildFallbackStockOption(row.warehouseId, row.locationId);
  if (fallback) {
    options.unshift(fallback);
  }
  return options;
};

const syncStockKey = (row: SaleOrderItem) => {
  if (!row.productId) {
    row.stockKey = '';
    return;
  }
  const options = productStockMap.value[row.productId] || [];
  const key = buildStockKey(row.warehouseId ?? null, row.locationId ?? null);
  const matched = options.find(item => item.key === key);
  row.stockKey = matched ? key : (row.warehouseId || row.locationId ? key : '');
};

const buildFallbackStockOption = (warehouseId?: number, locationId?: number): StockOption | null => {
  if (!warehouseId && !locationId) return null;
  const warehouse = warehouseOptions.value.find(item => item.id === warehouseId);
  const location = locationOptions.value.find(item => item.id === locationId);
  const warehouseName = warehouse?.name || '-';
  const locationName = location?.name || t('field.unassignedLocation');
  return {
    key: buildStockKey(warehouseId ?? null, locationId ?? null),
    warehouseId: warehouseId ?? null,
    locationId: locationId ?? null,
    warehouseName,
    locationName,
    qtyOnHand: 0,
    qtyAvailable: 0,
    qtyLocked: 0,
    label: `${warehouseName} / ${locationName}`,
    searchLabel: `${warehouseName} / ${locationName}`
  };
};

const applyProductDefaults = (row: SaleOrderItem, force = true) => {
  if (!row.productId) return;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product) return;
  if (product.defaultWarehouseId && (force || !row.warehouseId)) {
    row.warehouseId = product.defaultWarehouseId;
  }
  if (product.defaultLocationId && (force || !row.locationId)) {
    row.locationId = product.defaultLocationId;
  }
  if (row.locationId && row.warehouseId) {
    const location = locationOptions.value.find(item => item.id === row.locationId);
    if (location && location.warehouseId && location.warehouseId !== row.warehouseId) {
      row.locationId = undefined;
    }
  }
};

const getCurrentCustomerCategoryId = () => {
  if (!formData.customerId) return undefined;
  return customerOptions.value.find(item => item.id === formData.customerId)?.categoryId;
};

const fetchLastSalePrice = async (row: SaleOrderItem) => {
  if (!row.productId || !formData.customerId) return null;
  try {
    const res: any = await request.get('/erp/sale-orders/recent-items', {
      params: { customerId: formData.customerId, productId: row.productId, limit: 1 }
    });
    const items = normalizeArray<any>(res?.data?.data);
    if (!items.length) return null;
    const latest = items[0];
    if (latest?.price == null || latest?.price === '') return null;
    return Number(latest.price);
  } catch (error) {
    notifyError(error);
    return null;
  }
};

const applyPriceForRow = async (row: SaleOrderItem, force = false) => {
  if (!row.productId) return;
  if (!force && row.price) return;
  const lastPrice = await fetchLastSalePrice(row);
  if (lastPrice != null) {
    row.price = String(lastPrice);
    return;
  }
  const categoryId = getCurrentCustomerCategoryId();
  if (categoryId) {
    try {
      const res: any = await request.get('/erp/product-prices/resolve', {
        params: { productId: row.productId, customerCategoryId: categoryId }
      });
      const resolved = res.data.data?.salePrice;
      if (resolved != null && resolved !== '') {
        row.price = String(resolved);
        return;
      }
    } catch (error) {
      notifyError(error);
    }
  }
  const product = productOptions.value.find(item => item.id === row.productId);
  if (product && product.salePrice != null) {
    row.price = String(product.salePrice);
  }
};

const getProductCost = (row: SaleOrderItem) => {
  if (!row.productId) return null;
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!product || product.costPrice == null) return null;
  return Number(product.costPrice);
};

const calcLineAmount = (row: SaleOrderItem) => {
  const qty = parseDecimal(row.qty, 4);
  const price = parseDecimal(row.price, 4);
  if (qty == null || price == null) return null;
  return qty * price;
};

const totalAmountBeforeDiscount = computed(() => {
  let amount = 0;
  formData.items.forEach((row) => {
    const lineAmount = calcLineAmount(row);
    if (lineAmount == null) return;
    amount += lineAmount;
  });
  return amount;
});

const getDiscountAmount = () => {
  const discount = parseAmount(formData.discountAmount || '');
  if (discount == null) return 0;
  return Math.max(0, discount);
};

const calcLineDiscount = (row: SaleOrderItem) => {
  const totalAmount = totalAmountBeforeDiscount.value;
  const discountAmount = getDiscountAmount();
  if (!totalAmount || !discountAmount) return 0;
  const lineAmount = calcLineAmount(row);
  if (lineAmount == null) return 0;
  return (lineAmount / totalAmount) * discountAmount;
};

const calcLineNetAmount = (row: SaleOrderItem) => {
  const amount = calcLineAmount(row);
  if (amount == null) return null;
  return amount - calcLineDiscount(row);
};

const calcLineProfit = (row: SaleOrderItem) => {
  const amount = calcLineNetAmount(row);
  if (amount == null) return null;
  const cost = getProductCost(row);
  if (cost == null) return null;
  return amount - (cost * (parseDecimal(row.qty, 4) || 0));
};

const formatMoney = (value: number | null) => {
  if (value == null || Number.isNaN(value)) return '-';
  return value.toFixed(2);
};

const formatRate = (value: number | null) => {
  if (value == null || Number.isNaN(value)) return '-';
  return `${(value * 100).toFixed(2)}%`;
};

const formatProfitCell = (row: SaleOrderItem) => {
  const profit = calcLineProfit(row);
  const amount = calcLineNetAmount(row);
  if (profit == null || amount == null || amount === 0) return '-';
  return `${formatMoney(profit)} (${formatRate(profit / amount)})`;
};

const totalSummary = computed(() => {
  let amount = 0;
  let netAmount = 0;
  let profit = 0;
  let hasMissingCost = false;
  formData.items.forEach((row) => {
    const lineAmount = calcLineAmount(row);
    if (lineAmount == null) return;
    amount += lineAmount;
    const lineNetAmount = calcLineNetAmount(row);
    if (lineNetAmount != null) {
      netAmount += lineNetAmount;
    }
    const lineProfit = calcLineProfit(row);
    if (lineProfit == null) {
      if (row.productId) {
        hasMissingCost = true;
      }
      return;
    }
    profit += lineProfit;
  });
  const rate = netAmount ? profit / netAmount : null;
  return { amount, netAmount, profit, rate, hasMissingCost };
});

const totalProfitText = computed(() => {
  if (totalSummary.value.hasMissingCost) return '-';
  return formatMoney(totalSummary.value.profit);
});

const totalProfitRateText = computed(() => {
  if (totalSummary.value.hasMissingCost) return '-';
  return formatRate(totalSummary.value.rate);
});

const getDefaultSettlementMethod = () => {
  if (!settlementMethodOptions.value.length) return '';
  const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
  return defaultItem?.code || '';
};

const getDefaultDeliveryMethod = () => {
  if (!deliveryMethodOptions.value.length) return '';
  const defaultItem = deliveryMethodOptions.value.find(item => item.isDefault) ?? deliveryMethodOptions.value[0];
  return defaultItem?.code || '';
};

const applyMethodsForCustomer = () => {
  const customer = customerOptions.value.find(item => item.id === formData.customerId);
  const settlement = customer?.paymentTerms || getDefaultSettlementMethod();
  const delivery = customer?.deliveryMethodCode || getDefaultDeliveryMethod();
  if (settlement) {
    formData.settlementMethod = settlement;
  }
  if (delivery) {
    formData.deliveryMethod = delivery;
  }
};

const handleProductChange = async (row: SaleOrderItem) => {
  activeRowIndex.value = formData.items.indexOf(row);
  row.warehouseId = undefined;
  row.locationId = undefined;
  row.stockKey = '';
  row.price = '';
  applyProductDefaults(row, true);
  await fetchStockOptions(row.productId, true);
  syncStockKey(row);
  await applyPriceForRow(row, true);
};

const handleRowClick = (row: SaleOrderItem) => {
  activeRowIndex.value = formData.items.indexOf(row);
};

const openHistoryForRow = async (row: SaleOrderItem) => {
  activeRowIndex.value = formData.items.indexOf(row);
  if (!row.productId) {
    notifyWarning(t('message.selectProductFirst'));
    return;
  }
  historyProduct.value = productOptions.value.find(item => item.id === row.productId)
    || { id: row.productId, name: row.productName || String(row.productId) };
  historyDialogVisible.value = true;
  historyTab.value = 'purchase';
  saleHistoryItems.value = [];
  customerSaleHistoryItems.value = [];
  purchaseHistoryItems.value = [];
  priceHistoryItems.value = [];
  purchaseHistoryKeyword.value = '';
  saleHistoryKeyword.value = '';
  customerSaleHistoryKeyword.value = '';
  purchaseHistoryRange.value = [];
  saleHistoryRange.value = [];
  customerSaleHistoryRange.value = [];
  try {
    purchaseHistoryPage.value = 1;
    saleHistoryPage.value = 1;
    customerSaleHistoryPage.value = 1;
    purchaseHistoryTotal.value = 0;
    saleHistoryTotal.value = 0;
    customerSaleHistoryTotal.value = 0;
    await Promise.all([
      fetchProductPrices(),
      fetchSaleHistory(1),
      fetchPurchaseHistory(1),
      fetchCustomerSaleHistory(1)
    ]);
  } catch (error) {
    notifyError(error);
  }
};

const handleStockLocationChange = (row: SaleOrderItem) => {
  if (!row.productId || !row.stockKey) {
    row.warehouseId = undefined;
    row.locationId = undefined;
    return;
  }
  const options = getStockOptionsForRow(row);
  const selected = options.find(item => item.key === row.stockKey);
  if (!selected) {
    row.warehouseId = undefined;
    row.locationId = undefined;
    return;
  }
  row.warehouseId = selected.warehouseId ?? undefined;
  row.locationId = selected.locationId ?? undefined;
};

const handleCustomerChange = (value: number | null) => {
  if (isInitializing.value) {
    lastCustomerId.value = value;
    return;
  }
  if (value === lastCustomerId.value) return;
  const hasItems = formData.items.some(item => item.productId);
  if (hasItems) {
    pendingCustomerId.value = value;
    showCustomerChangeDialog.value = true;
    return;
  }
  lastCustomerId.value = value;
  applyMethodsForCustomer();
};

const applyCustomerChange = async (action: 'price' | 'clear' | 'cancel') => {
  const targetCustomerId = pendingCustomerId.value;
  showCustomerChangeDialog.value = false;
  if (action === 'cancel') {
    formData.customerId = lastCustomerId.value;
    pendingCustomerId.value = null;
    return;
  }
  lastCustomerId.value = targetCustomerId;
  pendingCustomerId.value = null;
  if (action === 'clear') {
    formData.items = [];
    addItem();
    applyMethodsForCustomer();
    return;
  }
  for (const item of formData.items) {
    await applyPriceForRow(item, true);
  }
  applyMethodsForCustomer();
};

const fetchCustomers = async () => {
  try {
    const res: any = await request.get('/erp/customers');
    customerOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchCustomerCategories = async () => {
  try {
    const res: any = await request.get('/erp/customer-categories');
    customerCategoryOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchProducts = async () => {
  try {
    const res: any = await request.get('/erp/products');
    productOptions.value = res.data.data || [];
    for (const item of formData.items) {
      await fetchStockOptions(item.productId);
      applyProductDefaults(item, false);
      syncStockKey(item);
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchWarehouses = async () => {
  try {
    const res: any = await request.get('/erp/warehouses');
    warehouseOptions.value = res.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const fetchLocations = async () => {
  try {
    const res: any = await request.get('/erp/locations');
    locationOptions.value = res.data.data || [];
    formData.items.forEach(item => applyProductDefaults(item, false));
  } catch (error) {
    notifyError(error);
  }
};

const loadDetail = async () => {
  const seq = ++loadDetailSeq;
  isInitializing.value = true;
  resetForm();
  const editing = isEditing.value;
  try {
    if (!editing) {
      await fetchNextOrderNo();
      if (seq !== loadDetailSeq) return;
      formData.orderAt = formatDateTime(new Date());
      formData.status = 'DRAFT';
      addItem();
      applyDefaultMethods();
      lastCustomerId.value = formData.customerId;
      return;
    }
    const id = route.params.id;
    const res: any = await request.get(`/erp/sale-orders/${id}`);
    if (seq !== loadDetailSeq) return;
    if (res.data.code === 200) {
      const data = res.data.data || {};
      formData.orderNo = data.order?.orderNo || data.orderNo || '';
      formData.status = data.order?.status || data.status || '';
      formData.customerId = data.order?.customerId || data.customerId || null;
      formData.orderAt = normalizeDateTimeValue(data.order?.orderAt || data.orderAt) || formatDateTime(new Date());
      formData.remark = data.order?.remark || data.remark || '';
      formData.settlementMethod = data.order?.settlementMethod || data.settlementMethod || '';
      formData.deliveryMethod = data.order?.deliveryMethod || data.deliveryMethod || '';
      formData.paidAmount = String(data.order?.paidAmount ?? data.paidAmount ?? '');
      formData.discountAmount = String(data.order?.discountAmount ?? data.discountAmount ?? '');
      formData.items = (data.items || data.order?.items || []).map((item: any) => ({
        id: item.id,
        productId: item.productId,
        productName: item.productName,
        warehouseId: item.warehouseId,
        locationId: item.locationId,
        stockKey: '',
        qty: item.qty == null ? '' : String(item.qty),
        price: item.price == null ? '' : String(item.price),
        taxRate: item.taxRate,
        remark: item.remark
      }));
      for (const item of formData.items) {
        await fetchStockOptions(item.productId);
        syncStockKey(item);
      }
      if (!formData.items.length) addItem();
      lastCustomerId.value = formData.customerId;
    }
  } catch (error) {
    if (seq === loadDetailSeq) {
      notifyError(error);
    }
  } finally {
    if (seq === loadDetailSeq) {
      isInitializing.value = false;
    }
  }
};

const addItem = () => {
  formData.items.push({
    productId: undefined,
    warehouseId: undefined,
    locationId: undefined,
    stockKey: '',
    qty: '',
    price: '',
    taxRate: 0,
    remark: ''
  });
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const resetForm = () => {
  formData.orderNo = '';
  formData.orderAt = '';
  formData.status = '';
  formData.customerId = null;
  formData.settlementMethod = '';
  formData.deliveryMethod = '';
  formData.paidAmount = '';
  formData.discountAmount = '';
  formData.remark = '';
  formData.items = [];
  themeMode.value = 'default';
};

const fetchSettlementMethods = async () => {
  try {
    const res: any = await request.get('/erp/settlement-methods', { params: { enabled: true } });
    settlementMethodOptions.value = res.data.data || [];
    applyDefaultMethods();
  } catch (error) {
    notifyError(error);
  }
};

const fetchDeliveryMethods = async () => {
  try {
    const res: any = await request.get('/erp/delivery-methods', { params: { enabled: true } });
    deliveryMethodOptions.value = res.data.data || [];
    applyDefaultMethods();
  } catch (error) {
    notifyError(error);
  }
};

const applyDefaultMethods = () => {
  if (isEditing.value) return;
  if (!formData.settlementMethod && settlementMethodOptions.value.length) {
    const defaultItem = settlementMethodOptions.value.find(item => item.isDefault) ?? settlementMethodOptions.value[0];
    if (defaultItem) {
      formData.settlementMethod = defaultItem.code;
    }
  }
  if (!formData.deliveryMethod && deliveryMethodOptions.value.length) {
    const defaultItem = deliveryMethodOptions.value.find(item => item.isDefault) ?? deliveryMethodOptions.value[0];
    if (defaultItem) {
      formData.deliveryMethod = defaultItem.code;
    }
  }
};

const fetchNextOrderNo = async () => {
  try {
    const res: any = await request.get('/erp/sale-orders/next-order-no');
    if (res.data.code === 200) {
      formData.orderNo = res.data.data || '';
    }
  } catch (error) {
    notifyError(error);
  }
};

  const saveData = async (options: { closeOnSuccess?: boolean; reloadAfterCreate?: boolean; showPostSaveDialog?: boolean } = {}) => {
    if (isSaving.value) return null;
    const closeOnSuccess = options.closeOnSuccess !== false;
    const showPostSaveDialog = options.showPostSaveDialog === true;
    if (!formData.customerId) {
      notifyWarning(t('message.required'));
    return;
  }
  if (!formData.settlementMethod) {
    notifyWarning(t('message.required'));
    return;
  }
  const validItems = formData.items.filter(item => item.productId);
  if (!validItems.length) {
    notifyWarning(t('message.noItems'));
    return;
  }
  for (const item of validItems) {
    const qtyValue = parseDecimal(item.qty, 4);
    if (qtyValue == null || qtyValue <= 0) {
      notifyWarning(t('message.mustBePositive'));
      return;
    }
    const priceValue = parseDecimal(item.price, 4);
    if (priceValue == null) {
      notifyWarning(t('message.invalidNumber'));
      return;
    }
  }

  const paidAmount = parseAmount(formData.paidAmount);
  const discountAmount = parseAmount(formData.discountAmount);
  if (paidAmount == null || discountAmount == null) {
    notifyWarning(t('message.invalidNumber'));
    return;
  }

    const payload = {
      orderNo: formData.orderNo || undefined,
      orderAt: formData.orderAt || undefined,
      customerId: formData.customerId,
      settlementMethod: formData.settlementMethod,
      deliveryMethod: formData.deliveryMethod || undefined,
      paidAmount,
      discountAmount,
      remark: formData.remark,
      items: validItems.map((item, index) => {
        ensureStockBinding(item);
        return {
          productId: item.productId,
          warehouseId: item.warehouseId,
          locationId: item.locationId,
          qty: parseDecimal(item.qty, 4),
          price: parseDecimal(item.price, 4),
          taxRate: item.taxRate,
          remark: item.remark,
          sortNo: index + 1
        };
      })
    };

  try {
    isSaving.value = true;
    const res: any = isEditing.value
      ? await request.put(`/erp/sale-orders/${route.params.id}`, payload)
      : await request.post('/erp/sale-orders', payload);

    if (res.data.code === 200) {
      const data = res.data.data || {};
      const savedId = data.order?.id || data.id || Number(route.params.id || 0) || null;
      const savedOrderNo = data.order?.orderNo || data.orderNo || formData.orderNo || '';
      if (!isEditing.value && savedId && options.reloadAfterCreate) {
        notifySuccess(t('message.saveSuccess'));
        await router.replace(`/erp/sale-orders/${savedId}/edit`);
      }
      if (!isEditing.value && savedId && showPostSaveDialog) {
        openSaveSuccessDialog(savedId, savedOrderNo);
        return savedId;
      }
      notifySuccess(t('message.saveSuccess'));
      if (closeOnSuccess) {
        closePage();
        await router.push('/erp/sale-orders/draft');
      }
      return savedId;
    }
  } catch (error) {
    await showSaveErrorDialog(error);
  } finally {
    isSaving.value = false;
  }
  return null;
};

const parseDecimal = (value: string | number | undefined, scale: number) => {
  if (value == null || value === '') return 0;
  const raw = String(value);
  const normalized = raw.endsWith('.') ? raw.slice(0, -1) : raw;
  if (!normalized) return 0;
  const regex = new RegExp(`^\\d+(\\.\\d{1,${scale}})?$`);
  if (!regex.test(normalized)) {
    return null;
  }
  return Number(normalized);
};

const parseAmount = (value: string) => parseDecimal(value, 2);

const formatDateTime = (date: Date) => {
  const pad = (num: number) => String(num).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
};

const normalizeDateTimeValue = (value: any) => {
  if (!value) return '';
  if (value instanceof Date) {
    return formatDateTime(value);
  }
  const raw = String(value);
  if (!raw) return '';
  if (raw.includes('T')) {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) {
      return '';
    }
    return formatDateTime(parsed);
  }
  return raw;
};

const handleTagClosing = (event: Event) => {
  const customEvent = event as CustomEvent<{ path?: string }>;
  if (customEvent.detail?.path === pagePath.value) {
    needsReload.value = true;
    resetForm();
  }
};

watch(
  () => route.fullPath,
  (newPath) => {
    if (newPath === lastRouteKey.value) return;
    if (!isSaleOrderRoute()) return;
    lastRouteKey.value = newPath;
    pagePath.value = route.path;
    loadDetail();
  }
);

onMounted(() => {
  pagePath.value = route.path;
  fetchCustomers();
  fetchCustomerCategories();
  fetchProducts();
  fetchWarehouses();
  fetchLocations();
  fetchSettlementMethods();
  fetchDeliveryMethods();
  loadDetail();
  if (typeof window !== 'undefined') {
    window.addEventListener('tags:closing', handleTagClosing as EventListener);
    window.addEventListener('tags:close', handleTagClosing as EventListener);
    window.addEventListener('keydown', handleKeydown);
  }
});

onActivated(() => {
  if (!isSaleOrderRoute()) return;
  if (!needsReload.value) return;
  needsReload.value = false;
  loadDetail();
});

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') {
    window.removeEventListener('tags:closing', handleTagClosing as EventListener);
    window.removeEventListener('tags:close', handleTagClosing as EventListener);
    window.removeEventListener('keydown', handleKeydown);
  }
  resetForm();
});
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;600&family=Noto+Serif+SC:wght@600;700&display=swap');

.sale-theme {
  background: transparent;
}

.sale-page-header {
  align-items: flex-start !important;
}

.sale-header-stack {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.sale-page-toolbar__filters {
  flex: 1 1 220px;
}

.sale-page-toolbar__actions {
  justify-content: flex-end;
}

.theme-switch {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 4px 10px;
  border-radius: 999px;
  background: rgba(64, 158, 255, 0.08);
  margin-right: 8px;
}

.theme-switch__label {
  font-size: 12px;
  color: #409eff;
  font-weight: 600;
  white-space: nowrap;
}

.theme-switch__select {
  width: 140px;
}

.history-dialog :deep(.el-dialog__body) {
  padding-top: 10px;
}

.history-header {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  align-items: center;
  margin-bottom: 12px;
  color: #2c3e50;
}

.history-header__item {
  display: inline-flex;
  gap: 6px;
  align-items: center;
}

.history-header__hint {
  margin-left: auto;
  font-size: 12px;
  color: #8c8c8c;
}

.history-grid {
  display: grid;
  gap: 16px;
}

.history-grid--tabs {
  grid-template-columns: 1fr;
}

.history-card {
  border: 1px solid #e6e8ee;
  border-radius: 12px;
  padding: 12px;
  background: #fafbfc;
}

.history-card__title {
  font-size: 14px;
  font-weight: 600;
  color: #2c3e50;
  margin-bottom: 8px;
}

.history-tabs :deep(.el-tabs__header) {
  margin-bottom: 8px;
}

.history-toolbar {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 8px;
}

.history-search {
  width: 220px;
}

.history-date {
  width: 260px;
}

.history-pagination {
  margin-top: 8px;
  display: flex;
  justify-content: flex-end;
}

.history-order-dialog :deep(.el-dialog__body) {
  padding: 0;
}

.history-order-frame {
  width: 100%;
  height: 78vh;
  border: none;
  display: block;
}

.action-button {
  min-width: 72px;
  font-weight: 600;
  border-radius: 10px;
}

.action-button--success {
  background: #f0f9eb;
  border-color: #b7e1a1;
  color: #4e8f2b;
}

.action-button--success:hover,
.action-button--success:focus-visible {
  background: #e3f4d8;
  border-color: #95d475;
  color: #3f7d21;
}

.action-button--danger {
  background: #fef0f0;
  border-color: #f3b3b3;
  color: #c45656;
}

.action-button--danger:hover,
.action-button--danger:focus-visible {
  background: #fde2e2;
  border-color: #f08a8a;
  color: #b43c3c;
}

.sale-theme--paper {
  --paper-ink: #2d2a26;
  --paper-muted: #7b6f65;
  --paper-accent: #c27c3f;
  --paper-accent-deep: #9b5b2b;
  --paper-card: #fffdfa;
  --paper-border: rgba(45, 42, 38, 0.12);
  --paper-shadow: 0 12px 24px rgba(45, 42, 38, 0.12);
  background: linear-gradient(135deg, #fbf7f1 0%, #f1e8dc 100%);
  border-radius: 20px;
  padding: 18px;
  font-family: 'Noto Sans SC', 'Segoe UI', sans-serif;
  color: var(--paper-ink);
  position: relative;
  overflow: hidden;
}

.sale-theme--paper::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(rgba(45, 42, 38, 0.05) 1px, transparent 1px);
  background-size: 18px 18px;
  opacity: 0.3;
  pointer-events: none;
}

.sale-theme--paper .page-title {
  font-family: 'Noto Serif SC', 'Noto Sans SC', serif;
  letter-spacing: 1px;
}

.sale-theme--paper .table-card {
  border-radius: 16px;
  border: 1px solid var(--paper-border);
  background: var(--paper-card);
  box-shadow: var(--paper-shadow);
}

.sale-theme--paper :deep(.el-input__wrapper),
.sale-theme--paper :deep(.el-select__wrapper),
.sale-theme--paper :deep(.el-textarea__inner) {
  border-radius: 10px;
  background: #fffaf5;
}

.sale-theme--paper :deep(.el-button--primary) {
  background: var(--paper-accent);
  border-color: var(--paper-accent);
}

.sale-theme--paper :deep(.el-button--primary:hover) {
  background: var(--paper-accent-deep);
  border-color: var(--paper-accent-deep);
}

.sale-theme--paper :deep(.el-button--success) {
  background: #b46a32;
  border-color: #b46a32;
}

.sale-theme--paper :deep(.paper-add-item-button.el-button) {
  background: rgba(194, 124, 63, 0.12);
  border-color: rgba(194, 124, 63, 0.6);
  color: var(--paper-accent-deep);
  font-weight: 600;
}

.sale-theme--paper :deep(.paper-add-item-button.el-button:hover) {
  background: rgba(194, 124, 63, 0.2);
  border-color: var(--paper-accent);
  color: var(--paper-accent-deep);
}

.sale-theme--paper :deep(.paper-add-item-button.el-button:focus-visible) {
  outline: 2px solid rgba(194, 124, 63, 0.35);
  outline-offset: 1px;
}

.sale-theme--paper :deep(.el-table th) {
  background: rgba(194, 124, 63, 0.08);
  color: var(--paper-ink);
  border-bottom: 1px solid rgba(45, 42, 38, 0.12);
}

.sale-theme--paper :deep(.el-table td) {
  background: rgba(255, 253, 250, 0.9);
  border-color: rgba(45, 42, 38, 0.08);
}

.sale-theme--paper :deep(.el-table__row:hover > td) {
  background: rgba(194, 124, 63, 0.06);
}

.sale-theme--paper :deep(.el-table__body-wrapper) {
  background: rgba(255, 253, 250, 0.9);
}

.sale-theme--paper .detail-table-wrapper {
  border: none;
  border-radius: 0;
  padding: 0;
  background: transparent;
}

.sale-theme--paper :deep(.el-table) {
  border-radius: 14px;
  overflow: hidden;
}

.sale-theme--paper :deep(.el-table__inner-wrapper) {
  border-radius: 14px;
  overflow: hidden;
}

.sale-form :deep(.el-form-item) {
  margin-bottom: 4px;
}

.sale-form--compact :deep(.el-form-item) {
  margin-bottom: 0;
}

.form-grid {
  display: flex;
  flex-wrap: nowrap;
  gap: 12px;
  overflow-x: auto;
  padding-bottom: 4px;
}

.compact-card .form-grid {
  padding-bottom: 0;
}

@media (max-width: 1200px) {
  .form-grid {
    gap: 4px;
  }
}

.form-group {
  min-width: 220px;
}

.compact-card .table-body {
  padding: 6px 12px;
}

.compact-card {
  flex: 0 0 auto;
}

.compact-card .table-body {
  flex: 0 0 auto;
  overflow: visible;
}

.sale-header-body {
  padding: 0;
}

.save-error-dialog__content {
  line-height: 1.6;
  color: var(--el-text-color-primary);
  white-space: pre-wrap;
  word-break: break-word;
}

.save-success-dialog__content {
  display: flex;
  flex-direction: column;
  gap: 10px;
  line-height: 1.6;
}

.save-success-dialog__message {
  color: var(--el-text-color-primary);
}

.save-success-dialog__order-no {
  color: var(--el-text-color-regular);
  font-size: 13px;
}

.sale-detail-card {
  flex: 1 1 auto;
  min-height: 0;
}

.sale-detail-body {
  display: flex;
  flex-direction: column;
  min-height: 0;
  padding: 12px 16px;
}

.detail-section {
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 8px;
}

.detail-table-wrapper {
  flex: 1 1 auto;
  min-height: 0;
  overflow: auto;
}

.product-cell {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  align-items: center;
  column-gap: 8px;
}

.product-cell__label {
  min-width: 0;
}

.product-cell__select {
  min-width: 0;
}

.history-inline {
  flex: 0 0 auto;
}

.history-tag {
  cursor: pointer;
  user-select: none;
}

.history-tag--inline {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 20px;
  padding: 0 6px;
  line-height: 20px;
}

.history-icon {
  font-size: 14px;
}

.delete-icon-btn {
  width: 15px;
  height: 15px;
  padding: 0;
}

.delete-icon-btn :deep(.el-icon) {
  font-size: 12px;
}

.history-tag.el-tag--info {
  cursor: not-allowed;
  opacity: 0.6;
}

.detail-actions {
  display: flex;
  justify-content: flex-start;
}

.detail-summary {
  display: flex;
  gap: 16px;
  justify-content: flex-end;
  font-size: 13px;
  color: #606266;
}

.summary-item {
  white-space: nowrap;
}

.payment-card-body {
  padding: 12px 16px !important;
}

.payment-card .form-grid {
  align-items: center;
  flex-wrap: nowrap;
  gap: 8px;
}

.payment-card .form-group {
  min-width: 0;
  flex: 0 0 auto;
}

.payment-card .form-group--settlement {
  min-width: 180px;
}

.payment-card .form-group--amount,
.payment-card .form-group--discount {
  width: auto;
}

.payment-card .sale-form--inline :deep(.el-form-item) {
  display: flex;
  align-items: center;
}

.payment-card .sale-form--inline :deep(.el-form-item__label) {
  padding-bottom: 0;
  display: inline-flex;
  align-items: center;
  height: 32px;
  line-height: 32px;
  margin-right: 4px;
  width: auto !important;
  padding-right: 2px;
  flex: 0 0 auto;
}

.payment-card .sale-form--inline :deep(.el-form-item__content) {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  min-height: 32px;
}

.page-header + .table-card {
  margin-top: 12px;
}

.table-card + .table-card {
  margin-top: 12px;
}

.order-time-picker {
  width: 100%;
}

.order-time-picker :deep(.el-input__wrapper) {
  width: 100%;
  box-sizing: border-box;
}

.order-time-picker :deep(.el-input__inner) {
  width: 100%;
  padding-right: 48px;
}

.order-time-picker :deep(.el-input__suffix) {
  width: 44px;
  display: flex;
  justify-content: flex-end;
}

.table-card.compact-card--inline {
  flex: 0 0 auto !important;
  height: auto !important;
  min-height: 0 !important;
}

.table-card.compact-card--inline .compact-card-body {
  flex: 0 0 auto !important;
  height: auto !important;
  min-height: 0 !important;
  padding: 6px 12px !important;
  overflow: visible !important;
}

.sale-form--inline .form-grid {
  align-items: center;
}

.sale-form--inline :deep(.el-form-item__label) {
  line-height: 20px;
  padding-bottom: 2px;
}

.sale-form--inline :deep(.el-form-item__content) {
  line-height: 28px;
}
</style>
