<template>
  <div class="page-shell page-shell--system">
    <div class="page-header">
      <div class="page-title">{{ $t('page.erpStockTransferManagement') }}</div>
      <div class="page-toolbar-card">
        <div class="table-toolbar inventory-toolbar">
          <div class="table-filters inventory-filters">
            <el-input
              v-model="searchQuery"
              :placeholder="$t('action.search')"
              class="inventory-field--wide"
              clearable
              @clear="handleSearch"
              @keyup.enter="handleSearch"
            />
            <el-date-picker
              v-model="startAt"
              type="datetime"
              :placeholder="$t('field.startTime')"
              format="YYYY-MM-DD HH:mm:ss"
              value-format="YYYY-MM-DD HH:mm:ss"
              class="inventory-field--date"
              @change="handleSearch"
            />
            <el-date-picker
              v-model="endAt"
              type="datetime"
              :placeholder="$t('field.endTime')"
              format="YYYY-MM-DD HH:mm:ss"
              value-format="YYYY-MM-DD HH:mm:ss"
              class="inventory-field--date"
              @change="handleSearch"
            />
          </div>
          <div class="table-actions inventory-actions">
            <el-button type="primary" v-permission="'erp-stock-count:add'" @click="openAddModal">
              {{ $t('action.add') }}
            </el-button>
          </div>
        </div>
      </div>
    </div>

    <div class="table-card">
      <div class="table-body">
        <el-table
          :data="tableData"
          style="width: 100%"
          stripe
          v-loading="loading"
          :empty-text="$t('table.empty')"
        >
          <el-table-column type="index" :label="$t('table.index')" width="70" />
          <el-table-column prop="transferNo" :label="$t('field.transferNo')" min-width="170">
            <template #default="{ row }">
              <el-button link type="primary" @click="openViewModal(row)">{{ row.transferNo }}</el-button>
            </template>
          </el-table-column>
          <el-table-column prop="status" :label="$t('field.status')" width="120">
            <template #default="{ row }">
              <el-tag type="success" size="small">{{ statusLabel(row.status) }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="transferAt" :label="$t('field.transferAt')" min-width="180">
            <template #default="{ row }">
              {{ formatDateTime(row.transferAt) }}
            </template>
          </el-table-column>
          <el-table-column prop="remark" :label="$t('field.remark')" min-width="220" show-overflow-tooltip />
          <el-table-column prop="printCount" :label="$t('field.printCount')" width="100" />
          <el-table-column prop="lastPrintedAt" :label="$t('field.lastPrintedAt')" min-width="180">
            <template #default="{ row }">
              {{ formatDateTime(row.lastPrintedAt) }}
            </template>
          </el-table-column>
          <el-table-column :label="$t('table.actions')" width="180" fixed="right">
            <template #default="{ row }">
              <el-button link type="primary" size="small" @click="openViewModal(row)">
                {{ $t('action.view') }}
              </el-button>
              <el-button
                link
                type="primary"
                size="small"
                v-permission="'erp-stock-count:view'"
                @click="openPrintDialog(row.id)"
              >
                {{ $t('action.print') }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </div>
      <div class="table-pagination">
        <el-pagination
          background
          layout="total, sizes, prev, pager, next, jumper"
          :total="total"
          :current-page="page"
          :page-size="size"
          :page-sizes="[10, 20, 50, 100]"
          @size-change="handleSizeChange"
          @current-change="handlePageChange"
        />
      </div>
    </div>

    <PrintPreviewDialog
      v-model="printDialogVisible"
      doc-type="STOCK_TRANSFER"
      :doc-id="printDocId"
      :title="$t('page.erpStockTransferPrint')"
    />

    <el-dialog
      v-model="showModal"
      :title="dialogTitle"
      width="1180px"
      top="5vh"
      append-to-body
      @closed="resetForm"
    >
      <el-form :model="formData" label-width="110px" class="stock-transfer-form">
        <div class="stock-transfer-grid">
          <el-form-item :label="$t('field.transferNo')">
            <el-input v-model="formData.transferNo" :placeholder="$t('placeholder.autoGenerated')" disabled />
          </el-form-item>
          <el-form-item :label="$t('field.transferAt')">
            <el-date-picker
              v-model="formData.transferAt"
              type="datetime"
              :placeholder="$t('field.transferAt')"
              format="YYYY-MM-DD HH:mm:ss"
              value-format="YYYY-MM-DD HH:mm:ss"
              style="width: 100%"
              :disabled="viewMode"
            />
          </el-form-item>
          <el-form-item :label="$t('field.status')">
            <el-input :model-value="statusLabel(formData.status || 'APPROVED')" disabled />
          </el-form-item>
        </div>
        <el-form-item :label="$t('field.remark')">
          <el-input
            v-model="formData.remark"
            type="textarea"
            :autosize="{ minRows: 2, maxRows: 4 }"
            :disabled="viewMode"
          />
        </el-form-item>
      </el-form>

      <div class="detail-section">
        <div class="detail-header">
          <h4>{{ $t('field.items') }}</h4>
          <el-button type="primary" plain size="small" :disabled="viewMode" @click="addItem">
            + {{ $t('action.addItem') }}
          </el-button>
        </div>
        <div class="detail-table-wrapper">
          <el-table :data="formData.items" style="width: 100%" border stripe>
            <el-table-column :label="$t('field.product')" min-width="180">
              <template #default="{ row }">
                <FuzzyProductSelect
                  v-model="row.productId"
                  :options="getSelectableProductOptions(row.productId)"
                  :placeholder="$t('placeholder.selectProduct')"
                  style="width: 100%"
                  :disabled="viewMode"
                  @change="() => handleProductChange(row)"
                />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.fromWarehouse')" min-width="220">
              <template #default="{ row }">
                <ProductStockSelect
                  v-model="row.sourceStockKey"
                  :product-id="row.productId"
                  :warehouse-id="row.fromWarehouseId"
                  :location-id="row.fromLocationId"
                  :warehouse-options="warehouseOptions"
                  :location-options="locationOptions"
                  :disabled="viewMode"
                  :placeholder="$t('placeholder.selectLocation')"
                  :allow-manual-location-select="true"
                  @selection-change="(payload) => handleSourceSelectionChange(row, payload)"
                />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.sourceQtyAvailable')" width="130">
              <template #default="{ row }">
                {{ row.sourceQtyAvailable }}
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.toWarehouse')" min-width="150">
              <template #default="{ row }">
                <el-select
                  v-model="row.toWarehouseId"
                  filterable
                  :placeholder="$t('placeholder.selectWarehouse')"
                  style="width: 100%"
                  :disabled="viewMode"
                  @change="handleTargetWarehouseChange(row)"
                >
                  <el-option v-for="item in warehouseOptions" :key="item.id" :label="item.name" :value="item.id" />
                </el-select>
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.toLocation')" min-width="150">
              <template #default="{ row }">
                <el-select
                  v-model="row.toLocationId"
                  filterable
                  clearable
                  :placeholder="$t('placeholder.selectLocation')"
                  style="width: 100%"
                  :disabled="viewMode || !row.toWarehouseId"
                >
                  <el-option
                    v-for="item in getLocationOptions(row.toWarehouseId)"
                    :key="item.id"
                    :label="item.name"
                    :value="item.id"
                  />
                </el-select>
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.quantity')" width="140">
              <template #default="{ row }">
                <DecimalInput v-model="row.qty" :scale="4" input-mode="decimal" :disabled="viewMode" />
              </template>
            </el-table-column>
            <el-table-column :label="$t('field.remark')" min-width="180">
              <template #default="{ row }">
                <el-input v-model="row.remark" :disabled="viewMode" />
              </template>
            </el-table-column>
            <el-table-column v-if="!viewMode" label="" width="80" align="center">
              <template #default="{ $index }">
                <el-button type="danger" circle size="small" @click="removeItem($index)">
                  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </div>

      <template #footer>
        <el-button @click="showModal = false">{{ viewMode ? $t('action.close') : $t('action.cancel') }}</el-button>
        <el-button v-if="viewMode && currentId" type="primary" @click="openPrintDialog(currentId)">
          {{ $t('action.print') }}
        </el-button>
        <el-button v-if="!viewMode" type="primary" @click="saveData">{{ $t('action.save') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onActivated, onMounted, reactive, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import request from '@/utils/request';
import { useApiError } from '@/composables/useApiError';
import { useSystemConfig } from '@/composables/useSystemConfig';
import DecimalInput from '@/components/DecimalInput.vue';
import FuzzyProductSelect from '@/components/FuzzyProductSelect.vue';
import ProductStockSelect from '@/components/ProductStockSelect.vue';
import PrintPreviewDialog from '@/components/PrintPreviewDialog.vue';
import { mergeOptionById } from '@/utils/erpMasterData';

interface OptionItem {
  id: number;
  name: string;
  code?: string;
  warehouseId?: number;
  defaultWarehouseId?: number;
  defaultLocationId?: number;
  enabled?: boolean;
}

interface StockTransferRow {
  productId: number | null;
  sourceStockKey: string;
  fromWarehouseId: number | null;
  fromLocationId: number | null;
  toWarehouseId: number | null;
  toLocationId: number | null;
  qty: string;
  sourceQtyAvailable: string;
  remark: string;
}

interface StockTransferHeader {
  id: number;
  transferNo: string;
  status: string;
  transferAt?: string;
  remark?: string;
  printCount?: number;
  lastPrintedAt?: string;
}

const { t } = useI18n();
const { notifyError, notifySuccess, notifyWarning } = useApiError();
const { bindPageSizeSync } = useSystemConfig();

const loading = ref(false);
const page = ref(1);
const size = ref(20);
const total = ref(0);
const tableData = ref<StockTransferHeader[]>([]);

const searchQuery = ref('');
const startAt = ref('');
const endAt = ref('');

const productOptions = ref<OptionItem[]>([]);
const warehouseOptions = ref<OptionItem[]>([]);
const locationOptions = ref<OptionItem[]>([]);

const showModal = ref(false);
const viewMode = ref(false);
const currentId = ref<number | null>(null);

const printDialogVisible = ref(false);
const printDocId = ref<number | null>(null);

const formData = reactive({
  transferNo: '',
  transferAt: '',
  status: 'APPROVED',
  remark: '',
  items: [] as StockTransferRow[]
});

const dialogTitle = computed(() => (viewMode.value ? t('action.view') : t('action.add')));

const formatDateTime = (value?: string) => {
  if (!value) return '-';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleString('zh-CN', { hour12: false });
};

const statusLabel = (status?: string) => {
  if (status === 'APPROVED') return t('status.approved');
  if (status === 'CANCELLED') return t('status.cancelled');
  return status || t('status.approved');
};

const createItem = (): StockTransferRow => ({
  productId: null,
  sourceStockKey: '',
  fromWarehouseId: null,
  fromLocationId: null,
  toWarehouseId: null,
  toLocationId: null,
  qty: '',
  sourceQtyAvailable: '-',
  remark: ''
});

const getSelectableProductOptions = (currentProductId?: number | null) =>
  productOptions.value.filter(item => item.enabled !== false || item.id === currentProductId);

const getLocationOptions = (warehouseId?: number | null) => {
  if (!warehouseId) return [];
  return locationOptions.value.filter(item => item.warehouseId === warehouseId);
};

const fetchOptions = async () => {
  try {
    const [productsRes, warehousesRes, locationsRes] = await Promise.all([
      request.get('/erp/products/options'),
      request.get('/erp/warehouses/options'),
      request.get('/erp/locations/options')
    ]);
    productOptions.value = productsRes.data.data || [];
    warehouseOptions.value = warehousesRes.data.data || [];
    locationOptions.value = locationsRes.data.data || [];
  } catch (error) {
    notifyError(error);
  }
};

const ensureProductOption = async (productId?: number | null) => {
  if (!productId || productOptions.value.some(item => item.id === productId)) return;
  try {
    const res: any = await request.get(`/erp/products/${productId}`);
    const product = res.data.data;
    if (product) {
      productOptions.value = mergeOptionById(productOptions.value, {
        id: product.id,
        name: product.name,
        code: product.code,
        defaultWarehouseId: product.defaultWarehouseId,
        defaultLocationId: product.defaultLocationId,
        enabled: product.enabled
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureWarehouseOption = async (warehouseId?: number | null) => {
  if (!warehouseId || warehouseOptions.value.some(item => item.id === warehouseId)) return;
  try {
    const res: any = await request.get(`/erp/warehouses/${warehouseId}`);
    const warehouse = res.data.data;
    if (warehouse) {
      warehouseOptions.value = mergeOptionById(warehouseOptions.value, {
        id: warehouse.id,
        name: warehouse.name
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const ensureLocationOption = async (locationId?: number | null) => {
  if (!locationId || locationOptions.value.some(item => item.id === locationId)) return;
  try {
    const res: any = await request.get(`/erp/locations/${locationId}`);
    const location = res.data.data;
    if (location) {
      locationOptions.value = mergeOptionById(locationOptions.value, {
        id: location.id,
        name: location.name,
        warehouseId: location.warehouseId
      });
    }
  } catch (error) {
    notifyError(error);
  }
};

const fetchList = async () => {
  loading.value = true;
  try {
    const params: Record<string, any> = {
      page: page.value,
      size: size.value
    };
    if (searchQuery.value.trim()) params.keyword = searchQuery.value.trim();
    if (startAt.value) params.startAt = startAt.value;
    if (endAt.value) params.endAt = endAt.value;

    const res: any = await request.get('/erp/stock-transfers/page', { params });
    if (res.data.code === 200) {
      tableData.value = res.data.data.items || [];
      total.value = res.data.data.total || 0;
    }
  } catch (error) {
    notifyError(error);
  } finally {
    loading.value = false;
  }
};

const handleSearch = () => {
  page.value = 1;
  fetchList();
};

const handlePageChange = (newPage: number) => {
  page.value = newPage;
  fetchList();
};

const handleSizeChange = (newSize: number) => {
  size.value = newSize;
  page.value = 1;
  fetchList();
};

const resetForm = () => {
  formData.transferNo = '';
  formData.transferAt = '';
  formData.status = 'APPROVED';
  formData.remark = '';
  formData.items = [];
  currentId.value = null;
  viewMode.value = false;
};

const addItem = () => {
  formData.items.push(createItem());
};

const removeItem = (index: number) => {
  formData.items.splice(index, 1);
};

const handleProductChange = (row: StockTransferRow) => {
  row.sourceStockKey = '';
  row.fromWarehouseId = null;
  row.fromLocationId = null;
  row.sourceQtyAvailable = '-';
  const product = productOptions.value.find(item => item.id === row.productId);
  if (!row.toWarehouseId) {
    row.toWarehouseId = product?.defaultWarehouseId || null;
  }
  if (!row.toLocationId) {
    row.toLocationId = product?.defaultLocationId || null;
  }
};

const handleSourceSelectionChange = async (
  row: StockTransferRow,
  payload: { stockKey: string; warehouseId: number | null; locationId: number | null }
) => {
  row.sourceStockKey = payload.stockKey;
  row.fromWarehouseId = payload.warehouseId;
  row.fromLocationId = payload.locationId;
  row.sourceQtyAvailable = '-';
  if (!row.productId || !payload.warehouseId) {
    return;
  }
  try {
    const params: Record<string, any> = {
      productId: row.productId,
      warehouseId: payload.warehouseId
    };
    params.locationId = payload.locationId == null ? -1 : payload.locationId;
    const res: any = await request.get('/erp/stock/balances/qty', { params });
    row.sourceQtyAvailable = String(res.data.data ?? 0);
  } catch (error) {
    row.sourceQtyAvailable = '-';
    notifyError(error, 'message.stockBalanceLoadFailed');
  }
};

const handleTargetWarehouseChange = (row: StockTransferRow) => {
  if (!row.toWarehouseId) {
    row.toLocationId = null;
    return;
  }
  if (!getLocationOptions(row.toWarehouseId).some(item => item.id === row.toLocationId)) {
    row.toLocationId = null;
  }
};

const openAddModal = async () => {
  resetForm();
  showModal.value = true;
  addItem();
  try {
    const res: any = await request.get('/erp/stock-transfers/next-transfer-no');
    formData.transferNo = res.data.data || '';
  } catch (error) {
    notifyError(error);
  }
};

const openViewModal = async (row: StockTransferHeader) => {
  resetForm();
  viewMode.value = true;
  currentId.value = row.id;
  try {
    const res: any = await request.get(`/erp/stock-transfers/${row.id}`);
    const detail = res.data.data;
    formData.transferNo = detail.transfer?.transferNo || '';
    formData.transferAt = detail.transfer?.transferAt || '';
    formData.status = detail.transfer?.status || 'APPROVED';
    formData.remark = detail.transfer?.remark || '';
    formData.items = (detail.items || []).map((item: any) => ({
      productId: item.productId || null,
      sourceStockKey: `${item.fromWarehouseId || 0}:${item.fromLocationId || 0}`,
      fromWarehouseId: item.fromWarehouseId || null,
      fromLocationId: item.fromLocationId || null,
      toWarehouseId: item.toWarehouseId || null,
      toLocationId: item.toLocationId || null,
      qty: String(item.qty ?? ''),
      sourceQtyAvailable: '-',
      remark: item.remark || ''
    }));
    await Promise.all(formData.items.flatMap(item => [
      ensureProductOption(item.productId),
      ensureWarehouseOption(item.fromWarehouseId),
      ensureWarehouseOption(item.toWarehouseId),
      ensureLocationOption(item.fromLocationId),
      ensureLocationOption(item.toLocationId)
    ]));
    showModal.value = true;
  } catch (error) {
    notifyError(error);
  }
};

const openPrintDialog = (id?: number | null) => {
  if (!id) return;
  printDocId.value = id;
  printDialogVisible.value = true;
};

const saveData = async () => {
  if (!formData.transferNo) {
    notifyWarning(t('message.required'));
    return;
  }
  if (!formData.items.length) {
    notifyWarning(t('message.noItems'));
    return;
  }

  const seen = new Set<string>();
  for (const [index, item] of formData.items.entries()) {
    const rowIndex = index + 1;
    if (!item.productId) {
      notifyWarning(t('message.requiredWithFieldRow', { row: rowIndex, field: t('field.product') }));
      return;
    }
    if (!item.fromWarehouseId) {
      notifyWarning(t('message.requiredWithFieldRow', { row: rowIndex, field: t('field.fromWarehouse') }));
      return;
    }
    if (!item.toWarehouseId) {
      notifyWarning(t('message.requiredWithFieldRow', { row: rowIndex, field: t('field.toWarehouse') }));
      return;
    }
    const qty = Number(item.qty);
    if (!Number.isFinite(qty) || qty <= 0) {
      notifyWarning(t('message.mustBePositiveWithFieldRow', { row: rowIndex, field: t('field.quantity') }));
      return;
    }
    if (item.fromWarehouseId === item.toWarehouseId && (item.fromLocationId || null) === (item.toLocationId || null)) {
      notifyWarning(t('message.stockTransferPathSameRow', { row: rowIndex }));
      return;
    }
    const duplicateKey = `${item.productId}|${item.fromWarehouseId}|${item.fromLocationId ?? 'null'}|${item.toWarehouseId}|${item.toLocationId ?? 'null'}`;
    if (seen.has(duplicateKey)) {
      notifyWarning(t('message.duplicateStockTransferItem'));
      return;
    }
    seen.add(duplicateKey);
  }

  try {
    const payload = {
      transferNo: formData.transferNo,
      transferAt: formData.transferAt || null,
      remark: formData.remark || '',
      items: formData.items.map(item => ({
        productId: item.productId,
        fromWarehouseId: item.fromWarehouseId,
        fromLocationId: item.fromLocationId,
        toWarehouseId: item.toWarehouseId,
        toLocationId: item.toLocationId,
        qty: Number(item.qty),
        remark: item.remark || ''
      }))
    };
    await request.post('/erp/stock-transfers', payload);
    notifySuccess();
    showModal.value = false;
    fetchList();
  } catch (error) {
    notifyError(error);
  }
};

onMounted(() => {
  fetchOptions();
  fetchList();
  bindPageSizeSync(size, fetchList);
});

onActivated(() => {
  fetchOptions();
  fetchList();
});
</script>

<style scoped>
.stock-transfer-form {
  margin-bottom: 12px;
}

.stock-transfer-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 0 16px;
}

.detail-section {
  margin-top: 8px;
}

.detail-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.detail-header h4 {
  margin: 0;
  font-size: 16px;
}

.detail-table-wrapper {
  width: 100%;
}

.inventory-field--date {
  width: 220px;
}

@media (max-width: 1280px) {
  .stock-transfer-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 768px) {
  .stock-transfer-grid {
    grid-template-columns: 1fr;
  }
}
</style>
