<template>
  <el-dialog
    v-model="dialogVisible"
    class="supplier-dialog customer-dialog"
    :style="dialogStyle"
    draggable
    overflow
    @closed="handleDialogClosed"
  >
    <template #header>
      <div class="supplier-dialog__header">
        <div class="supplier-dialog__header-main">
          <div class="supplier-dialog__title-block">
            <div class="supplier-dialog__title">
              {{ isEditing ? '编辑客户档案' : '新建客户档案' }}
            </div>
            <div class="supplier-dialog__subtitle">客户资料、结算方式和联系方式在同一处维护。</div>
          </div>
        </div>
        <div class="supplier-dialog__drag-hint customer-dialog__drag-hint">支持拖动位置与四角缩放</div>
      </div>
    </template>

    <div class="supplier-dialog__content">
      <div class="supplier-dialog__intro">
        <span class="supplier-dialog__intro-tag">自动编码</span>
        <span class="supplier-dialog__intro-text">带 * 的字段会在保存时校验，联系方式支持标签录入与主号码标记。</span>
      </div>

      <el-form :model="formData" label-position="top" class="supplier-dialog__form">
        <section class="supplier-section">
          <div class="supplier-section__header">
            <div class="supplier-section__title">基础信息</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.code')" required>
              <el-input v-model="formData.code" :placeholder="$t('placeholder.autoGenerated')" :disabled="!isEditing" />
            </el-form-item>
            <el-form-item :label="$t('field.customerCategory')" required>
              <el-select v-model="formData.categoryId" clearable style="width: 100%">
                <el-option
                  v-for="item in categoryOptions"
                  :key="item.id"
                  :label="item.name"
                  :value="item.id"
                />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.name')" required class="supplier-section__span-2">
              <el-input ref="customerNameInputRef" v-model="formData.name" />
            </el-form-item>
            <el-form-item :label="$t('field.status')" class="supplier-section__span-2 supplier-status-field">
              <el-radio-group v-model="formData.enabled" class="supplier-status-field__group">
                <el-radio :value="true">{{ $t('status.active') }}</el-radio>
                <el-radio :value="false">{{ $t('status.inactive') }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section">
          <div class="supplier-section__header">
            <div class="supplier-section__title">联系人与沟通</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.contacts')" class="supplier-section__span-2">
              <div class="supplier-contact-table">
                <div
                  v-for="(group, groupIndex) in formData.contacts"
                  :key="`customer-contact-group-${groupIndex}`"
                  class="supplier-contact-card"
                >
                  <div class="supplier-contact-card__header">
                    <label class="supplier-contact-table__primary">
                      <input
                        type="radio"
                        name="customer-primary-contact"
                        :checked="group.isPrimary"
                        @change="setPrimaryContact(groupIndex)"
                      >
                      <span>主联系人</span>
                    </label>
                    <div class="supplier-contact-card__meta">
                      <el-input v-model="group.name" :placeholder="$t('field.contactPerson')" />
                      <el-input v-model="group.email" :placeholder="$t('field.email')" />
                      <el-input v-model="group.remark" :placeholder="$t('field.remark')" />
                    </div>
                    <el-button link type="danger" @click="removeContact(groupIndex)">{{ $t('action.delete') }}</el-button>
                  </div>
                  <div class="supplier-contact-card__methods">
                    <el-input
                      v-model="group.draftMethod"
                      class="supplier-contact-card__method-input"
                      placeholder="输入联系方式后回车，或粘贴多个号码"
                      @keyup.enter.prevent="commitContactMethod(groupIndex)"
                      @blur="commitContactMethod(groupIndex)"
                    />
                    <div v-if="group.methods.length" class="supplier-contact-card__tag-list">
                      <div
                        v-for="(method, methodIndex) in group.methods"
                        :key="`customer-contact-${groupIndex}-method-${methodIndex}`"
                        class="supplier-contact-tag"
                        :class="{ 'is-primary': method.isPrimary }"
                      >
                        <span class="supplier-contact-tag__value">{{ method.value }}</span>
                        <button
                          type="button"
                          class="supplier-contact-tag__primary"
                          :class="{ 'is-active': method.isPrimary }"
                          @click="setPrimaryMethod(groupIndex, methodIndex)"
                        >
                          {{ method.isPrimary ? '主号码' : '设为主号码' }}
                        </button>
                        <button
                          type="button"
                          class="supplier-contact-tag__remove"
                          @click="removeContactMethod(groupIndex, methodIndex)"
                        >
                          ×
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="supplier-contact-table__actions">
                  <el-button type="primary" plain size="small" @click="addContact">{{ $t('action.addContact') }}</el-button>
                </div>
                <div class="supplier-field-hint">输入一个联系方式后按回车，或失焦自动生成标签；支持一次粘贴多个号码。</div>
                <div class="supplier-field-hint">保存时会自动用主联系人同步列表页展示与检索字段。</div>
              </div>
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section">
          <div class="supplier-section__header">
            <div class="supplier-section__title">业务信息</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.defaultSettlementMethod')">
              <el-select v-model="formData.defaultSettlementMethodCode" clearable style="width: 100%">
                <el-option
                  v-for="item in settlementMethodOptions"
                  :key="item.code"
                  :label="item.name"
                  :value="item.code"
                />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.defaultReceiptMethod')">
              <el-select v-model="formData.defaultReceiptMethodCode" clearable style="width: 100%">
                <el-option
                  v-for="item in receiptMethodOptions"
                  :key="item.code"
                  :label="item.name"
                  :value="item.code"
                />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.deliveryMethod')">
              <el-select v-model="formData.deliveryMethodCode" clearable style="width: 100%">
                <el-option
                  v-for="item in deliveryMethodOptions"
                  :key="item.code"
                  :label="item.name"
                  :value="item.code"
                />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.counterpartySubject')" class="supplier-section__span-2">
              <el-select
                v-model="formData.counterpartySubjectId"
                clearable
                filterable
                style="width: 100%"
                :placeholder="$t('placeholder.selectCounterpartySubject')"
              >
                <el-option
                  v-for="item in counterpartySubjectOptions"
                  :key="item.id"
                  :label="item.name"
                  :value="item.id"
                />
              </el-select>
              <div class="supplier-field-hint">更换往来主体时仍会走客户原有的改绑校验。</div>
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section supplier-section--optional">
          <div class="supplier-section__header supplier-section__header--muted">
            <div class="supplier-section__title">附加信息</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.address')" class="supplier-section__span-2">
              <el-input v-model="formData.address" />
            </el-form-item>
            <el-form-item :label="$t('field.remark')" class="supplier-section__span-2">
              <el-input v-model="formData.remark" type="textarea" :rows="3" />
            </el-form-item>
          </div>
        </section>
      </el-form>
    </div>

    <Teleport :to="resizeHandleTeleportTarget" :disabled="!resizeHandleTeleportTarget">
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--nw"
        aria-label="左上角缩放"
        @pointerdown="startResize('nw', $event)"
      />
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--ne"
        aria-label="右上角缩放"
        @pointerdown="startResize('ne', $event)"
      />
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--sw"
        aria-label="左下角缩放"
        @pointerdown="startResize('sw', $event)"
      />
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--se"
        aria-label="右下角缩放"
        @pointerdown="startResize('se', $event)"
      />
    </Teleport>

    <template #footer>
      <div class="supplier-dialog__footer">
        <div class="supplier-dialog__footer-actions">
          <el-button @click="dialogVisible = false">{{ $t('action.cancel') }}</el-button>
          <el-button type="primary" :loading="submitting" @click="handleSubmit">
            {{ isEditing ? '保存修改' : '保存客户' }}
          </el-button>
        </div>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, reactive, ref, Teleport, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useApiError } from '@/composables/useApiError';

interface OptionItem {
  id: number;
  name: string;
  isDefault?: boolean;
}

interface CodeOptionItem {
  id?: number;
  code: string;
  name: string;
  isDefault?: boolean;
}

interface CounterpartySubjectOption {
  id: number;
  name: string;
}

interface CustomerContactItem {
  name?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  remark?: string;
  isPrimary?: boolean;
}

interface CustomerFormValue {
  code?: string;
  name?: string;
  categoryId?: number | null;
  defaultSettlementMethodCode?: string;
  defaultReceiptMethodCode?: string;
  deliveryMethodCode?: string;
  contact?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  address?: string;
  contacts?: string | CustomerContactItem[];
  counterpartySubjectId?: number | null;
  enabled?: boolean;
  remark?: string;
}

interface CustomerContactMethod {
  value?: string;
  isPrimary?: boolean;
}

interface CustomerContactGroup {
  name?: string;
  email?: string;
  remark?: string;
  isPrimary?: boolean;
  methods: CustomerContactMethod[];
  draftMethod?: string;
}

interface CustomerSubmitPayload {
  code: string;
  name: string;
  categoryId: number;
  defaultSettlementMethodCode?: string;
  defaultReceiptMethodCode?: string;
  deliveryMethodCode?: string;
  contact?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  address?: string;
  contacts?: string;
  counterpartySubjectId?: number;
  enabled: boolean;
  remark?: string;
  contactInfo?: string;
}

interface DialogViewportBounds {
  minWidth: number;
  maxWidth: number;
  minHeight: number;
  maxHeight: number;
  padding: number;
}

const props = withDefaults(defineProps<{
  modelValue: boolean;
  mode: 'create' | 'edit';
  initialValue?: CustomerFormValue | null;
  categoryOptions: OptionItem[];
  settlementMethodOptions: CodeOptionItem[];
  receiptMethodOptions: CodeOptionItem[];
  deliveryMethodOptions: CodeOptionItem[];
  counterpartySubjectOptions: CounterpartySubjectOption[];
  nextCode?: string;
  submitting?: boolean;
}>(), {
  initialValue: null,
  nextCode: '',
  submitting: false
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
  (e: 'submit', value: CustomerSubmitPayload): void;
  (e: 'closed'): void;
}>();

const { t } = useI18n();
const { notifyWarning } = useApiError();

const dialogVisible = computed({
  get: () => props.modelValue,
  set: (value: boolean) => emit('update:modelValue', value)
});
const isEditing = computed(() => props.mode === 'edit');
const customerNameInputRef = ref<{ focus?: () => void } | null>(null);
const resizeHandleTeleportTarget = ref<HTMLElement | null>(null);
const dialogState = reactive({
  width: 960,
  height: 620,
  top: 48,
  left: 0
});
const activeResizePointerId = ref<number | null>(null);
const resizeState = ref<{
  direction: 'nw' | 'ne' | 'sw' | 'se';
  startX: number;
  startY: number;
  startWidth: number;
  startHeight: number;
  startTop: number;
  startLeft: number;
} | null>(null);

const formData = reactive({
  code: '',
  name: '',
  categoryId: undefined as number | undefined,
  defaultSettlementMethodCode: '',
  defaultReceiptMethodCode: '',
  deliveryMethodCode: '',
  contacts: [] as CustomerContactGroup[],
  counterpartySubjectId: undefined as number | undefined,
  enabled: true,
  address: '',
  remark: ''
});

const dialogStyle = computed(() => ({
  '--supplier-dialog-width': `${dialogState.width}px`,
  '--supplier-dialog-height': `${dialogState.height}px`,
  '--supplier-dialog-top': `${dialogState.top}px`,
  '--supplier-dialog-left': `${dialogState.left}px`
}));

const resetForm = () => {
  formData.code = '';
  formData.name = '';
  formData.categoryId = undefined;
  formData.defaultSettlementMethodCode = '';
  formData.defaultReceiptMethodCode = '';
  formData.deliveryMethodCode = '';
  formData.contacts = [];
  formData.counterpartySubjectId = undefined;
  formData.enabled = true;
  formData.address = '';
  formData.remark = '';
};

const parseContacts = (raw?: unknown): CustomerContactItem[] => {
  if (!raw) return [];
  if (Array.isArray(raw)) return raw as CustomerContactItem[];
  if (typeof raw === 'string') {
    try {
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed as CustomerContactItem[] : [];
    } catch {
      return [];
    }
  }
  return [];
};

const splitContactValues = (raw?: string) => (
  raw
    ?.split(/[\n,，;；/]+/)
    .map(item => item.trim())
    .filter(Boolean) ?? []
);

const ensurePrimaryMethod = (group: CustomerContactGroup) => {
  if (!group.methods.length) return;
  if (!group.methods.some(method => method.isPrimary)) {
    const firstMethod = group.methods[0];
    if (firstMethod) {
      firstMethod.isPrimary = true;
    }
  }
};

const applyDefaultMethods = () => {
  if (isEditing.value) return;
  if (!formData.categoryId && props.categoryOptions.length) {
    const defaultCategory = props.categoryOptions.find(item => item.isDefault) ?? props.categoryOptions[0];
    if (defaultCategory) {
      formData.categoryId = defaultCategory.id;
    }
  }
  if (!formData.defaultSettlementMethodCode && props.settlementMethodOptions.length) {
    const defaultItem = props.settlementMethodOptions.find(item => item.isDefault) ?? props.settlementMethodOptions[0];
    if (defaultItem) {
      formData.defaultSettlementMethodCode = defaultItem.code;
    }
  }
  if (!formData.defaultReceiptMethodCode && props.receiptMethodOptions.length) {
    const defaultItem = props.receiptMethodOptions.find(item => item.isDefault) ?? props.receiptMethodOptions[0];
    if (defaultItem) {
      formData.defaultReceiptMethodCode = defaultItem.code;
    }
  }
  if (!formData.deliveryMethodCode && props.deliveryMethodOptions.length) {
    const defaultItem = props.deliveryMethodOptions.find(item => item.isDefault) ?? props.deliveryMethodOptions[0];
    if (defaultItem) {
      formData.deliveryMethodCode = defaultItem.code;
    }
  }
};

const buildInitialContacts = (row: CustomerFormValue): CustomerContactGroup[] => {
  const parsed = parseContacts(row.contacts);
  if (parsed.length) {
    const grouped = new Map<string, CustomerContactGroup>();
    parsed.forEach((item, index) => {
      const key = [item.name || '', item.email || '', item.remark || ''].join('||');
      let group = grouped.get(key);
      if (!group) {
        group = {
          name: item.name || '',
          email: item.email || '',
          remark: item.remark || '',
          isPrimary: !!item.isPrimary || index === 0,
          methods: [],
          draftMethod: ''
        };
        grouped.set(key, group);
      }
      if (item.isPrimary) {
        group.isPrimary = true;
      }
      group.methods.push({
        value: item.mobile || item.phone || '',
        isPrimary: !!item.isPrimary
      });
    });
    const normalized = Array.from(grouped.values()).map((group, index) => ({
      ...group,
      isPrimary: group.isPrimary || index === 0,
      draftMethod: ''
    }));
    if (!normalized.some(item => item.isPrimary) && normalized.length) {
      const firstGroup = normalized[0];
      if (firstGroup) {
        firstGroup.isPrimary = true;
      }
    }
    normalized.forEach(ensurePrimaryMethod);
    return normalized;
  }
  if (row.contact || row.phone || row.mobile || row.email) {
    return [{
      name: row.contact || '',
      email: row.email || '',
      remark: '',
      isPrimary: true,
      methods: [{
        value: row.mobile || row.phone || '',
        isPrimary: true
      }],
      draftMethod: ''
    }];
  }
  return [{ isPrimary: true, methods: [], draftMethod: '' }];
};

const applyInitialValue = () => {
  resetForm();
  if (!isEditing.value) {
    formData.code = props.nextCode || '';
    formData.contacts = [{ isPrimary: true, methods: [], draftMethod: '' }];
    applyDefaultMethods();
    return;
  }

  const row = props.initialValue;
  if (!row) return;
  formData.code = row.code || '';
  formData.name = row.name || '';
  formData.categoryId = row.categoryId ?? undefined;
  formData.defaultSettlementMethodCode = row.defaultSettlementMethodCode || '';
  formData.defaultReceiptMethodCode = row.defaultReceiptMethodCode || '';
  formData.deliveryMethodCode = row.deliveryMethodCode || '';
  formData.contacts = buildInitialContacts(row);
  formData.counterpartySubjectId = row.counterpartySubjectId ?? undefined;
  formData.enabled = row.enabled !== false;
  formData.address = row.address || '';
  formData.remark = row.remark || '';
};

const addContact = () => {
  if (!formData.contacts.length) {
    formData.contacts.push({ isPrimary: true, methods: [], draftMethod: '' });
    return;
  }
  formData.contacts.push({ isPrimary: false, methods: [], draftMethod: '' });
};

const removeContact = (groupIndex: number) => {
  const removed = formData.contacts[groupIndex];
  formData.contacts.splice(groupIndex, 1);
  if (!formData.contacts.length) {
    formData.contacts.push({ isPrimary: true, methods: [], draftMethod: '' });
    return;
  }
  if (removed?.isPrimary) {
    const firstGroup = formData.contacts[0];
    if (firstGroup) {
      firstGroup.isPrimary = true;
    }
  }
};

const commitContactMethod = (groupIndex: number) => {
  const group = formData.contacts[groupIndex];
  if (!group) return;
  const values = splitContactValues(group.draftMethod);
  if (!values.length) {
    group.draftMethod = '';
    return;
  }
  const existing = new Set(group.methods.map(method => method.value?.trim()).filter(Boolean));
  values.forEach((value) => {
    if (existing.has(value)) return;
    group.methods.push({
      value,
      isPrimary: group.methods.length === 0
    });
  });
  ensurePrimaryMethod(group);
  group.draftMethod = '';
};

const removeContactMethod = (groupIndex: number, methodIndex: number) => {
  const group = formData.contacts[groupIndex];
  if (!group) return;
  const removed = group.methods[methodIndex];
  group.methods.splice(methodIndex, 1);
  if (removed?.isPrimary && group.methods.length) {
    const firstMethod = group.methods[0];
    if (firstMethod) {
      firstMethod.isPrimary = true;
    }
  }
};

const setPrimaryMethod = (groupIndex: number, methodIndex: number) => {
  const group = formData.contacts[groupIndex];
  if (!group) return;
  group.methods.forEach((method, index) => {
    method.isPrimary = index === methodIndex;
  });
};

const setPrimaryContact = (index: number) => {
  formData.contacts.forEach((group, itemIndex) => {
    group.isPrimary = itemIndex === index;
  });
};

const isMobileLike = (value?: string) => /^1\d{10}$/.test(value?.trim() || '');

const buildContactsPayload = () => {
  const hasPrimary = formData.contacts.some(group => group.isPrimary);
  const contacts = formData.contacts
    .flatMap((group, groupIndex) => group.methods.map((method, methodIndex) => ({
      name: group.name?.trim() || '',
      phone: isMobileLike(method.value) ? '' : method.value?.trim() || '',
      mobile: isMobileLike(method.value) ? method.value?.trim() || '' : '',
      email: group.email?.trim() || '',
      remark: group.remark?.trim() || '',
      isPrimary: ((!!group.isPrimary || (!hasPrimary && groupIndex === 0)) && !!method.isPrimary)
        || ((!!group.isPrimary || (!hasPrimary && groupIndex === 0)) && methodIndex === 0 && !group.methods.some(item => item.isPrimary))
    })))
    .filter(item => item.name || item.phone || item.mobile || item.email || item.remark);
  return contacts.length ? JSON.stringify(contacts) : undefined;
};

const getPrimaryContact = () => {
  const contacts = formData.contacts
    .map(group => {
      const primaryMethod = group.methods.find(item => item.isPrimary) || group.methods[0];
      return {
        name: group.name?.trim() || '',
        phone: isMobileLike(primaryMethod?.value) ? '' : primaryMethod?.value?.trim() || '',
        mobile: isMobileLike(primaryMethod?.value) ? primaryMethod?.value?.trim() || '' : '',
        email: group.email?.trim() || '',
        remark: group.remark?.trim() || '',
        isPrimary: !!group.isPrimary
      };
    })
    .filter(item => item.name || item.phone || item.mobile || item.email || item.remark);
  if (!contacts.length) return null;
  return contacts.find(item => item.isPrimary) || contacts[0];
};

const buildContactInfoSummary = () => {
  const contacts = formData.contacts
    .map(group => ({
      name: group.name?.trim() || '',
      email: group.email?.trim() || '',
      remark: group.remark?.trim() || '',
      methods: group.methods
        .map(item => item.value?.trim() || '')
        .filter(Boolean)
    }))
    .filter(item => item.name || item.email || item.remark || item.methods.length);
  if (!contacts.length) return undefined;
  return contacts
    .map(item => [item.name, item.methods.join('；'), item.email, item.remark].filter(Boolean).join(' / '))
    .join('；');
};

const buildPayload = (): CustomerSubmitPayload => {
  const primaryContact = getPrimaryContact();
  return {
    code: formData.code.trim(),
    name: formData.name.trim(),
    categoryId: formData.categoryId as number,
    defaultSettlementMethodCode: formData.defaultSettlementMethodCode || undefined,
    defaultReceiptMethodCode: formData.defaultReceiptMethodCode || undefined,
    deliveryMethodCode: formData.deliveryMethodCode || undefined,
    contact: primaryContact?.name || undefined,
    phone: primaryContact?.phone || undefined,
    mobile: primaryContact?.mobile || undefined,
    email: primaryContact?.email || undefined,
    address: formData.address.trim() || undefined,
    contacts: buildContactsPayload(),
    counterpartySubjectId: formData.counterpartySubjectId,
    enabled: formData.enabled,
    remark: formData.remark.trim() || undefined,
    contactInfo: buildContactInfoSummary()
  };
};

const focusCustomerName = () => {
  nextTick(() => {
    customerNameInputRef.value?.focus?.();
  });
};

const getViewportDialogBounds = (): DialogViewportBounds => {
  if (typeof window === 'undefined') {
    return {
      minWidth: dialogState.width,
      maxWidth: dialogState.width,
      minHeight: dialogState.height,
      maxHeight: dialogState.height,
      padding: 0
    };
  }

  const padding = 16;
  const minWidth = Math.min(680, window.innerWidth - padding * 2);
  const maxWidth = Math.max(minWidth, window.innerWidth - padding * 2);
  const minHeight = Math.min(520, window.innerHeight - padding * 2);
  const maxHeight = Math.max(minHeight, window.innerHeight - padding * 2);

  return {
    minWidth: Math.max(320, minWidth),
    maxWidth,
    minHeight: Math.max(420, minHeight),
    maxHeight,
    padding
  };
};

const applyDialogBounds = (nextWidth: number, nextHeight: number, nextTop: number, nextLeft: number) => {
  if (typeof window === 'undefined') return;
  const { minWidth, maxWidth, minHeight, maxHeight, padding } = getViewportDialogBounds();
  const width = Math.min(Math.max(nextWidth, minWidth), maxWidth);
  const height = Math.min(Math.max(nextHeight, minHeight), maxHeight);
  const maxLeft = Math.max(padding, window.innerWidth - width - padding);
  const maxTop = Math.max(padding, window.innerHeight - height - padding);

  dialogState.width = Math.round(width);
  dialogState.height = Math.round(height);
  dialogState.left = Math.round(Math.min(Math.max(nextLeft, padding), maxLeft));
  dialogState.top = Math.round(Math.min(Math.max(nextTop, padding), maxTop));
};

const centerDialog = () => {
  if (typeof window === 'undefined') return;
  const { maxWidth, maxHeight } = getViewportDialogBounds();
  const width = Math.min(960, maxWidth);
  const height = Math.min(620, maxHeight);
  const left = Math.max(16, Math.round((window.innerWidth - width) / 2));
  const top = Math.max(24, Math.round((window.innerHeight - height) / 2) - 24);
  applyDialogBounds(width, height, top, left);
};

const clearResizeListeners = () => {
  if (typeof window === 'undefined') return;
  window.removeEventListener('pointermove', handleResizePointerMove);
  window.removeEventListener('pointerup', stopResize);
  window.removeEventListener('pointercancel', stopResize);
};

const resolveDialogElement = () => document.querySelector('.el-dialog.customer-dialog') as HTMLElement | null;

const updateResizeHandleTeleportTarget = () => {
  if (typeof window === 'undefined') return;
  resizeHandleTeleportTarget.value = resolveDialogElement();
};

const syncDialogPositionFromTransform = () => {
  if (typeof window === 'undefined') return;
  const dialogElement = resolveDialogElement();
  if (!dialogElement) return;
  const computedStyle = window.getComputedStyle(dialogElement);
  const transform = computedStyle.transform;
  if (!transform || transform === 'none') return;

  const matrix = new DOMMatrixReadOnly(transform);
  if (!matrix.m41 && !matrix.m42) return;

  applyDialogBounds(
    dialogState.width,
    dialogState.height,
    dialogState.top + matrix.m42,
    dialogState.left + matrix.m41
  );
  dialogElement.style.transform = 'none';
};

const syncDialogStateFromDom = () => {
  if (typeof window === 'undefined') return;
  const dialogElement = resolveDialogElement();
  if (!dialogElement) return;
  const rect = dialogElement.getBoundingClientRect();
  applyDialogBounds(rect.width, rect.height, rect.top, rect.left);
};

const startResize = (direction: 'nw' | 'ne' | 'sw' | 'se', event: PointerEvent) => {
  event.preventDefault();
  event.stopPropagation();
  syncDialogPositionFromTransform();
  syncDialogStateFromDom();
  activeResizePointerId.value = event.pointerId;
  resizeState.value = {
    direction,
    startX: event.clientX,
    startY: event.clientY,
    startWidth: dialogState.width,
    startHeight: dialogState.height,
    startTop: dialogState.top,
    startLeft: dialogState.left
  };
  window.addEventListener('pointermove', handleResizePointerMove);
  window.addEventListener('pointerup', stopResize);
  window.addEventListener('pointercancel', stopResize);
};

const handleResizePointerMove = (event: PointerEvent) => {
  if (!resizeState.value) return;
  if (activeResizePointerId.value !== null && event.pointerId !== activeResizePointerId.value) return;

  const deltaX = event.clientX - resizeState.value.startX;
  const deltaY = event.clientY - resizeState.value.startY;
  let width = resizeState.value.startWidth;
  let height = resizeState.value.startHeight;
  let top = resizeState.value.startTop;
  let left = resizeState.value.startLeft;

  if (resizeState.value.direction.includes('e')) {
    width = resizeState.value.startWidth + deltaX;
  }
  if (resizeState.value.direction.includes('s')) {
    height = resizeState.value.startHeight + deltaY;
  }
  if (resizeState.value.direction.includes('w')) {
    width = resizeState.value.startWidth - deltaX;
    left = resizeState.value.startLeft + deltaX;
  }
  if (resizeState.value.direction.includes('n')) {
    height = resizeState.value.startHeight - deltaY;
    top = resizeState.value.startTop + deltaY;
  }

  applyDialogBounds(width, height, top, left);
};

const stopResize = (event?: PointerEvent) => {
  if (event && activeResizePointerId.value !== null && event.pointerId !== activeResizePointerId.value) {
    return;
  }
  resizeState.value = null;
  activeResizePointerId.value = null;
  clearResizeListeners();
};

const handleDialogClosed = () => {
  stopResize();
  resizeHandleTeleportTarget.value = null;
  resetForm();
  emit('closed');
};

const handleSubmit = () => {
  if (!formData.code.trim()) {
    notifyWarning(t('message.requiredWithField', { field: t('field.code') }));
    return;
  }
  if (!formData.name.trim()) {
    notifyWarning(t('message.requiredWithField', { field: t('field.name') }));
    return;
  }
  if (!formData.categoryId) {
    notifyWarning(t('message.requiredWithField', { field: t('field.customerCategory') }));
    return;
  }
  emit('submit', buildPayload());
};

watch(dialogVisible, (visible) => {
  if (!visible) {
    resizeHandleTeleportTarget.value = null;
    return;
  }
  applyInitialValue();
  nextTick(() => {
    updateResizeHandleTeleportTarget();
    centerDialog();
    focusCustomerName();
  });
});

watch(() => props.nextCode, (code) => {
  if (dialogVisible.value && !isEditing.value && !formData.code) {
    formData.code = code || '';
  }
});

watch(
  () => [props.categoryOptions, props.settlementMethodOptions, props.receiptMethodOptions, props.deliveryMethodOptions],
  () => {
    if (dialogVisible.value) {
      applyDefaultMethods();
    }
  }
);

onBeforeUnmount(() => {
  stopResize();
});
</script>
