<template>
  <el-dialog
    v-model="dialogVisible"
    class="supplier-dialog"
    :style="dialogStyle"
    draggable
    overflow
    @closed="handleDialogClosed"
  >
    <template #header>
      <div class="supplier-dialog__header">
        <div class="supplier-dialog__header-main">
          <div class="supplier-dialog__title-block">
            <div class="supplier-dialog__title">
              {{ isEditing ? $t('supplierDialog.editTitle') : $t('supplierDialog.createTitle') }}
            </div>
            <div class="supplier-dialog__subtitle">{{ $t('supplierDialog.subtitle') }}</div>
          </div>
        </div>
        <div class="supplier-dialog__drag-hint">{{ $t('supplierDialog.dragHint') }}</div>
      </div>
    </template>

    <div class="supplier-dialog__content">
      <div class="supplier-dialog__intro">
        <span class="supplier-dialog__intro-tag">{{ $t('supplierDialog.autoCodeTag') }}</span>
        <span class="supplier-dialog__intro-text">{{ $t('supplierDialog.requiredHint') }}</span>
      </div>

      <el-form :model="formData" label-position="top" class="supplier-dialog__form">
        <section class="supplier-section">
          <div class="supplier-section__header">
            <div class="supplier-section__title">{{ $t('supplierDialog.sectionBasic') }}</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.code')" required>
              <el-input v-model="formData.code" :placeholder="$t('placeholder.autoGenerated')" :disabled="!isEditing" />
            </el-form-item>
            <el-form-item :label="$t('field.shortName')">
              <el-input v-model="formData.shortName" />
            </el-form-item>
            <el-form-item :label="$t('field.name')" required class="supplier-section__span-2">
              <el-input ref="supplierNameInputRef" v-model="formData.name" />
            </el-form-item>
            <el-form-item :label="$t('field.supplierType')">
              <el-select v-model="formData.supplierTypeId" clearable style="width: 100%">
                <el-option
                  v-for="item in supplierTypeOptions"
                  :key="item.id"
                  :label="item.name"
                  :value="item.id"
                />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.region')">
              <el-input v-model="formData.region" />
            </el-form-item>
            <el-form-item :label="$t('field.status')" class="supplier-section__span-2 supplier-status-field">
              <el-radio-group v-model="formData.status" class="supplier-status-field__group">
                <el-radio value="enabled">{{ $t('status.active') }}</el-radio>
                <el-radio value="disabled">{{ $t('status.inactive') }}</el-radio>
                <el-radio value="blacklisted">{{ $t('status.blacklisted') }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section">
          <div class="supplier-section__header">
            <div class="supplier-section__title">{{ $t('supplierDialog.sectionContact') }}</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.contacts')" class="supplier-section__span-2">
              <div class="supplier-contact-table">
                <div
                  v-for="(group, groupIndex) in formData.contacts"
                  :key="`contact-group-${groupIndex}`"
                  class="supplier-contact-card"
                >
                  <div class="supplier-contact-card__header">
                    <label class="supplier-contact-table__primary">
                      <input
                        type="radio"
                        name="supplier-primary-contact"
                        :checked="group.isPrimary"
                        @change="setPrimaryContact(groupIndex)"
                      >
                      <span>主联系人</span>
                    </label>
                    <div class="supplier-contact-card__meta">
                      <el-input v-model="group.name" :placeholder="$t('field.contactPerson')" />
                      <el-input v-model="group.wechat" :placeholder="$t('field.wechat')" />
                      <el-input v-model="group.email" :placeholder="$t('field.email')" />
                      <el-input v-model="group.remark" :placeholder="$t('field.remark')" />
                    </div>
                    <el-button link type="danger" @click="removeContact(groupIndex)">{{ $t('action.delete') }}</el-button>
                  </div>
                  <div class="supplier-contact-card__methods">
                    <el-input
                      v-model="group.draftMethod"
                      class="supplier-contact-card__method-input"
                      placeholder="输入联系方式后回车，或粘贴多个号码"
                      @keyup.enter.prevent="commitContactMethod(groupIndex)"
                      @blur="commitContactMethod(groupIndex)"
                    />
                    <div v-if="group.methods.length" class="supplier-contact-card__tag-list">
                      <div
                        v-for="(method, methodIndex) in group.methods"
                        :key="`contact-${groupIndex}-method-${methodIndex}`"
                        class="supplier-contact-tag"
                        :class="{ 'is-primary': method.isPrimary }"
                      >
                        <span class="supplier-contact-tag__value">{{ method.value }}</span>
                        <button
                          type="button"
                          class="supplier-contact-tag__primary"
                          :class="{ 'is-active': method.isPrimary }"
                          @click="setPrimaryMethod(groupIndex, methodIndex)"
                        >
                          {{ method.isPrimary ? '主号码' : '设为主号码' }}
                        </button>
                        <button
                          type="button"
                          class="supplier-contact-tag__remove"
                          @click="removeContactMethod(groupIndex, methodIndex)"
                        >
                          ×
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="supplier-contact-table__actions">
                  <el-button type="primary" plain size="small" @click="addContact">{{ $t('action.addContact') }}</el-button>
                </div>
                <div class="supplier-field-hint">输入一个联系方式后按回车，或失焦自动生成标签；支持一次粘贴多个号码。</div>
                <div class="supplier-field-hint">保存时会自动用主联系人同步列表页展示与检索字段。</div>
              </div>
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section">
          <div class="supplier-section__header">
            <div class="supplier-section__title">{{ $t('supplierDialog.sectionBusiness') }}</div>
          </div>
          <div class="supplier-section__grid">
            <el-form-item :label="$t('field.businessScope')">
              <el-select v-model="formData.businessScope" style="width: 100%">
                <el-option :label="$t('option.supplierOnly')" value="SUPPLIER" />
                <el-option :label="$t('option.customerSupplier')" value="CUSTOMER_SUPPLIER" />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.purchaser')">
              <el-input v-model="formData.purchaser" />
            </el-form-item>
            <el-form-item :label="$t('field.counterpartySubject')" class="supplier-section__span-2">
              <el-select
                v-model="formData.counterpartySubjectId"
                clearable
                filterable
                style="width: 100%"
                :placeholder="$t('placeholder.selectCounterpartySubject')"
              >
                <el-option
                  v-for="item in counterpartySubjectOptions"
                  :key="item.id"
                  :label="item.name"
                  :value="item.id"
                />
              </el-select>
              <div class="supplier-field-hint">{{ $t('supplierDialog.counterpartyHint') }}</div>
            </el-form-item>
            <el-form-item :label="$t('field.defaultSettlementMethod')">
              <el-select v-model="formData.defaultSettlementMethodCode" clearable style="width: 100%">
                <el-option
                  v-for="item in settlementMethodOptions"
                  :key="item.code"
                  :label="item.name"
                  :value="item.code"
                />
              </el-select>
            </el-form-item>
            <el-form-item :label="$t('field.defaultPaymentMethod')">
              <el-select v-model="formData.defaultPaymentMethodCode" clearable style="width: 100%">
                <el-option
                  v-for="item in paymentMethodOptions"
                  :key="item.code"
                  :label="item.name"
                  :value="item.code"
                />
              </el-select>
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section supplier-section--optional">
          <button
            type="button"
            class="supplier-section__toggle"
            :aria-expanded="financeOptionalExpanded"
            aria-controls="supplier-finance-optional"
            @click="toggleFinanceOptional"
          >
            <span class="supplier-section__toggle-copy">
              <span class="supplier-section__title">{{ $t('supplierDialog.sectionFinanceOptional') }}</span>
              <span class="supplier-section__toggle-hint">{{ $t('supplierDialog.financeToggleHint') }}</span>
            </span>
            <span class="supplier-section__toggle-text">
              {{ financeToggleLabel }}
            </span>
          </button>
          <div v-show="financeOptionalExpanded" id="supplier-finance-optional" class="supplier-section__grid">
            <el-form-item :label="$t('field.email')">
              <el-input v-model="formData.email" />
            </el-form-item>
            <el-form-item :label="$t('field.openingAddress')">
              <el-input v-model="formData.address" />
            </el-form-item>
            <el-form-item :label="$t('field.taxNo')">
              <el-input v-model="formData.taxNo" />
            </el-form-item>
            <el-form-item :label="$t('field.bankName')">
              <el-input v-model="formData.bankName" />
            </el-form-item>
            <el-form-item :label="$t('field.bankAccount')" class="supplier-section__span-2">
              <el-input v-model="formData.bankAccount" />
            </el-form-item>
          </div>
        </section>

        <section class="supplier-section supplier-section--optional">
          <button
            type="button"
            class="supplier-section__toggle"
            :aria-expanded="historyOptionalExpanded"
            aria-controls="supplier-history-optional"
            @click="toggleHistoryOptional"
          >
            <span class="supplier-section__toggle-copy">
              <span class="supplier-section__title">{{ $t('supplierDialog.sectionHistoryOptional') }}</span>
              <span class="supplier-section__toggle-hint">{{ $t('supplierDialog.historyToggleHint') }}</span>
            </span>
            <span class="supplier-section__toggle-text">
              {{ historyToggleLabel }}
            </span>
          </button>
          <div v-show="historyOptionalExpanded" id="supplier-history-optional" class="supplier-section__grid">
            <el-form-item :label="$t('field.sourceCreatedBy')">
              <el-input v-model="formData.sourceCreatedBy" />
            </el-form-item>
            <el-form-item :label="$t('field.sourceCreatedAt')">
              <el-input :model-value="sourceCreatedAtDisplay" disabled :placeholder="$t('placeholder.importedSourceCreatedAt')" />
            </el-form-item>
            <el-form-item :label="$t('field.remark')" class="supplier-section__span-2">
              <el-input v-model="formData.remark" type="textarea" :rows="3" />
            </el-form-item>
          </div>
        </section>
      </el-form>
    </div>

    <Teleport :to="resizeHandleTeleportTarget" :disabled="!resizeHandleTeleportTarget">
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--nw"
        :aria-label="$t('supplierDialog.resizeHandleNorthwest')"
        @pointerdown="startResize('nw', $event)"
      />
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--ne"
        :aria-label="$t('supplierDialog.resizeHandleNortheast')"
        @pointerdown="startResize('ne', $event)"
      />
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--sw"
        :aria-label="$t('supplierDialog.resizeHandleSouthwest')"
        @pointerdown="startResize('sw', $event)"
      />
      <button
        type="button"
        class="supplier-dialog__resize-handle supplier-dialog__resize-handle--se"
        :aria-label="$t('supplierDialog.resizeHandleSoutheast')"
        @pointerdown="startResize('se', $event)"
      />
    </Teleport>

    <template #footer>
      <div class="supplier-dialog__footer">
        <div class="supplier-dialog__footer-actions">
          <el-button @click="dialogVisible = false">{{ $t('action.cancel') }}</el-button>
          <el-button type="primary" :loading="submitting" @click="handleSubmit">
            {{ isEditing ? $t('supplierDialog.saveEdit') : $t('supplierDialog.saveCreate') }}
          </el-button>
        </div>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, reactive, ref, Teleport, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useApiError } from '@/composables/useApiError';

type SupplierStatus = 'enabled' | 'disabled' | 'blacklisted';

interface CodeOptionItem {
  id?: number;
  code: string;
  name: string;
  isDefault?: boolean;
}

interface CounterpartySubjectOption {
  id: number;
  name: string;
}

interface SupplierFormValue {
  code?: string;
  name?: string;
  shortName?: string;
  supplierTypeId?: number;
  region?: string;
  contact?: string;
  phone?: string;
  mobile?: string;
  wechat?: string;
  purchaser?: string;
  contactInfo?: string;
  businessScope?: string;
  counterpartySubjectId?: number;
  sourceCreatedBy?: string;
  sourceCreatedAt?: string;
  email?: string;
  address?: string;
  taxNo?: string;
  bankName?: string;
  bankAccount?: string;
  defaultSettlementMethodCode?: string;
  defaultPaymentMethodCode?: string;
  contacts?: string | SupplierContactItem[];
  enabled?: boolean;
  blacklisted?: boolean;
  remark?: string;
}

interface SupplierContactItem {
  name?: string;
  phone?: string;
  mobile?: string;
  wechat?: string;
  email?: string;
  remark?: string;
  isPrimary?: boolean;
}

interface SupplierContactMethod {
  value?: string;
  isPrimary?: boolean;
}

interface SupplierContactGroup {
  name?: string;
  wechat?: string;
  email?: string;
  remark?: string;
  isPrimary?: boolean;
  methods: SupplierContactMethod[];
  draftMethod?: string;
}

interface SupplierSubmitPayload {
  code: string;
  name: string;
  shortName?: string;
  supplierTypeId?: number;
  region?: string;
  contact?: string;
  phone?: string;
  mobile?: string;
  wechat?: string;
  purchaser?: string;
  contactInfo?: string;
  businessScope?: string;
  counterpartySubjectId?: number;
  sourceCreatedBy?: string;
  sourceCreatedAt?: string;
  email?: string;
  address?: string;
  taxNo?: string;
  bankName?: string;
  bankAccount?: string;
  defaultSettlementMethodCode?: string;
  defaultPaymentMethodCode?: string;
  contacts?: string;
  enabled: boolean;
  blacklisted: boolean;
  remark?: string;
}

interface DialogViewportBounds {
  minWidth: number;
  maxWidth: number;
  minHeight: number;
  maxHeight: number;
  padding: number;
}

const props = withDefaults(defineProps<{
  modelValue: boolean;
  mode: 'create' | 'edit';
  initialValue?: SupplierFormValue | null;
  supplierTypeOptions: CodeOptionItem[];
  counterpartySubjectOptions: CounterpartySubjectOption[];
  settlementMethodOptions: CodeOptionItem[];
  paymentMethodOptions: CodeOptionItem[];
  nextCode?: string;
  submitting?: boolean;
}>(), {
  initialValue: null,
  nextCode: '',
  submitting: false
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
  (e: 'submit', value: SupplierSubmitPayload): void;
  (e: 'closed'): void;
}>();

const { t } = useI18n();
const { notifyWarning } = useApiError();

const dialogVisible = computed({
  get: () => props.modelValue,
  set: (value: boolean) => emit('update:modelValue', value)
});
const isEditing = computed(() => props.mode === 'edit');
const financeOptionalExpanded = ref(false);
const historyOptionalExpanded = ref(false);
const supplierNameInputRef = ref<{ focus?: () => void } | null>(null);
const resizeHandleTeleportTarget = ref<HTMLElement | null>(null);
const dialogState = reactive({
  width: 960,
  height: 620,
  top: 48,
  left: 0
});
const activeResizePointerId = ref<number | null>(null);
const resizeState = ref<{
  direction: 'nw' | 'ne' | 'sw' | 'se';
  startX: number;
  startY: number;
  startWidth: number;
  startHeight: number;
  startTop: number;
  startLeft: number;
} | null>(null);

const formData = reactive({
  code: '',
  name: '',
  shortName: '',
  supplierTypeId: undefined as number | undefined,
  region: '',
  purchaser: '',
  contacts: [] as SupplierContactGroup[],
  businessScope: 'SUPPLIER',
  counterpartySubjectId: undefined as number | undefined,
  sourceCreatedBy: '',
  sourceCreatedAt: '',
  email: '',
  address: '',
  taxNo: '',
  bankName: '',
  bankAccount: '',
  defaultSettlementMethodCode: '',
  defaultPaymentMethodCode: '',
  status: 'enabled' as SupplierStatus,
  remark: ''
});

const dialogStyle = computed(() => ({
  '--supplier-dialog-width': `${dialogState.width}px`,
  '--supplier-dialog-height': `${dialogState.height}px`,
  '--supplier-dialog-top': `${dialogState.top}px`,
  '--supplier-dialog-left': `${dialogState.left}px`
}));
const financeToggleLabel = computed(() => (
  financeOptionalExpanded.value ? t('supplierDialog.collapseOptional') : t('supplierDialog.expandOptional')
));
const historyToggleLabel = computed(() => (
  historyOptionalExpanded.value ? t('supplierDialog.collapseOptional') : t('supplierDialog.expandOptional')
));
const formatSourceCreatedAtDisplay = (value?: string) => {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat('zh-CN', {
    timeZone: 'Asia/Shanghai',
    hour12: false,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  }).format(date);
};
const sourceCreatedAtDisplay = computed(() => formatSourceCreatedAtDisplay(formData.sourceCreatedAt));

const resetForm = () => {
  formData.code = '';
  formData.name = '';
  formData.shortName = '';
  formData.supplierTypeId = undefined;
  formData.region = '';
  formData.purchaser = '';
  formData.contacts = [];
  formData.businessScope = 'SUPPLIER';
  formData.counterpartySubjectId = undefined;
  formData.sourceCreatedBy = '';
  formData.sourceCreatedAt = '';
  formData.email = '';
  formData.address = '';
  formData.taxNo = '';
  formData.bankName = '';
  formData.bankAccount = '';
  formData.defaultSettlementMethodCode = '';
  formData.defaultPaymentMethodCode = '';
  formData.status = 'enabled';
  formData.remark = '';
  financeOptionalExpanded.value = false;
  historyOptionalExpanded.value = false;
};

const resolveStatus = (value?: SupplierFormValue): SupplierStatus => {
  if (value?.blacklisted) return 'blacklisted';
  return value?.enabled === false ? 'disabled' : 'enabled';
};

const applyDefaultMethods = () => {
  if (isEditing.value) return;
  if (!formData.defaultSettlementMethodCode && props.settlementMethodOptions.length) {
    const defaultItem = props.settlementMethodOptions.find(item => item.isDefault) ?? props.settlementMethodOptions[0];
    if (defaultItem) {
      formData.defaultSettlementMethodCode = defaultItem.code;
    }
  }
  if (!formData.defaultPaymentMethodCode && props.paymentMethodOptions.length) {
    const defaultItem = props.paymentMethodOptions.find(item => item.isDefault) ?? props.paymentMethodOptions[0];
    if (defaultItem) {
      formData.defaultPaymentMethodCode = defaultItem.code;
    }
  }
};

const applyInitialValue = () => {
  resetForm();
  if (!isEditing.value) {
    formData.code = props.nextCode || '';
    formData.contacts = [{ isPrimary: true, methods: [{}] }];
    applyDefaultMethods();
    return;
  }

  const row = props.initialValue;
  if (!row) return;
  formData.code = row.code || '';
  formData.name = row.name || '';
  formData.shortName = row.shortName || '';
  formData.supplierTypeId = row.supplierTypeId;
  formData.region = row.region || '';
  formData.purchaser = row.purchaser || '';
  formData.contacts = buildInitialContacts(row);
  formData.businessScope = row.businessScope || 'SUPPLIER';
  formData.counterpartySubjectId = row.counterpartySubjectId;
  formData.sourceCreatedBy = row.sourceCreatedBy || '';
  formData.sourceCreatedAt = row.sourceCreatedAt || '';
  formData.email = row.email || '';
  formData.address = row.address || '';
  formData.taxNo = row.taxNo || '';
  formData.bankName = row.bankName || '';
  formData.bankAccount = row.bankAccount || '';
  formData.defaultSettlementMethodCode = row.defaultSettlementMethodCode || '';
  formData.defaultPaymentMethodCode = row.defaultPaymentMethodCode || '';
  formData.status = resolveStatus(row);
  formData.remark = row.remark || '';
};

const parseContacts = (raw?: unknown): SupplierContactItem[] => {
  if (!raw) return [];
  if (Array.isArray(raw)) return raw as SupplierContactItem[];
  if (typeof raw === 'string') {
    try {
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed as SupplierContactItem[] : [];
    } catch {
      return [];
    }
  }
  return [];
};

const addContact = () => {
  if (!formData.contacts.length) {
    formData.contacts.push({ isPrimary: true, methods: [], draftMethod: '' });
    return;
  }
  formData.contacts.push({ isPrimary: false, methods: [], draftMethod: '' });
};

const removeContact = (groupIndex: number) => {
  const removed = formData.contacts[groupIndex];
  formData.contacts.splice(groupIndex, 1);
  if (!formData.contacts.length) {
    formData.contacts.push({ isPrimary: true, methods: [], draftMethod: '' });
    return;
  }
  if (removed?.isPrimary && formData.contacts.length) {
    const firstContact = formData.contacts[0];
    if (firstContact) {
      firstContact.isPrimary = true;
    }
  }
};

const splitContactValues = (raw?: string) => (
  raw
    ?.split(/[\n,，;；]+/)
    .map(item => item.trim())
    .filter(Boolean) ?? []
);

const ensurePrimaryMethod = (group: SupplierContactGroup) => {
  if (!group.methods.length) {
    return;
  }
  if (!group.methods.some(method => method.isPrimary)) {
    const firstMethod = group.methods[0];
    if (firstMethod) {
      firstMethod.isPrimary = true;
    }
  }
};

const removeContactMethod = (groupIndex: number, methodIndex: number) => {
  const group = formData.contacts[groupIndex];
  if (!group) return;
  const removed = group.methods[methodIndex];
  group.methods.splice(methodIndex, 1);
  if (removed?.isPrimary && group.methods.length) {
    const firstMethod = group.methods[0];
    if (firstMethod) {
      firstMethod.isPrimary = true;
    }
  }
};

const setPrimaryContact = (index: number) => {
  formData.contacts.forEach((group, itemIndex) => {
    group.isPrimary = itemIndex === index;
  });
};

const commitContactMethod = (groupIndex: number) => {
  const group = formData.contacts[groupIndex];
  if (!group) return;
  const values = splitContactValues(group.draftMethod);
  if (!values.length) {
    group.draftMethod = '';
    return;
  }
  const existing = new Set(group.methods.map(method => method.value?.trim()).filter(Boolean));
  values.forEach((value) => {
    if (existing.has(value)) return;
    group.methods.push({
      value,
      isPrimary: group.methods.length === 0
    });
  });
  ensurePrimaryMethod(group);
  group.draftMethod = '';
};

const setPrimaryMethod = (groupIndex: number, methodIndex: number) => {
  const group = formData.contacts[groupIndex];
  if (!group) return;
  group.methods.forEach((method, index) => {
    method.isPrimary = index === methodIndex;
  });
};

const buildInitialContacts = (row: SupplierFormValue): SupplierContactGroup[] => {
  const parsed = parseContacts(row.contacts);
  if (parsed.length) {
    const grouped = new Map<string, SupplierContactGroup>();
    parsed.forEach((item, index) => {
      const key = [
        item.name || '',
        item.wechat || '',
        item.email || '',
        item.remark || ''
      ].join('||');
      let group = grouped.get(key);
      if (!group) {
        group = {
          name: item.name || '',
          wechat: item.wechat || '',
          email: item.email || '',
          remark: item.remark || '',
          isPrimary: !!item.isPrimary || index === 0,
          methods: [],
          draftMethod: ''
        };
        grouped.set(key, group);
      }
      if (item.isPrimary) {
        group.isPrimary = true;
      }
      group.methods.push({
        value: item.mobile || item.phone || '',
        isPrimary: !!item.isPrimary
      });
    });
    const normalized = Array.from(grouped.values()).map((group, index) => ({
      ...group,
      methods: group.methods,
      draftMethod: '',
      isPrimary: group.isPrimary || index === 0
    }));
    if (!normalized.some(item => item.isPrimary) && normalized.length) {
      const firstGroup = normalized[0];
      if (firstGroup) {
        firstGroup.isPrimary = true;
      }
    }
    normalized.forEach(ensurePrimaryMethod);
    return normalized;
  }
  if (row.contact || row.phone || row.mobile || row.wechat || row.email || row.contactInfo) {
    return [{
      name: row.contact || '',
      wechat: row.wechat || '',
      email: row.email || '',
      remark: row.contactInfo || '',
      isPrimary: true,
      methods: [{
        value: row.mobile || row.phone || '',
        isPrimary: true
      }],
      draftMethod: ''
    }];
  }
  return [{ isPrimary: true, methods: [], draftMethod: '' }];
};

const isMobileLike = (value?: string) => /^1\d{10}$/.test(value?.trim() || '');

const buildContactsPayload = () => {
  const contacts = formData.contacts
    .flatMap((group, groupIndex) => {
      const hasPrimary = formData.contacts.some(contact => contact.isPrimary);
      return group.methods.map((method, methodIndex) => ({
        name: group.name?.trim() || '',
        phone: isMobileLike(method.value) ? '' : method.value?.trim() || '',
        mobile: isMobileLike(method.value) ? method.value?.trim() || '' : '',
        wechat: group.wechat?.trim() || '',
        email: group.email?.trim() || '',
        remark: group.remark?.trim() || '',
        isPrimary: ((!!group.isPrimary || (groupIndex === 0 && !hasPrimary)) && !!method.isPrimary)
          || ((!!group.isPrimary || (groupIndex === 0 && !hasPrimary)) && methodIndex === 0 && !group.methods.some(item => item.isPrimary))
      }));
    })
    .filter(item => item.name || item.phone || item.mobile || item.wechat || item.email || item.remark);
  return contacts.length ? JSON.stringify(contacts) : undefined;
};

const getPrimaryContact = () => {
  const contacts = formData.contacts
    .map(group => ({
      name: group.name?.trim() || '',
      phone: isMobileLike(group.methods[0]?.value) ? '' : group.methods[0]?.value?.trim() || '',
      mobile: isMobileLike(group.methods[0]?.value) ? group.methods[0]?.value?.trim() || '' : '',
      wechat: group.wechat?.trim() || '',
      email: group.email?.trim() || '',
      remark: group.remark?.trim() || '',
      isPrimary: !!group.isPrimary
    }))
    .filter(item => item.name || item.phone || item.mobile || item.wechat || item.email || item.remark);
  if (!contacts.length) {
    return null;
  }
  return contacts.find(item => item.isPrimary) || contacts[0];
};

const buildContactInfoSummary = () => {
  const contacts = formData.contacts
    .map(group => ({
      name: group.name?.trim() || '',
      wechat: group.wechat?.trim() || '',
      email: group.email?.trim() || '',
      remark: group.remark?.trim() || '',
      phones: group.methods
        .map(method => method.value?.trim() || '')
        .filter(Boolean)
    }))
    .filter(item => item.name || item.wechat || item.email || item.remark || item.phones.length);
  if (!contacts.length) {
    return undefined;
  }
  return contacts.map((item) => [
    item.name,
    item.phones.join('；'),
    item.wechat ? `微信:${item.wechat}` : '',
    item.email,
    item.remark
  ].filter(Boolean).join(' / ')).join('；');
};

const buildPayload = (): SupplierSubmitPayload => ({
  ...(() => {
    const primaryContact = getPrimaryContact();
    return {
      contact: primaryContact?.name || undefined,
      phone: primaryContact?.phone || undefined,
      mobile: primaryContact?.mobile || undefined,
      wechat: primaryContact?.wechat || undefined,
      email: formData.email || primaryContact?.email || undefined,
      contactInfo: buildContactInfoSummary(),
      contacts: buildContactsPayload()
    };
  })(),
  code: formData.code,
  name: formData.name,
  shortName: formData.shortName || undefined,
  supplierTypeId: formData.supplierTypeId,
  region: formData.region || undefined,
  purchaser: formData.purchaser || undefined,
  businessScope: formData.businessScope || undefined,
  counterpartySubjectId: formData.counterpartySubjectId,
  sourceCreatedBy: formData.sourceCreatedBy || undefined,
  sourceCreatedAt: formData.sourceCreatedAt || undefined,
  address: formData.address || undefined,
  taxNo: formData.taxNo || undefined,
  bankName: formData.bankName || undefined,
  bankAccount: formData.bankAccount || undefined,
  defaultSettlementMethodCode: formData.defaultSettlementMethodCode || undefined,
  defaultPaymentMethodCode: formData.defaultPaymentMethodCode || undefined,
  enabled: formData.status === 'enabled',
  blacklisted: formData.status === 'blacklisted',
  remark: formData.remark || undefined
});

const focusSupplierName = () => {
  nextTick(() => {
    supplierNameInputRef.value?.focus?.();
  });
};

const toggleFinanceOptional = () => {
  financeOptionalExpanded.value = !financeOptionalExpanded.value;
};

const toggleHistoryOptional = () => {
  historyOptionalExpanded.value = !historyOptionalExpanded.value;
};

const getViewportDialogBounds = (): DialogViewportBounds => {
  if (typeof window === 'undefined') {
    return {
      minWidth: dialogState.width,
      maxWidth: dialogState.width,
      minHeight: dialogState.height,
      maxHeight: dialogState.height,
      padding: 0
    };
  }

  const padding = 16;
  const minWidth = Math.min(680, window.innerWidth - padding * 2);
  const maxWidth = Math.max(minWidth, window.innerWidth - padding * 2);
  const minHeight = Math.min(520, window.innerHeight - padding * 2);
  const maxHeight = Math.max(minHeight, window.innerHeight - padding * 2);

  return {
    minWidth: Math.max(320, minWidth),
    maxWidth,
    minHeight: Math.max(420, minHeight),
    maxHeight,
    padding
  };
};

const applyDialogBounds = (
  nextWidth: number,
  nextHeight: number,
  nextTop: number,
  nextLeft: number
) => {
  if (typeof window === 'undefined') return;
  const { minWidth, maxWidth, minHeight, maxHeight, padding } = getViewportDialogBounds();
  const width = Math.min(Math.max(nextWidth, minWidth), maxWidth);
  const height = Math.min(Math.max(nextHeight, minHeight), maxHeight);
  const maxLeft = Math.max(padding, window.innerWidth - width - padding);
  const maxTop = Math.max(padding, window.innerHeight - height - padding);

  dialogState.width = Math.round(width);
  dialogState.height = Math.round(height);
  dialogState.left = Math.round(Math.min(Math.max(nextLeft, padding), maxLeft));
  dialogState.top = Math.round(Math.min(Math.max(nextTop, padding), maxTop));
};

const centerDialog = () => {
  if (typeof window === 'undefined') return;
  const { maxWidth, maxHeight } = getViewportDialogBounds();
  const width = Math.min(960, maxWidth);
  const height = Math.min(620, maxHeight);
  const left = Math.max(16, Math.round((window.innerWidth - width) / 2));
  const top = Math.max(24, Math.round((window.innerHeight - height) / 2) - 24);
  applyDialogBounds(width, height, top, left);
};

const clearResizeListeners = () => {
  if (typeof window === 'undefined') return;
  window.removeEventListener('pointermove', handleResizePointerMove);
  window.removeEventListener('pointerup', stopResize);
  window.removeEventListener('pointercancel', stopResize);
};

const resolveDialogElement = () => document.querySelector('.el-dialog.supplier-dialog') as HTMLElement | null;

const updateResizeHandleTeleportTarget = () => {
  if (typeof window === 'undefined') return;
  resizeHandleTeleportTarget.value = resolveDialogElement();
};

const syncDialogPositionFromTransform = () => {
  if (typeof window === 'undefined') return;
  const dialogElement = resolveDialogElement();
  if (!dialogElement) return;
  const computedStyle = window.getComputedStyle(dialogElement);
  const transform = computedStyle.transform;
  if (!transform || transform === 'none') return;

  const matrix = new DOMMatrixReadOnly(transform);
  if (!matrix.m41 && !matrix.m42) return;

  applyDialogBounds(
    dialogState.width,
    dialogState.height,
    dialogState.top + matrix.m42,
    dialogState.left + matrix.m41
  );
  dialogElement.style.transform = 'none';
};

const syncDialogStateFromDom = () => {
  if (typeof window === 'undefined') return;
  const dialogElement = resolveDialogElement();
  if (!dialogElement) return;
  const rect = dialogElement.getBoundingClientRect();
  applyDialogBounds(rect.width, rect.height, rect.top, rect.left);
};

const startResize = (direction: 'nw' | 'ne' | 'sw' | 'se', event: PointerEvent) => {
  event.preventDefault();
  event.stopPropagation();
  syncDialogPositionFromTransform();
  syncDialogStateFromDom();
  activeResizePointerId.value = event.pointerId;
  resizeState.value = {
    direction,
    startX: event.clientX,
    startY: event.clientY,
    startWidth: dialogState.width,
    startHeight: dialogState.height,
    startTop: dialogState.top,
    startLeft: dialogState.left
  };
  window.addEventListener('pointermove', handleResizePointerMove);
  window.addEventListener('pointerup', stopResize);
  window.addEventListener('pointercancel', stopResize);
};

const handleResizePointerMove = (event: PointerEvent) => {
  if (!resizeState.value) return;
  if (activeResizePointerId.value !== null && event.pointerId !== activeResizePointerId.value) return;

  const deltaX = event.clientX - resizeState.value.startX;
  const deltaY = event.clientY - resizeState.value.startY;
  let width = resizeState.value.startWidth;
  let height = resizeState.value.startHeight;
  let top = resizeState.value.startTop;
  let left = resizeState.value.startLeft;

  if (resizeState.value.direction.includes('e')) {
    width = resizeState.value.startWidth + deltaX;
  }
  if (resizeState.value.direction.includes('s')) {
    height = resizeState.value.startHeight + deltaY;
  }
  if (resizeState.value.direction.includes('w')) {
    width = resizeState.value.startWidth - deltaX;
    left = resizeState.value.startLeft + deltaX;
  }
  if (resizeState.value.direction.includes('n')) {
    height = resizeState.value.startHeight - deltaY;
    top = resizeState.value.startTop + deltaY;
  }

  applyDialogBounds(width, height, top, left);
};

const stopResize = (event?: PointerEvent) => {
  if (
    event &&
    activeResizePointerId.value !== null &&
    event.pointerId !== activeResizePointerId.value
  ) {
    return;
  }
  resizeState.value = null;
  activeResizePointerId.value = null;
  clearResizeListeners();
};

const handleDialogClosed = () => {
  stopResize();
  resizeHandleTeleportTarget.value = null;
  resetForm();
  emit('closed');
};

const handleSubmit = () => {
  if (!formData.code) {
    notifyWarning(t('message.requiredWithField', { field: t('field.code') }));
    return;
  }
  if (!formData.name) {
    notifyWarning(t('message.requiredWithField', { field: t('field.name') }));
    return;
  }
  emit('submit', buildPayload());
};

watch(dialogVisible, (visible) => {
  if (!visible) {
    resizeHandleTeleportTarget.value = null;
    return;
  }
  applyInitialValue();
  nextTick(() => {
    updateResizeHandleTeleportTarget();
    centerDialog();
    focusSupplierName();
  });
});

watch(() => props.nextCode, (code) => {
  if (dialogVisible.value && !isEditing.value && !formData.code) {
    formData.code = code || '';
  }
});

watch(
  () => [props.settlementMethodOptions, props.paymentMethodOptions],
  () => {
    if (dialogVisible.value) {
      applyDefaultMethods();
    }
  }
);

onBeforeUnmount(() => {
  stopResize();
});
</script>
