import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

const __dirname = dirname(fileURLToPath(import.meta.url));
const viewsRoot = join(__dirname, '..');

test('stock init page uses excel upload to create opening stock drafts', () => {
  const source = readFileSync(join(viewsRoot, 'ErpStockCountManagement.vue'), 'utf8');

  assert.match(source, /v-if="countType === 'INIT'"\s+v-permission="permAdd"\s+@click="triggerImport">导入期初库存<\/el-button>/);
  assert.match(source, /v-if="countType === 'INIT'"\s+v-permission="permAdd"\s+@click="openStockInitImportHistoryDrawer">导入结果<\/el-button>/);
  assert.match(source, /:accept="countType === 'INIT' \? '\.xls,\.xlsx' : '\.csv,text\/csv'"/);
  assert.match(source, /openStockInitImportDialog/);
  assert.match(source, /openStockInitImportHistoryDrawer/);
  assert.match(source, /showStockInitImportDialog/);
  assert.match(source, /showStockInitImportHistoryDrawer/);
  assert.match(source, /STOCK_INIT_IMPORT_TIMEOUT_MS\s*=\s*120000/);
  assert.match(source, /request\.post\('\/erp\/stock-inits\/import\/preview', formData, \{\s*timeout: STOCK_INIT_IMPORT_TIMEOUT_MS\s*\}\)/);
  assert.match(source, /stockInitImportPreview/);
  assert.match(source, /stockInitImportFieldOptions/);
  assert.match(source, /stockInitImportMappings/);
  assert.match(source, /stockInitImportMappingConfirmed/);
  assert.match(source, /stockInitImportStrategyMode/);
  assert.match(source, /按仓库层级导入/);
  assert.match(source, /按商品层级导入/);
  assert.match(source, /不导入策略/);
  assert.match(source, /handleStockInitImportStrategyModeChange/);
  assert.match(source, /confirmStockInitImportMapping/);
  assert.match(source, /buildStockInitImportFieldMapping/);
  assert.match(source, /formData\.append\('fieldMapping', JSON\.stringify\(buildStockInitImportFieldMapping\(\)\)\)/);
  assert.match(source, /formData\.append\('strategyMode', stockInitImportStrategyMode\.value\)/);
  assert.match(source, /if \(!stockInitImportMappingConfirmed\.value\)/);
  assert.match(source, /@change="handleStockInitImportMappingChange\(row\)"/);
  assert.match(source, /@click="confirmStockInitImportMapping"/);
  assert.match(source, /@click="submitStockInitImport"/);
  assert.match(source, /request\.post\('\/erp\/stock-inits\/import', formData, \{\s*timeout: STOCK_INIT_IMPORT_TIMEOUT_MS\s*\}\)/);
  assert.match(source, /request\.get\('\/erp\/stock-inits\/import-batches'\)/);
  assert.match(source, /request\.get\(`\/erp\/stock-inits\/import-batches\/\$\{batch\.id\}\/items`\)/);
  assert.match(source, /startStockInitImportPolling/);
  assert.match(source, /stopStockInitImportPolling/);
  assert.match(source, /result\.status === 'PROCESSING'/);
  assert.match(source, /导入任务已创建：批次/);
  assert.match(source, /label="失败原因"/);
  assert.match(source, /formatDateTime\(row\.createdAt\)/);
  assert.match(source, /stockInitImportBatchStatusType/);
  assert.match(source, /stockInitImportItemStatusLabel/);
  assert.match(source, /已校验/);
  assert.match(source, /setTimeout\(\(\) => \{\s*void pollStockInitImportBatch/);
  assert.match(source, /<el-drawer v-model="showStockInitImportHistoryDrawer" title="期初库存导入结果"/);
  assert.match(source, /type StockInitImportResult|interface StockInitImportResult/);
});
